### ISSUE TITLE
Decide what metadata we require for submission

### ISSUE THREAD

**Issue by arfon** [openjournals/joss#1]
This should probably be based on https://github.com/codemeta/codemeta and should include sufficient information to automagically complete the form on the journal submission page.

**Comment by ctb** [comment]
The name of the output file should apparently be codemeta.json -- https://github.com/codemeta/codemeta/issues/81

**Comment by arfon** [comment]
👍 thanks @ctb. https://gist.github.com/arfon/478b2ed49e11f984d6fb now generates a file called `codemeta.json`, I'll update the docs accordingly.
