### ISSUE TITLE
Docker build and preview service use different section spacing.

### ISSUE THREAD

**Issue by Viech** [openjournals/joss#1000]
I have prepared a submission that I compile locally with the build script:

```shell
#!/bin/sh
docker run --rm \
    --volume ${PWD}:/data \
    --user $(id -u):$(id -g) \
    --env JOURNAL=joss \
    openjournals/paperdraft
```

In the paper I have carefully worded paragraphs such that it fits neatly on three pages. However, when I compile it using the preview service, then the space surrounding section headers gets significantly larger, so that the last reference ends up opening a fourth page containing a single reference (insert your favorite _most unsatisfying video in the world_ here). Additionally, some paragraphs use different line breaks and are longer when typeset on the preview service, in one case introducing a runt.

I have updated my image using `docker pull openjournals/paperdraft` but this did not change the locally built file, which remains more compact.

Looking at a recently published paper, the spacing of the preview service appears to be correct.

**Comment by arfon** [comment]
I would encourage you to submit and for us to work this out during the review and publication process.

**Comment by Viech** [comment]
I have already submitted after shorting my paper. This issue is not meant as a personal problem but as an inconsistency that might affect other users as well: The docker image is not producing an accurate preview.
