### ISSUE TITLE
Pre-submission enquiry

### ISSUE THREAD

**Issue by mattersoflight** [openjournals/joss#1002]
We are developing an open-source python package [recOrder](https://github.com/mehta-lab/recOrder) for computational label-free imaging of biological samples. The software provides pipelines for automated calibration, acquisition, analysis, and visualization. These features are made accessible via command line and via GUI. recOrder builds on top of open source acquisition software, [Micro-Manager](https://github.com/micro-manager) and open source ND visualization software, [napari](https://github.com/napari/napari). 

We are interested in the systematic review of the software in JOSS, after having noticed the review of [automated acquisition](https://github.com/openjournals/joss-reviews/issues/3394) and [analysis](https://github.com/openjournals/joss-reviews/issues/2440) pipelines. 

We have two specific questions:
* We would like to report some results (image data) with the JOSS paper. Is that permissible under current editorial guidelines?
* Our software is released under a modified 2-clause BSD license. This software license is the 2-clause BSD license plus clause a third clause that prohibits redistribution and use for commercial purposes without further permission. Is such a license compatible with software licenses that JOSS supports? 

I am  looping in the most active developer of this pipeline, @camFoltz, in this enquiry.

**Comment by arfon** [comment]
> We would like to report some results (image data) with the JOSS paper. Is that permissible under current editorial guidelines?

Novel results are not allow sorry.

> Our software is released under a modified 2-clause BSD license. This software license is the 2-clause BSD license plus clause a third clause that prohibits redistribution and use for commercial purposes without further permission. Is such a license compatible with software licenses that JOSS supports?

This sounds like a modification that you've made to the license. As such, this would not be allowed by us as the package would no longer be considered open source by the OSI.
