### ISSUE TITLE
Question: Can an author's name be incomplete and be changed later?

### ISSUE THREAD

**Issue by pragma-once** [openjournals/joss#1003]
Hello, I will change my first name in the future, so I prefer my first name not to be included and rely more on email address / ORCID for now to avoid conflicts.
So I have 2 questions before attempting to complete and submit my work:
1. Can my ORCID "Published Name" be used as author name which only includes my last name?
2. Can I request a name change some years after I've submitted the paper?

**Comment by kthyng** [comment]
Hi @pragma-once! Please check out the docs [here](https://joss.readthedocs.io/en/latest/submitting.html?#confidential-requests) — does that answer your questions?

**Comment by pragma-once** [comment]
Thank you for the quick reply, it does answer my second question.
Only wondering about the first one, that is whether only writing the last name as the author name (+ORCID identifier) is okay.
Though I will update after finding out by submitting if it remains unanswered.

**Comment by arfon** [comment]
I think this might break our paper processing pipeline but I'd encourage you to submit so we can find out! (We'll make it work if so).
