### ISSUE TITLE
Would a paper on the knitrdata R package be within the JOSS scope

### ISSUE THREAD

**Issue by dmkaplan2000** [openjournals/joss#1006]
Hi,

I have a paper describing the [knitrdata R package](https://github.com/dmkaplan2000/knitrdata). Before submitting it to JOSS, I would like to verify that it fits within the scope of the journal. knitrdata allows you to create standalone Rmarkdown documents that integrate the raw data that are the bases of analyses in special "data" chunks. As Rmarkdown is increasingly used to generate scientific publications and reports, the knitrdata package facilitates open, reproducible science by making it possible to include all elements necessary to produce a scientific document in a single source file. It also includes the possibility for using encrypted chunks for cases where reproducibility is important, but access to data must be limited to certain parties (e.g., confidential medical records, proprietary data). The package comes with a set of RStudio plugins that facilitate integrating and manipulating "data" chunks within Rmarkdown documents.

Thanks for your assistance,
David Kaplan

**Comment by danielskatz** [comment]
Hi - What are your expectations regarding the citation of knitrdata in other papers?

**Comment by dmkaplan2000** [comment]
It would be nice if the users of the package cited its use in the paper, but my primary objective is communicating about the package to a wide audience.

**Comment by danielskatz** [comment]
I don't think JOSS is the right venue to communicate about the software - JOSS doesn't really have readers.

JOSS papers are meant as placeholders to enable the reviewed software to be cited, as well as a means to have software reviewed and improved.

So my personal opinion is that this doesn't seem like a good fit, but I hope other JOSS editors will also comment here, perhaps with different opinions.

**Comment by dmkaplan2000** [comment]
I understand your point of view. What I wanted for this package was a widely accessible discussion of some of the uses and objectives of this package that would be less formal and more didactic than a typical package vignette. So far, I haven't found the appropriate venue for this type of information, so if there is any way it would work in JOSS, that would be great. Otherwise, suggestions welcome.

**Comment by danielskatz** [comment]
https://www.software.ac.uk/which-journals-should-i-publish-my-software might be useful to you

**Comment by dmkaplan2000** [comment]
Thanks, I am looking into some of the options on that website.
