### ISSUE TITLE
Pre-submission enquiry

### ISSUE THREAD

**Issue by engyasin** [openjournals/joss#1007]
Hi,

We were recording a dataset and needed some tracking and detection software. When we couldn't find that, we wrote the software for that (which include a trained network model). 

**is this kind of software eligible for publication in your journal?**
it still lack documentation and testing units, but I think it fulfills the other requirements (big enough, solve a defined problem we faced before, and it can be helpful to others for sure). 

_It's not state-of-the-art_, but more of practical tool that uses some advanced methods for our use case.

Another point is that parts of other project are used , but only less than 20-30% of the total code.

**Comment by danielskatz** [comment]
Can you provide a link to the software?

Also, note that https://joss.readthedocs.io/en/latest/submitting.html#what-we-mean-by-research-software includes "While useful for many areas of research, pre-trained machine learning models are not in-scope for JOSS."

**Comment by engyasin** [comment]
Actually, the code is still private, because it is still under development, so the final version isn't ready, but the title is:
_Multiple traffic entities detection and tracking from bird-view drone videos_

The code is supposed to give the final trajectories of the people in the video in an offline manner. The detection from bird-view is challenging so we trained on hand-labeled dataset.
Lastly, the logic for tracking, fixing the view, and other verification methods is included.

**Comment by arfon** [comment]
Without seeing the software and reading a draft paper it's not possible for us to give you a firm answer here sorry. Please go ahead and submit and the software will go through our standard editorial scope review.
