### ISSUE TITLE
confusing editor dashboard stats graphs

### ISSUE THREAD

**Issue by danielskatz** [openjournals/joss#1008]
The graphs at the bottom of the page are confusing, for example:
<img width="1145" alt="Screen Shot 2021-11-05 at 7 35 46 AM" src="https://user-images.githubusercontent.com/2913845/140511144-e0c7bcb1-68db-43b2-87a6-332937cc7ead.png">
In particular, I don't understand the doubled axes

**Comment by arfon** [comment]
Yeah, not sure what is going on here. I noticed this the other week but haven't had a chance to dig in yet.
