### ISSUE TITLE
Author name changes procedure?

### ISSUE THREAD

**Issue by AoifeHughes** [openjournals/joss#1012]
Hi, 

I was wondering if JOSS has a procedure for updating author name. For example, Nature Springer has recently clarified that it will help authors to do so: [https://www.nature.com/articles/d41586-021-02014-7](https://www.nature.com/articles/d41586-021-02014-7). Other journals such as IEEE have a semi-automated form to fill out.

Does JOSS offer this, if so I was not able to find it.

**Comment by arfon** [comment]
Yes! We've documented this process here: https://joss.readthedocs.io/en/latest/submitting.html?highlight=name#confidential-requests

Please let me know if this isn't sufficient here.

**Comment by AoifeHughes** [comment]
Very useful! Thank you and sorry I didn’t find myself!
