### ISSUE TITLE
Pre-submission enquiry

### ISSUE THREAD

**Issue by janschneida** [openjournals/joss#1014]
Hello JOSS Team!
We are currently working on a python package (taxodist) that implements the researched & discussed algorithms from this [paper](https://dx.doi.org/10.1186%2Fs12911-019-0807-y)
The package is supposed to offer similarity calculations on taxonomic hierarchies, because common features in similarity calculations are organized in such classifications. We are currently planning to implement parsers for other hierarchies than the currently available ICD-10-GM taxonomy. The package is supposed to be extendable by others, so that people who wish to perform similarity calculations can make use of this package and the previously implemented taxonomies, without having to implemented the data structures and algorithms themselves.
We are also going to add set-level-similarity algorithms to the package, to allow for code-set calculations (as mentioned in the corresponding paper)
The package also offers plotting of hierarchies and their concepts and the docs will help people decide, which algorithm to use and how to add own hierarchies to the package.
Is this suitable for JOSS publication?
Best regards!

**Comment by danielskatz** [comment]
This seems reasonable, assuming that it meets the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion

**Comment by janschneida** [comment]
Thanks for the fast reply,
Once we find it to be feature complete with common hierarchies available, we are going to submit it and see, what your reviewers think about it. Looking forward to this!
