### ISSUE TITLE
Pre-submission enquiry: synr, an R package

### ISSUE THREAD

**Issue by datalowe** [openjournals/joss#1017]
Hi,

## Background
I've developed an R package called synr that was recently approved for the CRAN network. Here are links to:

* [its GitHub repo](https://github.com/datalowe/synr)
* [its documentation](https://datalowe.github.io/synr/)
* [the official CRAN page for synr](https://cran.r-project.org/package=synr)

synr has a narrow focus on exploring, validating and applying well-established summary statistics for synesthesia consistency test data. The primary motivation for its creation was that there currently is no common tool for working with consistency test data, nor a common methodology for validation. This lack has led to much time being spent 'recoding the wheel' (and possibly some unfound bugs due to lack of code transparency) and manually sifting through data sets when validating them, as well as diffuse operationalizations of what 'valid data' mean.

Apart from domain-specific features, the software might be interesting in how it makes heavy use of R [reference classes](http://adv-r.had.co.nz/R5.html). The package also implements a novel method, primarily based on the [DBSCAN](https://en.wikipedia.org/wiki/DBSCAN) algorithm (and the 'dbscan' R package), for producing summary statistics describing how much 'color variation' there is in a matrix of color point data, as explained in a [dedicated vignette](https://datalowe.github.io/synr/articles/validate-data.html).

## Question 1: Inappropriate?
Is there anything, based on the description above, that makes synr appear inappropriate for submission to JOSS?

## Question 2: Submission in spite of plans on submitting to other journal in future?
The package has fairly extensive documentation, but I and my colleagues haven't written up a paper yet. Ideally we could write a traditional 'long-form' paper that would be accepted by a domain-related journal where other synesthesia researchers could learn about the package and start using it. It seems the most appropriate journal would be 'Behavior Research Methods'. However, they might find that synr has too narrow a focus. Even if they would accept a synr-related paper, publication would take a long time, and having a 'short-form' paper (as described in the guidelines) published in JOSS  would mean that research colleagues can start using and citing the package much sooner. I'd also appreciate the opportunity to get feedback through JOSS on the package, especially since it is the first software package I've shared publicly.

Is it fine to do a submission to JOSS even if there are plans on making a package-focused submission to a domain-specific journal some time in the future? If so, apart from citing the JOSS article, should any special mention be made in this later article?

(I hope this question doesn't come off as rude; we simply wish for synr to reach researchers who need it. if it's more appropriate, we might opt for only submitting a synr-focused paper to JOSS, and then reference that in articles making use of synr and hope that colleagues will thus find synr.)

## Question 3: Describing co-author roles?
The submission guidelines say
> Purely [financial or organizational] contributions are not considered sufficient for co-authorship of JOSS submissions, but active project direction and other forms of non-code contributions are

My research group leader has only done non-code contributions similar to what's mentioned in the example. Should her 'non-code' role be explicitly described somewhere, e. g. during the submission process or in the paper itself?

Thank you,
Lowe Wilsson

**Comment by arfon** [comment]
Thanks for opening this issue @datalowe. We'd welcome a submission of this package to JOSS. 

> Is there anything, based on the description above, that makes synr appear inappropriate for submission to JOSS?

No, this seems good.

> Is it fine to do a submission to JOSS even if there are plans on making a package-focused submission to a domain-specific journal some time in the future? If so, apart from citing the JOSS article, should any special mention be made in this later article?

This is fine as far as I'm concerned. That said, you may be limiting your future options with regards to a followup publication here, depending upon the editorial decisions of other journals (I'm thinking about another journal interpreting this as self-plagiarism in the future).

> My research group leader has only done non-code contributions similar to what's mentioned in the example. Should her 'non-code' role be explicitly described somewhere, e. g. during the submission process or in the paper itself?

This is up to you. We don't require contributor roles to be described, although this is sometimes flagged by the reviewers.

**Comment by datalowe** [comment]
Thanks for the quick and welcoming response :) I'll talk to my research group leader so that we can decide on how/what to submit and where.
