### ISSUE TITLE
Pre-submission enquiry: terrainr: Landscape Visualization in R and Unity

### ISSUE THREAD

**Issue by mikemahoney218** [openjournals/joss#1018]
Hi all! We've developed an R package named `terrainr` which enables producing landscape visualizations in R and Unity. Here are links to it online:

 * [GitHub repo](https://github.com/ropensci/terrainr)
 * [CRAN homepage](https://cran.r-project.org/package=terrainr)
 * [Documentation website](https://docs.ropensci.org/terrainr/)

While part of the package is indeed a thin API client for the U.S. Geological Survey's National Map, the focus of the package is on transforming spatial data into formats which can be imported by the Unity game engine and used for producing immersive virtual environments. This is an area of active research -- see for instance [Keil 2021](https://link.springer.com/article/10.1007/s42489-020-00069-6) which walks through the "manual" process for using real-world spatial data as terrain -- and we intend to use terrainr as part of a system for assessing these visualizations, to attempt to have a standardized "baseline" visual to compare manual approaches against (as well as in other domains -- see for instance [Mahoney 2021](https://www.mm218.dev/papers/vrs_2021.pdf)). 

I'm curious to know if you view this package as being within scope for JOSS. Thanks for your time!

**Comment by arfon** [comment]
Thanks for opening this issue. It sounds like it could well be in scope, especially if this data processing functionality is a critical piece of enabling a research area/questions.

Please go ahead and submit and we'll put the submission through a scope review with the wider editorial team if there are any concerns.
