### ISSUE TITLE
Include all contributors in the paper

### ISSUE THREAD

**Issue by Borda** [openjournals/joss#1024]
Hello,
 I have a question similar to some already asked - how to differentiate among contributors who shall be included as authors and who just mentioned in the acknowledgment section. At this moment we:
- included contributors who added a significant feature or set of features as authors 
- some other contributors we mention by name in acknowledgment (who we think that contributed more but did not pass the threshold to be authors)
- for the rest, we include the following sentence
  > We also thank all of our open-source contributors for reporting and resolving issues with this package.

The background story is that GH show over 100 contributors with various level of contribution from essential maintainer (authors) to people with fixing a typo or touching past codebase - inherited from the cut-out of the parent project. Also for many of these contributors, we don't have names as their GH account is not complete and there is another contact...

**Comment by arfon** [comment]
Please see our guidance on authorship here: https://joss.readthedocs.io/en/latest/submitting.html#authorship. Ultimately it's up to you to decide who your authors are.
