### ISSUE TITLE
Pre-submission enquiry

### ISSUE THREAD

**Issue by mishioo** [openjournals/joss#1025]
Dear JOSS Team,

I'm developing a python software for the simulation of optical spectra of organic compounds from the results of quantum-chemical calculations. Its main goal is to minimize the time and manual work needed for the analysis of optimization of conformers' structure and calculations of optical activity values. The main features it offers are:

  - bulk processing of Gaussian output files (the most popular quantum-chemical computations software);
  - algorithms for filtering parsed data, including RMSD geometry sieve;
  - simulation of various optical spectra types with gaussian or lorentzian approximation;
  - population-weighted averaging based on Boltzmann distribution;
  - setup for further calculations in Gaussian software.

Source code is available in my github repo: https://github.com/mishioo/tesliper. I'm currently preparing a full documentation and putting the finishing touches on the code. When it's done, probably in January 2022, I would like to publish it beyond github and pypi. I'm wondering if it would be a good candidate for publication in JOSS?

Best regards,
Michał M. Więcław

**Comment by danielskatz** [comment]
This seems reasonable.  Please pay attention to the https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements, and then submit, and if there are any questions, they will come up at that time.

**Comment by mishioo** [comment]
Great, and thanks for such a quick response! I will submit it as soon as it's ready.
