### ISSUE TITLE
Pre-submission enquiry: msigdbr

### ISSUE THREAD

**Issue by igordot** [openjournals/joss#1026]
I am considering submitting an R package. It is on [CRAN](https://cran.r-project.org/package=msigdbr) and [GitHub](https://github.com/igordot/msigdbr).

The package does seem to offer some value to the community. There are [about 20 citations](https://scholar.google.com/scholar?cites=601672181807152557&as_sdt=5,33&sciodt=0,33&hl=en) according to Google Scholar. There are [over 100 mentions](https://scholar.google.com/scholar?hl=en&as_sdt=0%2C33&q=%22msigdbr%22&btnG=) which are not recognized as proper citations. It would be great to have a citable resource.

This is more of a data package. From the four main JOSS submission requirements, the one point that is concerning is: "minor 'utility' packages, including 'thin' API clients, and single-function packages are not acceptable". I am curious if this is going to be a problem.

Thank you.

**Comment by arfon** [comment]
It does look very small and so I suspect this would be out of scope for it's size, and limited (albeit focused!) utility.

One possible alternative to JOSS is to follow [GitHub's guide](https://guides.github.com/activities/citable-code/) on how to create a permanent archive and DOI for your software. This DOI can then be used by others to cite your work.
