### ISSUE TITLE
Pre-submission enquiry: sonify

### ISSUE THREAD

**Issue by liamtoney** [openjournals/joss#1027]
I've developed a Python tool, [_sonify_](https://github.com/liamtoney/sonify), which generates movies showing graphical representations of ground shaking (seismic waves) or sound waves in the atmosphere. The time series are sped up so that the usually inaudible sounds can be heard — this is called "sonification." Such movies are very valuable for scientific outreach, as data from exciting events such as earthquakes, volcanic eruptions, and landslides can be portrayed in an appealing and engaging manner. You can view an example movie [here](https://www.youtube.com/watch?v=XAlbh6gTp-0&ab_channel=JHEPC).

I believe that _sonify_ satisfies the JOSS criteria except for perhaps one element: **It is a tool for creating scientific outreach materials, as opposed to assisting in scientific workflows.** It is, however, targeted towards a scientific user base. Furthermore, the movies it generates have been included in presentations at major conferences. Is such a piece of software applicable for JOSS submission? If so, I would be very keen to contribute this work. Cheers and thanks for your time.

**Comment by arfon** [comment]
Hi @liamtoney, thanks for your enquiry. I suspect this submission isn't in scope for us for a few reasons:

- It looks pretty small, and as such may be consider to fail our ['substantial scholarly effort'](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion.
- Outreach work is not considered in scope for JOSS.
- It may not be considered a significant contribution, especially given the other available tools in this space.

Finally, I would caution you on the name of this package. We've been struggling with a similarly-named package for quite some time in this review: https://github.com/openjournals/joss-reviews/issues/2446
