### ISSUE TITLE
Pre-submission enquiry: TAGS, the Totally Awesome Geolocator Service RShiny Data processing app

### ISSUE THREAD

**Issue by baeolophus** [openjournals/joss#1031]
Hello,

I am interested in publishing a software note for TAGS, the Totally Awesome Geolocator Service (https://tags.shinyapps.io/tags_shiny/), but I am unsure if it is suitable for JOSS.

Information that I feel favors a publication:
- I feel it meets the second criterion in your list "makes addressing research challenges significantly better (e.g., faster, easier, simpler)." in that its function is a critical part of the workflow for dealing with geolocator data ([rather like in this recent enquiry for a wrapper-type program)](https://github.com/openjournals/joss/issues/1018)
- The software is featured in has been recently featured as one of the major tool in the workflow for geolocators (Lisovski et al. 2020 - https://besjournals.onlinelibrary.wiley.com/doi/pdf/10.1111/1365-2656.13036) - see section 3 and table 1.  It is the only tool involved that does not have a suitable publication to cite other than the app's URL.
- The redesigned RShiny code base is about 4 years old but the project has existed in another format/language since at least 2013.
- Lines of code >700
- Commented to indicate where other users could extend the project
- Github repository with feature requests from user input

Reasons I am uncertain as to its suitability:
- <1000 lines of code
- Two authors only
- No updates in the past two years (have not received any new bug reports)
- The RShiny app is a wrapper for another R package

Please let me know what additional questions I could answer to help clarify if this is an appropriate submission to JOSS!  Thank you in advance for any feedback you can provide.

Best,
Claire

**Comment by arfon** [comment]
Hi @baeolophus – thanks for your enquiry. This _might_ pass a scope review with the wider editorial team (I'm not a topic expert in this area) but this is the main concern for me:

> - The RShiny app is a wrapper for another R package

GUI wrappers (such as Shiny apps) are generally considered out of scope for JOSS, unless there is significant functionality provided in the UI that the underlying library doesn't really offer.

I'm sorry I can't give you a strong yes/no here. Our full scope review happens by the wider editorial team so if you're willing to draft a short paper about this package, I'd encourage you to submit and the wider editorial team can weigh in.

**Comment by baeolophus** [comment]
Thanks @arfon .  I will go ahead and write it up then.  The wrapper does provide a lot of functionality: the original package writer actually recommends to use ours with his, for this reason, I believe.  Thanks for your feedback and I will try to get something to the editorial team soonish.
