### ISSUE TITLE
Pre-submission enquiry: shopty

### ISSUE THREAD

**Issue by colligant** [openjournals/joss#1032]
I've created a python tool named [shopty](https://github.com/TravisWheelerLab/shopty) that optimizes hyperparameters of iterative algorithms (mostly neural networks) on a personal computer or a slurm-managed cluster. We're already using it in multiple projects in our lab and we were thinking of submitting it to JOSS. I've gone over the requirements for submission and I think that it ticks most of the boxes, except possibly some aspects of the "substantial scholary effort" criterion - time since creation and number of maintainers being the main issues. 
Is shopty applicable for JOSS submission? Thanks for your time!

**Comment by jedbrown** [comment]
Thanks for your interest. My quick take is that it's pretty small, pretty young, and needs tests, contributing guidelines, and more documentation than the current readme. Think about how others might want to extend it and discuss alternatives. How can this tool support provenance? Automated plotting? What about more sophisticated optimization algorithms? Can good hyperparameters on one platform and scale transfer to another machine or problem? You don't have to do it all, but you probably want to express an opinion about how to make such extensions and what is out of scope.

@danielskatz may have opinions.

**Comment by arfon** [comment]
Closing as stale.
