### ISSUE TITLE
Pre-submission enquiry

### ISSUE THREAD

**Issue by hannorein** [openjournals/joss#1035]
I'm the maintainer of the open source N-body integrator package REBOUND. REBOUND contains several different integrators. I have recently completed the implementation of a new numerical integrator (Gragg-Bulitsch-Stoer) within REBOUND. I would like to write up the details of the implementation and some test cases in JOSS, both as a reference and to make the new integrator citable. Before I start, I wanted to check that it's ok to submit a paper that is only about one specific part of a software package.

**Comment by arfon** [comment]
Hi @hannorein – submissions that described a new capability for a well established package are generally allowed in JOSS (this has happened before), provided that the new capability itself meets [our submission criteria](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements). 

If you can share a link to this new capability then I can try and give you a more definitive answer.

**Comment by hannorein** [comment]
Thanks. I think it fits all the submission criteria. The new capabilities that I would like to describe are the BS integrator and a new API for coupling arbitrary ODEs to N-body integrations. [This](https://rebound.readthedocs.io/en/latest/ipython_examples/ChaoticHyperion/) or [this example](https://rebound.readthedocs.io/en/latest/ipython_examples/IntegratingArbitraryODEs/) gives you some idea. There are a couple of subtleties and it would be nice to have them explained and written down in their own paper, rather than adding a section to some other paper that focuses on the research results.

**Comment by arfon** [comment]
From your links, it's a little challenging to decipher what the code contributions here were for this new functionality?

One other option here would be to publish a paper that describes a major release/update of REBOUND (e.g., `v2.0`) and include descriptions of the new capabilities such as the BS integrator. The request you're currently making here, if done repeatedly (e.g., each time a new capability is added to REBOUND), may start to raise concerns about salami-slicing of the work which [wouldn't be allowed](https://joss.theoj.org/about#ethics).

**Comment by hannorein** [comment]
That makes sense. Thank you. I'll close this for now.
