### ISSUE TITLE
Pre-submission enquiry

### ISSUE THREAD

**Issue by Dntfreitas** [openjournals/joss#1037]
Dear Editors, 

Our team developed a Python package to automatically optimize machine learning models' hyperparameters. We focused on optimizing the hyperparameters of convolutional (CNN) and recurrent neural networks (LSTM and GRU), as these two models are currently the most used ones.

The package implements a new approach (suggested by us) that rests on heuristic optimization to finetuning the hyperparameters. The method was developed as an alternative to a full grid search that performs an exhaustive (and computer-intensive) search over all combinations of parameters to find the optimal parameters for a given model and data.

This method can be integrated into any machine learning pipeline; thus, we believe that the package would have several research applications. Moreover, it implements an software architecture similar to the scikit-learn library and uses the already-developed TensorFlow models. 

We wonder whether such a Python package would scope the Journal of Open Source Software.

Thank You.

**Comment by danielskatz** [comment]
This topic is in scope for JOSS, assuming it meets https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements.  Please go ahead and submit if you think it does, and if there are any questions, the JOSS editors will discuss them at that time.
