### ISSUE TITLE
bibliography: article title capitalization gets changed

### ISSUE THREAD

**Issue by wojdyr** [openjournals/joss#1038]
When using [Whedon paper preview service](https://whedon.theoj.org/) I see that some words in the cited article titles in bibliography get changed to lower or upper case. This example:

```
@article{cctbx,
title={The Computational Crystallography Toolbox: crystallographic algorithms in a reusable software framework},
author={Grosse-Kunstleve, Ralf W and Sauter, Nicholas K and Moriarty, Nigel W and Adams, Paul D},
journal={Journal of Applied Crystallography},
volume={35},
number={1},
pages={126--136},
year={2002},
publisher={International Union of Crystallography}
}
```

results in

> Grosse-Kunstleve, R. W., Sauter, N. K., Moriarty, N. W., & Adams, P. D. (2002). The
> computational crystallography toolbox: Crystallographic algorithms in a reusable software
> framework. Journal of Applied Crystallography, 35(1), 126–136.

Note the change:
The Computational Crystallography Toolbox: crystallographic…
The computational crystallography toolbox: Crystallographic…

Any workarounds?

**Comment by danielskatz** [comment]
Use {} to protect characters that you want to stay in a particular case

```title={The {C}omputational {C}rystallography {T}oolbox: crystallographic algorithms in a reusable software framework},```

**Comment by danielskatz** [comment]
The first character after the ":" should be C; the generation there is correct
