### ISSUE TITLE
Clarification request on notifications for joss-reviews

### ISSUE THREAD

**Issue by ctb** [openjournals/joss#104]
Hey @arfon, me again :)

In your response when you accept reviewers, you say:

```
Please keep an eye on your GitHub notifications for the https://github.com/openjournals/joss-reviews repository and if you think you would be able to review the submitted software please reply on the submission issue.
```

...so I set my notification prefs to watch all conversations. So now I'm getting review threads too ;).

Am I correct in thinking that you will always mention the team when asking for reviewers, so I can change my notification prefs to just notify me when the team is mentioned?

**Comment by arfon** [comment]
> Am I correct in thinking that you will always mention the team when asking for reviewers, so I can change my notification prefs to just notify me when the team is mentioned?

@ctb - yes that's correct. Perhaps I should updated the welcome note to reviewers recommending that they do this?

**Comment by ctb** [comment]
Sounds good - I did it yesterday and got the morning review req perfectly.

--
Titus Brown, ctbrown@ucdavis.edu

**Comment by ctb** [comment]
@arfon ok, new component to the issue: even when I'm not reviewing a paper, I see all of the review comments, b/c you bring in the team on the actual submission issue (e.g. [here](https://github.com/openjournals/joss-reviews/issues/16#issuecomment-217913920)). I think one way to avoid this is to have a separate issue calling for reviewers, who then go sign up at the actual submission link.

(The traffic isn't excessive right now, but I can imagine that it will become excessive soon ;)

**Comment by arfon** [comment]
> I think one way to avoid this is to have a separate issue calling for reviewers, who then go sign up at the actual submission link.

Yep, that's one of the suggested fixes in https://github.com/openjournals/joss/issues/125. Any input on that thread would be very welcome - I'd like us to start moving to this process soon.

**Comment by ctb** [comment]
Moved discussion to #125.
