### ISSUE TITLE
How to cite papers under publication or under review?

### ISSUE THREAD

**Issue by nastaran62** [openjournals/joss#1042]
I want to cite an article of mine that is under publication (Will be published next month) in the paper. What is the correct way to cite it?
I have Doi for it but it is not activated yet.

**Comment by arfon** [comment]
Feel free to cite with the DOI that is not yet available, or follow something like this: https://tex.stackexchange.com/questions/31384/how-to-enter-publications-in-press-or-submitted-to-in-bibtex
