### ISSUE TITLE
Urgent: It seems your twitter account was hacked

### ISSUE THREAD

**Issue by sherbold** [openjournals/joss#1048]
It seems your twitter account and possibly your DOI registration was hacked. 

https://twitter.com/JOSS_TheOJ/status/1496445475918077952?s=20&t=6fBHf9iiqS4L8zrvHfAB3A

The link in the tweet redirected me to a ... let's say not suited for work website.

**Comment by arfon** [comment]
Thanks for flagging this. We accidentally redirected a DOI to `theoj.com` rather than `theoj.org`. This should now be fixed.
