### ISSUE TITLE
Pre-submission enquiry: Bactopia v2

### ISSUE THREAD

**Issue by rpetit3** [openjournals/joss#1049]
Hello,

I'm the developer of Bactopia (https://bactopia.github.io/), a pipeline for the complete analysis of bacterial genomes. Version 1 of Bactopia was published in a journal in 2020 (https://journals.asm.org/doi/10.1128/mSystems.00190-20). Recently I released version 2 of Bactopia, which is a complete rewrite from Nextflow's DSL1 to DSL2. 

Here's the full changelog of version 2:  https://github.com/bactopia/bactopia/releases/tag/v2.0.0

Would submitting Bactopia v2 to JOSS be acceptable?

Thank you!

**Comment by arfon** [comment]
Followup publications for software that has gone through a major update are generally allowed, as long as the changes between the two versions meet the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion *and* there is some significant new capability.

Not being an expert, it's hard for me to tell if 'Nextflow's DSL1 to DSL2' is a significant change for your users.
