### ISSUE TITLE
Pre-submission enquiry

### ISSUE THREAD

**Issue by dorishung12** [openjournals/joss#1055]
Dear Editors,

Our team built a Python package as described in the paragraph below. We would like to know if our package is within the scope of JOSS.

We present a Python package, _BatteryRateCap_, to facilitate a standardized comparative analysis procedure for batteries across different published datasets. Due to the myriad of battery chemistries and testing procedures that exist today, comparative analysis of battery performance across different cell and electrode designs is challenging. To facilitate reuse and integration of published data into new research studies, we need more standardized reporting of datasets, as recently highlighted by battery experts, [[1](https://pubs-acs-org.offcampus.lib.washington.edu/doi/full/10.1021/acsenergylett.1c00870), [2](https://www-cell-com.offcampus.lib.washington.edu/joule/fulltext/S2542-4351(20)30625-5), [3](https://pubs-acs-org.offcampus.lib.washington.edu/doi/10.1021/acsenergylett.1c01710)] and more consistent data analysis procedures along with the corresponding software infrastructure. _BatteryRateCap_ is an open-source toolbox aimed at streamlining comparative analysis of different battery datasets while facilitating a more efficient data collection process for future reuse. Our goal is to help promote more rigorous and consistent comparative data analysis in the battery community through our toolbox. 

Thank you!

**Comment by arfon** [comment]
This could be in scope, but without seeing the software it's hard to know for sure. I encourage you to submit and for the normal scope review process to handle this.
