### ISSUE TITLE
Pre-submission enquiry

### ISSUE THREAD

**Issue by mlampros** [openjournals/joss#1057]
Dear Joss-team,

I've created an interface to the [OpenAltimetry API](https://openaltimetry.org/data/swagger-ui/) in R programming language (ICESat-2 altimeter photon data) and the [IceSat2R](https://github.com/mlampros/IceSat2R) package was submitted to [CRAN on February 2022](https://cran.r-project.org/web/packages/IceSat2R/index.html). The R package includes code for the interface and moreover the functionality is explained in the vignettes ([first](https://mlampros.github.io/IceSat2R/articles/IceSat-2_Mission_Orbits_HTML.html), [second](https://mlampros.github.io/IceSat2R/articles/IceSat-2_Atlas_products_HTML.html), [third](https://mlampros.github.io/IceSat2R/articles/IceSat-2_Virtual_File_System_Orbits_HTML.html)) based on use cases.

I'd like to ask if the submission of the "IceSat2R" package to Joss would be acceptable?

**Comment by arfon** [comment]
@mlampros – API wrappers are generally not in scope, unless they also deliver significant analysis capabilities. Is the case?

**Comment by mlampros** [comment]
hi @arfon and thank you for your response. 

The [IceSat2R](https://github.com/mlampros/IceSat2R) doesn't include only code for the connection to the OpenAltimetry API. It also includes 

- a [shiny application](https://mlampros.github.io/IceSat2R/reference/select_aoi_global_grid.html) that allows R users to create a global grid of 1-, 5-degrees or based on a user-selected value. The OpenAltimetry API accepts currently queries of 1- or 5-degrees and that way users can avoid potential (query) errors.

- a connection to NSIDC (National Snow and Ice Data Center) to download the [Reference Ground Tracks (RGTs) ](https://icesat-2.gsfc.nasa.gov/science/specs) which are required for the queries ([latest_orbits()](https://mlampros.github.io/IceSat2R/reference/latest_orbits.html), [overall_mission_orbits()](https://mlampros.github.io/IceSat2R/reference/overall_mission_orbits.html), [time_specific_orbits()](https://mlampros.github.io/IceSat2R/reference/time_specific_orbits.html))

- the [second vignette](https://mlampros.github.io/IceSat2R/articles/IceSat-2_Atlas_products_HTML.html) includes a detailed analysis on how a user can combine OpenAltimetry ICESat-2 data with other data sources such as Copernicus Digital Elevation Models (DEM) for comparison purposes (ICESat-2 can be combined with other external data sources as well). This vignette also includes code and information (beyond the connection to the OpenAltiimetry API) that allows users to extract information.

**Comment by arfon** [comment]
Seems like this is under review 😄 https://github.com/openjournals/joss-reviews/issues/4342
