### ISSUE TITLE
Pre-submission enquiry: Is my CLI a good fit for JOSS

### ISSUE THREAD

**Issue by alexhallam** [openjournals/joss#1058]
Here is my open source software: https://github.com/alexhallam/tv. I would like to know if this is something JOSS would accept before I get started on a submission.

1. Be open source (i.e., have an [OSI-approved license](https://opensource.org/licenses/category)).

*It is duel MIT/Unlicense.*

2. Have an obvious research application.

*It was design with researchers, data scientists, and engineers in mind.*

3. Be feature-complete (no half-baked solutions) and be designed for maintainable extension (not one-off modifications).

*The package has had many contributors and does what I originally envisioned it to do.*

4. Minor 'utility' packages, including 'thin' API clients, and single-function packages are not acceptable.

*This is a command line utility package, but I would not call it minor. It is a lot like `cat` and `column`, but for csv files.*

**Comment by arfon** [comment]
Hi @alexhallam – this looks like a useful package but I don't think this fits in [our definition of research software sorry](https://joss.readthedocs.io/en/latest/submitting.html#what-we-mean-by-research-software).
