### ISSUE TITLE
Weird paper page view bug in Safari

### ISSUE THREAD

**Issue by kyleniemeyer** [openjournals/joss#106]
When viewing the [first published paper](http://joss.theoj.org/papers/10.21105/joss.00011) (yay!) in Safari, I see a weird display bug for the JOSS name/link at the top:

The doesn't happen in Firefox or Chrome, and it seems to go away when I click the link... very strange.

<img width="496" alt="screen shot 2016-05-12 at 1 30 36 pm" src="https://cloud.githubusercontent.com/assets/190432/15204238/2e2f6dda-1846-11e6-9630-4f26f7797f1a.png">

**Comment by kyleniemeyer** [comment]
(This is still an issue)

**Comment by parrish** [comment]
:wave: What OS and Safari version did you see this on?  I was able to reproduce it in <= 5.0.5, but it seems fixed in >= 5.1.

**Comment by kyleniemeyer** [comment]
This is gone in my Safari 11.0.2, and doesn't appear in my up-to-date versions of Firefox, Chrome, and Opera, so this is probably fixed.

**Comment by arfon** [comment]
> This is gone in my Safari 11.0.2, and doesn't appear in my up-to-date versions of Firefox, Chrome, and Opera, so this is probably fixed.

My favourite kind of bug, one that fixes itself :-)
