### ISSUE TITLE
Pre-submission enquiry

### ISSUE THREAD

**Issue by RitikaPrasai** [openjournals/joss#1064]
Greetings!

I have recently released a web based application (open source) that can be useful in research related to spatial mutlicriteria anlaysis. I am not sure if I can write about my application in here. Please  suggest. Thank you

**Comment by arfon** [comment]
Possibly? Could you provide a link to the repository and explain whether it meets our [scope requirements](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements)?
