### ISSUE TITLE
HTML non-breaking-spaces from paper markdown end up in paper page and metadata (bibtex export)

### ISSUE THREAD

**Issue by slayoo** [openjournals/joss#1067]
CC @arfon 

As reported here: https://github.com/openjournals/joss-reviews/issues/3219#issuecomment-1107914511

HTML non-breaking spaces like `&nbsp` put into the paper markdown to prevent line breaks in between firstnames and surnames end up in paper metadata (e.g., bobtex export) and paper page, like here:

![image](https://user-images.githubusercontent.com/89685/165000348-85236808-3f99-4ab5-9e84-a67c365f7763.png)

(https://joss.theoj.org/papers/10.21105/joss.03219)

Thanks for help with fixing it!

**Comment by slayoo** [comment]
The `nbsp` is also in the Twitter post:
![image](https://user-images.githubusercontent.com/89685/165000507-b86e97f1-5889-428f-bcfc-dd34e07e14c6.png)

**Comment by arfon** [comment]
As we've fixed this in https://github.com/openjournals/joss-reviews/issues/3219 I'm going to go ahead and close. Thanks for flagging this @slayoo.
