### ISSUE TITLE
Pre-submission enquiry

### ISSUE THREAD

**Issue by JonasHuegel** [openjournals/joss#1070]
Dear JOSS team,
following up on our last enquiry (#1014 ), where we asked if our tool would be in the general scope of JOSS, we are now at a point where we consider submitting the current state of our [work](https://github.com/janschneida/taxodist).  You emphasized it would be in scope if it fulfilled the scholarly effort criterion. Could you give us feedback regarding this matter?
Thank you in advance.  
Best regards!

**Comment by arfon** [comment]
This software looks to be very small (~< 500 LOC) so would almost certainly be considered out of scope in JOSS due to our [substantial scholarly effort criterion](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) sorry.
