### ISSUE TITLE
Unknown status of submission openjournals/joss-reviews#4099

### ISSUE THREAD

**Issue by engyasin** [openjournals/joss#1074]
Dear Journal committee,

After submission of the package https://github.com/openjournals/joss-reviews/issues/4099 , from December 2021. The review process was followed by the authors and changes are made. 

However, about a month earlier no more responses or another issues are discussed. we assume it could be rejection? or just it requires more time? in the last case, should that be clarified as well?

**Comment by arfon** [comment]
Hi @engyasin. The submission is still under review. It looks like your editor @hugoledoux might need to respond, but please rest-assured, the submission is not rejected.
