### ISSUE TITLE
how to update reviewer profile

### ISSUE THREAD

**Issue by lucaferranti** [openjournals/joss#1077]
I see volunteered reviewers are tracked by an excel sheet and new reviewers are added via the form linked on the site. What I could not figure out is how can reviewers manage their profile (update keywords list, languages one is comfortable on, etc.). Is there a log in mechanism somewhere or should I just "revolunteer" with the same github handle? Will that reset my review history?

thanks in advance

**edit**: I see the website allows to login with orcid and then asks for github handle. Could that be used for reviewers too? If the logged in user has a valid github handle, fetch from the reviewers database their information and allow to update from the website. Alternatively allowing to log in with github could also help. No idea how hard to implement either of them would be 😄

**Comment by lucaferranti** [comment]
ah duplicated of #1023 apparently, sorry for the poor background check 😅

**Comment by arfon** [comment]
Yeah, we plan to fix this in the end. In the interim, if you want to update something feel free to let me know here and I can update the spreadsheet manually.
