### ISSUE TITLE
Pre-submission enquiry

### ISSUE THREAD

**Issue by gafrm** [openjournals/joss#1082]
Hi!

I am developping a GUI so that non-tech-savvy researchers can easily gather data using Twitter's API v2 for academic research; would this be of interest to the journal? The only similar software of which I am aware is an R package for collecting Twitter data, but many researchers are not comfortable with R.

Thanks in advance,

gafrm

**Comment by arfon** [comment]
GUI interfaces to other APIs are generally not considered if scope for JOSS but without seeing the software, it's hard to say for certain sorry.
