### ISSUE TITLE
Pre-submission enquiry

### ISSUE THREAD

**Issue by btmonier** [openjournals/joss#1087]
Dear JOSS Editors,

Our team has been working on an extensive R-interface ([rTASSEL](https://github.com/maize-genetics/rTASSEL)) for the open-source Java software [TASSEL](https://bitbucket.org/tasseladmin/tassel-5-source/src/master/) used in genetic analyses. The goal of this package is to provide optimized (1) association mapping methods for complex traits, (2) linkage disequilibrium methods, and (3) relatedness methods for analyzing high-throughput genotypic data in conjunction with providing novel R methods for visualization and downstream analytics of results.

Would this project be in scope for a JOSS publication?

**Comment by arfon** [comment]
Yes, I believe it would be.
