### ISSUE TITLE
Pre-submission enquiry

### ISSUE THREAD

**Issue by erdalkaraca** [openjournals/joss#1090]
Dear JOSS editors,
Within the [ANCP Lab](https://uol.de/en/applied-neurocognitive-psychology) we have been working on a [Python package](https://github.com/ANCPLabOldenburg/ancp-bids) to read/write/query/validate [BIDS](https://bids-specification.readthedocs.io/en/stable/) datasets.
We intend to [merge it back](https://github.com/bids-standard/pybids/pull/863) to an [existing package](https://github.com/bids-standard/pybids) with similar scope.
Our contribution (taking Software Engineering principles into account) consists of a new implementation from scratch whose highlights are a [significantly better runtime performance](https://github.com/bids-standard/pybids/issues/831#issuecomment-1115370663) and a minimal (transitive) [dependency tree](https://github.com/ANCPLabOldenburg/ancp-bids/blob/main/requirements.txt) to external packages.

Best regards,
Erdal

**Comment by arfon** [comment]
Sounds like it would likely be in scope, but may be on the smaller side of what we allow. Feel free to submit and we'll assess scope in detail at that point.
