### ISSUE TITLE
Re-render software paper after project page moved

### ISSUE THREAD

**Issue by blsqr** [openjournals/joss#1094]
I am co-author and co-maintainer of two software projects that were published in JOSS in 2020, [Utopia](https://github.com/openjournals/joss-reviews/issues/2165) and [dantro](https://github.com/openjournals/joss-reviews/issues/2316). Our research group has since dissolved and its GitLab instance where these projects were hosted will have to shut down within the next weeks.
Another project, [DORiE](https://github.com/openjournals/joss-reviews/issues/2313) (@peanutfun), is also affected by this.

We have already migrated the projects to [a GitLab.com group](https://gitlab.com/utopia-project). In the spirit of keeping information up-to-date, we now wanted to enquire what the process would be to re-render the PDF with updated links and update the respective JOSS publication pages? Would that be possible?

During the review of dantro, @arfon mentioned that you "have done so before", and I have already added a comment [in the review issue](https://github.com/openjournals/joss-reviews/issues/2316#issuecomment-1152473251) – but this seems like a better place to discuss such a procedure.

**Comment by arfon** [comment]
We should be able to do this. Please @mention me (@arfon) on the review threads for each of the papers with the new URLs.

**Comment by arfon** [comment]
Sorry, just realised you already did this. Processing them now.
