### ISSUE TITLE
Editorialbot command to update paper repository address

### ISSUE THREAD

**Issue by arfon** [openjournals/joss#1095]
Semi-regularly, authors will move their software repository during the review. Similar to how we support re-assigning the editor at any point during a review, it would be great to be able to do something like:

```
@editorialbot set https://github.com/openjournals/joss as repository
```

/ cc @danielskatz @Kevin-Mattheus-Moerman @xuanxu

**Comment by danielskatz** [comment]
I also wonder about when authors put in something like `https://github.com/openjournals/joss.git` instead. Does this matter?

**Comment by danielskatz** [comment]
We could probably discourage this via documentation, including on the submission form, if so

**Comment by arfon** [comment]
Fixed in https://github.com/openjournals/buffy/pull/72

> I also wonder about when authors put in something like https://github.com/openjournals/joss.git instead. Does this matter?

This is fine as far as I know.
