### ISSUE TITLE
share buttons

### ISSUE THREAD

**Issue by cranmer** [openjournals/joss#110]
Since Altmetrics are mainly based on DOI, it might be nice to have a share button that auto-populates twitter/FB whatever with the title and URL for DOI. 

For example this tweet points to DOI URLs not JOSS URLs

<blockquote class="twitter-tweet" data-partner="tweetdeck"><p lang="en" dir="ltr">Less than a week after our launch, we&#39;ve already got two accepted papers in JOSS: <a href="https://t.co/oGz9mBAj6f">https://t.co/oGz9mBAj6f</a> and <a href="https://t.co/8rAYw3ObNR">https://t.co/8rAYw3ObNR</a> ⚡ 🚀 💥</p>&mdash; Arfon Smith (@arfon) <a href="https://twitter.com/arfon/status/730620896012967938">May 12, 2016</a></blockquote>

<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

**Comment by arfon** [comment]
> For example this tweet points to DOI URLs not JOSS URLs

I this a good or a bad thing? DOIs are better for Altmetrics?

**Comment by danielskatz** [comment]
At the start, it seemed like creating a new type of journal that made the process of easily generating a paper from software easy was the main thing to do.  Now that this works, making the journal look and act  more like a traditional journal seems to me more important. :)

**Comment by danielskatz** [comment]
> > For example this tweet points to DOI URLs not JOSS URLs
> 
> I this a good or a bad thing? DOIs are better for Altmetrics?
> 

pointing to DOIs seems good to me.

**Comment by arfon** [comment]
> Now that this works, making the journal look and act more like a traditional journal seems to me more important. :)

👍 agreed!

**Comment by pboesu** [comment]
Altmetrics require at least one meta data tag that is an identifier, i.e. `citation_doi` in the case of JOSS: https://help.altmetric.com/support/solutions/articles/6000141419-what-is-good-metadata-

They also prefer that the `citation_issn` is present.

I've created PR https://github.com/openjournals/whedon/pull/8 to whedon implementing both tags in the article HTML template.

**Comment by arfon** [comment]
The `citation_doi` field (and more) was added in https://github.com/openjournals/whedon/pull/12

**Comment by cranmer** [comment]
👍

**Comment by pboesu** [comment]
I had filed a ticket with the altmetric support about the lack of coverage some months ago. 
Given the metadata updates, I have now reopened that ticket (https://help.altmetric.com/support/tickets/44401 - not sure if that is accessible for anyone besides me) , so hopefully full altmetric coverage will be available soon for JOSS.

**Comment by pboesu** [comment]
Just heard back from almetrics support. Coverage should work going forward. See e.g. https://www.altmetric.com/details/24601435
