### ISSUE TITLE
Pre-submission enquiry

### ISSUE THREAD

**Issue by beanumber** [openjournals/joss#1102]
Hello, we are hoping to submit our paper *MacLeish: An R package for monitoring environmental conditions in Whately, Massachusetts* to JOSS. The paper is based around the `macleish` R package. 

Repo: https://github.com/beanumber/macleish
Paper: 
  - [PDF for easy reading](https://github.com/beanumber/macleish/blob/master/joss_paper/paper.pdf)
  - [markdown source](https://github.com/beanumber/macleish/blob/master/joss_paper/paper.md)
  - [R markdown source](https://github.com/beanumber/macleish/blob/master/joss_paper/paper.Rmd)

Please let me or @rudeboybert know if there is anything else you need from us. 

Thank you!

**Comment by danielskatz** [comment]
I think you should just go ahead and submit, then let us decide.  One issue that is likely to come up is the relatively small amount of code, which will likely lead the editor to discuss if this submission meets the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS

**Comment by beanumber** [comment]
Thanks @danielskatz . Can you clarify: do you mean the relatively small amount of code *in the paper*? Or the relatively small amount of code *in the package*? (The former would be easy for us to address, but the latter not so much.)

**Comment by danielskatz** [comment]
In the package

**Comment by beanumber** [comment]
OK. Well, I guess we'll take our chances! Thanks!
