### ISSUE TITLE
clarifying example paper in documentation

### ISSUE THREAD

**Issue by ajohnson-uoregon** [openjournals/joss#1103]
It would be extremely helpful (especially for those not very familiar with markdown) if the documentation mentioned that the three dashes before and after the title, authors, affiliations, etc metadata _are_ necessary. The error message if they're missing is rather unhelpful:

```
Error running filter /usr/local/share/openjournals/data/filters/normalize-metadata.lua:
attempt to index a nil value
stack traceback:
	...al/share/openjournals/data/filters/normalize/authors.lua:46: in upvalue 'normalize_authors'
	...l/share/openjournals/data/filters/normalize-metadata.lua:56: in function 'Meta'
```

**Comment by arfon** [comment]
Where would you suggest we document this?

**Comment by ajohnson-uoregon** [comment]
Somewhere near the example paper here: https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography

**Comment by pdebuyl** [comment]
There are already a few words of caution there:

> Note that the paper ends with a References heading, and the references are built automatically from the content in the .bib file. You should enter in-text citations in the paper body following correct [Markdown citation syntax](https://pandoc.org/MANUAL.html#extension-citations). Also note that the references include full names of venues, e.g., journals and conferences, not abbreviations only understood in the context of a specific discipline.

The first sentence could start with

> Note that the paper begins by a metadata section (the enclosing `---` lines are mandatory) and ends with a References heading (...)
