### ISSUE TITLE
Pre-submission enquiry

### ISSUE THREAD

**Issue by fluhus** [openjournals/joss#1107]
__*biostuff*, a computational biology package suite for Golang__

Dear JOSS editors,

I am writing to inquire whether *[biostuff](https://github.com/fluhus/biostuff)* would be a good fit for submission to JOSS. Over the past 8 years I have been developing *biostuff* for my computational biology research. It is a suite of Golang packages that includes parsers, algorithms, and sequence manipulation utilities.

The project has a similar purpose to *[biogo](https://joss.theoj.org/papers/10.21105/joss.00167)*, but it differs by offering minimalist API's that require near-zero learning from its users. It can serve researchers who need quick, straightforward solutions for their bioinformatic work, especially those without an extensive background in programming or in Go.

Best regards
Amit Lavon

**Comment by danielskatz** [comment]
I think this looks like something that we would consider, with a final determination that can be made once you submit and we start the process.
