### ISSUE TITLE
Pre-submission enquiry

### ISSUE THREAD

**Issue by matsvanes** [openjournals/joss#1109]
Dear Editorial Board,

I would like to enquire about to possibility to submit to JOSS, as well as its format. We are interested in submitting a software tool that enables researchers to easily produce reproducible code and accompanying data. This is highly sought after in the field of neuroimaging, where the datasets are large, and analyses are complex. Data and code sharing is not standard, and even if they are shared, often reproducibility of published results is still limited.
The tool is not a standalone repository (which I believe is most common for JOSS submissions), but is integrated in the widely adopted open-source [FieldTrip Toolbox](https://github.com/fieldtrip/fieldtrip). It is therefore unclear to me whether it would be considered for publication in JOSS. 
Additionally, we have developed tutorials to help people get started with the tool. Currently, these are incorporated in the [pre-print](https://doi.org/10.1101/2021.02.05.429886 ) of the tool, but could potentially be added to the [FieldTrip website](https://www.fieldtriptoolbox.org/). I would like to ask if and how I could best incorporate the tutorials in the journal submission.

Many thanks for your help,

Mats W.J. van Es, PhD

**Comment by arfon** [comment]
@matsvanes – we have reviewed and published papers where the functionality is associated with a larger submission (in this case FieldTrip Toolbox) but it depends on a few things such as:

- Are there other papers about the 'parent' package?
- How significant/substantial is the contribution for this submission? Do they pass our [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion?
- Are the authors of the parent package happy for a paper to be published for a part of their overall work?

**Comment by arfon** [comment]
OK thanks @matsvanes.

> Based on my estimation the contribution does pass the substantial scholarly effort criterion, including having over 300 LOC, a substantial number of commits as well as authors, the parent package being well established, and the new contribution is likely to be cited in the field.

Is there a way to take a peek at the JOSS-specific contributions you'd be proposing for review here?

**Comment by matsvanes** [comment]
This is the question I had regarding the format of submission, i.e. how do we submit part of the parent toolbox for review? Is it helpful to list the functions that underwent changes for the implementation of the tool (and of course, entirely new function)? Also, would the documentation (outlined in the preprint) be of use, e.g. when incorporated in [fieldtrip/website](https://github.com/fieldtrip/website)? Currently the tutorial code is available at https://github.com/matsvanes/reproducescript
I believe the modified/added functions are the following:

- [/utilities/private/reproducescript.m](https://github.com/fieldtrip/fieldtrip/blob/master/utilities/private/reproducescript.m)
- [ft_reproducescript.m](https://github.com/fieldtrip/fieldtrip/blob/master/ft_reproducescript.m)
- [utilities/private/ft_preamble_init.m](https://github.com/fieldtrip/fieldtrip/blob/master/utilities/private/ft_preamble_init.m)
- [utilities/private/ft_preamble_loadvar.m](https://github.com/fieldtrip/fieldtrip/blob/master/utilities/private/ft_preamble_loadvar.m)
- [private/savevar.m](https://github.com/fieldtrip/fieldtrip/blob/master/private/savevar.m)
- [utilities/private/savevar.m](https://github.com/fieldtrip/fieldtrip/blob/master/utilities/private/savevar.m)
- [utilities/private/ft_postamble_savevar.m](https://github.com/fieldtrip/fieldtrip/blob/master/utilities/private/ft_postamble_savevar.m)
- [utilities/private/ft_postamble_savefig.m](https://github.com/fieldtrip/fieldtrip/blob/master/utilities/private/ft_postamble_savefig.m)
- [utilities/private/isplottingfunction.m](https://github.com/fieldtrip/fieldtrip/blob/master/utilities/private/isplottingfunction.m)
- [utilities/private/make_or_fetch_inputfile.m](https://github.com/fieldtrip/fieldtrip/blob/master/utilities/private/make_or_fetch_inputfile.m)
- [utilities/private/save_large_cfg_fields.m](https://github.com/fieldtrip/fieldtrip/blob/master/utilities/private/save_large_cfg_fields.m)
- [private/ignorefields.m](https://github.com/fieldtrip/fieldtrip/blob/master/fileio/private/ignorefields.m)
- [fileio/private/ignorefields.m](https://github.com/fieldtrip/fieldtrip/blob/master/fileio/private/ignorefields.m)
- [utilities/private/ignorefields.m](https://github.com/fieldtrip/fieldtrip/blob/master/utilities/private/ignorefields.m)
- [contrib/misc/private/ignorefields.m](https://github.com/fieldtrip/fieldtrip/blob/master/contrib/misc/private/ignorefields.m)

**Comment by matsvanes** [comment]
Hi @arfon - any news on this front?

**Comment by arfon** [comment]
> This is the question I had regarding the format of submission, i.e. how do we submit part of the parent toolbox for review? Is it helpful to list the functions that underwent changes for the implementation of the tool (and of course, entirely new function)? 

Yes, please make it clear in the submission form but also document this in the paper for completeness too. Thanks!
