### ISSUE TITLE
published paper should include "how to cite" instructions

### ISSUE THREAD

**Issue by danielskatz** [openjournals/joss#111]
The PDF of a published paper should ideally include isome "how to cite this paper" info.  The journal page for that paper should include this info too, and ideally in a manner that would generate bibtex and other citation styles.

(this is being broken off #107)

**Comment by arfon** [comment]
This was fixed in https://github.com/openjournals/whedon/commit/3fa7c4626ec7ab243111a75fd2c0acad96f20a89
