### ISSUE TITLE
Pre-submission enquiry

### ISSUE THREAD

**Issue by LyceanEM** [openjournals/joss#1114]
Dear Editorial Board,

I would like to enquire about submitting to JOSS. I am interesting in submitting [LyceanEM](https://lyceanem-python.readthedocs.io/en/latest/index.html), a software tool that allows for rapid virtual prototyping of antennas and antenna arrays, together with channel modelling in the frequency and time domain. Applications using this software have been published in the literature, and examples and tutorials are included in the documentation. 

Many Thanks

Timothy Pelham

**Comment by arfon** [comment]
This looks like it would probably be in scope, provided there is a strong research case for the use.
