### ISSUE TITLE
Pre-submission enquiry

### ISSUE THREAD

**Issue by riccarl** [openjournals/joss#1118]
Dear Editor,
here is enclosed a summary of a paper describing functionaliti of a R package called JFM already available in CRAN repository, and the code is available at github repository riccarl/JFM.
Please let me know if it can be considered for a submission and eventually publication.
Best Regards
Riccardo Campana
Servizio Geologico  - Provincia di Trento. Italy

Summary

The basis of a structural outcrop analysis is a field data collection of a representative orientation of rock joints. Data are successively plotted on a Schmidt stereogram to obtain, by statistical data analysis, the main set of joints in order to study the reciprocal intersection and the unfavourable combination with respect to rockfall. Sometimes the outcrop is not easy to be reached and
studied due to its position and steepness, and unless you are an expert climber, you must settle for a geological survey at the bottom of the rock cliff. This paper present a methodology to extract structural data from outcrops at a scale of a hectometer by applying available packages written for R, along with new additional algorithms developed to perform the search function of neighbouring
mesh elements and fit the least square plane of the 3D points. The process starts from a 3D point cloud with about 30 cm resolution of the studying outcrop; a 3D mesh is derived applying Vcg ballpivoting (Bernardini et al. 1999) function
of Rvcg R package (Schlager 2017), listing each triangular neighbouring facet and starting a search on the neighbours which satisfy co-planarity condition.
The most representative joints were found out by filtering all identified planes on the base of the sum of facets area. The relative poles were calculated applying a least square plane fitting function to the vertex of plane facets which were plotted on a lower hemisphere Schmidt stereogram. Density contour and density maxima were pointed out to find out the poles of representative joint families on
the stereogram and then visualized on the 3D surface mesh by the same colour.

**Comment by arfon** [comment]
Hi @riccarl. It's possible this could be in scope, but the software as currently presented/packaged would be rejected from JOSS as it falls far below the expected standards we expect of submissions. Please read the submission guidelines: https://joss.readthedocs.io/en/latest/submitting.html and familiarise yourself with the review criteria to gain an understanding of how JOSS submissions are assessed: https://joss.readthedocs.io/en/latest/review_criteria.html
