### ISSUE TITLE
Pre-submission enquiry

### ISSUE THREAD

**Issue by jhpantel** [openjournals/joss#1124]
Hello,

My name is Jelena Pantel, and I am a researcher in ecology & evolutionary biology. I have recently made a software package that runs a few simulation models of eco-evolutionary dynamics, and then uses machine learning and Approximate Bayesian Computing to make inference from data (either observed data or data generated from these simulations).

Some papers exist that run a simulation model and compare empirical data to model simulations using ABC or Machine Learning. Right now, each model has its own set of code. I would like to combine them all into 1 R package. Right now the package focuses on 3 models.

I have made the repository public, and the 2 vignettes explain the work done so far. I am interested in learning whether I might consider a submission to your journal based on this work.

https://github.com/jhpantel/ecoevoR

Thank you,

Prof Dr Jelena Pantel
Prof of Ecosystem Modelling
University of Duisburg-Essen (Germany)

**Comment by arfon** [comment]
@jhpantel - thanks for your enquiry to JOSS. Unfortunately, this software would likely fall foul of our [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) test.

One possible alternative to JOSS is to follow [GitHub's guide](https://guides.github.com/activities/citable-code/) on how to create a permanent archive and DOI for your software. This DOI can then be used by others to cite your work.
