### ISSUE TITLE
Pre-submission enquiry

### ISSUE THREAD

**Issue by bsnichols** [openjournals/joss#1128]
Hi there, 

I'm trying to compile the PDF of my paper using Github for submission and for some reason it's struggling with the references. I can't find any further guidance on why this might be. It's stating "Warning:  Citeproc: citation XXXX not found". I have my references in a .bib file in the same location as the paper.md. I'm sure it's something really simple that I've missed.

Best wishes,
Bethany

**Comment by xuanxu** [comment]
I seems the error comes from the wrong indentation of the author list in the paper's metadata, from the 3rd author on: https://github.com/bsnichols/GAGA/blob/main/paper/paper.md?plain=1#L18-L34

**Comment by bsnichols** [comment]
Hi there, thank you for flagging this, I couldn't see where the issue was. There were a few more bugs but I think I've got them all and it's compiling now - thanks for your help!
