### ISSUE TITLE
pre-submission enquiry

### ISSUE THREAD

**Issue by Hannibal83dk** [openjournals/joss#1129]
Dear JOSS
I have created an R package for assessing stability of expression data from RT-qPCR experiments and would like to make a Pre-submission enquiry on whether I could publish this in your journal.

I am working with RT-qPCR and expression analysis in samples from ovarian cancer patients
In this respect I have used the RefFinder (1) online tool for its simple stability ranking of targets based on Normfinder(2), GeNorm(3), Bestkeeper(4), and the delta-Ct method(5), four widely used gene stability algorithms. 
However, I found the workflow to be quite strenuous when copying and pasting back and forth many different data sets, pressing buttons changing panes, copy and pasting some more, editing the text files before importing into the popular free statistical data analysis tool, R.

The RefFinder online tool is available on github for anyone to host on their own website. I however, at one point found myself in the situation that the main host http://www.heartcure.com.au/reffinder/ was deemed unsafe, presumably caused by an out-of-date authentication certificate, and was forced to look for alternative sites hosting the tool.
I have therefore been working on a package for R to automate much of this workflow and make it easy to import data and receive results, either for further processing or to print graphs and make excel tables quickly.
I believe this package could be of great interest for other researchers using the RefFinder tool. 

Package features:
-	Easy import of datasets individually or in bulk.
-	Supports input data from:
o	csv
o	tsv
o	excel
-	Provides analysis from:
o	 Bestkeeper.
o	Normfinder.
o	GeNorm.
o	Delta-Ct.
o	RefFinder.
-	Easy graphing:
o	Singular.
o	Multifaceted form for comparisons.
-	Exporting results:
o	Text file formats (csv or tsv)
o	Excel format
-	Easy completely interactive function that through dialog windows ask for input data, and output paths for graphs and table export.

Package dependancies:
For Normfinder (2) (Andersen et. al. 2004) calculations the r.NormOldStab5.txt file is downloaded from https://moma.dk/normfinder-software, website and sourced by the rf_normfinder function to provide access to the Nomfinder function found in this script.
For GeNorm (3) the ctrlGene package found at the cran repository is used. This package is also used for complete BestKeeper (4) analysis.
Other dependencies are ggplot2, reshape2, readxl, openxlsx and data.table packages either available from cran or included in base R.

The package has been tested for windows and for linux (ubuntu 22.04) and is being updated continually.

I hope you find this package to be publishable in JOSS since it could potentially save many researchers a lot of time and effort for identifying stable controls in miRNA/mRNA experiments. Something that is easily automated and might potentially help to get more reproducible results between group as errors due to manual operations such as copy, and pasting are eliminated.

Kind Regards
Patrick Petersen

1)	F Xie, P Xiao, D Chen, L Xu, B Zhang. 2012. miRDeepFinder: a miRNA analysis tool for deep sequencing of plant small RNAs. Plant molecular biology 80 (1), 75-84.

2)	NormFinder: Andersen CL, Jensen JL, Orntoft TF. 2004. Normalization of real-time quantitative reverse transcription-PCR data: a model-based variance estimation approach to identify genes suited for normalization, applied to bladder and colon cancer data sets. Cancer research 64:5245-5250.

3)	Genorm: Vandesompele J, De Preter K, Pattyn F, Poppe B, Van Roy N, De Paepe A, Speleman F. 2002. Accurate normalization of real-time quantitative RT-PCR data by geometric averaging of multiple internal control genes. Genome biology 3:RESEARCH0034.

4)	BestKeeper: Pfaffl MW, Tichopad A, Prgomet C, Neuvians TP. 2004. Determination of stable housekeeping genes, differentially regulated target genes and sample integrity: BestKeeper--Excel-based tool using pair-wise correlations. Biotechnology letters 26:509-515.

5)	The comparative delta-Ct method: Silver N, Best S, Jiang J, Thein SL. 2006. Selection of housekeeping genes for gene expression studies in human reticulocytes using real-time PCR. BMC molecular biology 7:33.

**Comment by arfon** [comment]
Could you provide a link to the software?

**Comment by Hannibal83dk** [comment]
I have sent you and invite, the repository is private at the moment but will be made public when fully ready and published.

Here is a link:
https://github.com/Hannibal83dk/refSeeker

I am unsure if it works but you should have acces to it.

Thanks
Patrick

**Comment by arfon** [comment]
Thanks. I just checked it out. I'm almost certain this will fall foul of our [substantial scholarly effort test](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort).

**Comment by Hannibal83dk** [comment]
Hey, thanks for a swift reply.

May I ask if if this is due to commit history, significance or maybe number of authors?

**Comment by arfon** [comment]
I'm making a judgement purely based on lines of code. Anything under ~1000 LOC is typically at risk of being considered out of scope.

**Comment by Hannibal83dk** [comment]
Ok thanks alot
