### ISSUE TITLE
Links on submission page point to JOSS rather than JOSE documentations

### ISSUE THREAD

**Issue by AoifeHughes** [openjournals/joss#1134]
This page https://jose.theoj.org/papers/new links to https://joss.readthedocs.io/en/latest/submitting.html rather than something more appropriate like https://openjournals.readthedocs.io/en/jose/submitting.html. The other links here are off too. 

Pull request incoming.

**Comment by danielskatz** [comment]
closing, since the issue seems to have been resolved with the merged PR - feel free to reopen if I'm wrong.
