### ISSUE TITLE
Pre-submission enquiry: Metrics As Scores

### ISSUE THREAD

**Issue by MrShoenel** [openjournals/joss#1136]
Dear JOSS,

would you consider [__`mrshoenel/metrics-as-scores`__](/mrshoenel/metrics-as-scores) for submission?

It is a package and tool that was created to accompany a paper currently under review. While we used a certain dataset with software metrics, the package is intended to be used with arbitrary data. We have added a how-to for using own data.

The package unifies the way we can fit distributions and conduct statistical tests. More than 100 continuous distributions can be fitted using maximum likelihood estimation, and more than 20 discrete distributions can be fit by minimizing a mixed-variable global optimization problem (using Pymoo). Additionally to that, empirical distributions (both, continuous and discrete) and smooth approximate Kernel density estimates are available. Applicable statistical tests, such as the Cramér-von Mises- or Epps–Singleton-tests, are automatically performed.

There is a web application that is deployed at <https://metrics-as-scores.ml/> for you to test. The web application has many features of its own, such as being able to obtain scores for own metric values or to pseudo-randomly sample from context-dependent (conditional) distributions.

Thank you for your consideration.

**Comment by danielskatz** [comment]
Sorry for the delay in responding - Please see the first three headings under https://joss.readthedocs.io/en/latest/submitting.html#submitting-a-paper-to-joss and if you think the software meets those requirements, then submit it and if there are any issues, we'll be better able to check after the submission is in
