### ISSUE TITLE
Pre-submission enquiry: mvp

### ISSUE THREAD

**Issue by 0xaf1f** [openjournals/joss#1137]
Is https://gitlab.com/LPCDRP/mvp acceptable for this journal?
It's had approximately 1500 installations / year via [conda](https://anaconda.org/bioconda/mvp) and cited in two works.

This code enables a new sort of analysis that isn't typically done, so while it's under 1000 LOC (but over 300), I wouldn't say it's trivial or insignificant.

My main question is whether the requirement of 3 months of effort refers to actual writing of the code or the process of testing, development, and refinement.

**Comment by danielskatz** [comment]
This seems like it is, or could be in scope, and you should probably submit it and if there are any issues, we'll be better able to check after the submission is in.  The three months is mostly time, that this isn't something you wrote overnight, but it's a loose criteria, not a strict one, along with the others collectively.
