### ISSUE TITLE
Pre-submission enquiry: resubmission

### ISSUE THREAD

**Issue by EGaraldi** [openjournals/joss#1139]
Dear JOSS editors,
I submitted a paper about my code [CoReCon](https://github.com/EGaraldi/corecon) in 2020 and got fairly positive reviews. However, I had to discontinue the review process due to personal reasons (as explained to the assigned editor at the time, which is now not part anymore of JOSS). I have now addressed the referee reports and would like to resubmit my paper. My questions:
- Is it possible? 
- Should I start a new submission or is there a way to re-open the old review process?

Thank you in advance. Best regards,
Enrico Garaldi

**Comment by danielskatz** [comment]
Yes, it's possible. You should start a new submission, and when you submit, include the link to the old submission in the description and explain what you have done since that time.
