### ISSUE TITLE
software with long history, multiple versions, and multiple authors

### ISSUE THREAD

**Issue by carandraug** [openjournals/joss#114]
What is the policy for JOSS about academic FOSS software that is not being developed only by academics, that is done outside a typical research group, over many years, and with a large number of contributors that changes heavily over time?

My specific example is [Octave](http://octave.org/). This has been developed since 1992, and while the number of developers was very small at the start, it has [increased a lot](https://www.gnu.org/software/octave/doc/interpreter/Acknowledgements.html) after 2000. Also, developers that were very active 5 years ago are no longer involved at all. There is also no typical research group driving its development. I would image Scipy and R to be a similar example that many will be more familiar with.

If the problem JOSS tries to solve is to give credit to the authors, and if the list of authors of a JOSS publication does not change, then how to give credit to those that join development later?

I couldn't find any mention of software versions on the ["documentation"](http://joss.theoj.org/about). At the moment, this "hack of the academic-credit system" seems targeted to cite software that won't have more development.

I think the most obvious solution would be one publication per software release. Not patch/bug-fixing releases of course, only releases that have significant new features. Maybe this is so obvious that you found it not worth documenting on the JOSS guidelines.

But what is the policy about authors?  I would guess those involved in the development since the last publication although I can see a case to be made to include everyone ever involved.

If the policy then is to have one publication per software release, what to do about software that has already seen several major releases?  One initial publication for all the previous releases? Or one publication for each release with the authors involved at the time?

**Comment by arfon** [comment]
Great questions @carandraug and to be honest we don't have a solid answer for you right now. I definitely want us to support authorship for releases/versions/pull requests in the future.

> If the problem JOSS tries to solve is to give credit to the authors, and if the list of authors of a JOSS publication does not change, then how to give credit to those that join development later?

We can (and must) address this in JOSS.

> I think the most obvious solution would be one publication per software release. Not patch/bug-fixing releases of course, only releases that have significant new features. Maybe this is so obvious that you found it not worth documenting on the JOSS guidelines.

Yes, although I think my preference is to leave this up to the submitting authors and support a multitude of approaches. Different projects use versioning in different ways and so I'd hate to mandate a particular policy on a project just because that's the only thing JOSS can support.

> But what is the policy about authors? I would guess those involved in the development since the last publication although I can see a case to be made to include everyone ever involved.

I would suggest people who have contributed to the code since the last release. I actually started hacking on some code that could automatically generate this: https://gist.github.com/arfon/478b2ed49e11f984d6fb#file-generate-L39-L101

I don't think we'll ever want to completely automate authorship though as lots of people will want to list collaborators that haven't written code (their bosses for example).

BTW, there's a related discussion already going on here: https://github.com/openjournals/joss/issues/52

**Comment by carandraug** [comment]
>> I think the most obvious solution would be one publication per software release. Not patch/bug-fixing releases of course, only releases that have significant new features. Maybe this is so obvious that you found it not worth documenting on the JOSS guidelines.
>
> Yes, although I think my preference is to leave this up to the submitting authors and support a multitude of approaches. Different projects use versioning in different ways and so I'd hate to mandate a particular policy on a project just because that's the only thing JOSS can support.

I am not suggesting to mandate a software release policy. There could still be software releases in between paper releases. I guess this would work better in projects that have a separate bugfix branch.

The way I see it, the abstract of such papers then becomes similar to a list of changes since their last publication and it would be up to the reviewers to decide whether it's of enough significance to warrant a new publication.

> I don't think we'll ever want to completely automate authorship though as lots of people will want to list collaborators that haven't written code (their bosses for example).

Agreed.  There are also many cases where the author information is simply not correct.  Just because modern VCS allow for an history that reflects who did what, doesn't mean that people use it like that.

**Comment by danielskatz** [comment]
Is this the same as #52 ?

**Comment by arfon** [comment]
> The way I see it, the abstract of such papers then becomes similar to a list of changes since their last publication and it would be up to the reviewers to decide whether it's of enough significance to warrant a new publication.

@carandraug 👍.

Given the similarity of this discussion to #52 I think we should close this issue and move the coversation over there. Does that sound OK?

**Comment by carandraug** [comment]
> Given the similarity of this discussion to #52 I think we should close this issue and move the coversation over there. Does that sound OK?

That other issue sounded more focused on individual PR but I guess in the end it all boils down to the same.
