### ISSUE TITLE
Pre-submission enquiry: kimura R package

### ISSUE THREAD

**Issue by lbozhilova** [openjournals/joss#1142]
Dear JOSS,

Would you consider [lbozhilova/kimura](https://github.com/lbozhilova/kimura) for publication in JOSS? It is an R package for fitting 2-parameter Kimura distributions to mtDNA heteroplasmy data, and features some optimisations and significant extensions of previously available Python code ([WeiWei060512/Kimura-Distribution](https://github.com/WeiWei060512/Kimura-Distribution)).  

I originally wrote it for personal use but I was recently made aware it is also used by others in the mitochondrial biology field, with the GitHub repository already cited by [Broz _et al._ (2022)](https://www.pnas.org/doi/10.1073/pnas.2206973119) and [Giannakis _et al._ (2022)](https://www.biorxiv.org/content/10.1101/2022.09.06.506828v1). However, I realise that in terms of size and GitHub editing history it is somewhat borderline for JOSS.

All the best,
Lyuba Bozhilova

**Comment by danielskatz** [comment]
Sorry for the delay in responding - Please see the first three headings under https://joss.readthedocs.io/en/latest/submitting.html#submitting-a-paper-to-joss and if you think the software meets those requirements, then submit it and if there are any issues, we'll be better able to check after the submission is in
