### ISSUE TITLE
Pre-submission enquiry

### ISSUE THREAD

**Issue by StankovicLab** [openjournals/joss#1145]
Hello, 

I have a nice application I've coded that makes viewing Auditory Brainstem Responses easier for users, can semi-automatically find thresholds, and make paper ready figures. I would like to publish with JOSS but my PI is very particular about releasing anything without it being published already. Is it possible to do this with JOSS? How would I go about creating this submission?

Thank you,
Stephen McInturff
stephen_mcinturff@stanford.edu

**Comment by danielskatz** [comment]
For JOSS to review it, it must be open source with an OSI-approved license. We will not review submissions that don't meet these criteria.  Sorry.
