### ISSUE TITLE
Submitting a Library

### ISSUE THREAD

**Issue by jmdelahanty** [openjournals/joss#1148]
Hello! I've just discovered this awesome journal and I was wondering about whether or not something I've worked on could be applicable. How do I tell? Im not a professional software developer and, frankly, I think there's solutions to what I've tried to work on that are better overall, but I spent a fair bit of time working on it and learned a lot! I feel like writing about it in a place like this could be a great way to share our lab's experience with doing something.

Any advice?

Thank you!

**Comment by arfon** [comment]
@jmdelahanty – I'd encourage you to review these submission guidelines here which should hopefully help? https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements
