### ISSUE TITLE
Pre-submission enquiry / R package RCzechia 

### ISSUE THREAD

**Issue by jlacko** [openjournals/joss#1150]
Dear JOSS,

would you consider https://github.com/jlacko/RCzechia for publication in JOSS? It is an R package for working with spatial data in context of the Czech Republic, in its scope somewhat similar to what does `{tigris}` does for the US or `{rgugik}` for our Polish neighbors (rgugik has appeared in JOSS a few years back / https://joss.theoj.org/papers/10.21105/joss.02948). RCzechia has been on CRAN for some time / https://cran.r-project.org/package=RCzechia and is included in its Spatial Task View.

I originally wrote the package for personal use, but it has grown over the years and found some audience already. The package is by its nature limited in scope to users with local interest, and the volume of code may be borderline from a pure LOC count point of view. On the other hand a significant effort has been put into curating, documenting & validating the underlying datasets (some of which is visible in ./data-raw directory of the repo, which is however ignored in the package once built & distributed).

Thank you for your advice

Jindra Lacko

**Comment by danielskatz** [comment]
Please see the first three headings under https://joss.readthedocs.io/en/latest/submitting.html#submitting-a-paper-to-joss and if you think the software meets those requirements, then submit it and if there are any issues, we'll be better able to check after the submission is in
