### ISSUE TITLE
make JOSS bot toot to mastodon

### ISSUE THREAD

**Issue by danielskatz** [openjournals/joss#1153]
It would be nice if we could toot about newly published papers to fossodon.org

We probably need a JOSS account there first.

These toots should at least be title and DOI, ideally also abstract (or some part of it), link to source code, authors

cc @mfenner

**Comment by mfenner** [comment]
It might be nice to investigate the ActivityPub protocol how to this can best be done. I assume fully automated, but maybe over time pulling in the comments to a JOSS page.

**Comment by arfon** [comment]
Editorial bot does this now.

**Comment by remram44** [comment]
https://fosstodon.org/@joss
