### ISSUE TITLE
How can I change my Domain in joss_reviewers spreadsheet?

### ISSUE THREAD

**Issue by erik-whiting** [openjournals/joss#1154]
Hello! I first signed up as a reviewer a year ago (maybe more, I'm not sure) and have learned a lot since then. Is there a way I can update the values in the "Domains/topic areas you are comfortable reviewing" and "Other Programming Languages" columns for myself? No big deal if not, I just want to be helpful 👍

**Comment by danielskatz** [comment]
Can you say the new values you want here?  If not, feel free to email me (d.katz@ieee.org) and I'll get this updated either way

**Comment by erik-whiting** [comment]
Thanks @danielskatz, looks good!
