### ISSUE TITLE
Pre-submission enquiry

### ISSUE THREAD

**Issue by ExtremOPS** [openjournals/joss#1162]
Dear JOSS-editors,

my coworker and I are the maintainer of [OSAFT](https://gitlab.com/acoustofluidics/osaft). We already published versoin 0.9.x in [FrontiersInPhysics](https://www.frontiersin.org/articles/10.3389/fphy.2022.893686/full) last year.

Since then we added new freatures and models. The review for the first publication in FrontiersIn was probably more concerned with the "usefulness" and "demand" for this software rather than its code quality and methodology. We would really like to submit a new version 1.4.x to JOSS. Would that be possible?

**Comment by ExtremOPS** [comment]
Dear JOSS-editors,

I wanted to ask if you have any information regarding my request for us.

Thank you in advance

**Comment by arfon** [comment]
While we do allow multiple publications for a given piece of software, we'd expect this to be a major new release. Can you share more information about the changes that have been made to the software since the [earlier article](https://www.frontiersin.org/articles/10.3389/fphy.2022.893686/full)?

A link to a diff on GitLab would could be a helpful way to illustrate the changes.

**Comment by ExtremOPS** [comment]
Hi @arfon,

thank you for your response. Before I come to our answer, let me quickly explain what the purpose of the software is. @frankhauser

**Comment by ExtremOPS** [comment]
Hi @arfon,

thank you for your response 👍🏽. Before I come to the answer, let me quickly explain what the purpose of the software is. 

In the domain of acoustophoresis - _particle manipulation by means of sound waves_ - one of the most wanted information is the direction and magnitude of the so-called acoustic radiation force (ARF) which appears due scattering of the acoustic wave at the surface of the suspended particle. There are a handful theories that solve this problem for different approximations of the scatterer (e.g., rigid, inviscid-fluid like, viscous, thermo-viscous), the suspending medium (e.g., inviscid, viscous, visco-elastic), and approximations of the relative size of the scatterer to the acoustic wavelength.

Our aim with OSAF is it to gather as many theories with a common easy interface such that the user can easily compare and compute the ARF for different theories and so on.

Since the last publication which was `v.0.9.14` we are at the moment with releases at `v1.3.8`. The differences since then can be seen [here](https://gitlab.com/acoustofluidics/osaft/-/compare/v0.9.14...v1.3.8?from_project_id=31754220&straight=false). A summary of the implemented changed since the laste publication is

- Hasegawa (1969) model added (_frontend_)
- Doinikov (2021) viscous part of model added (_frontend_)
- Velocity potential and pressure plots added (_frontend_)
- General Solution to Doinikov (1994) models added (_frontend_)
- Simplified unit testing (_backend_)
- Doinikov (2021) viscoelastic scattering field added (_frontend_)

with the following planned additions before we would submit to JOSS

- Karlsen (2015) model (_frontend_)
- Streamingplots for viscous part of Doinikov (2021) (_frontend_)
- Re-factoring of plotting capabilities to make code more maintainable (_backend_)

I hope, I could express the current and planned changes well enough to give you a general overview. If you need more (detailed) information do not hesitate to contact us again.

Thank you very much!

**Comment by danielskatz** [comment]
Can you give us some idea of the number of months between the earlier publication and this planned one?  And the amount of new code that you expect?

**Comment by ExtremOPS** [comment]
Hi @danielskatz,

the last publication was June 2022. We would plan to have it ready around summer this year. Regarding the chances, please have a look to the comment before.

**Comment by danielskatz** [comment]
ok, now I see the link

**Comment by ExtremOPS** [comment]
@danielskatz @arfon Did you had a chance to have a glimpse at the posted link and think about the planned additions? And if so, could you judge if our updates and software are feasible for JOSS? We would really like to publish with you and start the publication process. If you have any further questions, do not hesitate to contact me.
Thank you in advance!

**Comment by danielskatz** [comment]
To me, it seems like it is worth submitting - this might lead to a scope review by the editors, which would be the best way to be sure that the update is sufficient.

**Comment by ExtremOPS** [comment]
@danielskatz thank you for the fast reply. We will finish on our side the mentioned steps and start preparing a publication according to [Submitting a paper to JOSS](https://joss.readthedocs.io/en/latest/submitting.html#submitting-a-paper-to-joss). I am looking forward to the transparent process.
