### ISSUE TITLE
Pre-submission enquiry

### ISSUE THREAD

**Issue by StankovicLab** [openjournals/joss#1163]
Hello,

We have a Github repository that we are getting ready to make public and submit to JOSS. Before we submit, we have a question regarding the DOI. We would prefer to not have the repository publicly available for long without an attributing DOI thus our question is, how long would it take to get a DOI from JOSS? If we have revisions, do we get a DOI placeholder? Is it possible to still submit to JOSS if we get a quick, temporary DOI from Zenodo for our repository? 

Please advice how best to approach this issue.

Thank you,
Stephen McInturff

**Comment by danielskatz** [comment]
You can get a DOI from Zenodo before you submit - if there aren't repo changes needed, that DOI will be published, along with the new DOI for the paper. If changes needed in the repo during the review, you would then need to update the zenodo deposit and get a new DOI, which would be linked into the JOSS submission.
