### ISSUE TITLE
Pre-submission enquiry

### ISSUE THREAD

**Issue by lposti** [openjournals/joss#1164]
Hello,

I was wondering if the code [vcdisk](https://github.com/lposti/vcdisk/) would qualify for submission to JOSS.

This compact python package is an handy toolbox for Astrophysicists working on galaxy rotation curves and on galaxy dynamics in general. It implements several well-known solutions of Poisson's equation in cylindrical symmetry, which are essential to model the observed rotation curves of spiral galaxies.
An initial non-public version of this code has already been used by my collaborators and myself in a few papers ([Posti et al. 2020](https://ui.adsabs.harvard.edu/abs/2020A%26A...644A..76P/), [di Teodoro et al. 2021](https://ui.adsabs.harvard.edu/abs/2021MNRAS.507.5820D/), [2022](https://ui.adsabs.harvard.edu/abs/2022arXiv220702906D/)). However, I have recently decided to polish the code and make it publicly available, hence my pre-submission enquiry to JOSS.

I have put a lot of effort in extensively [documenting](https://vcdisk.readthedocs.io/en/latest/) the code and in making it transparent, so that it is relatively easy to pick up for researchers with similar case studies to mine. I am also planning on expanding the tutorial section.

Please do let me know if it would make sense or not to proceed with submission to JOSS.

Best,
Lorenzo Posti

**Comment by arfon** [comment]
```
cloc vcdisk/
      26 text files.
      22 unique files.                              
       7 files ignored.

github.com/AlDanial/cloc v 1.96  T=0.02 s (1278.9 files/s, 138761.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           4            304            592            414
Jupyter Notebook                 1              0            688            102
reStructuredText                12             58             46             77
TOML                             1              4              3             24
SVG                              1              0              0             21
Markdown                         1              4              0             18
YAML                             1              5             14             10
Text                             1              0              0              3
-------------------------------------------------------------------------------
SUM:                            22            375           1343            669
-------------------------------------------------------------------------------
```

This looks to be pretty small and would almost certainly fall foul of our substantial scholarly effort test I'm afraid.
