### ISSUE TITLE
Citation string modification

### ISSUE THREAD

**Issue by AngryMaciek** [openjournals/joss#1167]
Dear Editors,

Would it be please possible to adjust the citation string in the following publication of ours?
https://joss.theoj.org/papers/10.21105/joss.02643

There is just two of us and the current scheme states `Bak et al., (2020)`, I've had several unpleasant situations at the department already due to this delicate matter.

Kind Regards,
Maciej Bak

**Comment by xuanxu** [comment]
Citation string updated to `Baz & Rozlach`
