### ISSUE TITLE
Cutoff for authors of git repositories?

### ISSUE THREAD

**Issue by KonradHoeffner** [openjournals/joss#1172]
If I cite a Git repository with 30 contributors as a bibtex entry, should I include all 30 in the bibtex author field or is there some cutoff.
If there is, which criteria is it based in (e.g. number of commits, number of total lines changed) and where is the cutoff point (e.g. 5 authors maximum or only those with more than 10 commits).

**Comment by danielskatz** [comment]
JOSS doesn't have a policy, and there is no community standard practice.

Ideally, the authors of the software will declare who should be listed as authors via a [citation.CFF](https://citation-file-format.github.io) file or some other indication.  If they don't, it's up to you to decide. Basing a decision on any quantitive metric is prone to error (some commits can be large but very minor; some important contributions don't appear as commits, e.g.. design discussions), so you might choose to list the authors as `{{X Project}}`

**Comment by goerz** [comment]
I've cited software packages as "<Maintainer> and Contributors", e.g. in https://dx.doi.org/10.22331/q-2022-12-07-871, but there isn't really an established practice

**Comment by KonradHoeffner** [comment]
Thanks for the clarification! I also noticed that the JOSS LaTeX/BibTeX template will cut off the author list on it's own when there are too many, so I will just provide all of them when there is no other indication.
