### ISSUE TITLE
Pre-submission enquiry

### ISSUE THREAD

**Issue by bensenderling** [openjournals/joss#1176]
Dear Editors,

I've been working on a data analysis, management and visualization (DAMVi) application in MATLAB and wondering if it would be a good submission to JOSS. It's being developed within our biomechanics research lab to more quickly perform data-related tasks. The core app is a dynamic environment that allows new methods to be more easily created and used. It's something I'm using as a more experienced programmer to develop new methods for students with less experience.

I believe I've hit all the items on the checklist and have created a new branch called JOSS_3. Here is a link to the repository. https://github.com/bensenderling/DAMVi_App.

Thank you,
Ben Senderling

**Comment by arfon** [comment]
Any thoughts @Kevin-Mattheus-Moerman ?

**Comment by bensenderling** [comment]
Hi @arfon and @Kevin-Mattheus-Moerman, What do you two think of this being a submission? If you don't think it would qualify I'd look into distributing it somewhere else.
