### ISSUE TITLE
Pre-submission enquiry

### ISSUE THREAD

**Issue by dtkerns** [openjournals/joss#1182]
I've been working on a project/paper for about a year where I'm re-implementing a novel method developed by our lab for which the original researcher's application code is no longer available. I've completed the software re-write and shown that it correctly implements the algorithm as described in the original paper. In speaking with my advisor about the project, I've come to the conclusion that now the only novel part of the project is my new software. Therefore, my advisor suggested that I submit to JOSS for publication. The software is implemented as an umbrella shell script, but calls a 500 line C++ program (twice, in 2 different modes) The C++ program manipulates directed graph (.dot) files but could be could be used independently of the frame-work it was developed for with a minimal amount of effort, which I'd be willing to do. However, I do plan on publishing the entire frame-work as OSS. I'd like to move forward with a paper published via JOSS.

**Comment by arfon** [comment]
~500 lines of C++ would be considered out of scope for JOSS I'm afraid (https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort).
