### ISSUE TITLE
Pre-submission enquiry

### ISSUE THREAD

**Issue by srmnitc** [openjournals/joss#1184]
Dear JOSS team, as part of a [project](https://potentials.rub.de/2022/index.php) we developed a set of workflows in the field of computational materials science. The workflows encompass everything from generating density function theory data, fitting machine learning interatomic potentials, to calculating phase diagrams of materials. These workflows were presented during a workshop (From electrons to phase diagrams) we organised and is also [publicly available](http://pyiron.org/potentials-workshop-2022/intro.html). The content is in the form of jupyter notebooks. We were wondering if this would qualify as a submission in JOSS. Apart from the JOSS paper, the notebooks would be fully reproducible and tunable for the potential user, and include detailed documentation. I would really appreciate it if you could provide some feedback! Thanks.

**Comment by arfon** [comment]
While these sound very useful I'm afraid they're not publishable in JOSS.
