### ISSUE TITLE
Pre-submission enquiry

### ISSUE THREAD

**Issue by BenWinchester** [openjournals/joss#1185]
Dear JOSS Editorial Team,

I have, in the course of my research, developed a few models which have a limited, but genuine, research application (e.g., [here](https://github.com/BenWinchester/HEATDesalination) and [here](https://github.com/BenWinchester/PVTModel)). As the usage of these models so far is limited (i.e., just me and my wider group, with some usage in a conference/journal publication), is there scope for submission to the JOSS?

I.E., is the fact that these models (complete with command-line interfaces and installable as python packages, so not "half-baked") are open source and used in research sufficient, or does the scope of their usage need to be wider before they would be considered?

Many Thanks,
Ben :smile:

**Comment by arfon** [comment]
Giving both repos a quick look over, they appear to be in scope. Provided they meet our [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion I would expect they could be published in JOSS.
