### ISSUE TITLE
Pr-submission enquiry: pygwb

### ISSUE THREAD

**Issue by a-renzini** [openjournals/joss#1186]
Dear JOSS Team,

We're a team of developers part of the LIGO, Virgo, Kagra Collaboration (LVK) who have developed a new data analysis codebase, `pygwb`. We would like to submit a paper to JOSS to present our new software to the community, and invite new users and contributors.

The first public release of the package is here: https://pypi.org/project/pygwb/
The code currently lives in an internal GitLab repository which we will make public. However, we have a collaboration GitLab account which does not allow non-members to open git issues. It is possible to view code, and clone the repository. To allow the broader community to contribute, I have created a public GitHub mirror to our repository, which is automatically updated when changes to the GitLab repository are made: https://github.com/a-renzini/pygwb
Anyone can open issues and pull requests on this repository. We can submit to JOSS via either the Gitlab or the Github repository (preferably the latter), as both are (or will be) public.

Does this setup satisfy the requirements to submit to JOSS? If not, what modifications can we make to satisfy the requirements?

Thanks and best,

Arianna

**Comment by kthyng** [comment]
@a-renzini From what you are saying, yes, this would satisfy JOSS requirements. The downside is that it sounds like you will have a split repository — will gitlab stay your package's home and github will just be used for the JOSS review?

**Comment by a-renzini** [comment]
@kthyng Thanks for your reply. As we accrete users, the plan is to migrate to github as our main repository, and reverse the mirror, such that the gitlab repo remains a place-holder of the project on our collaboration-owned account. However, this is a slower process than one may imagine, and we would like to decouple the two tasks (migrating to github and submitting the paper).

**Comment by kthyng** [comment]
Makes sense. I think you should go ahead and submit — you can bring this issue back up in the pre-review issue and link here or explain again there to make sure everyone is on the same page.
