### ISSUE TITLE
Paper withdrawn but pre-review issue was not closed

### ISSUE THREAD

**Issue by kyleniemeyer** [openjournals/joss#1190]
A [paper](https://joss.theoj.org/papers/dfa16c812141b8e4e7c61af6a33af293) was withdrawn by the author after I opened the [pre-review issue](https://github.com/openjournals/joss-reviews/issues/5218) (it was later resubmitted after correcting some issues), but doing this did not automatically close the pre-review issue or state anything about it being withdrawn outside the issue.

I would expect that when a paper is withdrawn outside of the issue, that the issue would be closed and that `editorialbot` would state that it was withdrawn (just as if it was done in the issue). Can this behavior be added?

**Comment by arfon** [comment]
I've noticed this happening a couple of times too. Rather than adding this logic from JOSS -> GitHub, I think what we should remove the ability to withdraw on the JOSS site, and instead make closing on the review issue the only way to do this.

What do you think?

**Comment by danielskatz** [comment]
That seems reasonable to me - I guess the JOSS site would then pick this up and remove the submission from the working list(s)?

**Comment by kyleniemeyer** [comment]
Sure, I think having all the non-AEIC commands on GitHub alone makes sense. Authors should have one place to engage after submitting
