### ISSUE TITLE
Pre-submission enquiry

### ISSUE THREAD

**Issue by nathhenry3** [openjournals/joss#1195]
Hello,

My name is Nathan, and I am a PhD candidate in the Department of Psychology at AUT University. 

I have written an article that I believe may be suitable for JOSS. The article is called "CRUD-Capable Mobile Apps with R and shinyMobile: a Case Study in Rapid Prototyping". In this article, I demonstrate the creation of the 'Harden' app using the shinyMobile package in R. This app can be used as a tool for Ecological Momentary Assessment, and is focussed on modelling addictions, but can be modified for a variety of purposes. The code is available [here](https://github.com/nathhenry3/Harden-app). 

The paper also discusses the utility of the shinyMobile package for rapid prototyping of apps, which I believe would be valuable to readers of JOSS. While using the code is a hands-on process, this paper may serve as a guide to those who wish to prototype their own shinyMobile apps. 

I have attached the article to this enquiry. Do you think such an article is suitable for JOSS, including any modifications I may need to make? I am happy to answer any queries you may have. 

Kind regards

Nathan

[CRUD-Capable Mobile Apps with R and shinyMobile a Case Study in Rapid Prototyping.pdf](https://github.com/openjournals/joss/files/10976099/CRUD-Capable.Mobile.Apps.with.R.and.shinyMobile.a.Case.Study.in.Rapid.Prototyping.pdf)

**Comment by danielskatz** [comment]
@nathhenry3 - I think you've misunderstood the purpose of JOSS. We don't publish research articles, we publish specific software packages along with short papers that provide a little description and context for the package. Please take a look at some of the recent published papers on https://joss.theoj.org, noting that each is really a short paper accompanying a software package. Also see https://joss.readthedocs.io/en/latest/submitting.html for more specific information.
