### ISSUE TITLE
Pre-submission enquiry

### ISSUE THREAD

**Issue by grimbough** [openjournals/joss#1196]
Hi and thanks for the great journal.

I was wondering if it was possible to submit an article that described multiple, but very closely related, software projects.  Specifically I'm thinking about tools for working with HDF5 in the R/Bioconductor ecosystem.  

That consists of 4 R packages with a clear linear dependency stack flowing through them.  In turn they provide:

1. A distribution of the HDF5 library as an R package
2. HDF5 dataset compression tools 
3. A "C-like" API to working with HDF5 in R
4. A more familiar "R-like" interface for interacting with HDF5 backed multi-dimensional arrays

The first two are probably not exciting on their own, but are fundamental to the latter two, which are widely used and I think would meet the criteria for a JOSS article.  Given that dependency, I think any article would probably mention all 4 packages, but it seems like spamming to write multiple articles on such closely related topics.

It wasn't clear to me if JOSS is the right venue for this slightly broader description of multiple tools, but if it is how might one go about doing the submission e.g. which repository should the `paper.md` be placed in?

Many thanks for the consideration.

For reference I've included the repositories for the 4 packages below:

https://github.com/grimbough/Rhdf5lib
https://github.com/grimbough/rhdf5filters
https://github.com/grimbough/rhdf5
https://github.com/bioconductor/HDF5array

**Comment by danielskatz** [comment]
We would accept such a submission (though of course we would check for scope and significance after the submission and before the review). It would be important to be clear about exactly which software was being submitted. Ideally, the software paper would be in one of the repos, whichever you think is the "main" one for the submission (maybe the first one you list?)

Feel free to reopen this issue if needed.
