### ISSUE TITLE
Pre-submission enquiry - Notebooks on Marine Biological Imagery

### ISSUE THREAD

**Issue by jcmontesherrera** [openjournals/joss#1199]
Hi JOSS team,

Throughout my research I've developed a wide collection of Jupyter notebooks, separated in steps, instruments, or processes that helped me process biodiversity, photogrammetry and hyperspectral data.

I am wondering if a collection of Jupyter notebooks to analyze marine biological imagery fits within the scope of the journal?

All the best,
Juan Carlos

**Comment by arfon** [comment]
I'm afraid this kind of submission isn't in scope for JOSS.
