### ISSUE TITLE
Pre-submission enquiry

### ISSUE THREAD

**Issue by willgearty** [openjournals/joss#1200]
Dear JOSS Editorial Team,

I'm wondering if our R package [rphylopic](https://github.com/palaeoverse-community/rphylopic) would be suitable for publication in JOSS. The functionality of the package is focused on adding silhouettes of organisms (from the PhyloPic website) to existing figures in R. While this does not serve a research purpose in and of itself, there are numerous uses for this in research and scientific publication workflows in the biological sciences. The package has existed since 2013, but has never been published on, and @LewisAJones and I recently redid nearly the entire package (v1.0.0) to address a change in the PhyloPic API.

Thanks in advance,
Will

**Comment by arfon** [comment]
Submissions like this that are purely for making figures/publication assets aren't allowable in JOSS sorry.

**Comment by willgearty** [comment]
Thanks for the info!
