### ISSUE TITLE
Pre-submission enquiry

### ISSUE THREAD

**Issue by schneiderpy** [openjournals/joss#1201]
Dear Editor

This is a pre-submission enquiry to know if the r package "concstats" is in scope or suitable for JOSS - Journal.
The package is available con https://github.com/ropensci/concstats 

With best regards
Andreas Schneider

**Comment by arfon** [comment]
If there's a research case, yes I would expect it to be allowable. I also note there's an rOpenSci review for this package so it would likely not need another review in JOSS.

One possible issue, the software looks to be quite small so it might be considered out of scope for that reason.
