### ISSUE TITLE
Where to put the ODD (Overview, Design concepts, Details) description?

### ISSUE THREAD

**Issue by platipodium** [openjournals/joss#1202]
The standard for documenting Individual or Agent-based Models (ABM) is the ODD protocol, i.e. the Overview, Design concepts, Details by Grimm et al. 

This ODD protocol typically exceeds the character count enforced by JOSS, and deviates from the structure suggested for JOSS papers.  What is the best way to add the ODD information to a JOSS submission?  

- Use ODD structure instead of JOSS structure?
- Add the ODD protocol as an appendix?
- Make the ODD protocol an independent paper submitted elsewhere?

Please advise!

**Comment by kthyng** [comment]
Hi @platipodium! Indeed JOSS papers are meant to be pretty different from more traditional academic papers. For example, you should not include new science results and generally the focus should be on the software, not the scientific methods. Probably you either want to have a different paper describing the science side of your work along with scientific results, or if there isn't enough to justify a whole separate paper, then have it in your docs instead.

**Comment by platipodium** [comment]
Dear Kristen, I am aware of the format of JOSS.  And the ODD protocol is exactly what I find is the scope of JOSS, namely to document the purpose and design of a software.  So I'd be interested to learn how you would be willing to accept an ODD in a JOSS paper.   But I am also happy to release the ODD on comes.net (where many ABMs are deposited and document with ODD) and write a short JOSS-style paper here

**Comment by kthyng** [comment]
The JOSS paper isn't meant to contain the information you want to put in there. If you want to do it anyway and you won't go too far over the word limit, it's probably fine. Otherwise put it in your docs. I'm not familiar with your field to know about comes.net but that is probably fine too.

**Comment by platipodium** [comment]
Thanks @kthyng. This answers the questions.  I'll go for two separate submissions. Overview on JOSS, details elsewhere.
