### ISSUE TITLE
Authorship rules for joint AAS publications

### ISSUE THREAD

**Issue by TomWagg** [openjournals/joss#1205]
Are there any rules for the list of authors between a JOSS paper and the associated AAS publication? I.e.

- Does the author list need to be the same?
- Does the _order_ of the author list need to be the same?

(e.g. if there are many authors on the AAS paper but only a subset worked on the software submitted for a JOSS paper, can you reshuffle the author list?)

Thanks!

**Comment by dfm** [comment]
@TomWagg — Thanks for checking! No, I don't believe that the author list must be the same. The JOSS submission should follow our guidelines for authorship and author order: https://joss.readthedocs.io/en/latest/submitting.html#authorship
