### ISSUE TITLE
Post-submission enquiry (pre-review not initiated yet)

### ISSUE THREAD

**Issue by SamDuffield** [openjournals/joss#1210]
I submitted our package [qujax](https://github.com/CQCL/qujax) on 29th March and have heard nothing since and pre-review hasn't started.

Can I check that it has been received?

**Comment by danielskatz** [comment]
👋 @openjournals/pe-eics

**Comment by bwheelz36** [comment]
I'm in the same boat; submitted [ParticlePhaseSpace](https://github.com/bwheelz36/ParticlePhaseSpace) on 21st of March and status is still `This paper is submitted but the review hasn't started.`
