### ISSUE TITLE
Pre-submission enquiry: R Package Conjurer

### ISSUE THREAD

**Issue by SidharthMacherla** [openjournals/joss#1211]
Dear editorial team,
   I have previously submitted my R package [conjurer ](https://github.com/SidharthMacherla/conjurer)and was rejected for lack of research application and being relatively new.  I have since then updated the package significantly and my work is cited already by a paper in [JOSS] (https://joss.theoj.org/papers/10.21105/joss.02763) and another in a book [Synthetic Data Generation with R](https://link.springer.com/chapter/10.1007/978-1-4842-8587-9_4). Furthermore, It currently has more than 20K installations. I would like to know if I can submit again with a more detailed research paper. 

Thanks,
Sidharth

**Comment by arfon** [comment]
If you feel like you've expanded the scope of the software, feel free to resubmit linking to the earlier pre-review issue. But please don't write a longer-paper here. JOSS submissions should be about the software, not detailed research articles.
