### ISSUE TITLE
Unnecessary comma in footer between two authors

### ISSUE THREAD

**Issue by KonradHoeffner** [openjournals/joss#1217]
When a paper has exactly two authors, the author list in the footer on every page is given as "LastnameA, & LastnameB".
Please close this issue if this is intended but at least to me it looks wrong to have a comma at this place and I recommend to change it to "LastnameA & LastnameB" without the comma.

As examples, see <https://joss.theoj.org/papers/10.21105/joss.05293> (finished paper) or <https://raw.githubusercontent.com/openjournals/joss-papers/joss.05114/joss.05114/10.21105.joss.05114.pdf> (final proof of https://github.com/openjournals/joss-reviews/issues/5114).

**Comment by xuanxu** [comment]
summoning @tarleb

**Comment by tarleb** [comment]
I have been summoned. 👿 

This happens in the bibliography as well, as can be seen in the finished paper. It does strike me as strange, but I'm not sure if that's a bug or not. If it is, then we'll have to report it to jgm/citeproc.

**Comment by tarleb** [comment]
I checked, this is indeed the [correct APA style](https://apastyle.apa.org/style-grammar-guidelines/references/examples/journal-article-references#6). Thus closing.

**Comment by KonradHoeffner** [comment]
I had looked up the Oxford comma which only happens with at least three items so I don't understand why they have this style but I guess that the APA must have some reason for that which I don't understand as a non-native speaker, thank you for checking and the clarification!
