### ISSUE TITLE
Instructions for becoming an editor

### ISSUE THREAD

**Issue by platipodium** [openjournals/joss#1218]
Dear team,

I'd be interested to volunteer as an editor for JOSS.  I don't find any instructions on how this could be achieved or what your policies are. 

Please add information at <pick/your/relevant/place> to inform users and potential volunteers.

**Comment by arfon** [comment]
We put out semi-regular calls for editors on our blog. I suggest you keep an eye out for the next one: https://blog.joss.theoj.org/
