### ISSUE TITLE
Pre-submission enquiry and compatibility with code availability standard

### ISSUE THREAD

**Issue by f-hafner** [openjournals/joss#1220]
Dear Editors,

I have a code that does some data engineering: it tidies various bibliometric data sets (Microsoft Academic, ProQuest Disseration&Theses, and NSF grants), combines them into a relational database and generates new tables, and uses a linking algorithm (algorithm itself is not novel) to match records across the data sources. The code is not in a publishable state at the moment, but you find the repo [here](https://github.com/f-hafner/mag_sample), and the main code [here](https://github.com/f-hafner/mag_sample/tree/main/src/dataprep).

The use case for other people would be that they can easily re-create the database and link bibliometric records for their research. I am not aware of a similar package.

My coauthor and I plan to soon submit a paper to an economics journal that uses the code and data. Would you still consider the code for a publication in JOSS?

Moreover, some journals in economics have adopted the [data and code availability standard](https://datacodestandard.org/). It means that all code -- from raw data to final analysis -- needs to be published upon acceptance of the paper, for instance on openicpsr.

If I have already deposited the code through such an outlet, would JOSS still consider publishing the software? 

Thanks!

**Comment by arfon** [comment]
> If I have already deposited the code through such an outlet, would JOSS still consider publishing the software?

This isn't a blocker for JOSS, as long as the first paper is *not* about the software itself (i.e., avoiding potential dual/duplicate publications).

> The use case for other people would be that they can easily re-create the database and link bibliometric records for their research. I am not aware of a similar package.

This is probably *not* in scope for JOSS but without reviewing a submission and the draft JOSS paper, it's hard to say for sure.
