### ISSUE TITLE
Pre-submission enquiry

### ISSUE THREAD

**Issue by Edinbro** [openjournals/joss#1221]
In the framework of the EU-funded [MICAT project](micatool.eu), we are developing an open-source tool to quantify and monetise multiple impacts of energy efficiency, which is an omnipresent issue in the energy efficiency research community. The tool consists of a core computing back end in Python, a front end in Javascript, a database, and several indicators. It will be published open source (probably AGPL 3.0) to allow other researchers to add or alter indicators, as well as to improve the database and calculation routines. 
We would therefore like to publish a paper explaining the workflow and how to make changes and improvements. Would that fall under the journal's scope?

**Comment by arfon** [comment]
It may be. Please proceed to submit and we can consider the scope then.
