### ISSUE TITLE
Pre-submission enquiry

### ISSUE THREAD

**Issue by harshamarupudi56** [openjournals/joss#1223]
I have developed an automated version of a Fiji/ImageJ plugin BoneJ. This package allows for analysis to be run on images of bone with these plugins without any GUI dependence, which allows for faster computation, easy integration into Python, and easily save results to a desired file. Is this a substantial enough contribution for submission to this journal?

**Comment by arfon** [comment]
It may be in scope. Please proceed to submit and we can consider the submission as part of our standard review processes.
