### ISSUE TITLE
Pre-submission enquiry: tethys

### ISSUE THREAD

**Issue by ifthompson** [openjournals/joss#1226]
Hello,

I am nearing completion of a major rewrite of a python package (tethys) for downscaling water demand data. An earlier version was published in another software journal back in 2018, but this rewrite generalizes the methodology to make it more widely usable beyond the specific workflow it was originally designed for. For example, working with a different breakdown of water demand sectors or spatial proxies previously required making large changes to the code to tailor it to that specific case, but the new version allows users to handle any case with simple modifications to the configuration file due to the more generalized structure under the hood.

Does this kind of advance fall within the scope of JOSS? If so I'll submit in the near future.

Thanks very much,
Isaac

**Comment by danielskatz** [comment]
If the advances in the code meet JOSS's [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion, this should be fine
