### ISSUE TITLE
How to request change misspelled name

### ISSUE THREAD

**Issue by ddhendriks** [openjournals/joss#1227]
LS,

My paper has just been published ([https://joss.theoj.org/papers/10.21105/joss.04642](https://joss.theoj.org/papers/10.21105/joss.04642)) but I see that my name is not spelled correctly:

![image](https://github.com/openjournals/joss/assets/74686531/261a06dd-c32e-4f80-83b2-735d1c49bbb3)

the "[" should not be part of my last name. How / where can I request to have this changed?

King regards,

David Hendriks

**Comment by Kevin-Mattheus-Moerman** [comment]
@openjournals/dev  :point_up:

**Comment by xuanxu** [comment]
Fixed!
