### ISSUE TITLE
Pre-submission enquiry

### ISSUE THREAD

**Issue by anusandhann** [openjournals/joss#1230]
I want to submit a paper, and have already created all the required documentation in GitHub.
I have one question. The software/program/code used in the paper is not a separate software. It is rather a series of 4 different python .py files, that are to be executed in Python --> Jupyter Notebook.
Is that an acceptable submission? or should I create a new python package? I dont want to create a python package as yet.
I want to submit it as a series of .py files that can be copy pasted into JupyterNotebook and the process in the paper can be completed.

**Comment by matthewfeickert** [comment]
@anusandhann Please see the section on ["Substantial scholarly effort" in the Submitting a paper to JOSS docs](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort). Given your description so far I don't think that (as is) it meets all the requirements laid out there, particularly the section

> In addition, JOSS requires that software should be feature-complete (i.e., no half-baked solutions), packaged appropriately according to common community standards for the programming language being used (e.g., [Python](https://packaging.python.org/), [R](https://r-pkgs.org/index.html)), and designed for maintainable extension (not one-off modifications of existing tools). “Minor utility” packages, including “thin” API clients, and single-function packages are not acceptable.
