### ISSUE TITLE
No trace of a submited paper 

### ISSUE THREAD

**Issue by sebastien-plutniak** [openjournals/joss#1232]
Hi,

I submitted this paper https://github.com/sebastien-plutniak/archeoviz/blob/main/paper.md
the  2th June, and received an automatic confirmation saying that 
`You can view the latest status of your paper here: https://joss.theoj.org/papers/ec7d14809161bb21d0e258742e64f131`
However, this links does not work, so there might be an issue with this submission. Could you check it, please?

**Comment by kthyng** [comment]
@sebastien-plutniak That is an internal link that you don't have permissions for. The pre-review issue hasn't been initiated for your submission, but you'll be notified by github when it is.
