### ISSUE TITLE
Pre-submission enquiry

### ISSUE THREAD

**Issue by vip40088** [openjournals/joss#1238]
Subject: Pre-submission Enquiry for an Upcoming Article

Dear JOSS Editorial Team,

I hope this message finds you well. My name is Yang, and I am a postgraduate student at JLNU in China. I am writing to make a pre-submission enquiry for a potential paper I would like to submit to your esteemed journal.

The article is focused on a program I developed using PsychoPy for the N-Back Paradigm, a procedure commonly used in psychological experiments to measure a part of working memory. I believe this program has substantial potential for the research community, as it not only provides an efficient way to implement the N-Back Paradigm, but is also easily accessible and modifiable for researchers with varying programming skills.

Before proceeding with the formal submission, I wanted to ensure that this work falls within the scope of JOSS. I understand that JOSS publishes articles about research software, and I believe this work aligns well with the journal's focus.

Thank you for your time and consideration. I look forward to your response.

Best regards,

Haiyang,
hacker_i@sina.com

**Comment by arfon** [comment]
It may be in scope. Please proceed to submit and we can consider the submission as part of our standard review processes.

**Comment by vip40088** [comment]
[[]](https://github.com/vip40088/n-back_experiment)(url)

**Comment by vip40088** [comment]
https://github.com/vip40088/n-back_experiment
