### ISSUE TITLE
How to get paper metadata in machine-readable form

### ISSUE THREAD

**Issue by nichtich** [openjournals/joss#1239]
Is the full list of papers with its metadata easily available? I only found the HTML listings at https://joss.theoj.org/toc and the [copyright statement](https://joss.theoj.org/about#content_license). Metadata for known DOIs can be fetched from CrossRef API ,but a list of all DOIs is needed and you may have more detailled metadata than CrossRef, don't you?

**Comment by xuanxu** [comment]
The list of published papers is available in JSON format: https://joss.theoj.org/papers/published.json

**Comment by nichtich** [comment]
Thanks! So would [the toc page](https://github.com/openjournals/joss/blob/939d1086d8fc3923bda19854ff9d03f8c009229a/app/views/toc/index.html.erb) be the right place to add a link or did I just missed a pointer to the file?

**Comment by xuanxu** [comment]
It is a JSON representation of this view: https://joss.theoj.org/papers/published
You can get only one page at a time:
https://joss.theoj.org/papers/published.json?page=2
https://joss.theoj.org/papers/published.json?page=3 
...

The paper view can also be retrieved as json:
HTML: https://joss.theoj.org/papers/10.21105/joss.04724 
JSON: https://joss.theoj.org/papers/10.21105/joss.04724.json
