### ISSUE TITLE
How to change the hyperlink to the code repo of a past submission?

### ISSUE THREAD

**Issue by ulf1** [openjournals/joss#1243]
Hello,
i want to move a GitHub repository to another organization but the Github repository is linked in an existing JOSS article.
How to change the hyperlink in the JOSS article to the new hyperlink?

**Comment by kthyng** [comment]
@openjournals/dev Is this possible?

**Comment by ulf1** [comment]
any news?

**Comment by arfon** [comment]
It's possible. Please ping me (@arfon) on the JOSS review issue and we can make the change.
