### ISSUE TITLE
Pre-submission enquiry

### ISSUE THREAD

**Issue by duanegris** [openjournals/joss#1244]
I want to rise a potential issue regarding the license of the software we intend to submit.
1) Our contribution can be licensed as Apache Public License
2) However, our contribution stands atop a research software that is licensed under an Academic Public License.

This does not seem to me a fully OSI license as it requires to ask for permission for a commercial use.
https://opencarp.org/download/license 

We first thought the Academic Free License that is proposed for JOSS submissions was similar to the Academic Public License but it differs in that respect.

How would you deal with such case?

**Comment by kthyng** [comment]
@danielskatz @jedbrown You two might have a useful response here?

**Comment by jedbrown** [comment]
So long as your package is entirely open source, it can be considered by JOSS. For example, JOSS has published packages written in MATLAB. You'll need to be careful that all code in your package has clear provenance (e.g., there are no copied fragments with a different license) and it is necessary that reviewers be able to run your software.

I am not a lawyer, but I see this license has this term inspired by GPLv2.0:
> You may not impose any further restrictions on the recipient's exercise of the rights granted here.

which to my eye, would hit the same conflict that open source lawyers have identified with the Apache-2.0 patent termination and indemnification clauses. [This is a loosely consensus transitive compatibility diagram](https://dwheeler.com/essays/floss-license-slide.html) and there is no way to mix GPLv2 and Apache-2.0 code. JOSS can't offer legal advice so you may want to investigate to see if there is a legally sound justification for combining these two licenses. You might also want to discuss with upstream whether a relicense could be considered.
