### ISSUE TITLE
Pre-submission enquiry

### ISSUE THREAD

**Issue by Fertasd** [openjournals/joss#1247]
Dear Sir/Madam,

    I was directed towards your journal as an avenue for getting research software into a peer review process, and have a related question.  
    To provide some context, I am a support scientist at GFZ Potsdam, currently reworking our section's data processing, data exploration, and data visualization libraries into a form that would (finally) qualify as a feature-complete package intended for long-term use.
    The final product will be a set of libraries for accessing, processing, exploring, and visualizing magnetospheric satellite data from several missions, and in particular for computing adiabatic invariants and phase space density for said missions (already implemented). Phase space density is an essential quantity for studying the radiation belt environment (for both case studies and model validation), but is often not prepared by the mission data providers and is not trivial to compute. Further notable features that could be of interest to existing similar initiatives are functions for handling specific standard-breaking products (already implemented as this was the original reason for the creation of the project, such products are challenging to handle with APIs developed based on the standards, and providers often no longer have the resources to address the issue by publishing a new release of the data set), as well as the (under development) functionality to adjust metadata such as variable names in the outputs/products through a "metadata dictionary" translating between the library's internal standard and user-defined standards, which would allow for efficient integration with existing standards like SPASE as it gets fine-grained enough to address relevant data types in the field.
    Unfortunately, the libraries were originally developed in Matlab, and due to various reasons outside my control, I do not foresee gaining the freedom to reimplement them in Python during this set of reworks. However, the libraries themselves are intended to be an open access and open source product. Would these libraries still qualify for publication in your journal given these circumstances (once the reworks are complete)?
    
Looking forward to hearing from you!
    
Regards,
Matyas Szabo-Roberts

**Comment by danielskatz** [comment]
I found it very hard to read your comment, so I've reformatted it below:

> I was directed towards your journal as an avenue for getting research software into a peer review process, and have a related question.  
> 
> To provide some context, I am a support scientist at GFZ Potsdam, currently reworking our section's data processing, data exploration, and data visualization libraries into a form that would (finally) qualify as a feature-complete package intended for long-term use.
> 
> The final product will be a set of libraries for accessing, processing, exploring, and visualizing magnetospheric satellite data from several missions, and in particular for computing adiabatic invariants and phase space density for said missions (already implemented). Phase space density is an essential quantity for studying the radiation belt environment (for both case studies and model validation), but is often not prepared by the mission data providers and is not trivial to compute. Further notable features that could be of interest to existing similar initiatives are functions for handling specific standard-breaking products (already implemented as this was the original reason for the creation of the project, such products are challenging to handle with APIs developed based on the standards, and providers often no longer have the resources to address the issue by publishing a new release of the data set), as well as the (under development) functionality to adjust metadata such as variable names in the outputs/products through a "metadata dictionary" translating between the library's internal standard and user-defined standards, which would allow for efficient integration with existing standards like SPASE as it gets fine-grained enough to address relevant data types in the field.
> 
> Unfortunately, the libraries were originally developed in Matlab, and due to various reasons outside my control, I do not foresee gaining the freedom to reimplement them in Python during this set of reworks. However, the libraries themselves are intended to be an open access and open source product. Would these libraries still qualify for publication in your journal given these circumstances (once the reworks are complete)?

We have reviewed software in Matlab before - this by itself is not an issue, as long as the other [JOSS submission requirements](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements) are met.

I'm going to close this with this answer, but please feel free to reopen it if you feel like we need to continue this discussion.
