### ISSUE TITLE
Website issue: web feed for search results not working

### ISSUE THREAD

**Issue by omian** [openjournals/joss#1249]
To reproduce - on the explore page (https://joss.theoj.org/papers) use the search box to conduct a search.
Then on the search results page click the feed icon (top right corner of page) and then click "This search".

My expectation is for this to produce a search-specific feed. 
Instead it takes you to an empty feed: https://joss.theoj.org/papers/search.atom

**Comment by xuanxu** [comment]
Code updated! This should be fixed now
