### ISSUE TITLE
Streamlining JOSS reviews

### ISSUE THREAD

**Issue by karthik** [openjournals/joss#125]
JOSS has been live for a few weeks now with four accepted papers and seven more in review. There is also considerable interest in reviewing for JOSS from the community. As our submissions and community grow, we also need to iterate on our review process so we reach the right editors/reviewers without overwhelming everyone involved. After discussion with @arfon, I've come up with a rough plan on how to streamline the review process.

**Current workflow**  

Arfon currently sees every incoming submission and does a quick sanity check before allowing Whedon to generate the checklist and tagging openjournals/joss-reviewers. This approach pings every single person. 

**Proposed workflow**

To reduce noise, target the appropriate reviewers, and also engage the editorial board more actively, we are considering creating more granular teams. This would involve:

a) Asking all existing editors and reviews to state their preferred domains/topics and programming languages they are comfortable reviewing.

b) Do the same for all existing reviewers and make this a requirement for new reviewers. 

c) Once we have these data, create smaller teams and cross list people as appropriate. 

Once this process is complete, for each incoming submission we will assign an appropriate editor/editors to handle the submission. They can then make a call to relevant teams OR tag anyone on Github to review the submission. Whedon (functionality yet to come) will add new reviewers to the appropriate teams. The plan is to develop Whedon into a full fledged system that can handle various commands such as adding reviewers to teams (e.g. `/whedon add @karthik joss-R joss-ecology`) and notify editors if reviews have not come back in after `x` elapsed days. Whedon will also have other functionality to reduce burden on editors.

Comments and feedback welcome. cc/ @openjournals/joss-editors

**Comment by danielskatz** [comment]
This seems reasonable to me.

**Comment by kyleniemeyer** [comment]
That sounds great—I felt like @arfon wouldn't be able to keep up processing everything himself...

Will someone (@arfon or someone else) still need to manually assign to an editor/team? Or will the submitter/author pick an area that will do that for him/them?

**Comment by katyhuff** [comment]
Yes! I think this is a great plan @karthik . I especially think it would be
a simple helpful step if the authors self identify, at submission time,
what topic or editor they want to have their submission handled under.
Thats common in other large journals and could help automate the first step
('we will assign the appropriate editor... ').  If the authors already do
that, it hasn't been obvious to me.

**Comment by labarba** [comment]
Authors should select the editor they want to handle their paper. The journal submission form should make it easy for them, providing a link to the names+bios page ... but it can also provide the list of Github handles, and we can ask authors to tag the preferred editor.

One thing that we are not controlling for at this time is conflict of interest. Anyone can raise their hand and say "I'm reviewing this" but we don't have a written policy for reviewers of when they should declare a COI. Perhaps we can simply use NSF guidelines.

**Comment by Kevin-Mattheus-Moerman** [comment]
I like these suggestions @karthik. I also like the suggestions of letting author choose. 
The list of programming languages seems clear to be and can easily be exhaustive. Creating fixed groups based on topic and domain could be a bit vague and difficult. For instance, where do we stop defining them, e.g. engineering, biomedical engineering, bioengineering, biomechanics... Perhaps we could create a basic tool so editors/reviewers can search for, pick, and add if required, keywords on their expertise. This way if I see bio-engineering in the list I wont accidentally add bioengineering or a very similar one like biomedical engineering. With this tool the list of topics/domains could be grown without doubles and mild variations. 
In terms of "creating teams", I think we should think of a flexible system. Authors can search for, pick, and add if required, keywords to their submission from the same list and also suggest editors/reviewers. Then you could automatically select a set of reviewers/editors based these suggestions.

**Comment by labarba** [comment]
+1 to authors also suggesting reviewers

**Comment by genomematt** [comment]
On the COI front I suggest we have an item at the top of the check list "reviewer has no COI" just to ensure it is thought about, and to document any minor COI like we do any other issue we work through.  The open review handles this pretty well IMO, but we need a checkbox trail in case issues arise.

**Comment by tracykteal** [comment]
Thanks @karthik this looks good to me. It does make sense as @Kevin-Mattheus-Moerman suggested to have the domains/topics be a given set rather than free-entry, and I don't think they need to be too fine-grained. 

I don't think we should require that authors select an editor. It seems fine to let authors request a particular editor though, with the understanding that they might not get that editor if, for instance, that editor is already handling a lot of submissions or isn't available at that time.

**Comment by ctb** [comment]
Carrying some conversations over from #104, I would suggest avoiding *ever* tagging an entire team in on a review, as that results in overly broad notifications. So perhaps we could:

* always create a "meta review" issue that discusses who wants to review, and tag in the domain/language-specific team on that; this would be low traffic by intent;
* only tag in the handling editor and reviewers on the actual submission;

I know this results in proliferation of issues but I think reducing github notification traffic is going to be key!

**Comment by arfon** [comment]
> I know this results in proliferation of issues but I think reducing github notification traffic is going to be key!

💯

**Comment by arfon** [comment]
Just looping back on this.

> a) Asking all existing editors and reviews to state their preferred domains/topics and programming languages they are comfortable reviewing.

In theory I agree with this being a fixed list of topics, that said, at this point we're (if we do well) going to get ~40 responses and I'm personally OK grouping that list of specialisms into some broader list of topics after the fact.

That said, if someone has a list to hand of suitable topic areas I'm OK with using that too.

Next steps (early next week I hope) on my part is to make a small Google form (or something similar) to collect this information. I was going to suggest a Markdown table but collaboratively editing Markdown tables is waaay to hard.

**Comment by arfon** [comment]
OK, here's the form I'm planning on sending to the reviewers:

http://goo.gl/forms/4LGHxwfLcU11f7Da2

**Comment by ctb** [comment]
#138 seems to suggest that all reviewers on a domain-specific team will still be receiving all notifications for a review - true?

**Comment by rmflight** [comment]
Is there any way to tag a group and ask for reviewers initially, and then once the submission is under review, remove the *group* tag and leave the issue with the author, editor, and reviewer, leaving the notifications with them only? 

I agree with @ctb, the level of traffic is going to become overwhelming to the point that I as a reviewer won't even see notifications for an active review because it will be buried under all the other submissions in review as well.

**Comment by arfon** [comment]
> I suggested splitting into a meta-review and a review issue, here; 

Oops, I missed that suggestion @ctb. Too many GitHub notifications :trollface: 😭 

I think that's a great idea. Let's do it. I don't think that changes anything about the current request for information from reviewers in http://goo.gl/forms/4LGHxwfLcU11f7Da2 . Once we've got a reasonable number of responses I'll set up the smaller teams and create some documentation outlining the new reviewer assignment process (including the meta-review issue).

**Comment by arfon** [comment]
Tracking this in #159
