### ISSUE TITLE
Pre-submission enquiry

### ISSUE THREAD

**Issue by pabloblancogomez** [openjournals/joss#1252]
Hi,
We have submitted 10 days ago a paper called _DAI Algorithm: a QGIS plugin for Daily Aerial Image interpolation_ and are wondering if there is some action missing from our part.
In this sense, in the section _Paper actions_ is indicated: "Available actions for you on this paper (note to editors that if you use these buttons, you'll still have to manually close the review issue on GitHub)." but we do not know how to proceed.
Could you please help us to solve this issue?
Many thanks and best

**Comment by danielskatz** [comment]
@pabloblancogomez - this should be handled this week. The track chair has been on vacation...
