### ISSUE TITLE
Pre-submission enquiry

### ISSUE THREAD

**Issue by jmmshn** [openjournals/joss#1253]
# Question about submitting a namespace/add-on package

Dear Editors,
I have been on the following repo for the simulation of quantum defects in semiconductors.

https://github.com/materialsproject/pymatgen-analysis-defects

The repo is pretty mature and being used in various parts of the materials informatics ecosystem.
The repo is a namespace package for the popular `pymatgen` materials analysis repo but is targeted at a very specific set of problems.  I'm wondering if a JOSS paper documenting this repo is appropriate.

**Comment by arfon** [comment]
It may be in scope. Please proceed to submit and we can consider the submission as part of our standard review processes.
