### ISSUE TITLE
Pre-submission enquiry

### ISSUE THREAD

**Issue by oleksulkowski** [openjournals/joss#1255]
Dear Editors,

I developed a Panel app for our virology lab (https://oleksulkowski.github.io/app/). I was thinking about publishing it in JOSS, as it might save significant amounts of time for researchers working on synonymous genome recoding of viruses, making the process more systematized.

1. I wanted to ask if deployment of a Pyodide PWA on GitHub Pages would be sufficient for submission? I chose this method to simplify the installation process bearing in mind my users wouldn't be researchers with a computer science background.
2. I also wanted to know if you would consider this a 'single function' package since the app takes a gene file as input, modifies it and outputs for the user to download. However, I'd consider the user-adjustable algorithm to be of value, as it has taken a substantial amount of time to develop.

Thank you.

**Comment by arfon** [comment]
It may be in scope, it's hard to say without seeing the code. Please proceed to submit and we can consider the submission as part of our standard review processes.
