### ISSUE TITLE
Juliacon proceedings paper submission form error

### ISSUE THREAD

**Issue by pitsianis** [openjournals/joss#1257]
I wonder if this is the right place to raise this issue. https://proceedings.juliacon.org/about#contact is pointing here...

We tried to submit a paper to the Juliacon proceedings from Safari and Chrome browsers and got the error

```quote
We're sorry, but something went wrong.
If you are the application owner check the logs for more information.
```

If you can see the logs, please let me know if there is something from our side that causes it.

**Comment by danielskatz** [comment]
ping @openjournals/dev

**Comment by arfon** [comment]
Sorry about this @pitsianis. This should be fixed now.
