### ISSUE TITLE
Wrong citation

### ISSUE THREAD

**Issue by koenedaele** [openjournals/joss#1259]
At https://doi.org/10.21105/joss.05040 there's an issue with the citation string:

_Koen et al., (2023). Atramhasis: An online SKOS vocabulary editor. Journal of Open Source Software, 8(83), 5040, https://doi.org/10.21105/joss.05040_

This should be:

_Van Daele et al., (2023). Atramhasis: An online SKOS vocabulary editor. Journal of Open Source Software, 8(83), 5040, https://doi.org/10.21105/joss.05040_

The corresponding Bibtex citation:

`@article{Koen2023, doi = {10.21105/joss.05040}, url = {https://doi.org/10.21105/joss.05040}, year = {2023}, publisher = {The Open Journal}, volume = {8}, number = {83}, pages = {5040}, author = {Van Daele, Koen and Tinne Cahy and De Clercq, Wim and Jonas Geuens and Bram Goessens and Jonathan Piraux and Bart Saelen and Maarten Taeymans and Cedrik Vanderhaegen}, title = {Atramhasis: An online SKOS vocabulary editor}, journal = {Journal of Open Source Software} } `

looks correct and renders properly at something like https://bibtex.online/

**Comment by danielskatz** [comment]
@openjournals/dev - can you look into this?

**Comment by arfon** [comment]
Is this different logic in the name handling @xuanxu ?

**Comment by arfon** [comment]
@koenedaele – could you please update your `paper.md` in your repository to be more explicit about the structure of your name? There are docs here showing how to do this: https://github.com/openjournals/inara/blob/main/docs/names.md

**Comment by koenedaele** [comment]
Hi @arfon pushed an update to the paper (it's in its own branch, not main)

Might I suggest adding a link to those docs from https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography ? I was unaware they existed at the time of writing the paper.

**Comment by arfon** [comment]
Good idea. We've been meaning to extend the docs with that information. The paper should now be updated (and the citation string appears to be correct now).

**Comment by koenedaele** [comment]
Looks good now. Thank you!
