### ISSUE TITLE
Support for multiple affiliations

### ISSUE THREAD

**Issue by genomematt** [openjournals/joss#126]
Currently an author with multiple affiliations only displays the last affiliation.  It would be good to support dual affiliation.
See https://github.com/genomematt/xenomapper/master/paper.md and https://github.com/openjournals/joss-papers/blob/master/joss.00018/10.21105.joss.00018.pdf as an example.

**Comment by arfon** [comment]
👍 thanks for spotting this. I've fixed the template and the PDF should be looking better now.
