### ISSUE TITLE
Pre-submission enquiry

### ISSUE THREAD

**Issue by drjphughesjr** [openjournals/joss#1260]
Dear JOSS editorial staff,

I recently developed R package Rmodule, which permits automated Markov chain Monte Carlo for arbitrarily structured correlation matrices. Modeling correlation matrices is a common and important task for many types of statistical model. The aim of the package is to outsource MCMC for correlation matrices to my code, which will free the user to focus on the "frontend" of his/her algorithm.

Would you be so kind as to evaluate the suitability of my work for publication in JOSS? I've attached the first draft of a manuscript to this message. I wrote the manuscript with SoftwareX in mind, but I suspect that JOSS is a better venue given that your scope appears to be broader and you help authors improve their software.

Thank you for your consideration.

Warmly,
[Rmodule.pdf](https://github.com/openjournals/joss/files/12403110/Rmodule.pdf)

John Hughes
Associate Professor
Lehigh University
[Rmodule.pdf](https://github.com/openjournals/joss/files/12403115/Rmodule.pdf)

**Comment by kthyng** [comment]
Hi @drjphughesjr! Have you taken a look at our submission guidelines? https://joss.readthedocs.io/en/latest/submitting.html#

We have a different (very short) format for our papers, and we include guidelines for what is in scope for JOSS.

**Comment by drjphughesjr** [comment]
Hi, Kristen.

Many thanks for your prompt reply.

I wasn't planning on submitting this paper to JOSS. I was hoping you could use this paper to decide whether my software falls within JOSS's scope. In any case, I've decided to expand my package. Perhaps I'll submit to JOSS in the future.

Warmly,

John

**Comment by arfon** [comment]
Without seeing the code, it's very hard to say. It may be in scope. Please proceed to submit and we can consider the submission as part of our standard review processes.
