### ISSUE TITLE
SigCorr: wrong link on the publication page

### ISSUE THREAD

**Issue by vindex10** [openjournals/joss#1261]
Hi! During the review process we had to move from cern-hosted gitlab to gitlab.com. The article passed review and got published, but it seems the change of the repository was not picked up by some automation:

Published page: https://joss.theoj.org/papers/10.21105/joss.04989

Correct repository link (also mentioned in the review issue below):
https://gitlab.com/sigcorr/sigcorr

Issue (review):
https://github.com/openjournals/joss-reviews/issues/4989

Could you please update the publication page with a correct link to the "Software repository".

Thank you!

**Comment by kthyng** [comment]
@openjournals/dev Could you help please?

**Comment by arfon** [comment]
Fixed!
