### ISSUE TITLE
Broken link to author names in docs

### ISSUE THREAD

**Issue by cliffckerr** [openjournals/joss#1262]
The JOSS [docs](https://joss.readthedocs.io/en/latest/submitting.html) say:
> For a complete description of available options to describe author names [see here](https://github.com/openjournals/inara/blob/main/docs/names).

A couple suggestions: 
- [x] The link gives a 404. I think it just needs to point to https://github.com/openjournals/inara/blob/main/docs/names.md, although the default display of this file on GitHub leaves a little to be desired, so maybe a Read the Docs link would be preferable if available?
- [x] It would also be nice to have even a very brief explanation of how these choices differ, e.g. dropping vs. non-dropping particles.
- [x] Would suggest changing "Western" to "English" or "Anglo-Saxon", since "Ludwig van Beethoven" and "Louis de Broglie" are pretty Western :grin:

**Comment by danielskatz** [comment]
Thanks @cliffckerr - would you want to create a PR with your suggested changes?

**Comment by cliffckerr** [comment]
Have made a PR -- oddly I can't reproduce the 404 I was getting before! Maybe it was already fixed but I was looking at an old version of the docs?

**Comment by kthyng** [comment]
I think this might have just changed recently — @arfon didn't you just update this?
