### ISSUE TITLE
Pre-submission enquiry: cortecs

### ISSUE THREAD

**Issue by arjunsavel** [openjournals/joss#1264]
Hi all!

I'm considering submitting a JOSS paper for my code, [`cortecs`](https://github.com/arjunsavel/cortecs). I wanted to check in beforehand to make sure that it's in scope.

Broadly, `cortecs` compresses chemical absorption data and provides scripts to uncompress its objects on GPUs. Utility scripts for chunking up and slicing absorption data are also included. The science case is primarily radiative transfer simulations of exoplanet atmospheres, though the method could be applied to radiative transfer simulations in general. 

The code is largely feature-complete, though I imagine I'll add more utility scripts, and testing / packaging / documentation is still in works.

Thanks!

**Comment by dfm** [comment]
I'm conflicted on this one (@arjunsavel was recently a visiting member of my research group), so it might be good if another editor can also comment, but it looks (at first glance) to me like this would be in scope. You would definitely need to expand the documentation to meet JOSS standards, but I believe that the code itself would be a good fit.

**Comment by arfon** [comment]
It may be in scope. Please proceed to submit and we can consider the submission as part of our standard review processes.
