### ISSUE TITLE
Pre-submission enquiry

### ISSUE THREAD

**Issue by jucordero** [openjournals/joss#1265]
Dear JOSS editors,

I’m currently developing a package to process and work with agrifood tabular and geospatial data, to interface with a few external models and packages and to provide a modelling pipeline. The main focus is on environmental and socioeconomic modelling.

To store and manipulate data we are employing _xarray_. As part of our testing and scientific goals we have pre-processed a few datasets to make them ‘compatible’ with our package.
To help in the development and accessibility of these pre-processed files we have created a separate repository from which these arrays can be imported directly.

I’m curious to know if and how the pre-processing repository should be incorporated into the submission of the main package given that both of these are developed in separate repositories.

In any case, the functionality of the main package is not dependent on the data package.

Best regards,

Juan P. Cordero

**Comment by arfon** [comment]
I think it's OK to just link the data repository in the docs (e.g., the paper) or on GitHub (or wherever the code is documented). Please make sure you mention this when submitting.
