### ISSUE TITLE
Pre-submission enquiry: cardsort

### ISSUE THREAD

**Issue by katoss** [openjournals/joss#1268]
Dear editors,

I recently had my package [`cardsort`](https://github.com/katoss/cardsort/tree/main) reviewed by [pyOpenSci](https://github.com/pyOpenSci/software-submission/issues/102) and would like to ask if you think it might also be in scope for JOSS.

`cardsort` offers functionality to analyse open card sorting tasks (hierarchical cluster analysis, dendrograms, extraction of user-generated cluster labels). Card sorting is used in user experience research to understand how people organize information in order to create information architectures. More information is in the [readme and documentation](https://github.com/katoss/cardsort/tree/main). To my knowledge, to date there are no other FOSS tools for this analysis.

Thank you!

**Comment by arfon** [comment]
Assuming these numbers are correct, I'm afraid this would be out of scope for us, failing the '[substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)' test:

```
cloc cardsort/
      27 text files.
      22 unique files.                              
       9 files ignored.

github.com/AlDanial/cloc v 1.96  T=0.01 s (1532.8 files/s, 99909.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           4             73            183            241
Markdown                         8             86             15            187
YAML                             4             22             11             88
CSV                              1              0              0             51
TOML                             1              6              0             38
DOS Batch                        1              8              1             27
Jupyter Notebook                 1              0            352             23
make                             1              4              5             10
Text                             1              0              0              3
-------------------------------------------------------------------------------
SUM:                            22            199            567            668
------------------------------------------------------------------------------- 
```
