### ISSUE TITLE
Pre-submission enquiry tfQMRgpu

### ISSUE THREAD

**Issue by paul-f-baumeister** [openjournals/joss#1269]
Dear Editors,

I just found JOSS to be very suitable for software publications.
However, I have already prepared a reference paper (as .tex file) that produces about 25 pages as .pdf
Would that be in the scope of JOSS?

thx

**Comment by danielskatz** [comment]
No, sorry, JOSS is meant for short papers that accompany the software. JOSS papers are around 1000 words.

Feel free to reopen this if needed.
