### ISSUE TITLE
Pre-submission enquiry

### ISSUE THREAD

**Issue by jsdodge** [openjournals/joss#1270]
Hello,

My group has been preparing the repository at this [link](https://github.com/dodge-research-group/thztools) for submission to JOSS, and I'd like to understand your guideline on the total lines of code before proceeding with our development. So far, the development and testing for this project has been more than three months of individual effort, initially by students under my supervision and more recently by me. But if I use the [codecov](https://app.codecov.io/gh/dodge-research-group/thztools) metric, there are currently 438 statements, with 287 in `src` and 151 in `tests`. This is less than half of the JOSS 1000 LOC guideline, so I'd like to get your feedback on whether the codebase is sufficient (and if not, what it would need) before turning to the documentation. This will of course add lines to the files, but presumably this is not included in your 1000 total LOC guideline.

The code was partially translated into Python from the MATLAB code used in the paper at this [link](https://doi.org/10.1364/OE.417724), then developed further. A significant portion of the work involved revising our previous algorithms and developing some new ones. This effort is not fully reflected in the LOC metric.

Thanks in advance! I look forward to your feedback.

Best,

Steve

**Comment by kthyng** [comment]
Running `cloc` on your codebase gave the following:
```
(myenv) kthyng@adams Downloads % cloc thztools-main.zip 
     204 text files.
      51 unique files.                              
     155 files ignored.

github.com/AlDanial/cloc v 1.96  T=0.29 s (175.9 files/s, 19969.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Jupyter Notebook                 6              0           1222           1914
Python                          10            279            387           1216
TOML                             1             20              7            188
YAML                             6             21              5            150
XML                              8              0              0            101
Markdown                         4             22              0             61
reStructuredText                12             45             39             44
DOS Batch                        1              8              1             26
JSON                             1              0              0             11
make                             1              4              7              9
Text                             1              0              0              4
-------------------------------------------------------------------------------
SUM:                            51            399           1668           3724
-------------------------------------------------------------------------------
```
which I would count as about 1200 LOC — possibly close enough to query the scope but depends on who is handling it. The package looks like you are working to set it up nicely, and looks like it is probably research based. So from a high level view it is probably in scope but might be scrutinized for being relatively small, however I would not recommend submitting a package that is considered alpha (as per the readme), please wait until it is more robust to save editor and reviewer time and effort until it is ready.

**Comment by jsdodge** [comment]
Thanks, @kthyng! We will definitely wait until it is ready for beta status before submitting—we just wanted to know if the size of the codebase would be a problem at this stage. We're approaching a significant milestone and had been hoping that we could submit to JOSS once we reach it. It is a research-based project, so the scope can be extended indefinitely.

Is `cloc` the standard tool that JOSS uses?

**Comment by kthyng** [comment]
Yep, it is used by the bot to run the same stats I posted.

**Comment by jsdodge** [comment]
Thanks again!
