### ISSUE TITLE
Pre-submission enquiry

### ISSUE THREAD

**Issue by sanjeevrs2000** [openjournals/joss#1276]
Dear JOSS editors,

We have been developing [this repository](https://github.com/sanjeevrs2000/cpp) for Coverage Path Planning. It has applications in field robotics where complete coverage of an area of interest is required. It takes in the required Area of Interest and returns a list of waypoint coordinates that generate a trajectory which enables full coverage of the area. 
Could you kindly evaluate its suitability to JOSS and let us know if it is within scope?

Thanks and best regards,
Sanjeev Kumar

**Comment by danielskatz** [comment]
Please just go ahead and submit it, and we'll review the scope at that point

**Comment by sanjeevrs2000** [comment]
Okay, thank you!
