### ISSUE TITLE
DOI badge in accepted papers page leads to review issue, not paper landing page

### ISSUE THREAD

**Issue by kyleniemeyer** [openjournals/joss#128]
The DOI badges for papers on http://joss.theoj.org/papers/popular leads to the review issue, rather than following the actual DOI to the paper landing page.

**Comment by kyleniemeyer** [comment]
Sorry, guess I could have fixed this myself...

**Comment by arfon** [comment]
> Sorry, guess I could have fixed this myself...

:smile: no worries.
