### ISSUE TITLE
Submitting with non OSI approved licences (CC BY-NC-SA 4.0)

### ISSUE THREAD

**Issue by Josef-Haupt** [openjournals/joss#1284]
Hi, we would like to submit a paper for our [repository](https://github.com/kahst/BirdNET-Analyzer).

But in the [review checklist](https://joss.readthedocs.io/en/latest/review_checklist.html) it says that only OSI approved licences will be accepted.
We currently use [Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License](http://creativecommons.org/licenses/by-nc-sa/4.0/). Will this prevent as from beeing accepted?

Also excuse me if this is the wrong place to ask such a question.

**Comment by danielskatz** [comment]
Yes, this will prevent JOSS from accepting this paper for review.
