### ISSUE TITLE
show reviewer's ORCID in JOSS manuscripts

### ISSUE THREAD

**Issue by steo85it** [openjournals/joss#1286]
Hi! During a recent revision ( https://github.com/openjournals/joss-reviews/issues/5728#issuecomment-1754151120 ) it came up that it is not possible to associate an ORCID to JOSS reviewers, similarly to what is available for authors.
It is no big deal, just a suggestion for an (hopefully) easy fix to help acknowledge reviewer's contributions, especially since github's username is often not clearly recognizable.
Thanks!

@mbobra

**Comment by xuanxu** [comment]
This is a future feature we have in mind. The idea is to use the reviewer's citation name and ORCID automatically for every reviewer that added them to their profile at https://reviewers.joss.theoj.org

**Comment by mbobra** [comment]
@xuanxu That's great news, thanks. I wanted to chime in and say I absolutely support @steo85it's suggestion. It would be nice to get some more visibility and credit for the referees.

**Comment by steo85it** [comment]
Thanks @xuanxu for your reply, this looks great: I filled my info in the portal as soon as I saw your message. Great work! I guess I can close this if it's already in your pipeline of planned updates.

**Comment by EpicStep** [comment]
@xuanxu hi! Are there any updates on this feature request?

**Comment by EwoutH** [comment]
After an extensive review process of over 9 months, it would be really nice to see my ORCiD (and full name) on the paper. Can this be given some priority? I think it will help encourage reviewers to keep reviewing.

<img width="2517" height="1412" alt="Image" src="https://github.com/user-attachments/assets/5ef69700-8b13-40b7-84a4-02b156926805" />
