### ISSUE TITLE
Editor docs needs updated with new system for finding reviewers

### ISSUE THREAD

**Issue by AoifeHughes** [openjournals/joss#1289]
- https://github.com/openjournals/joss/blob/main/docs/editing.md
- This link to the dashboard is also not rendering as correct markdown
<img width="708" alt="Screenshot 2023-10-26 at 10 05 46" src="https://github.com/openjournals/joss/assets/10923695/44913761-42e5-49b0-a9d4-30df4097d0cf">

I can make a PR to fix this later today (unless anyone else is super keen)

**Comment by xuanxu** [comment]
Fixed in https://github.com/openjournals/joss/pull/1290
