### ISSUE TITLE
Bad software URL in old paper

### ISSUE THREAD

**Issue by danielskatz** [openjournals/joss#1293]
As noticed by @sdruskat in https://github.com/openjournals/joss-reviews/issues/1760#issuecomment-1801327582, the software repo for the software in https://doi.org/10.21105/joss.01777 is entered as github.com/rmsare/pymccrgb rather than the correct https://github.com/rmsare/pymccrgb which causes the link to be treated as local and not to work.

Can this be fixed in our metadata, and then can the metadata be re-issued?

**Comment by xuanxu** [comment]
Fixed!

**Comment by sdruskat** [comment]
@xuanxu & @danielskatz Sorry for the postscript, but I found two more of the same errors in the current complete set of published papers:

- github.com/dflemin3/approxposterior (10.21105/joss.00781)
- www.github.com/bjodah/chempy (10.21105/joss.00565)

**Comment by danielskatz** [comment]
Thanks for finding these.
I hope @xuanxu can fix them fairly easily.

@xuanxu - do you think this is something we should be checking for in the `generate pdf` processing?
