### ISSUE TITLE
How are programming languages retrieved?

### ISSUE THREAD

**Issue by sdruskat** [openjournals/joss#1295]
I'm currently doing some digging around published paper metadata, and have a question about how languages are pulled into the publication.

It appears that the following code is used to determine the languages for a paper. I'm also _assuming_ that this info comes from the GitHub languages metadata?

https://github.com/openjournals/joss/blob/98775b3c46b8e71fee0e2d9edf74eb4244b6cd96/app/models/paper.rb#L224-L227

So for a [specific repository state](https://github.com/changliao1025/pyflowline/tree/0.3.4) of a [recent publication](https://joss.theoj.org/papers/10.21105/joss.05446) which has the following languages info in the repo: `Jupyter Notebook 56.4%, Python 41.4%, Cython 1.3%, 
TeX 0.7%, Makefile 0.2%, Dockerfile 0.0%`, I would expect the language information on the paper to be: `Jupyter Notebook, Python, Cython, Dockerfile`, as `TeX` and `Makefile` are in the list of [ignored languages](https://github.com/openjournals/joss/blob/98775b3c46b8e71fee0e2d9edf74eb4244b6cd96/app/models/paper.rb#L110-L118). However, the languages shown on the paper are `Dockerfile, Batchfile, Jupyter Notebook`. And `Python` (the second most used language in the repo) appears in the Tags, but not the Languages.

What am I getting wrong?

**Comment by xuanxu** [comment]
The languages are detected by the bot using the same code GitHub uses:

https://github.com/openjournals/buffy/blob/912c2b0753c13ff750625c9d5ed49fd6fec53c2f/app/workers/repo_checks_worker.rb#L52-L58

Thanks to your comment I realized we were not ordering the languages by size before picking the 3 most used. I just fixed it: 

https://github.com/openjournals/buffy/blob/main/app/workers/repo_checks_worker.rb#L52-L58

**Comment by sdruskat** [comment]
Ah, cool, thanks for the quick fix!

**Comment by sdruskat** [comment]
@xuanxu Would it make sense to retroactively fix the language metadata for already published papers?
