### ISSUE TITLE
Interest in assisting with submission triage/review handling

### ISSUE THREAD

**Issue by robcaulk** [openjournals/joss#1299]
Hello!

After a few publications in JOSS, I'd like to start giving back by volunteering to help with submission triage/review handling. Who should I get in touch with to discuss my application?

Thanks,

Rob

**Comment by danielskatz** [comment]
Thanks for your offer, but this is part of the job of the editors.  JOSS does sometimes have calls for new editors, for example, https://blog.joss.theoj.org/2023/10/call-for-editors, but submissions are closed and we are now in the midst of reviewing them and then inviting new editors. We generally advertise these calls via social media, so feel free to keep an eye out if you want.

**Comment by xuanxu** [comment]
If you are interested in reviewing submissions you can sign up and complete your profile as a reviewer here: https://reviewers.joss.theoj.org/join

You can also offer yourself to review directly in submissions you think fall in your field of expertise, if the editor is ok with it they will add you as reviewer for that paper. For example here is a search for pre-review issues for the "Data Science, Artificial Intelligence, and Machine Learning" track: [list of DSAIS pre-reviews](https://github.com/openjournals/joss-reviews/issues?q=is%3Aissue+is%3Aopen+label%3Apre-review+label%3A%22Track%3A+5+%28DSAIS%29%22+)

**Comment by robcaulk** [comment]
Thanks @danielskatz, looks like I narrowly missed the window :) I'm looking forward to the next call for editor applications.

@xuanxu thanks, I am registered as a reviewer, but I was unaware that we could approach pre-reviews without being called upon.
