### ISSUE TITLE
Undefined Control Sequence \citeproctext

### ISSUE THREAD

**Issue by platipodium** [openjournals/joss#1319]
I am using inara with an up-to-date pandoc and stumbled across the following message:

```
Undefined Control Sequence \citeproctext
```
I could trace this back to https://github.com/jgm/citeproc/issues/135 and I suspect that there is an incompatibility with newer pandoc in the joss template.

**Comment by sneakers-the-rat** [comment]
yep. addressed in https://github.com/openjournals/inara/pull/46

**Comment by platipodium** [comment]
Great then this can be close but hopefully leads people with the same problem to the merge request.  What's the hold-up in accepting it?

**Comment by sneakers-the-rat** [comment]
> What's the hold-up in accepting it?

do not know :) not sure who manages that repo
