### ISSUE TITLE
Special issue/section for data access utilities or API wrappers

### ISSUE THREAD

**Issue by epogrebnyak** [openjournals/joss#1336]
I read through the submission guidelines and understand a data access utility is  currently out of scope of JOSS. However they do also play a role in making research reproducible and supporting researcher productivity. 

Also a bit of pain to maintain to make the data access consistent, something the original data provider does not guarantee. 
A kind of public good that is rarely acknowledged. 

I wonder if you considered a separate section in JOSS for data extraction or data management tools. Please close an issue if irrelevant.

**Comment by kthyng** [comment]
Hi @epogrebnyak and thanks for your question. We definitely publish submissions that involve data access but probably not if they are "only" for data access as in they would probably have also some involved analysis or they would be data access to some large or complex database, if that makes sense. To get better information for a specific submission, you could submit and then you might have a scope query in which the editorial team takes a closer look and votes.
