### ISSUE TITLE
question on multi table 

### ISSUE THREAD

**Issue by HPicatto** [openjournals/joss#1338]
Hi I'm trying to compile an article using a [grid table](https://joss.readthedocs.io/en/latest/submitting.html#grid-tables) and it returns 

> Error producing PDF.
> ! Undefined control sequence.
> l.561 \multirow

how can I add the package multirow into the markdown template?

**Comment by HPicatto** [comment]
solved, can add packages at the bigining of markdown using header-includes

**Comment by sneakers-the-rat** [comment]
We should add this to the docs if its required!!!
