### ISSUE TITLE
Does Joss allow for updates to content and authors? 

### ISSUE THREAD

**Issue by jackiekazil** [openjournals/joss#1342]
Hello -- I would like to submit to JOSS to hold the conceptual core for the open source library a manage. While that core for the amount of content that JOSS holds wouldn't change over the years, it may and also the authors depending on-going contributions. 

Can I submit to JOSS and then in the future, update the authors, which provides version number for the paper? Could this work like open source itself? 

I believe having one citation that has the same ID that is the default citation is a better practice than having 10 papers with 10 IDs that repeat the same basic concepts, plus adds on a few distinctions of updates.

**Comment by danielskatz** [comment]
The ideas behind DOIs and archival content has led JOSS to not allow changes to published work, except for small errors that are found immediately after the publication, or technical errors in the metadata.

JOSS's solution for changing software and authors is to submit a new version after sufficient changes and time, often associated with a new major version.

Note that we recognize that the scholarly citation system doesn't deal with versioned objects well.

**Comment by jackiekazil** [comment]
:-( 

But thank you for the response though!
