### ISSUE TITLE
Misplaced item in documentation

### ISSUE THREAD

**Issue by jromanowska** [openjournals/joss#1344]
Shouldn't [this question](https://joss.readthedocs.io/en/latest/review_criteria.html#where-can-i-host-the-repository) be part of "Author guides", not "Review guides"?

I can fix that, but just wanted to double check that I've not misunderstood anything.

**Comment by xuanxu** [comment]
The question is meant to be for reviewers but I agree in its current form ("_Where can I host the repository?_") is misleading, maybe "_Where can I find the repository?_" or "_Where can the repository be hosted?_" would be better.

That info is already mentioned in the "Author guide" [here](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements).
