### ISSUE TITLE
`papers/by/AUTHOR` page doesn't work for names containing period characters

### ISSUE THREAD

**Issue by kandersolar** [openjournals/joss#1346]
On the page for published papers, the list of author names in the side bar is hyperlinked to a page listing all publications by each author.  However, that page seems broken (HTTP 406) for author names containing a period, at least on Chrome -- I observe no issues with Firefox.

Here is an example:

- Paper page: https://joss.theoj.org/papers/10.21105/joss.06714
- Broken link: https://joss.theoj.org/papers/by/James%20P.%20Ewen

Deleting the "." in the URL gets it working for me.

**Comment by sneakers-the-rat** [comment]
Can replicate in local development server. getting a 306 Not acceptable, "ActionController::UnknownFormat in PapersController#filter" right here: https://github.com/openjournals/joss/blob/4cd24daa5176eb8b4f6d7ecb0a93133b9cddc0ca/app/controllers/papers_controller.rb#L136

Chrome doesn't URL encode the `.` as `%2E` while firefox does.
