### ISSUE TITLE
Change wording of review criterion 'functionality documentation'?

### ISSUE THREAD

**Issue by krother** [openjournals/joss#135]
In the two JOSS reviews I've done I found that in the checkbox "Functionality documentation: Is the functionality of the software documented to a satisfactory level (e.g. API method documentation)?" the part "(e.g. API method documentation)" did not apply. In my opinion It might be replaced by something else ("use cases") or be removed.

**Comment by arfon** [comment]
@krother - could you say a little more about that? I suspect we might just have slightly different expectations of what 'API' means. 

The purpose of this requirement is to make sure that all of the public methods (and ideally private ones too) that a user could potentially use are well documented. So if a class exposes public methods `foo` `bar` and `buzz` then there should be documentation describing what each of these methods does.

**Comment by krother** [comment]
Yes, with API I had in mind "interfaces of classes and program modules" or "interfaces of web services". As I understood "API" at first, it does not include "command line interfaces". However, a well-documented CLI is in many cases sufficient. 
I understand the demand for well-documented public methods, but since e.g. in Python all methods are public it is hard to decide as a reviewer which are "potentially useful" unless you do a complete code review. 
Maybe I'm taking the discussion too far.. I guess it varies a lot from one case to the next.

**Comment by arfon** [comment]
> I understand the demand for well-documented public methods, but since e.g. in Python all methods are public it is hard to decide as a reviewer which are "potentially useful" unless you do a complete code review. 

OK. What about adding the word 'core' to [this line](https://github.com/openjournals/joss/blob/master/app/views/shared/review_body.erb#L41):

```
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a
 satisfactory level (e.g. API method documentation)?
```

**Comment by krother** [comment]
Yes, works for me.
