### ISSUE TITLE
dealing with link changes from documentation restructuring

### ISSUE THREAD

**Issue by danielskatz** [openjournals/joss#1350]
I see a message from a paper submitter that says

> Notes to editor: This is a comment regarding the submissions page: It appears that some of the links here don't exist any more! That is, the link https://joss.readthedocs.io/en/latest/submitting.html does exist, but the sections #what-should-my-paper-contain and #checking-that-your-paper-compiles are not there any more. I am checking the middle box anyway, since our paper does compile with the GitHub Action.

It seems that our changes in the docs have changed some URLs, and now we need to change the submitting page as well
cc @sneakers-the-rat

**Comment by sneakers-the-rat** [comment]
looks like it was fixed a few weeks ago - https://github.com/openjournals/joss/commit/31a4b75afa918bed29d6d9eb6ee07d31cd60279e

i just went through and confirmed that all links in this repo to the readthedocs site are correct just to be sure, looks like we're good here!

**Comment by danielskatz** [comment]
that's weird - the submission commenting about this just came in today

**Comment by danielskatz** [comment]
But I've now checked myself, and I agree with you that this all looks fine. Maybe the submitter was using a cached version, or opened the page long ago before this change.

In any case, I'll close this now as no change seems needed.

Thanks @sneakers-the-rat
