### ISSUE TITLE
JOSS and ROR

### ISSUE THREAD

**Issue by danielskatz** [openjournals/joss#1353]
If JOSS asked authors to use [RORs](https://ror.org) to indicate their affiliations, we could pass them to Crossref and be a better member of the community, and it would also be easier for us to understand our authors.

We could also use RORs for editors and reviewers.

**Comment by cthoyt** [comment]
See https://github.com/openjournals/inara/issues/71 and https://github.com/openjournals/inara/pull/72. I was also thinking about this

**Comment by danielskatz** [comment]
Thanks very much @cthoyt for your good and complete work!

**Comment by danielskatz** [comment]
@cthoyt & @xuanxu - We're now having problems accepting papers - see https://github.com/openjournals/joss-reviews/issues/6917#issuecomment-2331099794 for example. Is this problem tied to the ROR-related change?

**Comment by cthoyt** [comment]
looking at it now. will give an update in 20-30 minutes

**Comment by cthoyt** [comment]
See https://github.com/openjournals/inara/pull/77, I think I've got a solution

**Comment by danielskatz** [comment]
👋 @xuanxu & @arfon - Can either of you check this and then potential merge it if that seems appropriate?

**Comment by arfon** [comment]
@cthoyt @tarleb – looks like we have a paper using RORs (yay!), but the paper formatting looks pretty janky (see the spacing between affiliations text): https://github.com/openjournals/joss-papers/blob/joss.07377/joss.07377/10.21105.joss.07377.pdf

Any thoughts on how this could be potentially improved?

**Comment by cthoyt** [comment]
hi @arfon, thanks for being patient. I hope I wasn't holding up the daily JOSS grind. I've got a fix in https://github.com/openjournals/inara/pull/90 - just cleaning up the testing suite now :)

**Comment by cthoyt** [comment]
hi @arfon, we've merged the fix and made a new 1.1.2 release of Inara that includes it

**Comment by tarleb** [comment]
JOSS should make use of the new version once this PR is merged: https://github.com/xuanxu/publishing-artifacts-action/pull/1

**Comment by xuanxu** [comment]
Merged!

**Comment by cthoyt** [comment]
Maybe there's still room for improvement on the vertical positioning and left padding, but this is looking much better already!

**Comment by arfon** [comment]
> Maybe there's still room for improvement on the vertical positioning and left padding, but this is looking much better already!

😻
