### ISSUE TITLE
Pre-submission inquiry for Y0 Causal Inference engine

### ISSUE THREAD

**Issue by cthoyt** [openjournals/joss#1363]
We're planning on submitting a paper describing the [Y0 Causal Inference Engine](https://github.com/y0-causal-inference/y0) and have two clarifying questions:

1. Does JOSS have a notion of "senior" authorship? I.e., the two primary contributors to our software are me and @djinnome. Does it make sense if we put me as the first author and Jeremy as the last author, then denote equal contribution? Jeremy fits the more traditional notion of a senior/last author in addition to being a totally rad coder 🚀. I think this question is important since even if you don't have a notion of a last author, there is still a traditional connotation about the last person in the list
2. Is the supervisor of some of the students who made minor contributions to the package eligible as a co-author? These students also used and applied our software in their research and wrote papers with it, but the supervisor did not meaningfully participate in the software development or direction of the project. Is there a way we can still include them as a co-author under the JOSS guidelines?

cheers. I'm happy to try and formulate these questions and answers into additional documentation for the journal, since I'm already on an OJ PR spree 🐸

**Comment by cthoyt** [comment]
@arfon could you give some advice here? I'm happy to also make a follow-up PR that adds whatever you say to the documentation for future clarification

**Comment by arfon** [comment]
Hi @cthoyt, sorry for the slow reply. In short, it's up to you to decide who should be an author: https://joss.readthedocs.io/en/latest/submitting.html#authorship

As for ordering 'seniority' of authorship, your plan sounds reasonable, and I'd encourage you to use the contribution flags in this example (https://github.com/openjournals/inara/blob/main/example/paper.md?plain=1) although of course there's more coming on contributor roles :-)
