### ISSUE TITLE
Error when attempting new submission

### ISSUE THREAD

**Issue by alb3rtjarvis** [openjournals/joss#1372]
Hello,

When attempting to submit a new paper, the JOSS site returns the following error:

"We're sorry, but something went wrong.
If you are the application owner check the logs for more information."

and I do not see any issue created at: https://github.com/openjournals/joss-reviews/issues

I have tried on both Firefox and Opera and still get the same error. Please let me know if you need any other information from me. Thanks!

**Comment by JeffreyRStevens** [comment]
I'm having same experience. Tried on Firefox and Brave.

**Comment by sneakers-the-rat** [comment]
Pinging @openjournals/dev

**Comment by sneakers-the-rat** [comment]
Can't replicate in dev environment, can replicate on prod site.

**Comment by FlyingWorkshop** [comment]
I'm also having this issue.

**Comment by sneakers-the-rat** [comment]
Can anyone on @openjournals/dev put up a notice that submitting papers is broken atm and we're working on it? I don't think i have commit privs otherwise i'd do it

**Comment by samuelmurail** [comment]
Same issue on my side.
Cheers

**Comment by xuanxu** [comment]
This should be fixed now. After an update on the Heroku stack, there was a missing dependency.
Please reopen if still having the issue.

**Comment by duodenum96** [comment]
Hello, 

I'm having the same problem with the error message 
"""
The page you were looking for doesn't exist.
You may have mistyped the address or the page may have moved.

If you are the application owner check the logs for more information.
"""

Replicated this error in both microsoft edge and google chrome. Would appreciate any help.

**Comment by duodenum96** [comment]
Sorry for the above comment. I was a able to login without problems using firefox. 

> Hello,
> 
> I'm having the same problem with the error message. """ The page you were looking for doesn't exist. You may have mistyped the address or the page may have moved.
> 
> If you are the application owner check the logs for more information. """
> 
> Replicated this error in both microsoft edge and google chrome. Would appreciate any help.

**Comment by duodenum96** [comment]
Google chrome and microsoft edge
