### ISSUE TITLE
Problems with indexing under Google Scholar

### ISSUE THREAD

**Issue by MartinBeseda** [openjournals/joss#1376]
Hello everybody,
recently (~ 4 weeks ago) we've published a paper under JOSS (https://joss.theoj.org/papers/10.21105/joss.06036), while the pre-print was published on ArXiv before (https://arxiv.org/abs/2401.11884).

Today I found a puzzling thing, where the JOSS paper is not indexed by Google Scholar yet (while ArXiv is indexed in the matter of days), but it "returns" the ArXiv pre-print, when looking for JOSS DOI. 

![screen](https://github.com/user-attachments/assets/e80c8af1-65cc-42b0-922d-c194a7033eca)

I'm not sure, what's happening here, as GS seems to find the DOI correctly together with the paper's title, but it seems unable to index the JOSS page, so it resorts to returning only ArXiv version, which is visible. Now, as the crawler clearly found the title corresponding to DOI already, I find this a little disturbing.

 This issue may or may not be directly connected to problems mentioned in #130 .

**Comment by arfon** [comment]
> I'm not sure, what's happening here, as GS seems to find the DOI correctly together with the paper's title, but it seems unable to index the JOSS page, so it resorts to returning only ArXiv version, which is visible. Now, as the crawler clearly found the title corresponding to DOI already, I find this a little disturbing.

I don't think we know that this is the case (that Google Scholar can't index the JOSS page). A quick check of a random paper from two weeks ago finds the JOSS record correctly: https://scholar.google.com/scholar?hl=en&as_sdt=0%2C5&q=%22Statmanager-kr%3A+A+User-friendly+Statistical+Package+for+Python+in+Pandas%22&btnG=

My guess is that there's something weird going on here with Scholar and the fact that the paper is also on arXiv. 

Other than ensuring that the correct metadata are present (which they are for your paper), unfortunately this team has no control over how Google Scholar behaves. 

![Image](https://github.com/user-attachments/assets/d253611b-30b8-45e5-b93e-84968212abbd)

As such, I'd encourage you to take this up with the Google Scholar team.

**Comment by sneakers-the-rat** [comment]
I'm asking some scholcomm people if there's anything extra we need to do to indicate that the JOSS version is the version of record that google scholar would recognize, but looking at a few big journal sites they don't seem to do anything special. 

I am pretty sure you can control which link is presented as the primary link if you have claimed a work as yours in your google scholar profile (and also manually add the joss entry), but i am not seeing those NISO RP-8 tags for indicating version of record being rolled out in html metadata anywhere

**Comment by MartinBeseda** [comment]
@sneakers-the-rat I certainly can, but, if I do add the paper manually, no citations of the DOI will be listed at GS, am I right?

**Comment by sneakers-the-rat** [comment]
I think they will, but dont quote me! from what i recall, you can also add the DOI to a manual entry, and google scholar will automatically merge multiple sources of the same document (i think you can also do merges explicitly as well)

**Comment by MartinBeseda** [comment]
@sneakers-the-rat OK, I'll have a look at these options :) Also, I'd like to see, if the situation changes, if I do upload "Related DOI" of JOSS publication to ArXiv.

**Comment by logological** [comment]
> from what i recall, you can also add the DOI to a manual entry

I don't believe this is true.  I tried manually adding an entry to my Google Scholar profile just now and the form I was presented with had no field to enter a DOI.

**Comment by tennlee** [comment]
We have a potentially related issue. See the discussion thread https://github.com/openjournals/joss-reviews/issues/6889#issuecomment-2519661513 . Looking at your CrossRef data (https://api.crossref.org/works/10.21105/joss.06036) (note this renders nicely in Firefox), your title field has some errant "\n" newlines in it. Some of the other fields also show this. It's not necessarily the cause of the indexing issue, but it does strike me as something that would ideally be resolved and excluded as a potential cause. @xuanxu has kindly taken up the cause to look into the case of the errant newlines.

**Comment by MartinBeseda** [comment]
@tennlee Thank you for the great observation! Also, many thanks to @xuanxu and I'm really curious, if it helps :)

**Comment by tennlee** [comment]
@xuanxu fixed what I presume is the root cause for the errant newlines, and also our editor updated/re-published our paper. It may or may not affect the Google Scholar indexing. @MartinBeseda you might want to ask about a similar re-update. If our paper starts being found by Google Scholar, I can post an update here to let everyone know it's worth a try.

**Comment by MartinBeseda** [comment]
@tennlee Did you notice any change considering GoogleScholar indexing of your paper?

**Comment by tennlee** [comment]
No, unfortunately. It briefly re-appeared, and then disappeared again. I'm still please to have the newlines issue resolved, but the fix was not sufficient to resolve the issue with indexing. The brief re-appearance may also have been unrelated to the fix, it's hard to know.

**Comment by MartinBeseda** [comment]
@tennlee Thank you for your answer! That's really unfortunate... Do we have any means to recognize, what's the problem? Its strange, as the Arxiv.org version of the paper is there and GS also found the Arxiv version indexed through inspirehep.net and ui.adsabs.harvard.edu. But it seems, to completely ignore the original JOSS version, even if that one is linked to from Arxiv.org...

**Comment by tennlee** [comment]
Apparently I was incorrect, and the brief re-appearance didn't happen, I was misremembering what happened in what order. The sequence of events for us was:

1. ArXiv first version published
2. Google Scholar finds the first arXiv version
3. Second version published on arXiv with an updated title among other small changes
4. Google Scholar has not yet re-indexed this updated version, so it shows the old title, but the links go through to the new version on arXiv
5. Then it was published in JOSS (thanks JOSS, you were awesome)
6. Then, shortly after that, Google Scholar found the JOSS paper and indexed it correctly
7. Then, shortly after, maybe a few days, the JOSS version disappeared from Google Scholar altogether, and it went back to the first version on arXiv which it still hasn't re-indexed
8. JOSS fixes the newlines issue (and unfortunately this didn't fix the Google Scholar problem)

Like you, if we put the JOSS DOI into Google Scholar, it finds the first arXiv version and not the JOSS version. 

I don't see how to further diagnose what may be going on, I have no insight here. However, I felt like I should correctly spell out our sequence of events in case it can help someone. I think JOSS have done all they can, however.

**Comment by MartinBeseda** [comment]
@tennlee Thank you very much for you insight and a very detailed answer!

**Comment by MartinBeseda** [comment]
OK, now it seems, that the JOSS paper was indexed by Google Scholar out of nowhere... It's still not the "default" one, which is being found, but it can be seen in the list of different versions of the paper.

**Comment by MartinBeseda** [comment]
@arfon If it's still relevant, I think I know, what's the problem with GS indexation. It doesn't index JOSS papers as "papers" but as PDFs. That's why there are futher problems with them not allowed to be a "main" paper if there are some Arxiv preprints, etc. It happens very much the same with CEUR papers ([https://ceur-ws.org/](https://ceur-ws.org/)). Even the paper you provided some time ago as an example isn't registered as a paper, but only PDF: [https://scholar.google.com/scholar?hl=en&as_sdt=0%2C5&q=%22Statmanager-kr%3A+A+User-friendly+Statistical+Package+for+Python+in+Pandas%22&btnG=](https://scholar.google.com/scholar?hl=en&as_sdt=0%2C5&q=%22Statmanager-kr%3A+A+User-friendly+Statistical+Package+for+Python+in+Pandas%22&btnG=). The "paper webpage" would be [https://joss.theoj.org/papers/10.21105/joss.06642](https://joss.theoj.org/papers/10.21105/joss.06642), but that one is NOT indexed but GS, because it finds the visible PDF at the webpage.

Would it be possible to make a webpage without the PDF frame, where PDF would be simply opened after clicking on some View button? I believe it'd really deal with the complications here.

**Comment by arfon** [comment]
> Would it be possible to make a webpage without the PDF frame, where PDF would be simply opened after clicking on some View button? I believe it'd really deal with the complications here.

I'm not sure what problem this solves? Are you saying that the JOSS page would then become the 'defacto' one for the DOI?

I don't really want to change the default JOSS UI for a robot (GS indexer) but perhaps we could do some conditional rendering based on the user agent?

**Comment by MartinBeseda** [comment]
@arfon 

> I'm not sure what problem this solves? Are you saying that the JOSS page would then become the 'defacto' one for the DOI?

Well, basically yes. The current problem is that all the papers are indexed only as "standalone PDF" and not as a "paper". That means that the default (visible) version on Google Scholar is almost always only arXiv and not JOSS, and also some metadata are not extracted from the JOSS webpage in such a situation. That causes further problems with citations, as the exported citations from GS then reference only arXiv (or some other) versions and not JOSS with priority.

> I don't really want to change the default JOSS UI for a robot (GS indexer), but perhaps we could do some conditional rendering based on the user agent?

What do you exactly mean by "conditional rendering"? I'm pretty sure that the easiest way would be to open the PDF after clicking on some link or button on the webpage. It seems that when GS finds a PDF on the "first" journal webpage with metadata, it concludes it's "only" PDF in that case. Otherwise, I'm not sure how to bypass this stupid classification system they're using. Maybe also add some other "front webpage" for the paper?

I'm talking about this, as in some countries (Italy in my case) GS is getting more prominent recently, and this could be rather easy to improve on, if there's time, of course.
