### ISSUE TITLE
Request for information from JOSS reviewers

### ISSUE THREAD

**Issue by arfon** [openjournals/joss#138]
Dear @openjournals/joss-reviewers, we now have ~15 submissions to JOSS. Very many thanks to those who have helped out with reviews already!

We'd like to adapt the review workflow to reduce the noise for this group on GitHub as currently each review issue is creating notifications for all members of the @openjournals/joss-reviewers team even if only a single reviewer is active on the issue.

To reduce the noise we're planning on making smaller reviewer team based on programming language and research topic area. Before we can do this though we need to know each of your preferences.

**Please fill in this three-question Google form with your language preferences and topic areas of interest**: http://goo.gl/forms/4LGHxwfLcU11f7Da2

If you're interested in learning more about our motivations for this change please read this issue here: https://github.com/openjournals/joss/issues/125

**Comment by arfon** [comment]
It worked: https://gist.github.com/arfon/5317c568cb32c7b917fea3c13958131d

💖

**Comment by willdurand** [comment]
@arfon looks like I filled the form too late 😕

**Comment by arfon** [comment]
@willdurand no problem. Do you think you could add your details to this file (https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) in the form of a pull request?
