### ISSUE TITLE
Error attempting new submission: NS_ERROR_REDIRECT_LOOP

### ISSUE THREAD

**Issue by vnmabus** [openjournals/joss#1380]
When attempting to do a submission, by clicking "Submit paper", nothing happens. Inspecting the traffic in Firefox it seems that there is a error: NS_ERROR_REDIRECT_LOOP.

![image](https://github.com/user-attachments/assets/0b5555e3-502f-47a0-bbf9-b10cbc63c611)

I will write here the info, for reproducibility, and in case an editor can create the submission manually:

Title: rdata: A Python library for R datasets
Software's Git repository URL: https://github.com/vnmabus/rdata
Name of git branch containing the paper, not the path: feature/joss_paper
Software version: 0.11.0
Type of submission: New submission
Main subject of the paper: Data Science: Statistical Libraries and Tools [Physical Sciences]
Message to editors: The version proposed for acceptance was already reviewed and accepted by PyOpenSci (https://github.com/pyOpenSci/software-submission/issues/144). There has been (unexpected) new development since this was accepted by PyOpenSci. The new work has being added to the paper in a future/ongoing work section, so that the author of these improvements could be credited as a coauthor. This was a solution proposed by the main organizers of PyOpenSci and JOSS, due to the special situation that happened here (https://github.com/pyOpenSci/software-submission/issues/144#issuecomment-2310512550).

**Comment by danielskatz** [comment]
Can you try again? Papers by others have been successfully submitted to JOSS since you opened this issue.

**Comment by vnmabus** [comment]
Yes, it worked now. Must have been something temporary. Should I close the issue?

**Comment by danielskatz** [comment]
I will
