### ISSUE TITLE
Post-submission enquiry (pre-review not initiated yet)

### ISSUE THREAD

**Issue by multitalentloes** [openjournals/joss#1398]
Dear JOSS,
I submitted a paper about OPM Flow's new framework for Dune-compatible linear solvers on GPUs a month ago called `gpu-ISTL - Extending OPM Flow with GPU Linear Solvers` [(link)](https://joss.theoj.org/papers/8c35a29762fc508215904c0e1dd16013), but pre-review has still not started.

Would it be possible to know the state of this submission, i.e. is there something wrong with the submission or is this wait to be expected?

I also reached out via mail to [admin@theoj.org](mailto:admin@theoj.org) a bit over a week ago but have not received any response yet.

Thank you in advance

**Comment by danielskatz** [comment]
Sorry, something seems to have gone wrong in our system with this. Thanks for letting us know.  We'll check into this, and get back to you.
