### ISSUE TITLE
Should make it clear what our business model is

### ISSUE THREAD

**Issue by arfon** [openjournals/joss#145]
I've had some enquiries from folks about what our long-term business model is for JOSS. My answer is 'none', that is:

- We don't plan to have article processing charges (ever)
- We have clear policy on content licensing (CC-BY): http://joss.theoj.org/about#content_license

I'm thinking we should have a short section on the about page outlining this, perhaps with an overview of our running costs?

What do people think?

/ cc @openjournals/joss-editors

**Comment by katyhuff** [comment]
> have a short section on the about page outlining this, perhaps with an overview of our running costs?

I think that's a good idea.

**Comment by Kevin-Mattheus-Moerman** [comment]
Great! I agree it should remain free. I think openly sharing our running costs is a good idea too.

**Comment by cMadan** [comment]
I think it's good to have some text about this. I also have seen this come up on twitter a few times, so it would be good to have some 'standard' response to point people to.
