### ISSUE TITLE
Retain URL's in PDF version

### ISSUE THREAD

**Issue by pjotrp** [openjournals/joss#152]
In PDF version of the GeneNetwork paper the URL's got lost. PDF supports link-outs and we can generate them. I suggest we support that feature.

**Comment by arfon** [comment]
Can you tell me where the links are failing for you? I've downloaded the PDF (https://github.com/openjournals/joss-papers/blob/master/joss.00025/10.21105.joss.00025.pdf) and the links all work for me:

![links](https://cloud.githubusercontent.com/assets/4483/16882687/8c6e533e-4a7d-11e6-8c46-a42ffa95bb4f.gif)

**Comment by pjotrp** [comment]
I tried 

```sh
wget https://github.com/openjournals/joss-papers/blob/master/joss.00025/10.21105.joss.00025.pdf
xpdf 10.21105.joss.00025.pdf
```
and get

```
Error: PDF file is damaged - attempting to reconstruct xref table...
Error: Couldn't find trailer dictionary
Error: Couldn't read xref table
```

Also acroreader also fails. Using elinks to solve redirection elinks wants to start xpdf and I get the same error again. The github in-browser reader shows the PDF but does not show links (FF 36.0) - which is what I reported on.

**Comment by arfon** [comment]
I'm not sure you get the PDF if you `wget` it like that because the actual file is at `https://github.com/openjournals/joss-papers/raw/master/joss.00025/10.21105.joss.00025.pdf`

When I use the download button on the GitHub UI (or use `wget` with the address above) I can open in Preview on Mac and Adobe Reader.

The links aren't going to work in the GitHub UI as they're disabled there by default by GitHub.

**Comment by pjotrp** [comment]
I followed your previous link ;). OK tried again and now I can view the file with xpdf 3.03 and acroread on Linux - but no URLs in there. Also not in the browser version. What PDF viewer are you using?

**Comment by pjotrp** [comment]
Maybe someone can confirm it works on Windows? I can try a Linux fix later this month.

**Comment by arfon** [comment]
> Maybe someone can confirm it works on Windows? I can try a Linux fix later this month.

I've just checked on a Windows 8 VM and the links work find in Adobe Reader. Perhaps this is an issue with Linux and/or your setup? Seems really weird though that they're not working.

**Comment by pjotrp** [comment]
Other documents work fine. Only JOSS PDF's give this problem. I'll need to check what libs the generated TeX code is using.

**Comment by arfon** [comment]
>  I'll need to check what libs the generated TeX code is using.

OK good to know. This is the latex template we're using: https://github.com/openjournals/whedon/blob/master/resources/latex.template and this is the command we run to convert from Markdown to PDF: https://github.com/openjournals/whedon/blob/master/lib/whedon/processor.rb#L156-L164

**Comment by arfon** [comment]
🎏 flagging this as stale 🎏 

@pjotrp - did you manage to get to the bottom of this?

**Comment by arfon** [comment]
@pjotrp - we've recently updated the PDF generation. Can you take a look at a recent paper [such as this one](http://www.theoj.org/joss-papers/joss.00396/10.21105.joss.00396.pdf) and see if this issue still persists?

**Comment by arfon** [comment]
Closing this as stale.
