### ISSUE TITLE
Citation Info

### ISSUE THREAD

**Issue by michaellevy** [openjournals/joss#157]
A few suggestions for paper pages, all in the spirit of making it as easy as possible for other researchers (who may not be computationally oriented) to cite the paper.
- Provide the citation in plain text on the main paper page. The doi2bib link is great for bibtex users, but this would add clarity and help non-bibtex people.
- The doi2bib link seems to pick up authors' middle initials as their first initials (at least [mine](http://www.doi2bib.org/#/doi/10.21105/joss.00036) does).
- Zotero's "Save to Zotero" plugin (Chrome, OS X) detects the citations in the paper as citations to grab, rather than identifying just the paper of interest. Not sure how hard it would be to fix this.

**Comment by VickySteeves** [comment]
:+1: to this idea -- citations should be available in plain text on the paper page. There are [APA standards](http://blog.apastyle.org/apastyle/2015/01/how-to-cite-software-in-apa-style.html) for citing software, [MLA standards](http://www.citethisforme.com/guides/mla/how-to-cite-a-software), [Chicago standards](https://www.pierce.ctc.edu/library/ref/files/cms_citations.pdf) (on page 2), etc. Not saying that all of these should be available on the paper's page, but you could pick one standard and go with it.

**Comment by arfon** [comment]
Thanks for suggesting this @michaellevy. I definitely want to improve this part of the site.

> 👍 to this idea -- citations should be available in plain text on the paper page. 

@VickySteeves do you know of any standard libraries (ideally in Ruby or JavaScript) that can be used to generate these?

Of course if either of you were interested in improving this functionality yourselves I'd welcome a pull request implementing these changes 😁

**Comment by danielskatz** [comment]
Not just in plaintext, but in BibTex and a bunch of other standard formats...

It does seem like there should be a library for this.  Or perhaps we could use the http://www.doi2bib.org/#/doi service?  Or other services like this?

**Comment by michaellevy** [comment]
Does this do it? https://code.google.com/archive/p/bibtex-js/

**Comment by VickySteeves** [comment]
@arfon Can I wait until October so I get the credit for Hacktober? :wink: 

So the thing is -- they already have the doi2bib link, I think the original point was that _non bibtex users_ should get a plain text citation already on the page -- this makes it easy for programs like Zotero to grab them, like @michaellevy explained in the original issue. 

I haven't yet found a library to do this, but I'm on the lookout.

**Comment by arfon** [comment]
> @arfon Can I wait until October so I get the credit for Hacktober? 😉

But of course!

> It does seem like there should be a library for this. Or perhaps we could use the http://www.doi2bib.org/#/doi service? Or other services like this?

Yep, @danielskatz we already link to http://www.doi2bib.org/#/doi. I'd love to find another generic service that can format a citation based on a DOI lookup.

**Comment by augustfly** [comment]
Isn't CSL built into content negotiation via citeproc? 

http://www.crosscite.org/cn/

there's even a restful service:

http://crosscite.org/citeproc/format?doi=10.21105/joss.00075&style=apa&lang=en-US

or a server

https://github.com/crosscite/citeproc-doi-server

something like this is what datacite uses to have a dropdown "cite" formatter on their search pages:

http://search.datacite.org/works?query=JOSS&resource-type-id=software

**Comment by arfon** [comment]
> http://crosscite.org/citeproc/format?doi=10.21105/joss.00075&style=apa&lang=en-US

💥 look at that. Very nice @augustfly. I'd forgotten about this service. Looks like there's a [ton of styles too](http://crosscite.org/citeproc/styles).

**Comment by pboesu** [comment]
I think this is a very important suggestion, and so I've been playing with the latex template a bit to add a footer on the last page of a manuscript that contains citation and license info: https://github.com/pboesu/whedon/blob/citation-license-info/sandbox/output.pdf

I'm new to ruby, so this example was assembled with a bash script using a `curl` call to citations.crosscite.org, but if you think this is a reasonable way forward I'd be happy to try to include this in whedon's generate_pdf routine.

**Comment by arfon** [comment]
👋 @pboesu - this looks **awesome**. Thank you so much for taking a pass at this.

> I'm new to ruby, so this example was assembled with a bash script using a curl call to citations.crosscite.org, but if you think this is a reasonable way forward I'd be happy to try to include this in whedon's generate_pdf routine.

Please go ahead and open a pull request against https://github.com/openjournals/whedon and we can continue the discussion over there?

**Comment by clauswilke** [comment]
This whole discussion seems overkill to me. If you have the year, volume number, issue number, etc. in the database, then generating the output reference for the webpage (or the latex document) should be trivial. No specific library needed. Just print out the data. As an example, see here (written in Liquid, but should be reasonably clear, lines 42-49): https://github.com/wilkelab/wilkelab.github.io/blob/master/publications.html

And if you don't have the citation info in your database, where is it stored?

**Comment by arfon** [comment]
> This whole discussion seems overkill to me. If you have the year, volume number, issue number, etc. in the database, then generating the output reference for the webpage (or the latex document) should be trivial.

We do not.

> And if you don't have the citation info in your database, where is it stored?

It's associated with the Crossref DOI.

**Comment by clauswilke** [comment]
> It's associated with the Crossref DOI - e.g. https://github.com/openjournals/joss-papers/blob/master/joss.00133/10.21105.joss.00133.crossref.xml

That should be good enough, since presumably you can read these files from your ruby script.

But the better architecture would definitely be to store the key citation info in your own database.

**Comment by arfon** [comment]
> That should be good enough, since presumably you can read these files from your ruby script.

Yep. For sure. There's no disagreement here about doing this, it's just about technical bandwidth to actually implement this.

**Comment by peterjc** [comment]
Currently http://www.doi2bib.org/ is offline, so with no plain text citation information given, all the reader has is the DOI.

**Comment by arfon** [comment]
In https://github.com/openjournals/joss-papers/pull/2 I put a short-term fix in by simply writing out a  plain citation string, e.g.:

> Batut et al., (2017), _Journal of Open Source Software_, 2(18), 418, doi:10.21105/joss.00418

**Comment by danielskatz** [comment]
I would very much for that to include the article title.

**Comment by arfon** [comment]
> I would very much for that to include the article title.

Sorry, forgot about that. Will work on that shortly.

**Comment by arfon** [comment]
> Sorry, forgot about that. Will work on that shortly.

Done.
