### ISSUE TITLE
Travis build fails (when user isn't part of github/openjournals?)

### ISSUE THREAD

**Issue by jkahn** [openjournals/joss#167]
I submitted a [text-delta-only PR](https://github.com/openjournals/joss/pull/166), and Travis tried to test it, and failed one of the tests:

https://travis-ci.org/openjournals/joss/builds/156634500

I don't have enough bandwidth to debug this right now and I imagine it's low priority, since I'm not a participant in this org, but I thought I should raise this concern in case the toolkit could fix the bug.

**Comment by arfon** [comment]
> I don't have enough bandwidth to debug this right now and I imagine it's low priority, since I'm not a participant in this org, but I thought I should raise this concern in case the toolkit could fix the bug.

Thanks for submitting this @jkahn. This is failing as we stub the request for creating the review issue (the template you've just edited) as part of the test suite. The library we're using is a little fussy about the exact form of the requests it's stubbing.

As this has changed, the test is failing.

I'm going to merge your change and fix up the test manually. I'll think about how we can make this less pedantic.
