### ISSUE TITLE
Small bugs in the submission page

### ISSUE THREAD

**Issue by daattali** [openjournals/joss#169]
On the submission page http://joss.theoj.org/papers/new

The "Submit paper" button looks greyed out until the "is clickable even if you don't check the "I certify that I am submitting software for which I am a primary author" option is checked, which is good, but it's clickable. It should be disabled. That's how I submitted the bogus submission http://joss.theoj.org/papers/ba1f8b1a56b24955e112a5bf43ba7807 (I didn't check the checkbox)

On a similar note, the button should be disabled after it's clicked, because otherwise clicking on it twice will result in two submissions (which is why there are currently two submissions for `ezknitr`).

**Comment by arfon** [comment]
Thanks for reporting this @daattali.
