### ISSUE TITLE
Submitted papers tab doesn't include 'submitted' papers

### ISSUE THREAD

**Issue by cMadan** [openjournals/joss#175]
The submitted papers tab (http://joss.theoj.org/papers/submitted) shows 'under review' papers, but doesn't include 'submitted' papers (as shown in the full list http://joss.theoj.org/papers).

**Comment by arfon** [comment]
Fixed in 776fa2ee132f815fed7d7173e38aca1319742ad9. Thanks for spotting this @cMadan. I've also changed this to better represent what the filter is - it includes anything that's in progress in the system.
