### ISSUE TITLE
Interest in Docker version of JOSS?

### ISSUE THREAD

**Issue by mfenner** [openjournals/joss#178]
Has someone worked on a Docker version of the JOSS software? And if not, is there interest in such a version? A Docker version will make it easier to run the software locally for development, and also adds a lot of flexibility to deployment. I would be happy to do that work.

**Comment by arfon** [comment]
> Has someone worked on a Docker version of the JOSS software? 

No but that would be really helpful! We're currently running on Heroku which makes for easy deployments etc but local development isn't really optimised.

> I would be happy to do that work.

✨ that would be great! I'd certainly welcome this contribution. One question - do you think we'd be able to maintain compatibility with Heroku with this work? It looks like they have [beta support for Docker](https://devcenter.heroku.com/articles/container-registry-and-runtime) on Heroku. I'm pretty new to Docker stuff myself though so I've no idea how big a request this is :-)

**Comment by mfenner** [comment]
Docker is probably a bit orthogonal to Heroku, so if you are happy with Heroku there is no real reason to switch to Docker right now. Maybe the first step is to allow local development using Docker, something that works really nice even on a Mac since [Docker for Mac](https://docs.docker.com/docker-for-mac/) was released. I would recommend to use [Docker Hub](https://hub.docker.com/) with automated builds from Github. I can do a pull request in the coming weeks.

**Comment by arfon** [comment]
> Maybe the first step is to allow local development using Docker, something that works really nice even on a Mac since Docker for Mac was released. I would recommend to use Docker Hub with automated builds from Github. I can do a pull request in the coming weeks.

👍 sounds great. Thanks Martin.

**Comment by arfon** [comment]
Closing as stale.
