### ISSUE TITLE
ISSN for JOSS

### ISSUE THREAD

**Issue by satta** [openjournals/joss#184]
It would be nice if JOSS had an ISSN assigned. This would allow it to be included, for example, in ResearchGate's list of journals, making it possible to link to entries (https://explore.researchgate.net/display/support/Editing+publications).

Here is some information about ISSN assignment rules for electronic resources:
http://www.issn.org/understanding-the-issn/assignment-rules/the-issn-for-electronic-media/

**Comment by arfon** [comment]
⚡️ thanks for reminding me to do this @satta. I've just submitted an application for an ISSN.

**Comment by satta** [comment]
Cool, looking forward to see this happen :)

**Comment by satta** [comment]
I've been wondering if there has been any progress in this regard? Just curious how long it takes to get one of these...

**Comment by arfon** [comment]
> I've been wondering if there has been any progress in this regard? Just curious how long it takes to get one of these...

I'm afraid I've not heard anything back since my application some months ago. Thanks for the reminder though - I should chase this up 😄

**Comment by arfon** [comment]
Quick update: I got an email from the Library of Congress this morning and we have an ISSN for JOSS!

Journal of Open Source Software: ISSN 2475-9066

**Comment by kyleniemeyer** [comment]
(Whoops, fat fingers...

Great!

**Comment by Kevin-Mattheus-Moerman** [comment]
Fantastic!

**Comment by danielskatz** [comment]
I think this is good, but what do we need to do with it?  Does it become part of the metadata for new articles?  Does it need to be inserted into the metadata for old articles?  Or something else completely different?

**Comment by arfon** [comment]
> I think this is good, but what do we need to do with it? Does it become part of the metadata for new articles? Does it need to be inserted into the metadata for old articles? Or something else completely different?

Great question. I actually don't know. Need to figure this out next...

**Comment by labarba** [comment]
Maybe we can get the kind advice of @Repositorian on this question?

**Comment by Repositorian** [comment]
:-) Ahoy there!  ISSN is necessary to register DOIs with CrossRef and to be listed in DOAJ. It is also used by libraries (and other discovery agencies) to uniquely identify the journal in our various search and retrieval systems. Please put it on the masthead of your journal site and make it available in all journal metadata you supply.

**Comment by Repositorian** [comment]
PS: Martin Eve's guide on starting an OA journal might be worth a look: https://www.martineve.com/2012/07/11/starting-an-open-access-journal-a-step-by-step-guide-part-2/. (Not that librarians don't love being asked to provide roadside assistance - we do!)

**Comment by arfon** [comment]
> :-) Ahoy there! ISSN is necessary to register DOIs with CrossRef and to be listed in DOAJ.

Hi @Repositorian, many thanks for the input here. As far as I know the ISSN isn't _strictly_ required by Crossref (although it is presumably preferred) as we've managed to register ~70 DOIs for papers so far without one. See an example of the paper metadata [here](https://github.com/openjournals/joss-papers/blob/master/joss.00011/10.21105.joss.00011.crossref.xml). I'm assuming that now we have one then we should update our Crossref metadata with the ISSN for good bookkeeping.

**Comment by Repositorian** [comment]
Ah, thanks for the correction.  When we query the CrossRef API, we do rely on the ISSN in the CrossRef metadata record to disambiguate the journal. Libraries view the ISSN as the definitive 'name' for a periodical and expect it to be in any system we query.

**Comment by arfon** [comment]
> Ah, thanks for the correction. When we query the CrossRef API, we do rely on the ISSN in the CrossRef metadata record to disambiguate the journal. Libraries view the ISSN as the definitive 'name' for a periodical and expect it to be in any system we query.

👍 good to know. Thanks!

**Comment by arfon** [comment]
OK I've updated the title-level DOI for JOSS with the ISSN (deposited meta data here: https://gist.github.com/arfon/d05956490e0d908d81d8219b07b9340e)

In addition we'll be including the ISSN with the paper DOI metadata going forward: https://github.com/openjournals/whedon/pull/7

Finally, at some point we should update the existing Crossref metadata for all previously published papers (https://github.com/openjournals/joss-papers). I'll track that in another issue.

**Comment by Repositorian** [comment]
Congrats to you all on your 100th article!  Nice to see via twittersphere :-)

**Comment by gauteh** [comment]
Hi, this is great, I was searching the web-site for this info - maybe it should be promoted more visibly there?
