### ISSUE TITLE
Creating an new issue from pre-review to review is confusing

### ISSUE THREAD

**Issue by pjotrp** [openjournals/joss#185]
Can we use one single issue tracker for pre-review and review? Switching between issues - i.e., different URLs for pre-review and review - is confusing for editors, authors and reviewers.

I suggest to put the checklist on top in pre-review - so that is clearer too what is demanded of reviewers.

**Comment by pjotrp** [comment]
Note that I lost track of 3 papers this way and had to manually retrack.

**Comment by cMadan** [comment]
I think I'm on the other side for this one... it would probably be good to clearly link to the author/reviewer guidelines in the top of the pre-review, but I do like having a separate pre-review and review. Before the pre-review stage was added, I saw the first 5-10 comments all be about recruiting reviewers, rather than actually 'reviewing'.

**Comment by pjotrp** [comment]
Does that having information on finding reviewers actually hurt review? It is out in the open already. 

Current system is *confusing*. That is my point. Confusion means people make mistakes. Why close an issue, for example, if the process is ongoing?

I see no point in having two issues per submission.

**Comment by arfon** [comment]
Thanks for posting this @pjotrp. I agree this isn't perfect but it's important to remember why we moved to a two-issue-per-submission system and that was to reduce (GitHub notification) noise for people (see https://github.com/openjournals/joss/issues/125#issuecomment-222144096). 

Having the [PRE REVIEW] issue limited in scope to simply finding a reviewer means that we can mention lots of different users (and groups of users e.g. `@openjournals/joss-reviewers`) while searching for a reviewer. It's important to remember that once someone is mentioned on a thread on GitHub they will (usually) receive an email for any and every update to that thread. I received numerous complaints from reviewers about this. 

With the current system, once the reviewer is found then the main review (however long and noisy it might be) only involves three individuals: the editor, the reviewer and the submitting author.

> Current system is confusing. That is my point. Confusion means people make mistakes. Why close an issue, for example, if the process is ongoing?

Perhaps we can clear some of this confusion up by adding some additional language to the initial [PRE REVIEW] issue body. In addition, perhaps we should add some additional explanation in the `@whedon` comment once the review has been started (e.g. [this one](https://github.com/openjournals/joss-reviews/issues/89#issuecomment-253291366)).

> Note that I lost track of 3 papers this way and had to manually retrack.

When the main [REVIEW] issue is created (after the [PRE REVIEW] issue), `@whedon` mentions the editor, reviewer and author in the issue he creates (see [this one](https://github.com/openjournals/joss-reviews/issues/92#issue-182593775) for example). Are you not getting these notifications @pjotrp?

**Comment by pjotrp** [comment]
Yes, I think we should be a lot clearer. Why don't we add the following:

1. When closing pre-review issue make the last message very clear staying that we move to a new issue for full review, with a link. Perhaps reiterate that editor is editor and reviewer is reviewer and they should look up the new issue

2. IN the new issue have whedon reassign the reviewer, author and editor in a message. Also assign the github issue to the reviewer and editor. Also regenerate the PDF and have clear links in the first message (after the instructions) that point to git, PDF and MD versions of the paper. Perhaps also point to the pre-review.

Then it should be clear and the issue should be fully visible to people.  I know you have done some of this, but can we automate it and make sure it happens fully every time? That would make me happy :). When we make things hard to find I won't find them.

**Comment by kyleniemeyer** [comment]
I feel like the changes proposed in this issue have been made—can we close?

**Comment by arfon** [comment]
> IN the new issue have whedon reassign the reviewer, author and editor in a message. Also assign the github issue to the reviewer and editor. Also regenerate the PDF and have clear links in the first message (after the instructions) that point to git, PDF and MD versions of the paper. Perhaps also point to the pre-review.

Well, this part isn't done but we've definitely improved this.

**Comment by arfon** [comment]
Closing this as stale. We now have significantly improved tooling for editors to track submissions.
