### ISSUE TITLE
bananas is bananas

### ISSUE THREAD

**Issue by danielskatz** [openjournals/joss#199]
Can we get rid of the bananas?  I don't see how this currently serves any useful function, and it sends everyone 2 extra emails/notifications for each review that starts.

**Comment by arfon** [comment]
:-( ok, you're probably right. As this is an action that creates something, I was trying to make it harder to run this command (i.e. make sure that the editor doing this _really_ wants to start the review) but I can see how this would be annoying.

**Comment by acabunoc** [comment]
I support this change. If you point me to the file, I can probably send a PR with with the change if that would be helpful, @arfon 

🍌😝🍌😝🍌😝🍌😝🍌😝

**Comment by arfon** [comment]
I agree that we should get rid of this but I don't think we should do it until Whedon knows how to report errors back to people issuing commands. https://github.com/openjournals/whedon-api/issues/6 is a priority item for the Sloan-funded work.

**Comment by danielskatz** [comment]
Can we get rid of bananas now?  The more we write about it in the docs, the less "magic" it appears.
