### ISSUE TITLE
I'd like to review for JOSS

### ISSUE THREAD

**Issue by fgnievinski** [openjournals/joss#203]
Especially at the intersection of geosciences and matlab.

Congrats for the initiative.

**Comment by arfon** [comment]
:wave: @fgnievinski, thanks for offering to review for JOSS.

So that we can invite you to review on relevant papers, could you please add your details to this file (https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) in the form of a Pull Request?

Many thanks!
