### ISSUE TITLE
Should JOSS join one of COPE, DOAJ, OASPA?

### ISSUE THREAD

**Issue by genomematt** [openjournals/joss#215]
Although JOSS can not be accused of being a predatory publisher, it may be useful to join one of the publication ethics organisations to get their official stamp of approval.

 Committee on Publication Ethics (COPE) http://publicationethics.org/

 Directory of Open Access Journals (DOAJ) https://doaj.org/

Open Access Scholarly Publishers Association (OASPA) http://oaspa.org/

At a minimum an ostentatious statement that we comply with the suggested ethical procedures of one of these organisations would be worthwhile.

**Comment by nuest** [comment]
+1 to be listed on DOAJ, it's a "proper" directory that is widely accepted afaics.

**Comment by cMadan** [comment]
+1 for DOAJ; not sure about the other ones

**Comment by edmundlaugasson** [comment]
Would encourage to determine JOSS in one of the scientific databases. E.g. Estonian Research Portal has the following classification - https://www.etis.ee/Portal/Classifiers/Index?language=ENG - please look at _Publication classification_ under _Publications_ title. Only 1.1, 1.2 and 3.1 categories will count for doctoral students and it would be interesting to know whether JOSS belongs one of them.

**Comment by cMadan** [comment]
@edmundlaugasson - I think we're on-track to count as 1.2. We've applied for an ISSN (https://github.com/openjournals/joss/issues/184) and are international.

**Comment by arfon** [comment]
👍  yep, this sounds like a great idea. Do you know anyone at DOAJ? It looks like we have to have an ISSN to fill out the form and we're still waiting on this from the Library of Congress (see https://github.com/openjournals/joss/issues/184) and it would be good to find out if this is a hard requirement.

**Comment by cMadan** [comment]
I don't know anyone at DOAJ, just feel it has a solid reputation and principles. From the website, it does seem like the ISSN is a hard requirement (https://doaj.org/publishers#advice), but perhaps its possible to start the DOAJ application before the ISSN is assigned and and be accepted to DOAJ pending the ISSN.

**Comment by arfon** [comment]
OK, we've now got an ISSN for JOSS which should make this more straightforward. @cMadan - any interest on taking the lead on registering us with DOAJ?

**Comment by cMadan** [comment]
@arfon - I was looking through the issues here and just noticed that you tagged me on this. I'll scope it out :). (Sorry for not noticing earlier!!)

**Comment by cMadan** [comment]
@arfon - I went through the DOAJ application (https://doaj.org/application/new). There were a few things we need to do (or that I wasn't sure of) to be eligible for the "DOAJ Seal", though this is a bit more particular than just being listed in the DOAJ (see bottom-right of the application). I've already submitted the application as-is and the confirmation screen says we it could be up to 6 months before we hear back.

> have an archival arrangement in place with an external party (Question 25). 'No policy in place' does not qualify for the Seal.

Options include: LOCKSS, CLOCKSS, Portico, PMC

> provide article level metadata to DOAJ (Question 29). 'No' or failure to provide metadata within 3 months do not qualify for the Seal.

We'd need to add this infrastructure in

> embed machine-readable CC licensing information in article level metadata (Question 45). 'No' does not qualify for the Seal.

I don't think we do this?

> have a deposit policy registered in a deposit policy directory. (Question 51) 'No' does not qualify for the Seal.

Options include: Sherpa/Romeo, Dulcinea, Héloïse, Diadorim

**Comment by arfon** [comment]
OK thanks for reading up on this @cMadan. Sounds like the biggest thing we need to do here to support this is to start generating [JATS XML](https://jats.nlm.nih.gov/about.html) for all of our articles. This is definitely possible but will take some dedicated time to get up and running.

CLOCKSS for example, relies upon this format for ingesting articles as far as I can tell. One additional benefit of having JATS XML is that we can be more easily indexed by third parties such as [ScienceOpen](https://www.scienceopen.com/).

Anyway, thanks for looking into this!

**Comment by kyleniemeyer** [comment]
Any status update on this stuff?

**Comment by arfon** [comment]
> Any status update on this stuff?

Just that producing JATS XML is one of the tasks I'd like our contractor to work on (hence the `enhancement` label)

**Comment by cMadan** [comment]
Nothing new from the DOAJ application, but apparently it takes awhile.
> We will not reply to emails requesting a status update for applications which are less than 6 months old.

**Comment by kyleniemeyer** [comment]
@cMadan OK, thanks for the update—to clarify, you submitted an application to be listed in DOAJ, and then the extra stuff was to get the "DOAJ Seal"?

I took a quick look at the application site, but this wasn't clear: if we take care of those extra things, can we get "upgraded" with the seal later?

**Comment by cMadan** [comment]
Right, applied to be listed and think we can 'upgrade' to DOAJ Seal later.

**Comment by Kevin-Mattheus-Moerman** [comment]
Great stuff

**Comment by Kevin-Mattheus-Moerman** [comment]
Is the application for JOSS or for Open Journals? The latter would be better so that JOSE can become part of it too.

**Comment by jochym** [comment]
We should also work towards being listed among peer-review journals considered as "proper" by national founding agencies. I do not know how to even start, but know that without this it will be difficult to attract good submissions. Being cited in multiple papers will definitely help.

**Comment by cMadan** [comment]
@Kevin-Mattheus-Moerman - the DOAJ application is for JOSS, each journal needs to apply individually

**Comment by cMadan** [comment]
We are now listed in the DOAJ! 
https://doaj.org/toc/2475-9066

We still need to get our article metadata imported though, which requires generating a DOAJ XML file (https://doaj.org/publishers#upload) or integrating their API with our own workflow.

**Comment by arfon** [comment]
> We are now listed in the DOAJ! https://doaj.org/toc/2475-9066

Excellent. Thanks for working on this @cMadan.

> We still need to get our article metadata imported though, which requires generating a DOAJ XML file (https://doaj.org/publishers#upload) or integrating their API with our own workflow.

Understood.

**Comment by yasirroni** [comment]
It is 2022 and it seems that no article published on [DOAJ](https://doaj.org/toc/2475-9066?source=%7B%22query%22%3A%7B%22bool%22%3A%7B%22must%22%3A%5B%7B%22terms%22%3A%7B%22index.issn.exact%22%3A%5B%222475-9066%22%5D%7D%7D%5D%7D%7D%2C%22size%22%3A100%2C%22sort%22%3A%5B%7B%22created_date%22%3A%7B%22order%22%3A%22desc%22%7D%7D%5D%2C%22_source%22%3A%7B%7D%2C%22track_total_hits%22%3Atrue%7D). Did I miss something?
