### ISSUE TITLE
I'd like to review for JOSS

### ISSUE THREAD

**Issue by hugoledoux** [openjournals/joss#218]
My area of research is geographical information systems (GIS), and I have written several software. Your journal is great idea.

My webpage: https://3d.bk.tudelft.nl/hledoux/pubs/

**Comment by arfon** [comment]
👋 @hugoledoux , thanks for offering to review for JOSS.

So that we can invite you to review on relevant papers, could you please add your details to this file (https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) in the form of a Pull Request?

Many thanks!
