### ISSUE TITLE
Update JOSS papers with ISSN

### ISSUE THREAD

**Issue by arfon** [openjournals/joss#222]
We now have an ISSN for JOSS (https://github.com/openjournals/joss/issues/184) and so at some point we should update the Crossref metadata for JOSS papers published before we had an ISSN: https://github.com/openjournals/joss-papers

**Comment by SimonGreenhill** [comment]
Fixed in PR https://github.com/openjournals/joss-papers/pull/1

**Comment by pboesu** [comment]
I've just created PR https://github.com/openjournals/whedon/pull/8 which adds a corresponding metadata tag to the HTML papers themselves.

**Comment by arfon** [comment]
Thanks @SimonGreenhill and @pboesu - I've been doing a bunch of updates to JOSS content and fixed this finally in https://github.com/openjournals/whedon/pull/12
