### ISSUE TITLE
Format of author surnames and initials in "References" section of the paper PDF

### ISSUE THREAD

**Issue by JNisk** [openjournals/joss#230]
My paper got recently accepted into JOSS, and after compilation of the paper PDF I noticed that the format of the author surnames and initials are not consistent.

* The PDF is here: https://github.com/openjournals/joss-papers/blob/master/joss.00179/10.21105.joss.00179.pdf
What it says in the paper: Niskanen, J., E. Salmela, and H. Lohi
What it should preferably say: Niskanen, J., Salmela, E., and Lohi, H.

* paper.bib is here: https://github.com/JNisk/AncesTrim/blob/master/paper/paper.bib
At the time of the PDF compilation, the bibtex entry in paper.bib said the following:
author = {Niskanen, J., Salmela, E., Lohi, H.},
The paper.bib has since been changed, but that is the exact format that it had.

I am not familiar with bibtex formats but @arfon suggested that the issue might have something to do with this reference being the @ online bibtex style. But in any case, if it is at all possible, I would like the PDF to be fixed. The same issue also exists on the JOSS page for the paper: http://joss.theoj.org/papers/10.21105/joss.00179.

Sincerely,
JNisk

**Comment by kyleniemeyer** [comment]
Without any additional knowledge about the code formatting the PDF, it looks like the first author's initial is being placed after the last name, while for additional authors it is first initial + last name.

This is actually consistent with other papers; for example, see https://github.com/openjournals/joss-papers/blob/master/joss.00194/10.21105.joss.00194.pdf, and follows (I believe) the author-year reference format, among a few others—see https://www.sharelatex.com/learn/Biblatex_bibliography_styles.

So, this paper is at least consistent with others. (That doesn't mean we can't have a conversation about the reference style used by JOSS.)

**Comment by JNisk** [comment]
Okay. Thank you very much for explaining that. I apologize for this rather unnecessary issue. I'm not familiar with that kind of style and it caught me by surprise.

**Comment by kyleniemeyer** [comment]
No problem at all! I admit it isn't typically my preferred style either, which generally is a numbered reference with "First initial last name" for all authors.

**Comment by kyleniemeyer** [comment]
@JNisk if this satisfies your concerns with consistency following the journal style, I'm going to close the issue.

**Comment by JNisk** [comment]
By all means, yes, please do close the issue. This was a welcome reminder that there are also other citation styles than the mainstream ones. I'm sorry for wasting your time but thank you for clearing things up.
