### ISSUE TITLE
Editor emails formatting issues

### ISSUE THREAD

**Issue by arokem** [openjournals/joss#235]
This is what it looks like on my end: 

<img width="1070" alt="screen shot 2017-03-19 at 9 07 18 pm" src="https://cloud.githubusercontent.com/assets/118582/24088482/204bbcf4-0ce8-11e7-85ba-c2d1c0a64d52.png">

**Comment by kyleniemeyer** [comment]
Same.

**Comment by pjotrp** [comment]
I don't dare to show what it looks like in vim.

**Comment by arfon** [comment]
👍 thanks. Fixed in https://github.com/openjournals/joss/commit/75d00bd97866d99e8331579c5b35006d10736389
