### ISSUE TITLE
Weekly update emails missing papers

### ISSUE THREAD

**Issue by cMadan** [openjournals/joss#246]
I've noticed a few times that there have been papers I'm editing that don't show up in the 'weekly update' emails. Currently it's this one (https://github.com/openjournals/joss-reviews/issues/217).

Maybe it's occurs when the reviewer is also an editor and something doesn't get parsed correctly?

**Comment by arfon** [comment]
Thanks for reporting this @cMadan. Definitely sound like a bug. I'll try and dig into this at some point...
