### ISSUE TITLE
I'd like to review for JOSS

### ISSUE THREAD

**Issue by bjmorgan** [openjournals/joss#249]
Areas of interest: Solid State Chemistry / Physics, Materials Science, Python, Fortran.

**Comment by arfon** [comment]
:wave @bjmorgan thanks for offering to review for JOSS.

So that we can invite you to review on relevant papers, could you please add your details to this file (https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) in the form of a Pull Request?

Many thanks!
