### ISSUE TITLE
I'd like to review for JOSS

### ISSUE THREAD

**Issue by djmitche** [openjournals/joss#250]
Hi!  I would like to review!

I have a strong background in Python and a bunch of other languages that aren't R, and general software development.  I don't have any specific science background, but I can usually figure things out.  In general, I'd very much like to support improving the world of science software in any way I can.

Also, I found this link from http://www.arfon.org/announcing-the-journal-of-open-source-software but not at http://joss.theoj.org/about

**Comment by arfon** [comment]
👋 @djmitche - thanks for offering to review for JOSS.

So that we can invite you to review on relevant papers, could you please add your details to this file (https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) in the form of a Pull Request?

Many thanks!
