### ISSUE TITLE
Ping @ropensci/editors instead of @noamross for rOpenSci suggestions

### ISSUE THREAD

**Issue by noamross** [openjournals/joss#252]
Quick protocol update: please ping `@ropensci/editors` rather than myself when suggesting joint rOpenSci-JOSS submissions.  This lets us rotate editor duty.

**Comment by arfon** [comment]
> Quick protocol update: please ping @ropensci/editors rather than myself when suggesting joint rOpenSci-JOSS submissions. This lets us rotate editor duty.

Sure thing.

**Comment by arfon** [comment]
Actually I'm not sure I can ping a team (`@ropensci/editors`) without being in the `@ropensci` organization.

**Comment by karthik** [comment]
In that case I can add you to a JOSS team

**Comment by karthik** [comment]
You can ping `@ropensci/joss` from now on that includes all of us (and Scott + Maelle)

**Comment by arfon** [comment]
> You can ping `@ropensci/joss` from now on that includes all of us (and Scott + Maelle)

@karthik - can you invite me to that team too?

**Comment by karthik** [comment]
I've already invited you

**Comment by arfon** [comment]
> I've already invited you

Hrm. I didn't receive an invite and there's nothing showing up on at http://github.com/ropensci (invites to an organization are usually shown at the top of this page)

![screen shot 2017-05-31 at 2 48 47 pm](https://cloud.githubusercontent.com/assets/4483/26648414/693ad8f8-4610-11e7-8197-f65addc0fa98.png)

**Comment by karthik** [comment]
I see the issue. Fixed now (and I see the pending invite)

**Comment by arfon** [comment]
Perfect. Thanks! I *think* this will work (not sure if cross-org mentions work on GitHub) but happy to try @ropensci/joss

**Comment by arfon** [comment]
In fact. Just playing around with this I don't think this will work, that is, you can't mention an `@rOpenSci` team from a `@openjournals` repository. I think we need to have the rOpenSci folks join a team under this (`@openjournals`) GitHub organization.

**Comment by noamross** [comment]
In that case, can you invite @noamross @karthik @sckott @maelle to the org and we can make an `ropensci` team?

**Comment by arfon** [comment]
Done. I've added you all to @openjournals/ropensci (please visit https://github.com/openjournals if you don't have the invite in your email)
