### ISSUE TITLE
Don't allow a user to submit a paper on the JOSS website if a paper.md file is not in the repository.

### ISSUE THREAD

**Issue by moorepants** [openjournals/joss#254]
I was able to submit a paper without realizing that I was supposed to create a `paper.md` file before the submission. It might be worth having the author guidelines on the submission form instead of the small, easy-to-miss, hyperlink. Even better, maybe this metadata could be entered into the submission form and a pull request is made against the repository with the file.

**Comment by arfon** [comment]
Closing in favour of https://github.com/openjournals/whedon-api/issues/9
