### ISSUE TITLE
Make PDF of paper look more formal by showing citation info

### ISSUE THREAD

**Issue by labarba** [openjournals/joss#256]
The paper PDFs look like pre-prints. I would like the paper to be formatted to have a header that says _The Journal of Open Source Software_ (nice if it has a small logo), and a footer that has a copyright notice and the citation details. 

The footer could be something like: 

(c) The Authors. _J. Open Source Software_, 
Vol. 1(4): 43, doi:10.21105/joss.00043

**Comment by pboesu** [comment]
I started playing with aspects of this a while ago (following this thread  https://github.com/openjournals/joss/issues/157). I did manage to come up with a template that adds citation info (see here: https://github.com/pboesu/whedon/blob/a4e15ce11c1517a8e4f2de03494d01f960f8de05/sandbox/output.pdf and corresponding PR for whedon https://github.com/openjournals/whedon/pull/5) but got stuck when I couldn't get a local or Travis version of whedon running to test the changes and then other things took over my time...

Regarding layout, I had looked at the template used by ReScience (https://github.com/ReScience/ReScience-submission/tree/master/article) but never actually got round to implementing anything for Joss).

I'd be happy to revisit this, if I could get some help on setting up a local instance of whedon to ensure I'm not breaking other aspects of the publication workflow. My fork of whedon with the citation info template is here: https://github.com/pboesu/whedon/tree/citation-license-info

**Comment by labarba** [comment]
Thanks for the contribution, @pboesu !

Looking at the PDF example, I find the content of the box a bit verbose. So I suggest an edited version:

> (c) The Authors. Article under CC | BY and code snippets under MIT license.

And for the final line, I suggest:

> The Journal of Open Source Software (JOSS) is a peer-reviewed open-access journal for articles on research software.

**Comment by kyleniemeyer** [comment]
I admit I do like the ReScience article design... going beyond a very-standard-looking LaTeX article would be nice.

**Comment by labarba** [comment]
Is it possible to add the volume number and article number to the citation info?

I think we agreed that the volume number goes with the year, right?
So 2016 is Vol. 1, 2017 is Vol. 2, etc.?

**Comment by labarba** [comment]
I would _love_ for us to introduce some graphic design into this thing. I could do it if it's a matter of working on a LaTeX file, but I don't know how the LaTeX is produced in JOSS from the markdown source.

**Comment by kyleniemeyer** [comment]
I believe Whedon essentially runs pandoc to convert from Markdown, using the LaTeX template here: https://github.com/openjournals/whedon/blob/master/resources/latex.template

There is a `generate_pdf` method in https://github.com/openjournals/whedon/blob/master/lib/whedon/processor.rb, which is where the actual commands are located.

**Comment by jochym** [comment]
I have a little of print design experience. I can help with layout redesign effort. Right now joss papers look very amateurish, and not very beautiful. Maybe we can "borrow" some aspects of design from ReScience (much better and modern design IMHO)? Anybody knows what is the license for their template?

**Comment by Kevin-Mattheus-Moerman** [comment]
This is great. I can help provide the graphics for the JOSS logo etc. E.g. something like this logo could be incorporated in the header
![joss_logo](https://user-images.githubusercontent.com/8392709/28418833-33e842de-6d2b-11e7-8d53-48c0e0d6cc32.png)
I can work on a vector graphic instead

**Comment by Kevin-Mattheus-Moerman** [comment]
For instance like this: 

![paperlook](https://user-images.githubusercontent.com/8392709/28419206-495d76a6-6d2c-11e7-8d83-918d2d8dd0a4.jpg)

**Comment by Kevin-Mattheus-Moerman** [comment]
I also propose we change the font to a non-standard Latex type. I vote for the Ubuntu font (currently used in the JOSS logo).  We can also use the badges in the paper, and use ORCID/GitHub links 

![paperlook](https://user-images.githubusercontent.com/8392709/28420324-c8f24ccc-6d2f-11e7-8e26-c5aa3cda3bc0.jpg)

**Comment by labarba** [comment]
Thanks, Kevin. I agree that the first step to a page that doesn't look like a preprint is abandoning Computer Modern! 

Let's see here. We can improve the layout with some simple "design for non-designers" rules of thumb: Contrast, Repetition, Alignment, Proximity.

Let me make some suggestions. 

Contrast: use two typefaces, one for title, authors and headings (plus "Paper DOI," etc.), another one for body text. Ubuntu looks great for the title. I suggest Palatino for body text (common wisdom is that reading paragraphs of text is easier with serif typefaces): `/usepackage{palatino}`

Repetition: well, use the _same_ type in all non-body-text content: Ubuntu for title, headings, authors, header and footer.

Alignment: I suggest a wide left margin, and placing the metadata (DOI, etc.) there (similar to the ReScience template). Since the papers are short, it's alright to have a narrower text width. Align-left the Title, author list and all headings. Centered titles seldom look elegant.

Proximity: place author list closer to title than body (leave plenty of whitespace around title + authors)

Leave _plenty_ of whitespace around the logo, and ideally use the version of the logo that has the full name in bigger font, to the right of the graphic.

I do not think that the badges look good on a PDF layout. Too cluttered.

**Comment by arfon** [comment]
Please take a look at the new template over in https://github.com/openjournals/whedon/pull/12 and let me know what you think!
