### ISSUE TITLE
remind reviewers to log in to github

### ISSUE THREAD

**Issue by danielskatz** [openjournals/joss#257]
In the initial issue that starts a review, if the reviewer clicks on the notification that they were emailed without being logged in to GitHub, the review may not show enough to make complete sense.

We could add something to say that they should be sure that they log in to fully view the review and instructions.

**Comment by arfon** [comment]
> In the initial issue that starts a review, if the reviewer clicks on the notification that they were emailed without being logged in to GitHub, the review may not show enough to make complete sense.

What don't you think they're seeing? The reviews are public so the only real different (I think) would be that the check list wouldn't be clickable. Am I missing something?

**Comment by danielskatz** [comment]
This was based on a comment from @kc9qey.  Galen, what was unclear to you when you were not logged in?

**Comment by kc9qey** [comment]
When not logged in, none of the buttons in the Reviewer Questions checklist
appear.  It looked like there was nothing to do.
