### ISSUE TITLE
GitHub logo next to projects hosted on BitBucket and in other places

### ISSUE THREAD

**Issue by wojdyr** [openjournals/joss#263]
Having a GitHub logo next to every entry in http://joss.theoj.org/papers doesn't feel right.

![screenshot_2017-07-05_01-11-59](https://user-images.githubusercontent.com/491873/27845024-1c1e7a98-6122-11e7-88a7-07296d7b2467.png)

**Comment by kyleniemeyer** [comment]
This is a fair point—not all entries are hosted on GitHub.

It looks like this icon is set in `joss/app/views/papers/_list.html.erb`. @arfon I'm not sure what else is easily supported, perhaps it could be changed to something more general like `octicon-file-code` or `octicon-repo`?

**Comment by kyleniemeyer** [comment]
(Choosing a more general icon to apply to all entries seems simpler than trying to change it based on where the project is hosted...)

**Comment by arfon** [comment]
👍 thanks for pointing this out @wojdyr - we'll try and get this fixed up soon.
