### ISSUE TITLE
We should define COIs between reviewers and authors in the about page

### ISSUE THREAD

**Issue by danielskatz** [openjournals/joss#264]
We should define COIs between reviewers and authors in the about page

**Comment by arfon** [comment]
Do you mean we should write down what constitutes a conflict of interest as far as JOSS is concerned?

**Comment by labarba** [comment]
I added a CoI explainer to the SciPy 2017 Guide for Reviewers and Chairs:
https://scipy2017.scipy.org/ehome/220975/532468/
... might be useful.

**Comment by danielskatz** [comment]
@arfon - correct.  If a reviewer says "I have a possible COI with this paper," we don't have a set of guidelines to say, "yes, that's the COI and you shouldn't review it," or, "no, that's not a problem, go ahead."

**Comment by kyleniemeyer** [comment]
OK, @labarba if you are ok with me mostly stealing the language you linked to above, I can add a section describing COIs to the reviewer guidelines and then modify the COI checkbox text with a link.

**Comment by kyleniemeyer** [comment]
How does this sound as a draft COI description:

>The definition of a Conflict of Interest in peer review is a circumstance that makes you "unable to make an impartial scientific judgment or evaluation." (PNAS Conflict of Interest Policy).
>
> As a reviewer, your present or previous association with any authors of a submission poses a textbook COI: recent collaborators in research funding or publications (in the past four years), family members, business partners, and thesis student/advisor or mentor. Other associations could be more tenuous: being employed by the same institution, for example. In this case, your obligation as reviewer is to disclose the potential COI to the area chair or Program Chair, and state whether you think you are able to make an impartial assessment of the work. If you have a conflict of interest with a submission, you should decline to review it and disclose the specific reason to the submissions's editor.
> 
> Declaring a potential of conflict of interest is required under professional ethics. If in doubt: ask the editors.
> 
> (Adopted from the [SciPy 2017 COI guidelines](https://scipy2017.scipy.org/ehome/220975/532468/))

**Comment by labarba** [comment]
The COI explainer should go in the Reviewer Guide.

**Comment by kyleniemeyer** [comment]
Yes, I was planning on putting it first in the "Other considerations" section, and linking to it directly from the review checklist.

**Comment by labarba** [comment]
In my opinion, it deserves its own "Conflicts of Interests" heading.

**Comment by kyleniemeyer** [comment]
I intended on having a "Conflicts of Interest" subheading underneath "Other considerations", but can easily make it a standalone heading too.

**Comment by danielskatz** [comment]
I agree it should have its own heading.

**Comment by danielskatz** [comment]
However, I also think we should use something a little different than what was originally proposed, because I have a couple of concerns about what was proposed:

>The definition of a Conflict of Interest in peer review is a circumstance that makes you "unable to make an impartial scientific judgment or evaluation." (PNAS Conflict of Interest Policy).
>
>As a reviewer, your present or previous association with any authors of a submission poses a textbook COI: recent collaborators in research funding or publications (in the past four years), family members, business partners, and thesis student/advisor or mentor. Other associations could be more tenuous: being employed by the same institution, for example. In this case, your obligation as reviewer is to disclose the potential COI to the editor, and state whether you think you are able to make an impartial assessment of the work. If you have a conflict of interest with a submission, you should decline to review it and disclose the specific reason to the submissions's editor.
>
>Declaring a potential of conflict of interest is required under professional ethics. If in doubt: ask the editors.

Specifically, I think we should say that we are concerned both about actual COIs and the appearance of COIs, and want to avoid actual COIs and be transparent to avoid the appearance of COIs.  I also would like to make the thesis student/advisor or mentor be a lifetime conflict, or if this was intended, to make it more clear.  And I don't think being employed by the same institution should be considered tenuous.  I would prefer that we say that being employed by the same organization is a potential conflict, and if they reviewer thinks it is not, we could waive it (but by default, it is.)

So, I would propose the following:

The definition of a Conflict of Interest in peer review is a circumstance that makes you "unable to make an impartial scientific judgment or evaluation." (PNAS Conflict of Interest Policy). JOSS is concerned with avoiding any actual conflicts of interest, and being sufficiently transparent that we avoid the appearance of conflicts of interest as well, even when they are only perceived (but not actual).

As a reviewer, your present or previous association with any authors of a submission is a COI: recent (past four years) collaborators in funded research or work that is published, and a lifetime for the family members, business partners, and thesis student/advisor or mentor. In addition, your recent (past year) association with the same organization of a submission is a COI by default, for example, being employed at the same institution.

If you have a conflict of interest with a submission, you should decline to review it and disclose the specific reason to the submissions's editor.  Some conflicts may be recorded and then waived, and if you think you are able to make an impartial assessment of the work, you should request that the conflict be waived. For example, if you and a submitted were two of 2000 authors of a high energy physics paper but did not actually collaborate.  Or if you and a submitter worked together 6 years ago, but due to delays in the publishing industry, a paper from that collaboration with both of you as authors was published 2 year ago. Or if you and a submitter are both employed by the same very large organization but in different units without any knowledge of each other.

Declaring actual, perceived, and potential conflicts of interest is required under professional ethics. If in doubt: ask the editors.

**Comment by kyleniemeyer** [comment]
@labarba are you ok with @danielskatz's slightly modified language?

**Comment by labarba** [comment]
> JOSS is concerned with avoiding any actual conflicts of interest, and being sufficiently transparent…

JOSS wants to avoid any actual conflicts of interest, and be sufficiently transparent…

>  as well, even when they are only perceived (but not actual).

Delete: redundant; verbose.

> recent (past four years) collaborators in funded research or work that is published, and a lifetime for the family members

Lacks parallel construction: "recent collaborators" and "a lifetime for the family" ... awkward.
Delete "and a lifetime for the" since it really is not needed. COIs exist with these kinds of people: recent collaborators, family members, etc. (no time limits specified for the latter).

> For example, if you and a submitted were two of 2000 authors

Huh? I guess the intended wording is "a submission where"?

> high energy physics paper

high-energy physics (although we have two compounded adjectives here, so really should be high-energy-physics, but seems a bit awkward)

Also, this is a sentence fragment: "For example, if … but did not collaborate" ... then what?
And, you're an author bud did not collaborate? Then you shouldn't be an author! Not an example I would like to highlight …

I would remove the examples altogether, TBH. I think folks will get the idea from the previous explanation, and will ask for a waiver when they feel it applies.

**Comment by danielskatz** [comment]
>> For example, if you and a submitted were two of 2000 authors

> Huh? I guess the intended wording is "a submission where"?

Sorry, this should have been "a submitter were"


> Also, this is a sentence fragment: "For example, if … but did not collaborate" ... then what?
And, you're an author bud did not collaborate? Then you shouldn't be an author! Not an example I would like to highlight …

There are plenty of times that a pair of authors on the same paper did not collaborate with each other, but still contributed to a paper.  A simple example is when I worked with an investigator to explore the performance of her code on one system, and another author worked to investigate performance on a second system.  Both of us and the lead investigator were co-authors on a paper, but the two of us didn't ever collaborate with each other.  HEP papers with 2000 authors create another example.

> Lacks parallel construction: "recent collaborators" and "a lifetime for the family" ... awkward.
Delete "and a lifetime for the" since it really is not needed. COIs exist with these kinds of people: recent collaborators, family members, etc. (no time limits specified for the latter).

The commas make this unclear otherwise - it could be read as "recent" applying all the text that follows, and while family is clearly no subject to recent, advisor/mentor could be.

Ok, here's an updated version.  @labarba, if you are not happy with this, please suggest an alternative - hopefully we can converge.  If not, we can ask others for their opinions as well.

The definition of a conflict of Interest in peer review is a circumstance that makes you "unable to make an impartial scientific judgment or evaluation." (PNAS Conflict of Interest Policy). JOSS is concerned with avoiding any actual conflicts of interest, and being sufficiently transparent that we avoid the appearance of conflicts of interest as well.

As a reviewer, COIs are your present or previous association with any authors of a submission: recent (past four years) collaborators in funded research or work that is published; and lifetime for the family members, business partners, and thesis student/advisor or mentor. In addition, your recent (past year) association with the same organization of a submitter is a COI, for example, being employed at the same institution.

If you have a conflict of interest with a submission, you should disclose the specific reason to the submissions's editor. This may lead to you not being able to review the submission, but some conflicts may be recorded and then waived, and if you think you are able to make an impartial assessment of the work, you should request that the conflict be waived. For example, if you and a submitter were two of 2000 authors of a high energy physics paper but did not actually collaborate. Or if you and a submitter worked together 6 years ago, but due to delays in the publishing industry, a paper from that collaboration with both of you as authors was published 2 year ago. Or if you and a submitter are both employed by the same very large organization but in different units without any knowledge of each other.

Declaring actual, perceived, and potential conflicts of interest is required under professional ethics. If in doubt: ask the editors.

**Comment by danielskatz** [comment]
**Latest version:**

The definition of a conflict of Interest in peer review is a circumstance that makes you "unable to make an impartial scientific judgment or evaluation." (PNAS Conflict of Interest Policy). JOSS is concerned with avoiding any actual conflicts of interest, and being sufficiently transparent that we avoid the appearance of conflicts of interest as well.

As a reviewer, COIs are your present or previous association with any authors of a submission: recent (past four years) collaborators in funded research or work that is published; and lifetime for the family members, business partners, and thesis student/advisor or mentor. In addition, your recent (past year) association with the same organization of a submitter is a COI, for example, being employed at the same institution.

If you have a conflict of interest with a submission, you should disclose the specific reason to the submissions's editor. This may lead to you not being able to review the submission, but some conflicts may be recorded and then waived, and if you think you are able to make an impartial assessment of the work, you should request that the conflict be waived. For example, if you and a submitter were two of 2000 authors of a high energy physics paper but did not actually collaborate. Or if you and a submitter worked together 6 years ago, but due to delays in the publishing industry, a paper from that collaboration with both of you as authors was published 2 year ago. Or if you and a submitter are both employed by the same very large organization but in different units without any knowledge of each other.

Declaring actual, perceived, and potential conflicts of interest is required under professional ethics. If in doubt: ask the editors.

**Comment by tracykteal** [comment]
Agreement from JOSS editors to use the above version and put in repo as COI.md

**Comment by arfon** [comment]
PR opened here: https://github.com/openjournals/joss/pull/331
