### ISSUE TITLE
We need a simpler and obvious way to add new reviewers

### ISSUE THREAD

**Issue by kyleniemeyer** [openjournals/joss#265]
Right now, potential reviewers can volunteer only by finding the reviewer list at https://github.com/openjournals/joss/blob/master/docs/reviewers.csv and adding themselves—but, this file is not obvious to find, and not linked to from the About page.

Here are some things we can/should do:

1. Put an obvious link on the About page for potential reviewers to add themselves. At minimum this should link to the `reviewers.csv` file with instructions on how to add themselves. At best, this should link to a page where they can enter their info in a more user-friendly manner, which gets added to the list (by `whedon` or something).

2. Many of the folks who actually review submissions are not on this list. I think that editors should be responsible for adding any new reviewers that helped on a submission to that list, both for future reviewing purposes and for recognition.

3. We should also consider adding authors of submissions to our reviewer list. I think this is fair, and I imagine fairly standard practice at other journals.

**Comment by stsievert** [comment]
I'd recommend adding a link to the reviewer guidelines to help clarify reviewer expectations. This is something I asked @kyleniemeyer after expressing interest in reviewing at SciPy.

**Comment by kyleniemeyer** [comment]
@stsievert Those are actually fairly visible, given in the about page http://joss.theoj.org/about#reviewer_guidelines and linked to in actual review issues themselves

**Comment by karthik** [comment]
Great idea, Kyle.
At rOpenSci we have a this form: https://ropensci.org/onboarding/

The data goes into airtable (a hybrid between a spreadsheet and a database)
that the editors regularly query to find new reviewers. We also update the
tables after each submission so that we know not to ping someone too many
times in the same year.

We could implement something analogous (maybe even write back to that csv).
Perhaps a updated Whedon could respond with query results (`@whedon suggest
reviewers <topics>`)

- Karthik

**Comment by kyleniemeyer** [comment]
This form looks awesome—any way we (you?) can incorporate that onto the JOSS website?
 
I'd be fine with moving away from that flat CSV file, as long as there's a good way to view/query whatever we do end up using.

**Comment by kyleniemeyer** [comment]
@karthik what would it take to get a similar onboarding form linked from the JOSS website? 

The whedon addition also sounds great, although that seems lower-priority than fixing our clunky reviewer addition process.

**Comment by karthik** [comment]
@kyleniemeyer I'm happy to do it! 
What do you prefer as the storage backend?
Googlesheets or an airtable?

If a Googlesheet, maybe a cron job can semi-regularly update the copy here on GitHub?

@arfon thoughts?

**Comment by kyleniemeyer** [comment]
airtable sounds cool!

**Comment by karthik** [comment]
Ah, I did Googlesheets for now. Happy to switch it over to airtable. I have a PR (https://github.com/openjournals/joss/pull/290) and if that get's merged, I can seamlessly switch the backend (or have it go both places).

**Comment by kyleniemeyer** [comment]
I'll let @arfon take a look at this first, but looks good to me. We'll need to add a prominent link on the About page.

I assume that it *should* be possible to have the Rails app regularly update the .csv file here?

**Comment by karthik** [comment]
ok. Once the PR is merged, anyone will be able to sign up at `joss.theoj.org/reviewer-signup.html`
The entry gets added to the Googlesheet I shared with you, and also an airtable (which I have invited you and @arfon to for now). I'm sure a Rails app can regularly sync that csv back to this repo.

**Comment by kyleniemeyer** [comment]
Excellent! Think we could borrow/steal the same setup for JOSE?

**Comment by karthik** [comment]
@kyleniemeyer Sure, once Arfon approves this, I'll duplicate the form and change the output files for you!

**Comment by Fil** [comment]
Adding oneself to a list is very intimidating — the current process will select for uninhibited reviewers. Onboarding with a friendly discussion somewhere might be easier.

By which I volunteer to review articles in the fields of geography, cartography, data visualization and algorithms visualizations :)  Javascript mainly, python OK. Cheers!

**Comment by danielskatz** [comment]
but in the meantime, @Fil , until we get things going, you might to brave a pull request to https://github.com/openjournals/joss/blob/master/docs/reviewers.csv to add yourself

Assuming you are sufficiently uninhibited :)

**Comment by arfon** [comment]
#290 is now merged.

@kyleniemeyer - I'm not sure if you want to add the extra folks you suggested at the top of the thread (reviewers and authors not in the list)?
