### ISSUE TITLE
I'd like to review for JOSS

### ISSUE THREAD

**Issue by deniederhut** [openjournals/joss#267]
I'm interested in serving as a software reviewer for JOSS. Thanks!

**Comment by kyleniemeyer** [comment]
Hi @deniederhut, can you add yourself to the list at https://github.com/openjournals/joss/blob/master/docs/reviewers.csv via a PR?

**Comment by deniederhut** [comment]
Done!

**Comment by kyleniemeyer** [comment]
Could you expand "nlp"? I don't actually know what that stands for... neuro-linguistic programming?

**Comment by deniederhut** [comment]
Sorry! Natural language processing - us scientists and our jargon...

**Comment by kyleniemeyer** [comment]
ah, ok—could you expand that out, and then I'll merge?

**Comment by deniederhut** [comment]
Of course! Give me five, I'm afk.
