### ISSUE TITLE
Archiving the reviews

### ISSUE THREAD

**Issue by katyhuff** [openjournals/joss#269]
Hi team! After @kyleniemeyer's great talk at SciPy, @vickysteeves, from her perspective as a librarian, suggested we should consider archiving JOSS review content (just in case). 

This could easily be scripted using the GitHub API (https://developer.github.com/v3/issues/) and pulled once in a while (nightly cron job?) into a plain text format (default is markdown) to be archived somewhere.

- Perhaps we should set up a script at some point that does this. I have some scripts for pulling issue info down in approximately this way and @labarba mentioned that @gforsyth also has some such scripts. 
- Perhaps first, though, we should consider where to put such an archive.

**Comment by gforsyth** [comment]
To avoid a single-machine-point-of-failure, we could consider using Travis or similar to perform the archival task whenever a PR / paper is merged? Or some other hook.

**Comment by arfon** [comment]
> This could easily be scripted using the GitHub API (https://developer.github.com/v3/issues/) and pulled once in a while (nightly cron job?) into a plain text format (default is markdown) to be archived somewhere.

👍 Definitely agree we should do this.

> Perhaps first, though, we should consider where to put such an archive.

Given that Zenodo has versioned DOIs now what about just tarring them all up and pushing them all to Zenodo in any automated task we write?

Alternatively we could look at uploading them individually somewhere (perhaps Zenodo too)?

**Comment by kyleniemeyer** [comment]
We could conceivably upload review content + article source/PDF with each publication, and possibly even link to that in the article landing page (I assume).

I'd also be fine with regular uploads of all content together as a backup—maybe not every automated task, but some regular interval (monthly? nightly?).

**Comment by HaoZeke** [comment]
This is probably not feasible with the current workflow, since reviewers mostly open issues or pull requests in target repositories and it would be unfeasible to scrape them for meaningful text.

Meaningful as in things which have any real post publication benefit. From an archival point of view, the corresponding issue is the best indicator of the review itself.

**Comment by arfon** [comment]
In https://github.com/openjournals/joss/blob/master/lib/tasks/portico.rake we now archive with Portico:

- The JOSS paper (in PDF form)
- The Crossref XML
- The JOSS review issue (in JSON format)

Here's an example deposit: [10.21105.joss.01700.zip](https://github.com/openjournals/joss/files/3665711/10.21105.joss.01700.zip)

**Comment by arfon** [comment]
> I'd also be fine with regular uploads of all content together as a backup—maybe not every automated task, but some regular interval (monthly? nightly?).

Also, I should note that these are only archived once a paper is accepted and published, and the archiving happens nightly.
