### ISSUE TITLE
Suggest re-wording "Business Model" heading

### ISSUE THREAD

**Issue by labarba** [openjournals/joss#279]
"Business Model" generally refers to how you plan to make money out of the operation, so it doesn't quite apply to the information we provide there. Suggest changing the heading to *"Cost and Sustainability Model"* (and in fact adding a few words about sustainability).

**Comment by kyleniemeyer** [comment]
Yes! Also, based on feedback given after the SciPy talk, we may want to mention a few other things, like the volunteer (but worth $$$) dev time @arfon put into building the site, along with the fact that we don't pay for things like marketing like many publishers.

These changes should probably also be reflected in the article.

**Comment by labarba** [comment]
We could add:
_"Currently, JOSS has no plans to add author processing charges (APC). Under the NumFOCUS nonprofit umbrella, JOSS is now eligible to seek grants for sustaining its future. With an entirely volunteer team, JOSS is seeking to sustain its operations via donations and grants, keeping its low cost of operation and free service for authors."_

I'd be pleased to do some editing of the website text myself, but it appears right now the mode is directly editing the raw HTML? If so, this deters me.
