### ISSUE TITLE
Following RuboCop guidelines

### ISSUE THREAD

**Issue by arcticbarra** [openjournals/joss#280]
Hi there! I was checking out the code and noticed that there are several [rubocop](https://github.com/bbatsov/rubocop) violations (using old ruby hashes, not using guard clauses, using double quoted strings, etc). Would you like me to create a PR correcting those violations?

You can see current violations by installing the rubocop gem as `gem install rubocop` and then just running `rubocop` on the project folder.

**Comment by kyleniemeyer** [comment]
PR away! We always welcome contributions that make JOSS better.

**Comment by arcticbarra** [comment]
Done! 👍
