### ISSUE TITLE
I'd like to review for JOSS

### ISSUE THREAD

**Issue by jochym** [openjournals/joss#285]
I am a physicist working in computational material science field. I am an author and contributor to several OS software projects (e.g. Elastic, PhonoPy, ASE, libINDI). I work as a research scientist in the Institute of Nuclear Physics, Polish Academy of Sciences, Cracow, Poland.

**Comment by kyleniemeyer** [comment]
Hi @jochym, could you add yourself to the reviewer spreadsheet via a PR? https://github.com/openjournals/joss/blob/master/docs/reviewers.csv

**Comment by jochym** [comment]
Done. PR created

**Comment by kyleniemeyer** [comment]
🎉 welcome aboard!
