### ISSUE TITLE
instructions for reviewer volunteers

### ISSUE THREAD

**Issue by danielskatz** [openjournals/joss#289]
We should add information on the JOSS web site and here about how reviewers should volunteer:

"add themself to the reviewer spreadsheet via a PR
https://github.com/openjournals/joss/blob/master/docs/reviewers.csv"

**Comment by danielskatz** [comment]
or, if this is already there somewhere, it's not obvious to me, and maybe it should be highlighted/emphasized

**Comment by labarba** [comment]
TBH, I find this way of adding reviewers super clunky. They have to fork and clone the whole JOSS repo, to add a few words into a CSV file and then open a pull request? Undue hardship!

Can we have a web form that folks fill easily?

**Comment by kyleniemeyer** [comment]
This issue is essentially a duplicate of #265, where we were already talking about some ways to improve. Can we keep the conversation over there?

**Comment by danielskatz** [comment]
sure.
