### ISSUE TITLE
Website: bullet list in submission "Description" breaks alignment

### ISSUE THREAD

**Issue by labarba** [openjournals/joss#292]
![screen shot 2017-07-20 at 10 06 52 am](https://user-images.githubusercontent.com/4800109/28421504-61dac416-6d33-11e7-9908-2bba74a0001e.png)

As you can see, when the submitter includes a bullet list in their "Description," it breaks the left-alignment of the content on the journal's web page. 

This is a small thing, but it looks off.

**Comment by arfon** [comment]
Yeah, this is CSS bug I think. Labeled as such and added to the backlog. Thanks for spotting this @labarba

**Comment by arfon** [comment]
Closing this as the new site isn't affected by this bug.
