### ISSUE TITLE
Including authors not contributing to the code repository?

### ISSUE THREAD

**Issue by keiranmraine** [openjournals/joss#295]
Hi,

My understanding is that the author list is based on commits (via the generation code listed in the docs).

Is it acceptable to edit the generated file to include the principal investigators etc of a research group?

**Comment by labarba** [comment]
Of course. You must discuss authorship with your collaborators, and manually edit the metadata accordingly.

**Comment by kyleniemeyer** [comment]
Also, authorship is *not* based on anything automatically generated, but just the paper that the authors write (i.e., paper.md).

**Comment by keiranmraine** [comment]
Oh, so is the index not built from the json file generated by the script in the docs:

https://gist.github.com/arfon/478b2ed49e11f984d6fb

**Comment by danielskatz** [comment]
note that this is under "Experimental stuff".

It's up to the submitter to decide who the authors (really, contributors) are.

This is a tool that might help, but is not the last statement...

**Comment by kyleniemeyer** [comment]
Right—as given in the [author guidelines](http://joss.theoj.org/about#author_guidelines), we do encourage the creation of a metadata file that helps with auto generation of certain things, but that is still created by the submitters and can include whoever they want as authors, just like the paper.

**Comment by keiranmraine** [comment]
So if I generate the metadata I should ensure that it matches the `paper.md` if I add additional authors.  That's fine, just wanted to ensure that there wasn't a different purpose, e.g. easily tag who did the coding vs who provided "other" input.

**Comment by kyleniemeyer** [comment]
Yes, if you create the file, the author list should match. And no, we currently don't track how different authors contributed. 

As @labarba said, it's up to the authors/submitters to decide who made author-worthy contributions, but personally I think this can include actual code contributors, people who provide overall project guidance or funding (i.e., faculty advisors), or someone who provides other directional guidance—just like the author list on a typical journal article.
