### ISSUE TITLE
The title of a paper page should contain the title + authors

### ISSUE THREAD

**Issue by Fil** [openjournals/joss#296]
Right now it reads `<title>Journal of Open Source Software</title>`.

Could be  `<title>Software: A great tool to open knowledge, by Author McAuthorFace - Journal of Open Source Software</title>`.

I suppose it's https://github.com/openjournals/joss/blob/68f42584a67727c4c5ec4e53ae6c921e49b9886c/app/views/layouts/application.html.erb#L4

**Comment by arfon** [comment]
This was fixed in #363
