### ISSUE TITLE
Commented out link leaves the text truncated

### ISSUE THREAD

**Issue by mccalluc** [openjournals/joss#303]
With the link commented out, the text that gets rendered is truncated. Not sure if there's a problem with the link, or if it's just a typo.

http://joss.theoj.org/about -> https://github.com/openjournals/joss/blob/62e906e2221a936eb2afffba45e14084da42f3a5/app/views/home/about.html.erb#L150

> ... the review is carried out in the <%# link_to "JOSS reviews repository" ...

**Comment by arfon** [comment]
Good catch! Fixed in 3448ca3e3ab2637966839b3b117d6ba20b891a66
