### ISSUE TITLE
Problem signing in

### ISSUE THREAD

**Issue by weymouth** [openjournals/joss#304]
When I try to log in with my Orcid, I get the following message:

We're sorry, but something went wrong.
If you are the application owner check the logs for more information.

I've tried multiple browsers and attempts to no avail.

**Comment by Kevin-Mattheus-Moerman** [comment]
Sorry for the inconvenience. @arfon can you help?

**Comment by arfon** [comment]
Hey @weymouth - I saw this error coming through but wasn't sure the origin of it. Thanks for reporting here.

Could you tell me if you have your name (first and last name) on your ORCID profile? It looks like it's failing to parse the ORCID data when logging in and I'm wondering if it has something to do with the name information?

**Comment by weymouth** [comment]
Thanks @arfon, 

Name:Gabriel Weymouth, ID:0000-0001-5080-5016

**Comment by arfon** [comment]
Thanks @weymouth - can you confirm that your name is listed on your ORCID profile? I don't see it here: http://orcid.org/0000-0001-5080-5016

**Comment by weymouth** [comment]
I guess that is a separate privacy setting. I've turned it on now. I've set it to Gabriel D Weymouth

**Comment by arfon** [comment]
OK thanks. Can you try logging in again now on the JOSS site?

**Comment by weymouth** [comment]
It worked! Was it the privacy setting?

**Comment by arfon** [comment]
> It worked! Was it the privacy setting?

Yes I think it must have been. We try and parse the ORCID user's full name when logging them in. I'll see what I can do to make that code more robust.
