### ISSUE TITLE
Error handling for out-of-order workflow operations

### ISSUE THREAD

**Issue by arokem** [openjournals/joss#306]
For example, a more informative error in cases where an editor forgets to assign the reviewer before  starting the review, see https://github.com/openjournals/joss-reviews/issues/327

**Comment by labarba** [comment]
Same thing happened to me here:
https://github.com/openjournals/joss-reviews/issues/321#issuecomment-318050465

**Comment by labarba** [comment]
And @arfon opened a bug report here:
https://github.com/openjournals/whedon-api/issues/6

**Comment by arfon** [comment]
Thanks for reporting this. Closing as a dup of https://github.com/openjournals/whedon-api/issues/6
