### ISSUE TITLE
Have the PDF be generated at start of review

### ISSUE THREAD

**Issue by eteq** [openjournals/joss#311]
If I understand right, the PDF of the JOSS paper gets generated *after* the review is complete.  Is there any reason it couldn't get generated at the start? Perhaps by @whedon and included in the reviewer checklist?  That would make the review process (slightly) easier.

**Comment by arfon** [comment]
@eteq - we used to do this but we stopped as it's a semi-manual process on my part. It's high on my todo list of things to add to `@whedon`'s capabilities so he can automatically compile as soon as there's a submission.

**Comment by cMadan** [comment]
As a slight addition to this, it would be great if editors can request the PDF be re-compiled (i.e., with a `@whedon` command) after the paper.md has been revised as part of the review process

**Comment by arfon** [comment]
Related to https://github.com/openjournals/joss/issues/105

**Comment by arfon** [comment]
Fixed in https://github.com/openjournals/whedon-api/commit/a15bf22b3f27b0150d05792076c545fd39a4da76
