### ISSUE TITLE
Encourage citations by offering authors code snippet to add citation badge to top of their readme 

### ISSUE THREAD

**Issue by Kevin-Mattheus-Moerman** [openjournals/joss#314]
Once a submission is accepted perhaps we could automatically offer a code snippet, e.g. something like this: 
`[![Citing](http://joss.theoj.org/papers/10.21105/joss.00359/status.svg)](http://joss.theoj.org/papers/10.21105/joss.00359)`
Which generates: [![Citing](http://joss.theoj.org/papers/10.21105/joss.00359/status.svg)](http://joss.theoj.org/papers/10.21105/joss.00359)
This way authors can add this to the top of their README for instance to highlight how to cite the work. 
(it seems the badge does not render in this issue comment for some reason, anyway, I mean the green badge as seen here: http://joss.theoj.org/papers/9ebcd154fd6df78155d1655ff677b823).

**Comment by Kevin-Mattheus-Moerman** [comment]
Interestingly I recently added a gitter channel for one of my projects. Gitter has automated the process of adding a badge to the top of a readme and offered to do so via a pull request. So that was handy.

**Comment by arfon** [comment]
> Interestingly I recently added a gitter channel for one of my projects. Gitter has automated the process of adding a badge to the top of a readme and offered to do so via a pull request. So that was handy.

That's a good idea. Perhaps Whedon could suggest this in the review thread when the review is closed?
