### ISSUE TITLE
Add browse/search options for papers

### ISSUE THREAD

**Issue by nicoguaro** [openjournals/joss#315]
I think that it would be useful to have the option to search in the Journal

**Comment by arfon** [comment]
WIP solution to this in https://github.com/openjournals/joss/pull/369

**Comment by Miserlou** [comment]
+1 for search.

**Comment by cdeil** [comment]
Would be really nice to have a way to see all the papers.
Even a single HTML page would to, then I could use the page search functionality in my browser to find some author or keyword.

**Comment by pllim** [comment]
I was just looking for this exact feature.

Fun fact: Searching on Google landed me at https://en.wikipedia.org/wiki/Joss_paper .

**Comment by Fil** [comment]
vote up

**Comment by banesullivan** [comment]
Is there a status update on this? Or even a workaround solution if I'd like to search for papers on different topics?

**Comment by jordibc** [comment]
A workaround: https://www.google.com/search?q=site%3Ajoss.theoj.org+YOURSEARCH

It would be so much better with a native searching functionality. Looking forward to having it!

**Comment by banesullivan** [comment]
Thanks @jordibc!!

**Comment by karllark** [comment]
would be great to have this search capability.  Adding my voice to this request.
