### ISSUE TITLE
From initial submission to pre-review issue

### ISSUE THREAD

**Issue by cMadan** [openjournals/joss#316]
I was just wondering, what's the process between a project being submitted to the pre-review issue being generated? I noticed this takes a few days and was just wondering why... E.g., is there a step here that @arfon is currently doing manually?

**Comment by arfon** [comment]
> E.g., is there a step here that @arfon is currently doing manually

Yes, I manually check these before allowing them through. We get a very small amount of spam so I have a manual check. We could probably remove this though.
