### ISSUE TITLE
Suggestions for improving reviewer instructions

### ISSUE THREAD

**Issue by jmjwozniak** [openjournals/joss#320]
I suggest adding a few points under the Reviewer questions header in the main review issue that may help new reviewers like myself:

- Where to look for paper.md
- A note about the primary concrete actions that the reviewer will take, which I assume are: read paper.md , run the software, complete the checkboxes or create issues that indicate what blocks them.  Reviewers may start by looking for a place to score the submission and write a critical review
- In the reviewer is expected to have read the Author Guidelines (I assume not), there should be a pointer to that

**Comment by arfon** [comment]
👍 this is good feedback. Thanks @jmjwozniak

**Comment by arfon** [comment]
Closing this as stale. We've made a ton of progress on JOSS documentation since this issue was opened (e.g. https://joss.readthedocs.io/en/latest/reviewer_guidelines.html). If there are still outstanding issues with what we have then we should open new issues to track this.
