### ISSUE TITLE
Update DOI URLs

### ISSUE THREAD

**Issue by arfon** [openjournals/joss#322]
We currently use the old URL scheme for our DOI links (e.g. `http://dx.doi.org`) whereas we should be just using `https://doi.org` https://www.doi.org/doi_handbook/3_Resolution.html

**Comment by kyleniemeyer** [comment]
This had been bugging me... thanks for making the issue.

**Comment by arfon** [comment]
Between #324 and https://github.com/openjournals/whedon-api/commit/5ad482f659b1b2643c25c0f5a576eb72006262af this should now be fixed.
