### ISSUE TITLE
whedon + github assignments

### ISSUE THREAD

**Issue by lheagy** [openjournals/joss#323]
Would it be possible to have whedon also set the editor (and potentially reviewer?) as an assignee on github when they are set in the issue? It is helpful to be able to sort issues by assignee to find the ones that I am currently working on

![image](https://user-images.githubusercontent.com/6361812/29885077-47377aa8-8d6a-11e7-9c7b-ab5215b94118.png)

**Comment by arfon** [comment]
👍 thats a good idea.

**Comment by arfon** [comment]
@lheagy - it turns out I can't assign multiple people easily when creating the review issue but for now I've just assigned the editor.

**Comment by lheagy** [comment]
Thanks @arfon!
