### ISSUE TITLE
JOSS pre-submission enquiry

### ISSUE THREAD

**Issue by andreas-h** [openjournals/joss#332]
https://gitlab.com/andreas-h/pyatran

pyatran is a set of Python modules to make working with the [SCIATRAN](http://www.iup.uni-bremen.de/sciatran/) radiative transfer model easier. pyatran's main purposes are

* automatically generate SCIATRAN runtime directories from JSON configuration files
* allow configuration of SCIATRAN via Python code
* read SCIATRAN output into xarray data structures

I am aware that [the documentation](https://pyatran.readthedocs.io/) is not complete yet and it would be polished significantly before submission.

So, pyatran does not really *do* scientific calculation, but it *facilitates* working with the SCIATRAN RTM significantly.

Is pyatran eligible for submission to JOSS or not?

**Comment by labarba** [comment]
From a quick browse of your repo, I can see that this a non-trivial effort (maybe a couple of thousands l.o.c.? ) and looks tidy and well written. But its application sounds like a utility to make it easier to use another library (the research software). What would help here is an explanation of how this software has been used in a research project, or has enabled a research project or publication.

**Comment by andreas-h** [comment]
Thanks, @labarba !  So I'll take this as a "heads-up"; I'll make sure to include a user story and references to publications which have used this code before.
