### ISSUE TITLE
JOSS pre-submission enquiry

### ISSUE THREAD

**Issue by fmichel** [openjournals/joss#334]
**Project repository URL:** https://github.com/fmichel/MaDKit

Hello everyone,

[MaDKit](http://www.madkit.net/madkit/), is a lightweight Java library for designing and simulating Multi-Agent Systems (MAS), i.e. systems which are composed of interacting autonomous entities. MaDKit’s API allows both to develop (1) MAS-based applications, e.g. for solving distributed problems using AIs that interact by exchanging messages and (2)  simulations that rely on agent-based models (ABM), e.g. for simulating ant colonies.

I am pretty sure that MaDKit could fit in JOSS’s scope, since it is already cited in research papers. The problem is that the references which are used to cite it are too old (> 10 years), not explicitly about the software itself, and of course on an out-of-date version. But before submitting, I have a question about the authorship I should use for the submission (and also about the paper’s content) and would be glad to have some advices from JOSS editorial board members.

In fact, the first version of the software has been initiated long time ago (1997) by two of my colleagues. I get involved in the project in 1999 and took the “main developer” position (when one of my colleague leaved) and I refactored and evolved the source code of the core parts for the third (2001) and fourth versions (2003). The latter being still hosted on sourceforge. I maintained and evolved v.4 until 2010/2011, that is when I decided to rewrite everything from scratch for the fifth version (integrate new features in v.4 was harder everyday and thus clearly no longer relevant). I started to use Git and put my repo on GitHub in 2011, for which I am the only commiter (I was already alone since some years for maintaining v.4). Some of the underlying core concepts/classes are still the same since day one, but 99% of the code has been changed between v.4 and v.5. Especially v.4 and v.5 are not only incompatible but also rely on a very different approach concerning the way they are conceived and distributed. Still, I kept my colleagues’ names in the license file, in source code files, etc. It was for me a matter of OSS spirit (keep the soft’s history) as well as acknowledging their seminal work on the initial core concepts and versions. Today, if I would write a paper about v.5 for a usual academic journal, for finally having a correct reference which could be used by the actual users, I would clearly author it alone (which I should have done for years... but developing this is not at the heart of my research: It is a tool I use to build other tools. I also like to keep it alive because I know that it is regularly used… By the way, JOSS’s point is very relevant).

Since JOSS is about the code/repository per se, I am unsure of what is the more relevant for the authorship of this submission. It is kind of *repository vs. history* (for instance, should I stick to the outputs of Arfon’s generate script?). A second question is about the paper’s content: Should I tell the all story (shortly of course) or only write about v.5’s features? For information, I plan to entitle the paper with “*MaDKit-5: A lightweight library...*” for making explicit which major version is behind it.

Sorry for this long message but I prefer to resolve these questions before submitting. Thanks.

**Comment by pjotrp** [comment]
@fmichel the authors listed on the submission should represent the work presented in your submission. If you present the full software as a product I suggest to include all major contributors. If you present work done since the last paper or release, make that clear in the paper and include all major contributors that made that happen. To be safe, discuss this with your fellow contributors beforehand - you don't want people arguing online about authorship. Note it is also possible to add authors that contributed in other ways. Be sure to be fair, credit where credit is due, and all is fine.

**Comment by fmichel** [comment]
@pjotrp thank you so much for this answer. These are the feedbacks I needed. Especially, it is now clear that I will not just write on the software’s features but also about its story. I was not sure that this part could fit joss’s format. I will now prepare my repo for submitting. Thanks again.
