### ISSUE TITLE
Weekly emails, without an editor

### ISSUE THREAD

**Issue by cMadan** [openjournals/joss#338]
Papers listed as 'without an editor' in the editor weekly emails probably shouldn't include withdrawn submissions (e.g., https://github.com/openjournals/joss-reviews/issues/212).

**Comment by arfon** [comment]
Yeah, this was showing up as the issue was still open. If it had been closed it wouldn't show up. I'm closing this as I don't really think there's a software bug to fix here, this was more of a human processing failure on my part not remembering to close the original issue.
