### ISSUE TITLE
JOSS pre-submission enquiry

### ISSUE THREAD

**Issue by jtleek** [openjournals/joss#339]
Hi JOSS Folks

I'm considering submitting this work to JOSS: 

https://github.com/jtleek/tidypvals

It is an R package that organizes and tidies published p-values from thousands of articles. Both myself and others have already used the data/package to write blog posts and I"m going to be using it in an upcoming research paper. 

It isn't a method, but it is a resource, and it is research-useful. Would this be a good fit for JOSS? 

Thanks!

Jeff

**Comment by labarba** [comment]
What do you think, @karthik ? 
I'm not an R person, but if you say that this software is being used in an upcoming research paper, then it sounds like it should be eligible. I visited the repository, and did not find a clear statement of the research application —the JOSS paper would need to include a statement of that sort. You may need a couple of sentences describing how this software was useful to conduct research that is submitted for publication. You'll also have to add a contributing guide.

**Comment by karthik** [comment]
Hi @jtleek 
I looked over the package and I don't think this is a good fit for JOSS. The package is a data package, i.e. a collection of datasets (packaged to make it easy to install and use in R) and does not have any functions that implement research methods of any kind. JOSS isn't the right venue to publish data. 

Thoughts @arfon

**Comment by jtleek** [comment]
Ok I'll look elsewhere thanks!
