### ISSUE TITLE
JOSS pre-submission enquiry

### ISSUE THREAD

**Issue by ljvmiranda921** [openjournals/joss#340]
**Project repository URL:** https://github.com/ljvmiranda921/pyswarms
__Documentation__: https://pyswarms.readthedocs.io/en/latest/

PySwarms is a research-toolkit for Particle Swarm Optimization in Python. It's targeted for use of optimization/algorithm researchers who wants to compare their methods to existing/standard PSO algorithms. 

Its features include:
- Python implementation of PSO algorithms in pure `numpy`.
- Hyperparameter search tools
- Plotting environment for cost and animation

Some Questions:
1. Is it still possible to submit to JOSS even if a Zenodo DOI already exists? (Please check badges in `README.rst`)
2. Just an issue of feature-completeness. I have a [Development Roadmap](https://github.com/ljvmiranda921/pyswarms/issues/5)  for my next v.0.2.0 release, and I believe I will still keep on releasing new features after that. However, standard functionalities are already implemented. Is this then publishable in its current state?

**Comment by kyleniemeyer** [comment]
Hi @ljvmiranda921, this package definitely looks suitable for JOSS, once you've written an article following the [JOSS author guidelines](http://joss.theoj.org/about#author_guidelines).

In response to your two questions:
1. The Zenodo DOI is not an issue—in fact, we require authors to archive their software via something like Zenodo and provide us with the DOI, that will be associated with the article. JOSS is not just archiving the software, after all, the way the existing Zenodo record does, but publishing the improved article + software following peer review.
2. Most software will continue development after being published in JOSS, and we welcome future submissions if the new versions are substantially different. As long as your software does what it promises to do at this time, then it should be fine.

**Comment by ljvmiranda921** [comment]
Hello @kyleniemeyer ,

Thank you for your swift response. Okay, I will follow the instructions in the author guidelines and proceed on making my submission.

Again, thank you! Will close this issue now.
