### ISSUE TITLE
doi2bib fallback?

### ISSUE THREAD

**Issue by adrn** [openjournals/joss#341]
It looks like [doi2bib.org](http://www.doi2bib.org) is down, and has been down for several days, meaning that bibtex links on all JOSS papers are broken. Is there any alternate service to fall back on if/when doi2bib is down?

**Comment by danielskatz** [comment]
See: https://citation.crosscite.org/docs.html

For example:

curl -LH "Accept: application/x-bibtex" https://doi.org/10.1016/j.parco.2011.05.005

returns:

@Article{Wilde_2011,
doi = {10.1016/j.parco.2011.05.005},
url = {https://doi.org/10.1016%2Fj.parco.2011.05.005},
year = 2011,
month = {sep},
publisher = {Elsevier {BV}},
volume = {37},
number = {9},
pages = {633--652},
author = {Michael Wilde and Mihael Hategan and Justin M. Wozniak and Ben Clifford and Daniel S. Katz and Ian Foster},
title = {Swift: A language for distributed parallel scripting},
journal = {Parallel Computing}
}

**Comment by arfon** [comment]
Fixed by https://github.com/openjournals/joss/commit/98e8fd70a4394d97eda3fa879f0feddc7e8b574b
