### ISSUE TITLE
paper webpage should show date of publication

### ISSUE THREAD

**Issue by labarba** [openjournals/joss#342]
When a visitor pulls up the page of an accepted paper, she cannot tell the date of publication. In fact, I don' t see how one could know the date of publication.

On the latest accepted paper:
http://dx.doi.org/10.21105/joss.00411
... if I click on the PDF, it has a date of Aug. 25. But if I click on the review issue, I see that it was accepted on Sep. 21.

**Comment by rgieseke** [comment]
Is the date still in the current rendering of the PDF? Or is the comment above referring to the old layout?

**Comment by arfon** [comment]
> Is the date still in the current rendering of the PDF? Or is the comment above referring to the old layout?

It's referring to the old layouts. We currently don't have any dates on the paper 😱

**Comment by labarba** [comment]
Oops.
