### ISSUE TITLE
Sherpa/Romeo listing?

### ISSUE THREAD

**Issue by danielskatz** [openjournals/joss#346]
A potential reviewer asked me:

> why is the journal not referenced on the Sherpa/Romeo database ? I could not find it, neither with the full name, nor with the ISSN.  http://www.sherpa.ac.uk/romeo/search.php

We should try to get listed there, if possible.

**Comment by labarba** [comment]
We are listed in the DOAJ, though.
https://doaj.org/toc/2475-9066

Thanks to @cMadan
https://github.com/openjournals/joss/issues/215#issuecomment-326787926

**Comment by cMadan** [comment]
I'd be happy to look into getting us listed in the Sherpa/Romeo database.

**Comment by danielskatz** [comment]
great!!

**Comment by cMadan** [comment]
Fyi. I just filled out the "Suggest a New Journal" form, will update as the application progresses

**Comment by cMadan** [comment]
Done!

http://www.sherpa.ac.uk/romeo/search.php?source=journal&sourceid=33288
