### ISSUE TITLE
JOSS pre-submission enquiry

### ISSUE THREAD

**Issue by physicsdavid** [openjournals/joss#348]
This is a more general question about the scope of what is acceptable in JOSS. Those of us in the digital/computational fine arts perform research in a somewhat different way to those in the sciences but still generate software and libraries for our (and others') research purposes. (Yes, research has a different meaning in the fine arts to the sciences, but it is a definition accepted by academic institutions.)

Part of the use of software in digital arts research is to enable new explorations of artistic and aesthetic topics in ways that have not typically been done. However, these applications might look quite different and have different use cases to those in the sciences.

So my overall question is whether software for these kinds of submissions might be considered. For example, would a software library that allows a different kind of visual interactivity that is useful in the production of digital arts projects be suitable? Specifically, I have a p5.js library that allows for easy mouse interactivity with 3D WebGL canvases including object identification, which is not supported natively, and for which back-calculation from the 2D canvas projection to the 3D model is highly non-trivial for other than elementary 3D primitives.

Thanks for your opinions,
David

**Comment by arfon** [comment]
Thanks for posting this @physicsdavid. After reading this question I went and re-read our own [submission guidelines](http://joss.theoj.org/about#submission_requirements) and realised there's some language that might make it sound like we only want _scientific_ software but I don't think that's the case (emphasis added for clarity here):

> JOSS publishes articles about research software. This definition includes software that: solves complex modeling problems in a _**scientific**_ context (physics, mathematics, biology, medicine, social science, neuroscience, engineering); supports the functioning of research instruments or the execution of research experiments; extracts knowledge from large data sets; offers a mathematical library, or similar.

Did the term 'scientific' turn you off here or is it that we don't have an obvious category for your software?

In addition, I'm curious if you think your software meets the 'obvious research application' criteria:

> Your software should have an obvious research application

Personally I think that software that solves a research problem/has an obvious research application (regardless of the research discipline) should be able to be published in JOSS (the other criteria would need to be met too of course).

Thoughts @openjournals/joss-editors ?

**Comment by kyleniemeyer** [comment]
@arfon I agree that software that solves a research problem should be considered, regardless of the discipline.

**Comment by labarba** [comment]
I'm ambivalent about expanding the meaning of "research" beyond the disciplines that search for some  version of truth. That is, I agree that we may welcome research applications outside of hard sciences, to include perhaps history, behavior, politics ... and even literature, when the study seeks to ascertain _facts_ or discover a generalizable principle. But I would back off from divergent forms of "research" in the arts, where there is a process of quest but not a ground truth.

**Comment by arfon** [comment]
Hi @physicsdavid. The JOSS editorial team had a discussion about this question earlier in the week and we concluded that this kind of submission _is_ acceptable provided that the software is part of academic research that you plan to publish on more widely (e.g. as a paper/conference paper/PhD thesis etc).
