### ISSUE TITLE
Open source project that requires specialty hardware

### ISSUE THREAD

**Issue by cMadan** [openjournals/joss#350]
I'm currently working on a project that is based on developing a Python API and framework for using a specific USB 'human interface device' for experimental psychology research. The hardware device is a 3x5 keypad with LCD displays in each key, called Elgato Stream Deck ([photo](https://twitter.com/cMadan/status/923574789045932034)).

I'd like to submit a paper about the project to JOSS once it's in a reasonably feature-complete state, but testing the code will require someone to have the device too. The idea of open source code requiring specialty hardware was briefly discussed awhile ago (https://github.com/openjournals/joss/issues/142), but in this case it's not that the hardware is necessary for data acquisition--where one could supply some sample data--but for the code is mainly about interfacing with the hardware. So, I don't think it would be easy to find a reviewer that also has the necessary hardware... 

Could such a project be submitted to JOSS?

**Comment by kyleniemeyer** [comment]
This is tricky... without the hardware, how can someone review the software effectively?

Also, is the hardware/software specialized enough that it's unlikely anyone else would use it? If that's the case, then I'm not sure publication in JOSS would be appropriate.

**Comment by cMadan** [comment]
The device is effectively an interface device, with LCD displays on the buttons, and costs US$150. It's readily purchasable and general purpose... and I want to re-purpose it for psychology research. The project includes low-level interaction with the device, e.g., sending images to the buttons and listening for key presses; medium-level functions such as reading in images and overlaying text; as well as higher-level functions for programmatically updating the display based on pre-defined events and logging user responses. I've talked to some colleagues that would likely use the project in their research, but they don't currently have the hardware and have sufficient expertise to use the toolbox, but not to review the code themselves.

![Elgato Stream Deck](https://cdn.vox-cdn.com/uploads/chorus_image/image/54298497/91fukDTbNVL._SL1500_.0.jpg)

My concern is that I think the likelihood of finding a reviewer who (a) has the device already, (b) is proficient enough in Python to review the code, and (c) will do a review at JOSS, is relatively low. Regardless of my particular case here, I do think this is a broader issue we should consider anyway.

**Comment by iljah** [comment]
Is it an option to temporarily send the device to a reviewer if they agree to (b) and (c)? Could joss pay for shipping?

**Comment by kyleniemeyer** [comment]
@iljah No, I don't think we want to try to do this... too many issues involved.

**Comment by arfon** [comment]
Closing this out as stale, but to summarize what I think JOSS policy is today:

Submissions for speciality hardware _are_ allowed, provided that the author recognizes that it may not be possible for JOSS to find reviewers of their software as we cannot ask reviewers to purchase the hardware, nor are we willing to support [transport costs](https://github.com/openjournals/joss/issues/350#issuecomment-359740894). So in _theory_ this is supported but we expect the assistance of the submitting author to find potential reviewers and should it not be possible to find any, we would reject the paper.
