### ISSUE TITLE
paper location

### ISSUE THREAD

**Issue by lheagy** [openjournals/joss#351]
The location of the paper is not clearly communicated to the reviewer. It is in the author instructions, but for reviewers new to our process, it is not immediately evident where to find it. Ideally, we should include this in the info of the review issue (they should all be at http://github.com/org/repo/tree/master/paper if they are using github), but even a short description saying that 
```
the paper should be in a "paper" directory at the root of the repository 
```
would help clarify things for reviewers. It might also be worth adding a note in the reviewer guidelines. 

![image](https://user-images.githubusercontent.com/6361812/32118263-039b912a-bb1f-11e7-87ba-ecc9e363ee71.png)

**Comment by arfon** [comment]
@lheagy - do you think we need to do this give that we automatically post the compiled PDF to the review?

**Comment by arfon** [comment]
Closing as stale and as potentially not relevant as Whedon now compiles the papers.
