### ISSUE TITLE
Adding Search Functionality 

### ISSUE THREAD

**Issue by tomhohenstein** [openjournals/joss#352]
I was browsing the website and I thought it would be great if it had search functionality. I think you could do this with [lunr.js](https://lunrjs.com/) or [elasticlunr.js](http://elasticlunr.com/). 

I was looking around at the repos you use for the website and for the articles and it seems like adding json metadata files to your workflow wouldn't be too tricky. 

Keep up the great work!

**Comment by arfon** [comment]
Closing as a dup of https://github.com/openjournals/joss/issues/315
