### ISSUE TITLE
reviewer/author instructions re LICENSE

### ISSUE THREAD

**Issue by danielskatz** [openjournals/joss#356]
As brought up in https://github.com/iljah/hdintegrator/issues/4

Note that [GItHub](https://help.github.com/articles/licensing-a-repository/) suggests that the license should go in a ```LICENSE.md``` or ```LICENSE.txt``` file

JOSS review instructions say "Does the repository contain a plain-text LICENSE file..."

Should we be more specific, and say that the LICENSE file should be called ```LICENSE``` or ```LICENSE.txt```?

And, are we concerned that GitHub says an .md file is ok, and we don't?

**Comment by danielskatz** [comment]
Your change to the review instructions sounds good to me.
And I agree with the text check, but indeed think this is a different issue.
Building a license checking tool/service would probably be a nice hackathon project ...

**Comment by Kevin-Mattheus-Moerman** [comment]
If you paste license text when you create your license (without using the auto-generated method) I think GitHub detects what type of license it is to create the license "badge" on the repository front page. So they somehow parse the text and compare it to the official ones. There must be tools for it out there already I imagine.

**Comment by Kevin-Mattheus-Moerman** [comment]
@arfon @danielskatz can you point me in the right direction if I want to alter the review instruction text? i.e. such that it reads: 

> Does the repository contain a plain-text LICENSE file (either no extension, .txt)

**Comment by leeper** [comment]
There's a ruby gem ('Licensee') that detects licenses based on a variety of heuristics: https://github.com/benbalter/licensee

**Comment by danielskatz** [comment]
> @arfon @danielskatz can you point me in the right direction if I want to alter the review instruction text? i.e. such that it reads...

There are two files that need to be changed.  See [this PR](https://github.com/openjournals/joss/pull/313) that also changed reviewer text as an example that shows the two files.

**Comment by arfon** [comment]
> There's a ruby gem ('Licensee') that detects licenses based on a variety of heuristics: https://github.com/benbalter/licensee

Yeah, this is what GitHub uses for its license detection. We could add this as a 'pre-check' step by Whedon when a submission is first made.

**Comment by arfon** [comment]
Closing this as I think it's pretty outdated now. Plus Whedon knows how to detect licenses on new submissions now.
