### ISSUE TITLE
enable https for badges and main web site

### ISSUE THREAD

**Issue by sbinet** [openjournals/joss#358]
hi there,

I was very happy and proud to have my library reviewed by JOSS.
so much so that I put the JOSS badge to the website of my library: https://go-hep.org.

unfortunately, the JOSS badge isn't available via https, which makes Chromium flag my website as not completely secure, which is a shame :)

could JOSS serve pages and badges over https ?

**Comment by arfon** [comment]
Thanks for reminding me about this @sbinet. I've just enabled https on the `joss.theoj.org` domain so this *should* just be working now. Could you confirm?

**Comment by arfon** [comment]
I believe this is now fixed.

**Comment by sbinet** [comment]
apologies for the belated answer: yes, it's fixed.
thanks!
