### ISSUE TITLE
develop locally?

### ISSUE THREAD

**Issue by vsoch** [openjournals/joss#359]
hey @arfon! I want to reproduce this kind of repo and am wondering if you have docs about how you work locally and/or deploy? I was going to give heroku a try, but I first hit some warnings from github about vulnerabilities, and for heroku the gemfile is missing some suggested things (so I'm guessing you aren't using it?) I'm really excited about making josc (the equivalent for containers) and hope we can chat soon!

**Comment by arfon** [comment]
👋 @vsoch. I just replied to you over email about JOSC. This repo is the one being used for JOSS. Do you have much experience running Rails applications? It should be possible to simply `bundle install` this application.

There are some environment variables that need setting when the application boots but other than that it _should_ work 😄

**Comment by vsoch** [comment]
hey @arfon ! I responded to your email, and wanted to leave a note here as well! I don't have a ton of experience with Rails (beyond using Github and jekyll) but I'm pretty ok at figuring things out, and wha-la I have a heroku thing!  --> https://shielded-mountain-65855.herokuapp.com/  It looks like it's missing various API keys for things like Orcid, etc. What is the typical development setup, and are you using heroku too? I usually would have a Docker / container development set up so I don't have to install all the dependencies on the host, but I'm open to trying what you think is best. Can you give me some hints at how to hack it properly, set environment stuffs, or should I keep stumbling around and try to figure out?

**Comment by arfon** [comment]
> and wha-la I have a heroku thing! --> https://shielded-mountain-65855.herokuapp.com/ I

Oh nice! Yes, Heroku is where we're deployed. Basically with the dependencies expressed in the `Gemfile` and the `Procfile` in the repository, Heroku knows how to run this thing. 

> Can you give me some hints at how to hack it properly, set environment stuffs, or should I keep stumbling around and try to figure out?

I should probably give you a walk though of how this all works when we chat on the phone but the most important environment variables are the `ORCID_KEY` and `ORCID_SECRET` for auth, the `GH_TOKEN` for allowing the application to make issues on GitHub under the `@whedon` account, and the `WHEDON_SECRET` which is used to authenticated incoming messages from `@whedon`.

I wouldn't do anything other than kick the tyres right now on this as we're in the process of making some fairly major changes to the application to make it easier to fork the journal and have multiple versions running simultaneously. If you'd like to follow along, that work is currently being reviewed in https://github.com/openjournals/joss/pull/353

**Comment by vsoch** [comment]
going to close the issue here as we have discussion / work underway! :D

**Comment by emdupre** [comment]
I'm currently trying to set up a development environment for JOSS and came across this issue !

Did you happen to create any more detailed documentation re: getting this up and running, @vsoch ? I'm working on some docs right now, but I'm also having some trouble and I'd love to learn from your experience !

**Comment by vsoch** [comment]
hey @emdupre ! We didn't wind up working on this because @arfon had too many pots in the fire (is that how they say that?) - but if a development version is something you'd be interested in, I'd be happy to try and help again (it's been a while and I don't remember the specifics of the deployment). I do think we'd probably need your help with questions that might come up, is that something you'd have time for @arfon?

**Comment by arfon** [comment]
I'm happy to try and assist here. Some general pointers:

- You'll need an ORCID account set up with developer tokens (which are used to boot the application like this `ORCID_KEY=xxxx ORCID_SECRET=xxxx bundle exec rails s`)
- You'll need Postgres and Elastic Search installed locally (as well as Ruby etc.)
- After first logging in locally you'll need to get on the Rails console locally and set your user account as an admin account (`admin` is a boolean field on User)

Other than that, this is a fairly vanilla Rails application.

**Comment by xuanxu** [comment]
>  this could be a good opportunity to learn where docs are needed...

Indeed! 
@emdupre just ping me if you need any help with the docs or setting up your deployment
I've just created a `dev-docs` [branch](https://github.com/openjournals/joss/tree/dev-docs) to work on [these guides](https://joss.readthedocs.io/en/latest/installing.html) and issue PRs against

**Comment by emdupre** [comment]
Great, thank you all !!

I've made it through the steps listed above, and a few others that might be worth mentioning (e.g. getting a SendGrid account, which requires having an email address on a domain you control; provisioning a scheduler add-on to send weekly reminder emails using the `libs/tasks` scripts; fixing up a few hard-coded variables, like the reviewer google sheet ID).

What would be the best way to move forward, @xuanxu ? Should I open a PR with what I have so far, and an issue with the questions I'm currently facing ? I'm at the stage of interfacing with github / whedon, so I'm not sure if that makes sense as an issue on this repo or on whedon-api !

**Comment by xuanxu** [comment]
> What would be the best way to move forward? Should I open a PR with what I have so far, and an issue with the questions I'm currently facing ? 

Yes, I think that's a good way to go. We can usen PRs to add code and resolve questions.

> I'm at the stage of interfacing with github / whedon, so I'm not sure if that makes sense as an issue on this repo or on whedon-api

+1 to this repo, I think is better to have a central place with all the _deploy a journal_ docs together. 
BTW in the future whedon-api will be replaced by [Buffy](https://github.com/openjournals/buffy), maybe you find its docs useful.
