### ISSUE TITLE
Binder badges for JOSS articles?

### ISSUE THREAD

**Issue by betatim** [openjournals/joss#360]
We wanted to reach out and hear what your thoughts were on letting authors add a "binder badge" to their publications like the PDF, repo, etc link

<img src="https://files.gitter.im/jupyterhub/binder/EU6P/2017-11-30-10_40_05-The-Journal-of-Open-Source-Software.png" />

This seems like a super partnership as a lot of people who submit to JOSS will already have examples in their repositories. It would also help reviewers check if the install instructions work, examples run, etc, etc without having to install things locally to get started.

We (obviously) think readers would also find this useful for similar reasons.

[Binder](https://github.com/jupyterhub/binderhub) helps you when have a repository full of Jupyter notebooks and let's anyone open those notebooks in an executable environment, making your code immediately reproducible by anyone, anywhere. There is a public instance [here](https://mybinder.org). The [PyHector](https://github.com/openclimatedata/pyhector) repo has a binder badge already if you want to try it out.

While binder comes from the world of jupyter it isn't python only. There are examples of [c++ kernels](https://mybinder.org/v2/gh/QuantStack/xeus-cling/master?filepath=notebooks%2Fxcpp.ipynb), [RStudio](https://github.com/binder-examples/dockerfile-rstudio), [Julia](https://github.com/binder-examples/julia-python) and my personal fave [appmode](https://github.com/oschuett/appmode) (Shiny for python anyone?!!)

Lot's of details and engineering to be worked out but we thought we put the idea out there to hear what you think.

cc @minrk @yuvipanda @willingc @choldgraf @Kevin-Mattheus-Moerman @arfon

**Comment by willingc** [comment]
FYI @labarba @lheagy @katyhuff

**Comment by choldgraf** [comment]
Probably worth clarifying something in terms of how much overhead this would create: the only thing needed to make a repo binder-ready is for it to have "configuration" files that define the environment needed to run the code within. E.g., a `requirements.txt` or `environment.yml` file will install a Python environment within Binder. Other than this, we'd just need to create a URL that points Binder to the person's repo, and Binder should then take care of the rest.

**Comment by arfon** [comment]
👋 @betatim - thanks for opening this issue. Long-time fan of Binder here :-)

I'm definitely interested in this idea but after thinking on it for a few days I can't help but come back to the thought that these badges seem more appropriately placed in the GitHub README (or associated documentation) than on the JOSS paper page. I'm also concerned that it probably doesn't make sense for many of our JOSS submissions to have a Binder badge, so what would we do in that case?

Relatedly, I've been noodling on the idea of having a 'JOSN' (Journal of Open Source Notebooks) where the primary (only?) acceptable submission format would be in the form of Jupyter Notebooks. In this scenario I could totally imagine having a deep Binder integration...

Sorry for the muted response. I like the idea, I'm just not convinced it's the right thing to do for JOSS.

I'd appreciate thoughts from my fellow JOSS editors / cc @openjournals/joss-editors

**Comment by labarba** [comment]
I agree with @arfon that JOSS is not the best place for the Binder badge (GitHub-repo README.md better), and many (if not most) of the papers would not have use for it (as have no Jupyter files).

**Comment by choldgraf** [comment]
Yeah that's a fair point. I didn't realize that those the sections in the "authors" area were _always_ there. I mistakenly made the assumption you could pick and choose what info to put there. If there were a "Journal of Open Source Notebooks" that'd definitely make sense.

That said, it's worth pointing out that Binder is *not* just for Jupyter Notebooks. It already supports RStudio and JupyterLab interfaces. It should be seen as a platform/tech for sharing interactive computing environments more generally, rather than something that is jupyter notebook-focused (though notebooks are obviously a good way to share this kind of content and are a first-class citizen in Binder)

**Comment by labarba** [comment]
I'm going to close this issue—if anyone has further to add, go ahead and re-open.
