### ISSUE TITLE
JOSS pre-submission enquiry

### ISSUE THREAD

**Issue by dhhagan** [openjournals/joss#362]
https://github.com/dhhagan/py-opc

This software makes it simple to operate a popular optical particle counter (Alphasense OPC-N2) via python. Over the three years it has been in existence, it has been used by organizations including the EPA. It has also been cited in at least one academic paper thus far, with more on the way.

My questions are as follows:

  1. Does this qualify?
  2. I have a [second repository containing the c++ version](https://github.com/dhhagan/opcn2) for those using other MCU's that aren't running python. Is there a way to join these two despite being two separate repositories?

**Comment by danielskatz** [comment]
Sorry for the delay in anyone responding...

1 - this seems reasonable.
2 - yes, there is a way to have a paper that includes multiple repositories, though doing so involves some manual work by @arfon currently.  (an example is https://github.com/openjournals/joss-reviews/issues/456)

**Comment by pdebuyl** [comment]
Paper submitted in https://github.com/openjournals/joss-reviews/issues/540 and https://github.com/openjournals/joss-reviews/issues/782
