### ISSUE TITLE
mention donations in acceptance emails?

### ISSUE THREAD

**Issue by danielskatz** [openjournals/joss#365]
Our current acceptance email looks like this:

> 🎉🎉🎉 Congratulations on your paper acceptance! 🎉🎉🎉
> 
> If you would like to include a link to your paper from your README use the following code snippet:
> 
> [DOI link here]
> This is how it will look in your documentation:
> 
> [DOI image link here]
> 
> We need your help!
> 
> Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html

We could add something about how to donate to the "We need your help" section.  I'm not sure that we should, but I think it's worth discussing.

**Comment by arfon** [comment]
Yes, I definitely want to do this. I'm currently waiting on some guidance from the NumFOCUS folks on what donation links to include. Once I have them, I'll be sure to add them.

**Comment by arfon** [comment]
Related to https://github.com/openjournals/joss/issues/154
