### ISSUE TITLE
JOSS website - links for papers

### ISSUE THREAD

**Issue by danielskatz** [openjournals/joss#366]
On the main JOSS website, the papers link (upper right) takes you to http://joss.theoj.org
However, on the main site itself, there's a different view of papers below the header.  Why do we need two different views?  What's the purpose of this view in particular?

**Comment by arfon** [comment]
I'm not sure I follow sorry. The upper right-most link goes to http://joss.theoj.org/papers which segments the papers by:

- `Accepted` (accepted papers)
- `Active` (papers under review or recently submitted)
- `All Papers` (the combination of both)

On the homepage, we simply show the `All Paper` tab. I'm not sure I understand what's confusing/of concern here?

**Comment by danielskatz** [comment]
I guess it's because it looks different - the other tabs aren't available on the home page.
And the fact that the same tab is available on 2 different pages isn't aesthetically pleasing to me.

I feel like I heard someone once say "everything in its place, and a place for everything" as a design principle...  (though I find on a google a claim that this first appeared in print the other way around in 1640 as a sailors' motto)

If no one else is unhappy with this, we can ignore my concern.

**Comment by labarba** [comment]
I've been mulling similar things for a while. I feel that the landing page should only show the _accepted_ papers by default. Under review and submitted are OK to be visible after two or three clicks. But it bothers me that when you land on JOSS you see mostly non-published items.

**Comment by arfon** [comment]
Yeah, I agree. I've updated the site to show accepted papers on the homepage and made the top level menu link to `Papers` link to the 'All papers' tab here http://joss.theoj.org/papers

**Comment by danielskatz** [comment]
looks good - thanks.
