### ISSUE TITLE
JOSS website - Article level metrics

### ISSUE THREAD

**Issue by danielskatz** [openjournals/joss#367]
We should try to add article level metrics to http://joss.theoj.org/papers/accepted, including potentially Altmetrics badges and citation counts

**Comment by arfon** [comment]
@danielskatz - could you link to an example of a journal you think does this particularly well? Is this as simple as using the [Altmetric widget](https://api.altmetric.com/embeds.html)?

**Comment by danielskatz** [comment]
I think it is almost that simple, except for the text they give that says:

>If you want to use the badges on a site that isn't your lab or personal homepage, blog or an institutional repository then you should first contact us at support@altmetric.com so that we can clear your use case. Do not use the badges commercially - on a journal, search engine, in an app etc. - without talking to us first! We're required by some of our data sources to keep track of who is using the badges and what for, and so need to issue you a license.

PeerJ uses these, but in a slight different format.  For [our article](https://doi.org/10.7717/peerj-cs.86), for example:
clicking on the "visitors (click for details)" gives a popup that includes a small altmetrics badge, and clicking on this gets you to:
https://www.altmetric.com/details/12082344

**Comment by Benjamin-Lee** [comment]
PLoS does a really good job of it: article level views, saves, citations and shares.

**Comment by arfon** [comment]
OK, I've emailed the Altmetrics folks to seek permission to use the widgets on the JOSS and JOSE sites.

**Comment by arfon** [comment]
OK, I've heard back from the Altmetrics folks and unfortunately the cost for using the badges on our sites is way higher than we could ever afford:

> Pricing for the badges for one journal typically starts at around £2,500. They’re a great way of providing instantaneous feedback to authors, and to help visitors to your site see the reach and influence of your content. 

I asked if there's a 'discount' rate for volunteer-run, zero-APC journals like ours but apparently there isn't so... `¯\_(ツ)_/¯` 😿

**Comment by Benjamin-Lee** [comment]
Could we at least get a page views list? That should be free.

**Comment by labarba** [comment]
Maybe we could start a donations campaign to crowdfund the Altmetrics fee? 
And is that a one-time fee? (or yearly ARGH)

**Comment by arfon** [comment]
> And is that a one-time fee? (or yearly ARGH)

Not sure. 

TBH, I’m personally not particularly motivated to pay this fee. I’d rather see them develop some kind of plan for community-run efforts like ours.

**Comment by rossmounce** [comment]
altmetrics (the concept) and Altmetric (a service provider) are two different things. Altmetric are just one of many article level metrics providers. Why not look into other sources of altmetrics data e.g. Crossref Event Data? I could be wrong but at a basic level CR event data is free and open? https://www.crossref.org/services/event-data/

**Comment by a-slide** [comment]
I bumped into [PlumX Metrics](https://plu.mx/w/a/-EbQ1LVxuj0zlIYHfvBX1ifZXoHvgTCf-39HL_MOwH4) today. It gives you a social metrics badge similar to Altimetrics.

![Screenshot_2019-05-29 PlumX](https://user-images.githubusercontent.com/5701192/58545959-4623be00-81fc-11e9-86d0-f315480b9669.png)

Apparently it is free of charge for Open source journals
https://plumanalytics.com/integrate/embed-metrics/

**Comment by labarba** [comment]
Plum Analytics was acquired by Elsevier a couple of years ago. Not sure we want to be using an Elsevier product in our journal...

**Comment by arfon** [comment]
I'm working on building out the redesigns for JOSS and they will include an Altmetric badge:

<img width="1223" alt="Screen Shot 2019-05-29 at 7 08 33 AM" src="https://user-images.githubusercontent.com/4483/58552538-a278e480-81e0-11e9-9e5c-5980fb8f5884.png">

**Comment by a-slide** [comment]
Great. The new layout looks awesome.

**Comment by arfon** [comment]
New site is shipped which includes Altmetric.com badges.
