### ISSUE TITLE
Rendering of 289

### ISSUE THREAD

**Issue by rgieseke** [openjournals/joss#371]
I noticed that in http://joss.theoj.org/papers/10.21105/joss.00289 from @lwilson the list is not rendered properly in the PDF. 

The Markdown rendered on GitHub looks fine:
https://github.com/TACC/launcher/blob/master/paper/paper.md

An empty line above the list would likely solve the PDF issue.

I think there is also a typo in "Immune repertoire"

**Comment by danielskatz** [comment]
@rgieseke - thanks for pointing this out.

@lwilson - any comment on the "typo"?

@arfon - this is the second problem of this type in the last week or two.  Is this is problem with pandoc and lists, or something we can fix?

**Comment by rgieseke** [comment]
I believe the problem is that GitHub flavored Markdown allows this, so it's not spotted easily before rendering the JOSS pdf. With better instructions on local compilation this might be improved (https://github.com/openjournals/whedon/issues/17, https://github.com/openjournals/joss/issues/370)

**Comment by arfon** [comment]
> @arfon - this is the second problem of this type in the last week or two. Is this is problem with pandoc and lists, or something we can fix?

Pandoc seems to be much more fussy about Markdown lists than GitHub. 

Won't make a list with Pandoc -> PDF:

```
Some text and then a list:
- List one
- List two
- List three
```

*Will* make a list with Pandoc -> PDF:
```
Some text and then a list:

- List one
- List two
- List three
```

Note the space at the top of the list between it and the previous paragraph.

**Comment by danielskatz** [comment]
This should be documented somewhere for JOSS submitters, I guess?

**Comment by arfon** [comment]
> This should be documented somewhere for JOSS submitters, I guess?

Yeah, I guess so but perhaps there are some Pandoc docs that cover this?

**Comment by lwilson** [comment]
I've committed the typo fix and and added a blank line before the list elements (https://github.com/TACC/launcher/commit/a3c87c908a7a2d197c54a5fa211f9bae8dccc66b)

**Comment by arfon** [comment]
I've updated the PDF visible at http://joss.theoj.org/papers/10.21105/joss.00289 . You might need to refresh your browser a few times to get the new version to show up.
