### ISSUE TITLE
Issue in paper title in Papers page

### ISSUE THREAD

**Issue by kyleniemeyer** [openjournals/joss#372]
I've noticed that the title of some papers (or at least one) in the list on the website doesn't match the actual software/article title; for example, the ["ros_control" article](http://joss.theoj.org/papers/8449c6e7b2757d90d7d8451ebecf7fce) is listed as "ros-controls/joss_paper".

I imagine the issue is related to grabbing the directory where the paper resides rather than the article title/software name.

<img width="1042" alt="screen shot 2017-12-18 at 1 59 50 pm" src="https://user-images.githubusercontent.com/190432/34130363-5f66a750-e3fc-11e7-9f89-0684a85e4648.png">

**Comment by kyleniemeyer** [comment]
(This may be resolved with the work @parrish and @arfon are doing, e.g., #369, but I'm not sure)

**Comment by arfon** [comment]
`ros-controls/joss_paper` is the name of the repository that was submitted to JOSS for review and in this case the reviewer had to review ~3-4 different repositories on GitHub as there wasn't a single repository for review.

I'm not sure that I see this as a bug to be honest. We could talk about showing a different thing here but the repository address is submitted by the author (and not something we generally edit).

Could you say more about what you think should be fixed here @kyleniemeyer?

**Comment by kyleniemeyer** [comment]
Ah, so this one is a bit unusual since there isn't a single repository—I guess I expect the name in the list of papers to match the software name mentioned in the article title, but perhaps this is an outlier that isn't easily solvable.

**Comment by arfon** [comment]
Fixed in the new JOSS website updates.
