### ISSUE TITLE
Replace paper sample in Author Guidelines

### ISSUE THREAD

**Issue by labarba** [openjournals/joss#374]
The Author Guidelines have the following text:

 > Author a short Markdown paper `paper.md` with a title, summary, author names, affiliations, and key references. See an example [here](https://github.com/arfon/fidgit/tree/master/paper).

The sample paper linked to is an old example in @arfon's GitHub account—(1) it shows the old, unformatted PDF template; (2) it may give the wrong impression to potential submitters about what our (new) expectations are for the paper.

Wouldn't it be nicer to link to an actual published JOSS paper that reflects the current expectations? Or otherwise make a sample with _Lorem Ipsum_ text, showing a reasonable length, headings for expected content, and the current PDF template.

**Comment by danielskatz** [comment]
either of these would be a good change

**Comment by arfon** [comment]
👍 I think this is a good idea. Is there a particular submission you think we should link to?

**Comment by pdebuyl** [comment]
It would nice if the example includes inline and standalone math, see #409

**Comment by arfon** [comment]
@pdebuyl I included your examples in https://github.com/openjournals/joss/commit/13f55436f831af7952ece53e42378a020d0367c2

**Comment by arfon** [comment]
In fact, I think this issue can now be closed given the example paper we now have at https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography
