### ISSUE TITLE
Enquiry about special issues in JOSS

### ISSUE THREAD

**Issue by Juanlu001** [openjournals/joss#375]
The organizers of the PyCon Spain 2018 would like to explore different ways to encourage participation by an academic/scientific audience. Despite having a Scientific/Data track in all the previous editions, we noticed reluctance from some researchers to send talks due to lack of proceedings. Therefore we would like to try something different and publish some selected contributions in the form of academic papers while retaining the open and collaborative nature that the whole conference fosters, and we think JOSS would be the ideal place to do that.

For traditional journals, sometimes an agreement is made with the editors to publish the papers from the conference in an "special issue". We would like to know whether this idea would be of interest for the JOSS board, and if so:

* Could some sort of prominent or distinctive space be created for such special issues on the JOSS website?
* Should we change the review process in any way, for example adding a pre-selection step by the conference organizers?

I will be happy to discuss the details here on GitHub or via email.

cc @maigimenez @sanguinariojoe @AunSiro @javipalanca @atugores

**Comment by labarba** [comment]
JOSS does not publish extended papers. It publishes description summaries of research software, where the research software exists in its own repository and is the subject of the peer review. Therefore, it is not a good fit to publish proceedings.

**Comment by kyleniemeyer** [comment]
Yeah, JOSS is not the right fit for publishing proceedings—however, we would be happy to consider software submissions that are associated with submissions to the conference.

**Comment by Juanlu001** [comment]
Thank you for your response, we will then encourage the interested authors to submit their software to JOSS. I am closing this.
