### ISSUE TITLE
Explain how to preview papers in the JOSS format

### ISSUE THREAD

**Issue by mhucka** [openjournals/joss#379]
In trying to prepare a paper submission, I got stumped by formatting: the submission guidelines give a sample paper in Markdown format with YAML metadata and Bibtex for bibliography, but there doesn't seem to be an explanation of how an author can generate a preview of the paper in the JOSS format. 

Where can I find information about the software pipeline and command arguments to be used?

To be clear, I know multiple ways of generating HTML from Markdown files – I just don't know what JOSS does in particular.  I'd like to preview my paper while preparing a submission.

**Comment by arfon** [comment]
@mhucka - [this is the command](https://github.com/openjournals/whedon/blob/master/lib/whedon/processor.rb#L97-L119) that we run when processing the submissions. It's also the same command that is run by the @whedon bot in review issues (e.g. https://github.com/openjournals/joss-reviews/issues/501#issuecomment-351157004)

For now there's some documentation available on the [Whedon Gem repository](https://github.com/openjournals/whedon) which is the best way to replicate the PDF papers. Sorry this isn't easier :-\

**Comment by mhucka** [comment]
@arfon Thank you very much for that pointer – that was exactly what I needed. This allowed me to create a simple Makefile that encapsulates the process of running pandoc to generate a PDF using the Whedon latex template. I put it in a [gist](https://gist.github.com/mhucka/5ecb18aa2fd088c055de07366f70135e) if you would like to see it. The makefile can certainly be improved (e.g., by making it get title and author from the `.md` file), but perhaps this can be the start of something that can be made available to other people too.

**Comment by mhucka** [comment]
Thanks for this work and the ping. I haven't had a chance to write a new joss article, but when I do, I'll take a look at this!

**Comment by CameronDevine** [comment]
I recently wanted to preview a JOSE paper, and ended up writing a bash script to compile both JOSS and JOSE papers. The script is based off of the `pandoc` options in [lib/whedon/processor.rb](https://github.com/openjournals/whedon/blob/master/lib/whedon/processor.rb). This [script](https://gist.github.com/CameronDevine/338a140dac03ca9f39a5d8a2f7f50e5e) automatically downloads the LaTeX template, CSL file, and appropriate logo from the `wheadon` repository and compiles the paper using the metadata. Other options, such as DOI names, can be included using command line arguments.

**Comment by vsoch** [comment]
@CameronDevine did you try the paper builder? --> https://github.com/openbases/builder-pdf
