### ISSUE TITLE
JOSS pre-submission enquiry

### ISSUE THREAD

**Issue by henrik227** [openjournals/joss#380]
https://github.com/HPAC/matchpy

We want to submit MatchPy, a pattern matching module for Python. My question concerns the requirement "You should be a major contributor to the software you are submitting". I'm not, in the sense that I didn't write any code. The author is Manuel (@wheerd ), who implemented MatchPy as part of his Master's thesis. I was his supervisor (I'm a graduate student). Manuel now works in the industry, I'm still in contact with him and he supports the submission. I use MatchPy for my research, and I'm now responsible for it and will continue to work on it (or more likely, have other students work on it). Can I submit MatchPy in this case, or does Manuel have to do it?

**Comment by arfon** [comment]
Thanks for the question @henrik227. I think it's fine for you to submit this - I'm assuming that both you and @wheerd will be authors on the paper?

**Comment by henrik227** [comment]
Thank you for the quick response! Yes, and he is first author.
