### ISSUE TITLE
Create clickable hyperlink for whedons generate pdf output

### ISSUE THREAD

**Issue by Kevin-Mattheus-Moerman** [openjournals/joss#383]
Currently when one calls whedon to generate a pdf, and a pdf is successfully created, a plain text link to the paper is presented. It would be great if this was a hyperlink to the article instead. Currently I copy past the text to get to the draft of the paper. 

So instead of: 
`https://github.com/openjournals/joss-papers/blob/joss.00493/joss.00493/10.21105.joss.00493.pdf`

have: 
[https://github.com/openjournals/joss-papers/blob/joss.00493/joss.00493/10.21105.joss.00493.pdf](https://github.com/openjournals/joss-papers/blob/joss.00493/joss.00493/10.21105.joss.00493.pdf)

Or even something with happy pictures e.g. 📖  🔖 📑 📃 📄 📎 : 
pdf creation successful [--> Check article proof 📑 <--](https://github.com/openjournals/joss-papers/blob/joss.00493/joss.00493/10.21105.joss.00493.pdf)

**Comment by arfon** [comment]
Great idea. Fixed in https://github.com/openjournals/whedon-api/commit/eb170f6fc31c8c3e77453dbdfa6a8ae9183dc5b5

**Comment by Kevin-Mattheus-Moerman** [comment]
🦈  and 🤖  that is awesome 😱

**Comment by Kevin-Mattheus-Moerman** [comment]
ah 💩 it is still code style text

**Comment by arfon** [comment]
OK, actually fixed in https://github.com/openjournals/whedon-api/commit/b9ab0bdee8ef24f22a381a85cb0b6f28518c0c01
