### ISSUE TITLE
JOSS pre-submission enquiry

### ISSUE THREAD

**Issue by ericfranz** [openjournals/joss#384]
**Project repository URL:** https://github.com/OSC/Open-OnDemand

Open OnDemand is to provide an easy way for system administrators to provide web access to their HPC resources. It is like a web version of an HPC cluster's login node. User's are given their own web server to connect to so that processes are isolated in the same way that an SSH session provides. A popular feature is the ability to launch graphical desktop environments and applications (Jupyter, MATLAB, etc.) on one or more compute nodes in the context of a batch job. It reduces the barrier to entry for using HPC, is very popular with our HPC center's users, and is installed or is being evaluated by 10+ HPC institutions in the US.

Questions:

1. What if the codemeta.json file changes or the repo location for the project changes after the project is published to JOSS? What is the procedure for updating the links in JOSS?<sup>1</sup>
2. Does the order of the authors in codemeta.json matter?
3. Regarding the [codemeta.json](https://github.com/OSC/Open-OnDemand/blob/master/codemeta.json) I wanted to confirm that datePublished, dateModified, and dateCreated are referring to the project itself

<sup>1</sup> Currently the bulk of OnDemand's code is scattered across multiple repos. The [website and main project repo](https://github.com/OSC/Open-OnDemand) has links to the [documentation](https://osc.github.io/ood-documentation/master/) which in turn has links to the repos for the [Infrastructure](https://osc.github.io/ood-documentation/master/infrastructure.html), [Core apps](https://osc.github.io/ood-documentation/master/applications.html), and [Interactive App Plugins](https://osc.github.io/ood-documentation/master/install-ihpc-apps.html). In the future we will be merging some of these repos into a single repo.

**Comment by labarba** [comment]
It sounds like a very useful project. My concern is that the application is not directly a _research_ application. The question we ask ourselves is: _will a researcher feel the need to **cite** the software?_

**Comment by ericfranz** [comment]
We acknowledge that researchers transparently using [Open OnDemand](https://dl.acm.org/citation.cfm?doid=2949550.2949644) to do research in their domains will not cite the project (any more than they would cite Linux).  However, there is a vibrant cyberinfrastructure research community dedicated to innovating capabilities for domain scientists.  This community has a tradition of citing software projects such as [Globus](https://www.globus.org/) and we’d expect them to cite Open OnDemand in a similar fashion.

**Comment by labarba** [comment]
@arfon ?

**Comment by arfon** [comment]
> This community has a tradition of citing software projects such as Globus and we’d expect them to cite Open OnDemand in a similar fashion.

👍 that's good enough for me. Please go ahead and submit your package to JOSS.
