### ISSUE TITLE
JOSS pre-submission enquiry

### ISSUE THREAD

**Issue by kwilliams-mo** [openjournals/joss#391]
https://code.metoffice.gov.uk/trac/utils/wiki/leaf_simulator

We would really like to contribute our research software package to JOSS, if possible. We are hoping that our package is eligible, but wanted to check that it meets the opens source criteria first, before going through the submission process.

Our python package (leaf_simulator) makes it easier to manipulate observations of leaf carbon and water fluxes and use them to tune the parameters given as input to the (fortran) JULES land-surface model (published in Geoscientific Model Development, https://www.geosci-model-dev.net/4/677/2011/). The leaf_simulator can be used to validate the leaf-level processes in the JULES model or add new vegetation types and processes. It is currently being used in three separate research projects (tallgrass prairie in Kansas, ozone damage of soybean in Illinois and tropical forest canopy in Brazil), and we expect this to increase. We hope it will foster more interaction between the observational and numerical modelling community.

The leaf_simulator package is on the Met Office code subversion repository: https://code.metoffice.gov.uk (there are many other projects here, including JULES). There is no charge for access to the code but it does require user registration. The code is under a CLA license. Does this meet the conditions for publication in JOSS?

**Comment by kwilliams-mo** [comment]
Thanks for getting back to me so quickly! Our software is contributed to the code repository under a Contributor Licence Agreement licence and the project is individually licensed under a BSD 3-clause "New" or "Revised" License. But the code repository does require user registration to view the code. I think maybe the best thing for me to do would be to check with our institute's Science Code Information Asset Owner once #219 has been resolved, and see whether we have the option of moving to a more open location that meets all the criteria.

**Comment by arfon** [comment]
Hi @kwilliams-mo - thanks for your responses. Prompted by your enquiry we've recently updated our policies to address these questions in https://github.com/openjournals/joss/issues/219

Unfortunately the current setup for your project is _not_ acceptable to JOSS. If it's possible for you to move to a more open location that would be great!
