### ISSUE TITLE
including ISBNs in JOSS papers

### ISSUE THREAD

**Issue by danielskatz** [openjournals/joss#392]
Some authors reference books in their submissions, and these books often have ISBNs instead of DOIs.

We don't seem to have a way to make the ISBNs, even if they are in the .bib file entry, actually appear in the pdf of the submission, including using the notes field.

This issue is intended to track this problem.

See https://github.com/openjournals/joss-reviews/issues/639#issuecomment-379245236

**Comment by motib** [comment]
The issue could be generalized to the "note" field in general. I use it, for example, for online documents:
`note={\url{https://....}}`

**Comment by logological** [comment]
IIRC the LaTeX template is set to use biblatex, so adding support for ISBNs might be as simple as passing the `isbn=true` parameter to `\usepackage{biblatex}`.

**Comment by arfon** [comment]
Thanks for the suggestion @logological. I just tried that but it didn't seem to affect the output. I suspect it might be something to do with our CSL.

@tarleb - do you have any suggestions?

**Comment by tarleb** [comment]
I agree that this looks like a CSL issue. ISBN is a supported CSL field, but `apa.csl` does not seem to support it. As far as I can tell from a [quick search](https://github.com/citation-style-language/styles/search?q=isbn&type=Code), ISBNs are used in quite a few cases. Including it should be easy following, for example, [iso690-numeric-en](https://github.com/citation-style-language/styles/blob/61b34393eb1b7db87603b537ebd61e0936565e99/iso690-numeric-en.csl).
Of course, the resulting style would no longer be stock APA.

**Comment by logological** [comment]
One of the authors of biblatex has indicated [how to get the APA style to include ISBNs](https://tex.stackexchange.com/a/302576/22603).  He also warns that with this modification, the style is no longer fully APA-compliant.

**Comment by arfon** [comment]
> Of course, the resulting style would no longer be stock APA.

Yeah, I'm not sure we care too much to be honest. I personally would rather we showed ISBNs when we have them than be APA-compliant.

Thoughts @openjournals/joss-editors?

**Comment by danielskatz** [comment]
I agree - content beats style

**Comment by tarleb** [comment]
I opened openjournals/whedon#71 to address this, but didn't verify yet that it really works as expected.

**Comment by arfon** [comment]
openjournals/whedon#71 is verified and deployed. Thanks to @tarleb for the fix!
