### ISSUE TITLE
JOSS pre-submission enquiry

### ISSUE THREAD

**Issue by drjmm84** [openjournals/joss#396]
[https://github.com/drjmm84/applehealthdata](https://github.com/drjmm84/applehealthdata
)

I am putting together a submission, but want to check if my software package is too simple or even appropriate for this journal. My software extracts the Apple Health step count and distance data so that researchers can easily collect the daily values from participants. Currently, there is no easy way for researchers to aggregate this data from iPhone users. I think that I have nearly everything that I need in my Git, but just want to make sure that I am on the right track.

Thanks,

**Comment by Kevin-Mattheus-Moerman** [comment]
Apologies for the delayed response. This unfortunately falls under the "minor utility package" category (see also our [author guidelines](http://joss.theoj.org/about#author_guidelines)). I hope you do consider out platform in the future. 
Side note: From your profile page it seems you may also be interested in the [Journal of Open Harware](https://openhardware.metajnl.com/).
