### ISSUE TITLE
What should/shouldn't the paper include?

### ISSUE THREAD

**Issue by kyleniemeyer** [openjournals/joss#40]
Recording a comment from a conversation earlier today with @arfon and @danielskatz: should there be a way to allow discussion of implementation details or underlying theory (e.g., equations)? Or should that be mandated in the software documentation?

Some suggestions/options:
- Leave implementation/theory details in documentation.
- Keep "main" section of paper empty, but allow appendices.
- Allow "methodology" or "implementation details" (e.g.) section in paper

**Comment by daattali** [comment]
Just came here to say that to me it seemed very odd to submit such a short paper.

Most of my scientific packages do include longer vignettes with details on the theory and usage, and my instinct was to just use my vignette as the paper content, but then I learned that it's too long.

When browsing through the published papers in JOSS, to me it seemed a bit strange that everything was so short and it kind of gave me a feeling of "very minimum work needs to go into this" which I do realize is the core value of JOSS, but it still felt a little bit too amateur to be taken seriously.  I hope I'm not being too cynical, it's just the honest reaction I had.

I would personally vote to have the option to submit longer papers if the author has the content handy already.

**Comment by danielskatz** [comment]
If you want to publish a longer paper, there are lots of existing options - see https://www.software.ac.uk/which-journals-should-i-publish-my-software

**Comment by daattali** [comment]
@danielskatz Thank you. I added my comment because of @arfon 's last comment:

> and if we get lots of people asking to submit longer-form pieces then perhaps we could revisit?

So I wanted to voice my support for longer-form. If you guys think this decision is set in stone, then it might be worth mentioning and making it clear that JOSS is by design ONLY for short papers and if you want a longer paper then you can submit to X/Y/Z.

**Comment by pjotrp** [comment]
Personally I don't see why we should set the limit at the size of a paper. We can encourage an author to shorten a paper - but if there is valuable information in there, who are we to disagree? @arfon do you think JOSS is by design for short papers?

**Comment by arfon** [comment]
> @arfon do you think JOSS is by design for short papers?

Very much so, this is a deliberate decision (see http://joss.theoj.org/about#author_guidelines):

> - A list of the authors of the software
> - Author affiliations
> - A short summary describing the high-level functionality of the software
> - A list of key references including a link to the software archive

and...

> You can see an example paper here. Given this paper format it is _not_ permitted to write a "full length" paper i.e. one that includes software documentation such as API (Application Programming Interface) functionality, as this should instead be outlined in the software documentation.

As @danielskatz mentioned earlier in this thread, there are already a number of good options for publishing a 'full' paper about software. JOSS' focus is on short abstract/summary-style papers.

**Comment by labarba** [comment]
Another option for long-form papers is PeerJ CS. 
See, for example:
https://peerj.com/articles/cs-68/
