### ISSUE TITLE
Broken software archive link under article details

### ISSUE THREAD

**Issue by davem7** [openjournals/joss#401]
Clicking the "Software archive >>" link under the "Article details" section of a paper's page returns a 404 not found.  For example, on the page for the paper "[GeoStats.jl -- High-performance geostatistics in Julia](http://joss.theoj.org/papers/63d603dc7b9e9bd51a841864f4c8f4ff)" the link attempts to redirect to [http://joss.theoj.org/papers/"http://dx.doi.org/10.5281/zenodo.1228609"](http://joss.theoj.org/papers/%22http://dx.doi.org/10.5281/zenodo.1228609%22).  I believe it should be redirecting to the portion in quotes.

**Comment by lheagy** [comment]
@arfon, this seems to be affecting a few recent papers, eg
- http://joss.theoj.org/papers/58fed1624a37520d3f8eb40175dd40ae
- http://joss.theoj.org/papers/ad45003e0530e32579534b57322dd2f1

**Comment by arfon** [comment]
Thanks for spotting this. It's now fixed.
