### ISSUE TITLE
Interactive figures?

### ISSUE THREAD

**Issue by ngoldbaum** [openjournals/joss#407]
I'd like to include a javascript-powered web visualization along with my submission. Is that even remotely supported? I'm happy to convert it to a static image, but it would be a lot cooler as an interactive figure.

**Comment by arfon** [comment]
Hi @ngoldbaum - this isn't going to work very well sorry. The PDF is the only representation of the paper that we render these days so unless it works in a PDF (which I'm pretty sure it won't) then there's no-where that anyone would experience the interactivity in the paper.

**Comment by ngoldbaum** [comment]
Fair enough, thanks!
