### ISSUE TITLE
is it possible to embed mathmatics in paper.md?

### ISSUE THREAD

**Issue by moorepants** [openjournals/joss#409]
I've search github.com/openjournals for references on how to do so but have yet to find anything. Is it possible to include mathematics in the paper?

**Comment by Kevin-Mattheus-Moerman** [comment]
Not sure. Maybe through some html blocks. 

Also there is an "ugly" way to render latex equations through an external service e.g.:

```
![equation](http://latex.codecogs.com/gif.latex?%5Cfrac%7B%5Cpartial%5E2%20%7D%7B%5Cpartial%20x%5E2%7D%5Ciint_%7Ba%7D%5E%7Bb%7DA)  
```
Renders as:
![equation](http://latex.codecogs.com/gif.latex?%5Cfrac%7B%5Cpartial%5E2%20%7D%7B%5Cpartial%20x%5E2%7D%5Ciint_%7Ba%7D%5E%7Bb%7DA)  

See also: https://www.codecogs.com/eqnedit.php

https://github.com/STAT545-UBC/Discussion/issues/102

**Comment by moorepants** [comment]
Ok, that seems like it would work. Doesn't use the native math in the latex produced pdf, but works. Thanks.

**Comment by moorepants** [comment]
Oh yeah, my use can was inline math. So I'm not sure this would work well for that.

**Comment by Kevin-Mattheus-Moerman** [comment]
It seems like inline ![alpha=5](https://latex.codecogs.com/gif.latex?\inline&space;\alpha=5) would work ![beta=3](https://latex.codecogs.com/gif.latex?\inline&space;\beta=3) too as this equation clearly ![](https://latex.codecogs.com/gif.latex?\inline&space;\gamma=sin(\alpha)*\boldsymbol{q}^{2}&plus;\lim_{\beta\rightarrow&space;\infty&space;}) demonstrates. 

It seems you can use the [codecogs link](https://www.codecogs.com/eqnedit.php) to paste or type your equation. Then, as this screenshot shows you can either copy the link to the image or select in the dropdown window to get a link you can use in markdown. 
![screenshot from 2018-05-18 09-31-51](https://user-images.githubusercontent.com/8392709/40237485-9c95d4d6-5a7e-11e8-9648-e843f972d066.png)

It seems the if you copy the link to the image you can make something like:
```
![Awesome equation](https://latex.codecogs.com/gif.latex?%5Cinline%20%5Cgamma%3Dsin%28%5Calpha%29*%5Cboldsymbol%7Bq%7D%5E%7B2%7D+%5Clim_%7B%5Cbeta%5Crightarrow%20%5Cinfty%20%7D)
```
Which does not look like latex unfortunately (btw I changed the `git.download` part to `git.latex` to use it to render an image inline in markdwon). 

If you copy the URL that looks much more like the actual latex: 
```
![Awesome equation](https://latex.codecogs.com/gif.latex?\inline&space;\gamma=sin(\alpha)*\boldsymbol{q}^{2}&plus;\lim_{\beta\rightarrow&space;\infty&space;})
```

**Comment by moorepants** [comment]
Thank for the help. Hoping to submit a new paper later today and will try these out.

**Comment by arfon** [comment]
I think you should be able to just do whatever standard LaTeX in Pandoc maths looks like, e.g. https://stackoverflow.com/questions/25042901/how-to-use-latex-equation-environment-in-pandoc-markdown

We've definitely had people put (LaTeX) maths in submissions before. I'm just struggling to find an example...

**Comment by moorepants** [comment]
@arfon, your suggestion seems to work for full equations but that pandoc filter doesn't seem to have inline math notation. I'll look for other pandoc math filters.

**Comment by moorepants** [comment]
It looks like syntax like this will work:

```
my math expression is \(x^2\)
```

**Comment by pdebuyl** [comment]
For info, i use

`Dollars for inline math $f(x) = e^{\pi/x}$`

and

```
Double dollars make self-standing equations

$$\Theta(x) = \left\{\begin{array}{l}
0\textrm{ if } x < 0\cr
1\textrm{ else}
\end{array}\right.$$
```

with no problem.

**Comment by moorepants** [comment]
Yes, that seems to work with whedon. I couldn't get it to work locally, so I must have assumed it wouldn't work on whedon or somethings changed since then...

Thanks!

**Comment by pdebuyl** [comment]
@moorepants can the issue be closed?
