### ISSUE TITLE
Bibtex example next to published paper

### ISSUE THREAD

**Issue by pjotrp** [openjournals/joss#410]
It would be really nice if we show bibtex example (maybe as a fold-out or hover) on the left pane, e.g., for http://joss.theoj.org/papers/10.21105/joss.00025

```bibtex
@article{Sloan:2016,
  doi = {10.21105/joss.00025},
  url = {http://dx.doi.org/10.21105/joss.00025},
  year  = {2016},
  month = {jun},
  publisher = {The Open Journal},
  volume = {1},
  number = {2},
  pages = {25},
  author = {Sloan, Z. and Arends, D. and Broman, K. W. and Centeno, A. and Furlotte, N. and Nijveen, H. and Yan, L. and Zhou, X. and Williams,
R. W. and Prins, P.},
  title = {{GeneNetwork}: framework for web-based genetics},
  journal = {JOSS}
}
```

I believe it would encourage citations. Note the number and month are out of sync for this paper, see #124

**Comment by hbaniecki** [comment]
Hi @arfon,
I was wondering if a working `Copy BibTeX entry »` button is taken into consideration as a possible new enhancement. I think it would be a very useful functionality.
Is there a possibility for the author to add the `BibTeX entry` on his own?

**Comment by arfon** [comment]
Fixed in https://github.com/openjournals/joss/commit/98e8fd70a4394d97eda3fa879f0feddc7e8b574b
