### ISSUE TITLE
List editor and/or reviewer on paper

### ISSUE THREAD

**Issue by leeper** [openjournals/joss#411]
We've previously discussed how to give credit to reviewers. One way that some journals give credit is to list reviewers on the paper as metadata. Similarly, many journals with multiple editors list the managing editor on the paper for purposes of transparency. Perhaps we could do both?

**Comment by pdebuyl** [comment]
This is what @ReScience does :-) See an example: https://github.com/ReScience-Archives/Caze-Stimberg-Girard-2018/blob/master/article/Caze_2018.pdf

**Comment by arfon** [comment]
This is now captured (and displayed) on the paper view e.g. on https://joss.theoj.org/papers/10.21105/joss.01601:

<img width="1204" alt="Screen_Shot_2019-08-12_at_2_32_19_PM" src="https://user-images.githubusercontent.com/4483/62888839-233e7b80-bd0e-11e9-8b0d-486c02f2bde4.png">
