### ISSUE TITLE
JOSS pre-submission enquiry

### ISSUE THREAD

**Issue by suyashkumar** [openjournals/joss#412]
**Project repository URL:** https://github.com/suyashkumar/conduit

Conduit is an open-source web service and firmware library that allows users to securely control and interface with IoT devices (like the cheap [ESP8266](https://www.amazon.com/HiLetgo-Version-NodeMCU-Internet-Development/dp/B010O1G1ES/ref=sr_1_3?ie=UTF8&qid=1483953570&sr=8-3&keywords=nodemcu+esp8266)) via a centralized REST API from anywhere in the world. Traditional solutions (like running a server on the device itself) are difficult to configure and can require public static IP addresses or the use of closed source platforms. Such platforms like [particle](https://www.particle.io/) are not conducive for use in protected environments like research or hospital networks. Moreover, interfacing with fleets of devices becomes troublesome when each device is its own independent server.

The goal is that Conduit will make it easy for researchers to build IoT devices for research done in protected environments (like behind hospital networks where personal health information can't be leaked) because it is fully open-source and auditable unlike particle. Instances of Conduit can easily be deployed behind private networks or on private servers. Some examples of this particular type of research include:
* Bedside patient monitors 
* Home healthcare monitoring and interventions (triggering alarms, opening pill bottles, etc)
* Handheld medical devices 
* DoD drone research

Of course, the usefulness of this library extends beyond protected research use cases as it makes it very easy to build end-to-end IoT solutions with fleets of devices to collect data or to trigger firmware actions over the internet. 

I was wondering if something like Conduit would be a good candidate for publication in JOSS? There are still some improvements I would add before submission, but I was curious if something like this fits into what JOSS is looking for. 

Thanks!

**Comment by suyashkumar** [comment]
@labarba @jedbrown would y'all be able to provide some "off the top of your head" guidance as to whether or not software like the above would be appropriate for JOSS given your thesis? I understand that you're typically looking for research/scientific software packages, and since this is a bit different I wanted to ask.

Thanks!

**Comment by jedbrown** [comment]
> JOSS publishes articles about research software. This definition includes software that: solves complex modeling problems in a scientific context (physics, mathematics, biology, medicine, social science, neuroscience, engineering); supports the functioning of research instruments or the execution of research experiments; extracts knowledge from large data sets; offers a mathematical library, or similar. (http://joss.theoj.org/about#submission_requirements)

From the description, I think this is responsive to "supports the functioning of research instruments or the execution of research experiments" in the sense of research in cyber-physical systems. I think this should be within scope, though we may need to find a CPS editor if we get more submissions in this area.

**Comment by labarba** [comment]
Perhaps the key question is whether the software has been or us being used in any ongoing research project.

**Comment by suyashkumar** [comment]
@labarba @jedbrown Thanks for the responses and the insight! Indeed I was thinking this would fall under "[supporting] the functioning of research instruments or the execution of research experiments," but figured I'd get your thoughts as I know this isn't a typical research software package. By the way, if you all ever do need an additional reviewer in the Biomedical Engineering or Computer Science area for other submissions, happy to toss my hat (and time) into the ring (I have extensive experience reviewing software architecture and code in industry, and on the academic side have reviewed for IEEE Transactions on Medical Imaging).

Now that the library exists in a functional form, there are a couple projects interested in leveraging it for their research at Duke--one potential use case is a project that collects accelerometer and biometric data from football players to study head injury and another is [a sanitation project](https://github.com/mlp6/ADPL) that currently uses particle to monitor and control anaerobic digestion of waste at sites all over the world (among other interested projects). Whether through JOSS or otherwise, I hope that sharing and communicating this library more widely may help other research projects leverage cloud connectivity without the usual hassle.

Not sure if this is relevant in the case of JOSS, but there are other student design projects in Biomedical Engineering at Duke that are using or hoping to use conduit (a cloud connected respiratory training device will be using conduit this year, for one). 

So it seems that given some more active research/project use cases spun up, a library like this may be a good fit for JOSS. I'm a big fan of open source and am pretty excited to have stumbled across a developer-friendly research journal like JOSS, particularly for some more typical research software that I expect to be working on this year. 

Thanks!

**Comment by jedbrown** [comment]
I agree with the above -- it will be a better submission with some active research to point to. It sounds like your internal (and external?) research user base are coalescing and the package may be almost there. Please submit when you think it's ready. Are you okay closing this issue for now?

And thanks for volunteering to review! Please [sign up here](http://joss.theoj.org/reviewer-signup.html).

**Comment by suyashkumar** [comment]
@jedbrown Yep exactly, and sounds good! Feel free to close this out for now. And thanks for the sign up link, I'll go ahead and sign up :).
