### ISSUE TITLE
Update reviewer instructions to say what to do after completing checklist

### ISSUE THREAD

**Issue by leeper** [openjournals/joss#413]
Can we update the reviewer instructions to say "Message {editor} when you've completed your initial review."? At the moment, it's not clear from the instructions what reviewers are supposed to do once they run through the checklist.

**Comment by danielskatz** [comment]
Or maybe just "When you have completed your review, please leave a comment in the issue saying so"?

**Comment by leeper** [comment]
That would be perfect.

**Comment by arfon** [comment]
> Or maybe just "When you have completed your review, please leave a comment in the issue saying so"?

Sounds good to me. @leeper - would you be able to open a PR with this change?
