### ISSUE TITLE
JOSS pre-submission enquiry

### ISSUE THREAD

**Issue by marshki** [openjournals/joss#414]
[matlab_installer](https://github.com/marshki/matlab_installer)

Bash script to retrieve, install, and symlink various versions of [Matlab](https://www.mathworks.com/products/matlab.html) in both OS X and Debian-based versions of Linux. 

While Matlab is proprietary, the process for deploying it doesn't have to be.  This script automates the boring part of an install so that system administrators and researchers can free up valuable time. Suitable for single- and mult-node environments. 

Would something like this be suitable for your journal?

**Comment by Kevin-Mattheus-Moerman** [comment]
Although this software seems really useful I unfortunately I agree with @labarba in that it does not seem to have a research application. It seems unlikely that people would feel the need to cite this package as it may not influence the science they are doing.

**Comment by marshki** [comment]
Thanks for the clarification.
