### ISSUE TITLE
JOSS pre-submission enquiry

### ISSUE THREAD

**Issue by douglaslyon** [openjournals/joss#415]
**Project repository URL:** INSERT YOUR REPOSITORY LINK HERE

Hi All,
We are interested in the problem of source code minimization when deploying large projects that only require a small subset of source files for compilation. Our new system does a static dependency analysis that enables the output of a Java project with a subset of only required jar files in order to compile and run the software. Dynamic loading considerations are left as a topic of future research. We have a solution to the problem now.

Would this be of interest to your journal?
Thanks!
 - Doug

**Comment by jedbrown** [comment]
Do you think it fits the criteria in http://joss.theoj.org/about#submission_requirements, especially these?
* Your software should have an *obvious* research application
* Should be a significant contribution to the available open source software that either enables some new research challenges to be addressed or makes addressing research challenges significantly better (e.g., faster, easier, simpler)
* Should be feature complete (no half-baked solutions)
* Minor, 'utility' packages, including 'thin' API clients are not acceptable

**Comment by douglaslyon** [comment]
Hi Jed,
How can I tell if my research application is "obvious"?
What is the criterion of obviousness?
Thanks!
  - Doug

**Comment by kyleniemeyer** [comment]
@douglaslyon It just means that it should be obvious (to us) that the software relates to or supports scientific/engineering/academic research

**Comment by labarba** [comment]
From your description, it sounds like you have a general-purpose tool for dependency analysis for software projects, with the purpose of reducing bloat at deployment/installation. Is this being used in the context of a scientific software library somewhere?

**Comment by douglaslyon** [comment]
Hi Kyle,
It sounds like you will know it when you see it.

  - Doug


"The first question I ask myself when something doesn't seem to be 
beautiful is why do I think it's not beautiful. And very shortly you 
discover that there is no reason." - John Cage

**Comment by douglaslyon** [comment]
Hi Lorena,
Yes, it is the next step in project Initium. The problem is
one of deployment and configuration.
See below.

Thanks!
  - Doug


[Lyon 08D] "I Resign! Resigning Jar Files with Initium",by Douglas A. 
Lyon, Journal of Object Technology, vol. 7, no. 4, April-May 2008, pp. 9-27
[Lyon 04E] "The Initium X.509 Certificate Wizard" by Douglas A. Lyon, 
Journal of Object Technology, vol. 3, no. 10, November-December 2004, 
pp. 75-88

[Lyon 04D] "Project Initium: Programmatic Deployment" by Douglas A. 
Lyon, Journal of Object Technology, vol. 3, no. 8, September-October 
2004, pp. 55-69

**Comment by douglaslyon** [comment]
Are you interested in publishing about software tools?

**Comment by arfon** [comment]
Closing as stale.
