### ISSUE TITLE
Contact information.

### ISSUE THREAD

**Issue by jfjlaros** [openjournals/joss#425]
I am quite sure this is not the proper channel, but I could not find any contact information online.

I would like to make a donation via my institute, for which I need some information like a bank account number, address, etc. Would it be possible to share this information, or is Flipcause the only way to donate?

**Comment by labarba** [comment]
Thank you! JOSS receives donations through NumFOCUS, the 501(c)(3) that is fiscal sponsor of The Open Journals (parent of JOSS).

https://www.numfocus.org/project/open-journals

**Comment by kyleniemeyer** [comment]
@jfjlaros I'll second those thanks!

If you cannot donate through the Flipcause link for Open Journals (https://www.flipcause.com/secure/cause_pdetails/MjA4Mzk=) for some reason, then [Leah Silen](mailto:leah@numfocus.org) (Executive Director of NumFOCUS) would be the appropriate person to contact.

**Comment by jfjlaros** [comment]
Thanks for your quick reply. I will ask them again to use Flipcause, if that fails, I will contact Leah Silen.
