### ISSUE TITLE
How can I request to be removed from reviewer list?

### ISSUE THREAD

**Issue by fritzo** [openjournals/joss#429]
It's a great idea to review open source code, but I've become swamped reviewing specific projects. How can I opt-out of further JOSS review requests?

[Here](https://docs.google.com/spreadsheets/d/1PAPRJ63yq9aPC1COLjaQp8mHmEq3rZUzwUYxTulyu78/edit#gid=856801822) is a spreadsheet of reviewers. I cannot edit or comment on it and cannot determine its owner.

Thanks!

**Comment by karthik** [comment]
Hi Fritz,
I removed your record.
