### ISSUE TITLE
Please reconsider government software released in the "public domain" 

### ISSUE THREAD

**Issue by guyer** [openjournals/joss#430]
I realize this topic has been discussed before (#179, #394, openjournals/joss-reviews#559) and that there is, unfortunately, not consistency across US Federal agencies. The legal counsel for my agency is nonetheless explicit that our works are not subject to copyright and are to be released to the public domain. Despite what @ianhbell was apparently told, there is no formal guidance from the lawyers at our agency (we work for the same one) that permits releasing software under a license that asserts copyright (and certainly not the patent absurdity of assigning copyright to our Cabinet Secretary).

The [OSI FAQ](https://opensource.org/faq#public-domain) acknowledges this situation and that "that such software is effectively open source":

> There are certain circumstances, such as with U.S. government works as described above, where it is not easy to apply a license, and the software must be released into the public domain. In these cases, while it would be inaccurate to display the OSI logo or say that the license is OSI-approved (since there is no license), nevertheless we think it is accurate to say that such software is effectively open source, or open source for most practical purposes, even though it is not officially released under an open source license. (This is assuming, of course, that in the laws of releasing jurisdiction the meaning of "public domain" is compatible with the Open Source Definition.) After all, the freedoms guaranteed by open source licenses are still present, and it is possible for the familiar dynamics of open source collaboration to arise around the software.

I believe that the United States is not the only government that waives copyright restrictions for the works of their employees.

**Comment by arfon** [comment]
Hi @guyer, I've followed up privately in email to see if we can make some progress here...
