### ISSUE TITLE
Display ORCiD logo/links?

### ISSUE THREAD

**Issue by leeper** [openjournals/joss#434]
Given we capture ORCiD for authors, should we add ORCiD links on papers and on paper HTML pages? Seems lots of other journals are doing this.

**Comment by arfon** [comment]
These are now visible on the `paper#show` pages, e.g. https://joss.theoj.org/papers/10.21105/joss.01601 :

<img width="1204" alt="Screen_Shot_2019-08-12_at_2_32_19_PM" src="https://user-images.githubusercontent.com/4483/62888911-4d903900-bd0e-11e9-9bf9-1143509e5eda.png">
