### ISSUE TITLE
Broken Zenodo links

### ISSUE THREAD

**Issue by TimSmithCH** [openjournals/joss#435]
On the home page (https://joss.theoj.org) links to the Zenodo archive version of the paper/code contain quote characters and so lead to 404s, for example the first in the list currently is:
`<a target="_blank" class="doi" href="&quot;https://doi.org/10.5281/zenodo.1341034&quot;">10.5281/zenodo.1341034</a> `
which renders as:
https://joss.theoj.org/%22https://doi.org/10.5281/zenodo.1341034%22

It seems to be wrong for papers accepted after July 5th, which means it might be related to this change, I guess: https://github.com/openjournals/whedon-api/commit/3d0574b72663f7379add1e03e79849f3e26f8e0f

**Comment by arfon** [comment]
> It seems to be wrong for papers accepted after July 5th, which means it might be related to this change, I guess: openjournals/whedon-api@3d0574b

Could you link to an example of a paper that has this problem @TimSmithCH. Many of the most recent ones _don't_ have this problem as far as I can tell.

**Comment by TimSmithCH** [comment]
@arfon As far as I can see it is every link on the home page! I've screenshotted the first one for illustration, and annotated it, showing that if you hover over the Zenodo link it points to an unresolvable local URL:

![screen shot 2018-08-19 at 13 45 15](https://user-images.githubusercontent.com/7299592/44308496-55492600-a3b7-11e8-982b-c4d93b6a7389.png)

**Comment by arfon** [comment]
Ahhh, thanks @TimSmithCH. I thought you meant the links on the individual paper pages. I've gone ahead and fixed this and the change is live.

**Comment by TimSmithCH** [comment]
Excellent thanks - indeed all looks fine again now
