### ISSUE TITLE
Building an editor dashboard

### ISSUE THREAD

**Issue by arfon** [openjournals/joss#437]
I've been thinking a lot about the workload associated with being a JOSS editor recently and I think it might be time to think about building a small amount of additional tooling to help reduce the noise (email, GitHub notifications) associated with this role.

I'm proposing we build some kind of dashboard that essentially offers editors a (near) realtime view on the papers they are editing. The basic idea would be to have (on the JOSS website somewhere), a dashboard that shows information like this: 

![img_0457](https://user-images.githubusercontent.com/4483/44229079-f42a1400-a164-11e8-99e5-7ac2a677bf81.jpg)

The idea being, that this UI would become the go-to place for a JOSS editor to take a quick look at the papers they were handing, when they were last commented on, how long the review was taking etc. The goal of building this would be that JOSS editors wouldn't necessarily have to trawl through all of their GitHub notifications (or emails) to get a quick overview of their papers.

Some questions:

- Is this interesting to you all @openjournals/joss-editors  @openjournals/jose-editors 
- What else would you want to see on this screen? I don't want to try and rebuild GitHub views on this dashboard but there might be obvious things I've missed here
- Who else would benefit from this? Would it make sense to have the equivalent view for the reviewers and authors?

**Comment by kyleniemeyer** [comment]
This sounds great! The reminder emails are already helpful, but it would be nice to have a real-time site we can check. 

Also, it would be nice if it included a historical view of our editing assignments, so we can keep track of what we've done in the past.

**Comment by lheagy** [comment]
Would it be useful to have the list of current submissions without an editor beneath this? (similar to that sent in the email)

**Comment by arokem** [comment]
This would indeed provide some additional convenience. I think that I can already see a lot of this information by searching on my user-name in the open issues.

**Comment by danielskatz** [comment]
Also in the dashboard for a paper:
reviewer NAME: x of 18 checkmarks, last comment X days ago

**Comment by karthik** [comment]
I love the idea of a dashboard! As @arokem and @leeper note, one can easily see what they have been assigned by bookmarking links with filters. But that's not the only functionality we would get from a dashboard.

It would be good to see:
- Overdue reviews highlighted (maybe getting darker with age) as a reminder for the editor to check in.
- Help with reviewer assignment. Maybe one could search by real name, username, topic area to find people to assign. If the dashboard could email them as well, that would be sweet.
- Would it be too much to look at reviewer stats? How often someone has been assigned, how often they were late or went awol etc.
- Love Kyle's idea of editor history.
- Love Dan's suggestion for checkmark progress

As a point of inspiration check out this real time dashboard that Rstudio's tidyverse team uses: https://connect.rstudioservices.com/jimhester/tidyverse_dashboard/tidyverse_dashboard.html#days-issue-progress. It is obviously designed for tracking software issues but we could have views by editor, a reviewer search tab, stats on submission types/review times etc.

**Comment by brainstorm** [comment]
Sounds like http://waffle.io -like services.

Den fre 17 aug. 2018 07:29Karthik Ram <notifications@github.com> skrev:

**Comment by tracykteal** [comment]
I also like the idea of a dashboard. It seems like it would also help with transparency for the journal, so authors and the Editor-in-chief could easily see the status of all the papers. As @danielskatz suggests it would also be nice if it could send out reminders.

**Comment by brainstorm** [comment]
This issue should be done, right?: http://joss.theoj.org/dashboard/<github_user>

Thanks Arfon for it, quite handy 👍

**Comment by danielskatz** [comment]
It's done, but some bugs remain, eg 
1. https://github.com/openjournals/joss/issues/468
1. the fact that the stats page/tab shows the second part (Accepted papers per month by editor) with a pulldown menu set to the logged-in editor, but the graph below for @arfon - to get to the editor shown, you have to select another editor, then go back to the first editor - I guess I should make an issue for this, since this was just in an email thread - I've now done so as https://github.com/openjournals/joss/issues/478
1. I wonder if we should tie this to https://github.com/openjournals/joss/issues/232 as well?

Are there more issues? And does closing this depend on fixing them, or is it independent?
