### ISSUE TITLE
Odd page number rendering in PDF

### ISSUE THREAD

**Issue by moorepants** [openjournals/joss#440]
I just noticed that the "818" has a character overlayed on it on each page of a paper of mine:
![selection_234](https://user-images.githubusercontent.com/276007/44356070-27b9b680-a463-11e8-9442-6dee8246fa0c.png)
This doesn't look correct.
Paper: http://joss.theoj.org/papers/10.21105/joss.00818

**Comment by Kevin-Mattheus-Moerman** [comment]
@arfon it looks like page numbers intersect with the paper foot note.

**Comment by arfon** [comment]
Yeah, this is an issue with the latex template. If anyone has the time and
expertise to look into this I'd be very grateful. I unfortunate have
neither :-(

**Comment by Kevin-Mattheus-Moerman** [comment]
@arfon can you point me to where (e.g. what file?) this change would need to be made?
