### ISSUE TITLE
Mention COI policy on docs site?

### ISSUE THREAD

**Issue by leeper** [openjournals/joss#444]
Currently it's only here: https://github.com/openjournals/joss/blob/master/COI.md

**Comment by arfon** [comment]
:+1: sounds like a good idea to me. Can I convince you to open a pull request with this change 😬, the relevant content for the docs site is here: https://github.com/openjournals/joss/tree/master/docs

**Comment by arfon** [comment]
It's there now: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html#joss-conflict-of-interest-policy
