### ISSUE TITLE
Presubmission enquiry: WordTokenizers.jl

### ISSUE THREAD

**Issue by oxinabox** [openjournals/joss#445]
Hi,
I have begun preparing a paper on some NLP tokenizers I have been preparing for julia.
https://github.com/JuliaText/WordTokenizers.jl

WIP paper is at https://github.com/JuliaText/WordTokenizers.jl/pull/7

On further reflection I think it might fall a foul of 

 > Minor, ‘utility’ packages, including ‘thin’ API clients are not acceptable

However, it is unclear to me for sure.
There is perhaps a fine line between foundational tools required for research,
and ‘utility’ packages.
I suspect this falls on the wrong side,
being that it is just ports of existing algorithms.

**Comment by arfon** [comment]
Closing as this looks to be under review: https://github.com/openjournals/joss-reviews/issues/1956
