### ISSUE TITLE
Presubmission enquiry: MultiResolutionIterators.jl

### ISSUE THREAD

**Issue by oxinabox** [openjournals/joss#446]
Hi,
I am considering preparing a submission on 
https://github.com/oxinabox/MultiResolutionIterators.jl

It is, in short,  a tool to help natural language processing, information retrieval, 
and corpus linguistics researchers manipulate corpus data.
Which is naturally high in structure.
Being a Corpus of Documents, of Sections, of Paraphrase, of Sentences, of Words, of Characters.
The package allows for the easy discarding of structure that is not wanted.
So that that highly structures corpus could be converted into a Corpus of Documents of Words (Use ful for information retrieval),
or just a stream of characters (useful for training a char-RNN).
It is basically an extension of various functions that are commonly used on iterators (map, flatten etc) 
to be able to take into account level in a nested iterator.

I think it might fall a foul of 

> Minor, ‘utility’ packages, including ‘thin’ API clients are not acceptable

However, it is unclear to me for sure.  
It is a vexing problem in my research area; and so I created a utility package to deal with it.
It is only really a pragmatic problem.
Without this package software can still be written to accomplish the same thing.
It is just more ad-hoc.

**Comment by arfon** [comment]
Hi @oxinabox, apologies for the _very_ slow response here. I think `MultiResolutionIterators.jl` would fall under the minor utility category for us sorry.

**Comment by oxinabox** [comment]
no problem.
