### ISSUE TITLE
Presubmission inquiry: Open source dependencies with account requirements (e.g., Google Earth Engine)

### ISSUE THREAD

**Issue by rmsare-lanl** [openjournals/joss#447]
Hi,

We are developing a package for segmenting active river channels in satellite imagery, a common task in fluvial geomorphology. It would be nice to submit it to JOSS so others could use it or make contributions like extending to different imaging platforms or landforms.

It is open source but relies heavily on the [Google Earth Engine API](https://github.com/google/earthengine-api), which requires the user to sign up for an account and authenticate. The API is open source (Apache 2.0 license). The server-side algorithms are not, but many of them re-implement open source or published methods (e.g., [perceptron](https://developers.google.com/earth-engine/api_docs#eeclassifierperceptron)).

Would either of the following guidelines make this ineligible for consideration?

> Minor, ‘utility’ packages, including ‘thin’ API clients are not acceptable

The package is not just a GEE wrapper, but re-implementing the functionality without GEE would seriously limit data access and scalability. That said, it could be done with sklearn, skimage, and public datasets only.

> We strongly prefer software that doesn’t rely upon proprietary (paid for) development environments/programming languages. However, provided your submission meets our submission requirements (including having a valid open source license) then we will consider your submission for review.

GEE is not currently a paid service, but this package requires the use of Google compute resources that may not always be free. 

Thanks!

(Originally emailed to @kthyng. Related to #350.)

**Comment by kthyng** [comment]
Based on input from others (@karthik and @Kevin-Mattheus-Moerman), needing to have a user account seems like a common case that is reasonable as a requirement for your submission. So, go ahead and submit!

**Comment by rmsare-lanl** [comment]
Thanks all! 

Looking forward to submitting soon. It will have to go through a national lab approval process first so there will be some delay there.

**Comment by kthyng** [comment]
Ok sounds good.
