### ISSUE TITLE
JOSS/JOSE UI improvements

### ISSUE THREAD

**Issue by arfon** [openjournals/joss#449]
:wave: @andyhulme. As we discussed last week I'd like to do a refresh of the JOSS site. The current layout is looking a little dated and I'd like to update it. As discussed, here are some areas I think we could improve the design:

### Home page

- Visible at http://joss.theoj.org/
- The Header is unnecessarily large
- The styling of the list of accepted papers is kind of janky
- I'm not in love with the font we're using next to the logo
- The footer is too crowded (although we want to keep this content)

![header](https://user-images.githubusercontent.com/4483/45254122-7fe82800-b340-11e8-9559-1acf45d8207c.png)
![footer](https://user-images.githubusercontent.com/4483/45254121-7fe82800-b340-11e8-9774-da7b734ccc95.png)

### Dashboard views

We're currently building out some new views for editors to view their activity across the site. Below are some screenshots of the current views.

This whole section could do with some TLC (currently it's completely un-styled) and general thought about what the layout should be for this section of the site.

![screen shot 2018-09-08 at 8 18 42 am](https://user-images.githubusercontent.com/4483/45254119-7bbc0a80-b340-11e8-945e-c8fc59798ce7.png)
![screen shot 2018-09-08 at 8 18 45 am](https://user-images.githubusercontent.com/4483/45254120-7bbc0a80-b340-11e8-96fc-8980a76ef908.png)

### Paper view

- This screen is basically an embed of the PDF in the browser together with some metadata associated with the paper. I'm generally happy with this screen but would be open to suggestions.

![screen shot 2018-09-08 at 8 28 59 am](https://user-images.githubusercontent.com/4483/45254146-47951980-b341-11e8-8207-c99b52293185.png)

### Search UI

Over in https://github.com/openjournals/joss/pull/369, @parrish is working on a search UI for JOSS. With ~400 papers, we need to build some new views to allow people to search/filter papers in JOSS. These views currently don't exist.

As you can see [in this example paper](https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography), we have the paper contents (i.e. what people wrote), the title, authors, and some basic tags/keywords. I think we want to make it possible for users to search all of those fields.

## How this could work

I realize Ruby/Rails might not be your thing so I'm happy to scope this work to you delivering either:

- Designs in PDF/PNG/Photoshop + basic CSS styles for fonts, general layout etc.
- Static HTML templates with HTML/CSS/images that I can then port to Rails views

Of course, if you'd like to run the app and make changes then be my guest but I suspect this isn't a great use of your time.

Also, please use a CSS framework such as Bootstrap or [GitHub's primer](https://primer.github.io/) as your base set of UI components/layouts etc. so that we can use their defaults (with your extensions). That way, we can minimize the custom CSS etc.

**Comment by Benjamin-Lee** [comment]
This is semi-UI related, but a per-section RSS feed would be highly appreciated, including submissions pending review (so I can volunteer!).

**Comment by arfon** [comment]
> This is semi-UI related, but a per-section RSS feed would be highly appreciated, including submissions pending review (so I can volunteer!).

These already exist, they're just not linked to:
- Active papers (i.e. submitted, under review): http://joss.theoj.org/papers/active.atom
- Accepted papers: http://joss.theoj.org/papers/accepted.atom

I should link to these from the UI and in the metadata tags so these are more discoverable...

**Comment by arfon** [comment]
Mostly addressed in the latest UI updates.
