### ISSUE TITLE
Add metadata to journal entries for preview

### ISSUE THREAD

**Issue by Spaxe** [openjournals/joss#450]
Hi! This looks like a very cool journal, and I am interested to contribute. I am opening this issue to remind myself that I need to make a PR for this, if someone doesn't beat me to it.

**The problem:** When linking a journal paper online (e.g. Slack, Twitter, Facebook), their web crawler is not able to recognise individual pages and show the correct preview. Namely, you get this:

<img width="526" alt="screen shot 2018-09-13 at 22 36 45" src="https://user-images.githubusercontent.com/708395/45488755-afb28800-b7a5-11e8-9033-52d52b1ba91d.png">

**Expected results:** When I link a journal paper, I expect to see the title of the paper in the link preview, a brief description of the paper (can be authors or abstract, or at least words that relate to the paper) in the excerpt, and a preview picture that isn't the journal's own logo.

This has a profound impact on how journal papers are shared on the internet, especially in the age of social media.

For example, the screenshot above would benefit a lot if it had said:
```
**jstor: Import and Analyse Data from Scientific Texts**
Klebel, (2018). jstor: Import and Analyse Data from Scientific Texts . Journal of Open Source Software, 3(28), 883, https://doi.org/10.21105/joss.00883
```

**Proposed solution:** There is already a decade-old standard called OpenGraph (http://ogp.me/). It is supported by nearly all major user-created content platforms and social media platforms. Even chat clients like Telegram understands how to parse it. 

Essentially, each journal paper webpage needs to have additional `<meta>` tags that describes itself. This needs to be done on the server side, as web spiders do not have the luxury to run Javascript. 

I am currently writing my thesis due end of the month, and I hope not to extend it. After that, I should have some time to look at this issue and make a PR!

**Comment by arfon** [comment]
@Spaxe - I took a pass at fixing this in https://github.com/openjournals/joss/pull/451
