### ISSUE TITLE
Broken link on JOSS

### ISSUE THREAD

**Issue by Benjamin-Lee** [openjournals/joss#454]
For "[graynet: single-subject morphometric networks for neuroscience connectivity applications](http://joss.theoj.org/papers/abddd873e5bd22e4bf0124d2778878f4)", it appears that the link to repo is broken:

http://joss.theoj.org/papers/github.com/raamana/graynet

Rather than:

http://github.com/raamana/graynet

**Comment by arfon** [comment]
Thanks for spotting this @Benjamin-Lee.
