### ISSUE TITLE
Support for embedded video?

### ISSUE THREAD

**Issue by TheChymera** [openjournals/joss#457]
I remember the JOSS motto being something along the lines of “the software (including the documentation) is the publication”, and as such a persistent archive of the versioned paper being associated with the DOI.

I would be interested in submitting a package which deals with an embedded system (hardware + software) and the documentation of which linkes a video walking the user through the hardware assembly. Obviously this is not tracked in Git alongside the rest of the documentation. I could just drop it into the archive, but unlike software, I guess people expect to access videos easier than unarchiving a container and looking inside it for a video file.

Do you have any suggestions regarding how to best handle this?

**Comment by danielskatz** [comment]
You could publish the video to somewhere archives, such as figshare, and then just provide a DOI to the video as part of the documentation

**Comment by TheChymera** [comment]
@danielskatz thank you. Is there any way to embed the video in the JOSS abstract page or link it directly from there? Like from the “Article Details” section, or from the part of the title which refers to hardware? I think it would be very helpful for potential users to see that even though the software is for an embedded system the documentation really comes with “batteries included”.

**Comment by danielskatz** [comment]
👋 JOSS-editors - maybe someone else knows about embedding video?

**Comment by arfon** [comment]
> Like from the “Article Details” section, or from the part of the title which refers to hardware? I think it would be very helpful for potential users to see that even though the software is for an embedded system the documentation really comes with “batteries included”.

I can't immediately think of a straightforward way to do this sorry.
