### ISSUE TITLE
JOSS logo

### ISSUE THREAD

**Issue by Kevin-Mattheus-Moerman** [openjournals/joss#46]
![joss_logo](https://cloud.githubusercontent.com/assets/8392709/14715663/918f9cfa-07b7-11e6-9706-77c13eabbe25.png)
![joss_logo1](https://cloud.githubusercontent.com/assets/8392709/14715664/91904362-07b7-11e6-9190-6228e3532e05.png)

**Comment by prisae** [comment]
Question @Kevin-Mattheus-Moerman - is the code to generate the logo, in true JOSS-spirit, open-source? I think it would be awesome if it was, together with your explanation. Should be somewhere in the docs or similar, I am pretty sure I am not the only one asking myself about the JOSS-logo.

**Comment by Kevin-Mattheus-Moerman** [comment]
@prisae thanks for expressing an interest in the logo source. The logo was coded using MATLAB in my open source ([GNU General Public License v3.0](https://github.com/gibbonCode/GIBBON/blob/master/LICENSE)) toolbox [GIBBON](https://github.com/gibbonCode/GIBBON). The code is now part of the demo [`DEMO_JOSS_logo`](https://www.gibboncode.org/html/DEMO_JOSS_logo.html). 

Side notes. The GIBBON project is being translated into a Julia package as well. This would remove the dependency on an non-open source environment like MATLAB. An octave translation would also be easy. 

@arfon if we wanted to add this link to the logo source code anywhere, where would we put it? 
https://github.com/gibbonCode/GIBBON/blob/master/docs/DEMO_JOSS_logo.m

**Comment by prisae** [comment]
Thanks for the info @Kevin-Mattheus-Moerman , very interesting your package! I think it would be great if the link to the source of the logo (and the info what it is) could be found somewhere in the docs.

**Comment by danielskatz** [comment]
There is a joss logos repo - why not put it there?
And for @arfon - can you put the current sticker there too? (The one there is an old version)

**Comment by prisae** [comment]
I don't think this is easy discoverable. I searched for it within https://github.com/openjournals , but did not find this within reasonable time. This is why I personally think it would be nice to have it documented (a link) in a more prominent place within the documentation.

**Comment by danielskatz** [comment]
There are two issues here - one is what's in this place, and another is a link to this place.
@Kevin-Mattheus-Moerman and @arfon might add content (source for making the logo, current sticker image).
@prisae - perhaps you want to suggest where this should go in the JOSS docs via a PR?

**Comment by prisae** [comment]
One place I could think of is http://joss.theoj.org/about, after or before "Any use of the JOSS logo is licensed CC BY 4.0.".

If that sounds plausible I'll create a PR.

**Comment by prisae** [comment]
"Any use of the JOSS logo is licensed CC BY 4.0. See the logo directory in the [digital-assets](https://github.com/openjournals/digital-assets)-repository for more information about it."

And then rewrite the following info and put it into https://github.com/openjournals/digital-assets/tree/master/joss/logo/README.md

> The logo was coded using MATLAB in my open source (GNU General Public License v3.0) toolbox GIBBON. The code is now part of the demo DEMO_JOSS_logo.

> Side notes. The GIBBON project is being translated into a Julia package as well. This would remove the dependency on a non-open source environment like MATLAB. An octave translation would also be easy.

> Thanks. It is a long story :) I thought the logo would need to look like it requires a code to make so I coded it using my toolbox (I use models like this as test shapes but they look like they make good logos). The inner grey shape stems from a spherical Buckminster-Fuller dome with radii altered according to the distance with the vertices of an icosahedron, followed by Laplacian smoothing. The result looks like a smooth stellation of a dodecahedron (the dual of the icosahedron). The blue shape wrapped around the grey shape is a skeleton of a dodecahedron. So where the grey shape has protrusions the other has holes. One has icosahedral symmetry the other dodecahedral symmetry. Also the inner mesh consisting of pentagons and hexagons is dual to a triangulation which is the outer mesh. I centred the view on one of the inner pentagons which is echoed by the outer pentagon surrounding it. So there is lots of interesting geometrical symmetry/duality going on. Also the grey and blue colors are based on the current website colors.

As I said, I can create a PR for the first part, but I guess the second part is best done by @Kevin-Mattheus-Moerman
