### ISSUE TITLE
Removing an assigned reviewer

### ISSUE THREAD

**Issue by cMadan** [openjournals/joss#464]
I have a submission that has multiple reviewers assigned, two of which have nearly completed the review, but a third hasn't started. I'm inclined to remove that third reviewer and move ahead, but I'm not sure if whedon can ***safely*** do this for me. I.e., I'm worried that whedon might accidentally lose the reviewer responses from the other two, so I thought I'd check if this feature has been tested and is safe, before trying it myself.

For reference, this is the review in question, https://github.com/openjournals/joss-reviews/issues/862/.

**Comment by arfon** [comment]
@cMadan - you can just type `@whedon remove xxxx as review`, _I think_. If you want to be safe, edit the issue and copy the issue text before issuing the Whedon command. That way if something goes really wrong, you can just paste the contents of the top of the issue back in again.

**Comment by cMadan** [comment]
Fyi. I just tried this and it partially worked.

Nothing went wrong, but `@whedon` didn't remove the reviewer checklist. This might be good a safety precaution and doesn't necessarily need to be fixed though.

**Comment by arfon** [comment]
> Nothing went wrong, but @whedon didn't remove the reviewer checklist. 

OK thanks. The `remove` is mostly designed for a issues in the `pre-review` state (when there's no checklist) so that makes sense.

> This might be good a safety precaution and doesn't necessarily need to be fixed though.

:+1: I think I agree.
