### ISSUE TITLE
whedon does not pick up specified branch

### ISSUE THREAD

**Issue by dzhoshkun** [openjournals/joss#471]
whedon does not seem to pick up the specified branch.
`@whedon generate pdf` and `@whedon generate pdf from branch this-branch-does-not-exist` seem to be equivalent.

Related:
* https://github.com/openjournals/joss-reviews/issues/1104#issuecomment-444090707
* https://github.com/gift-surg/Xono2L/pull/21

**Comment by arfon** [comment]
Thanks for reporting this @dzhoshkun. This was fixed in https://github.com/openjournals/whedon/commit/01ece1d1d135eb8993fb6422ccaa96a056d4a7d5
