### ISSUE TITLE
Updating editor list and properties

### ISSUE THREAD

**Issue by Kevin-Mattheus-Moerman** [openjournals/joss#480]
@arfon I tried updating the [`seeds.rb`](https://github.com/openjournals/joss/blob/master/db/seeds.rb) to fix and update my entry for the editor list. The website does not seem to have updated. Should I make the changes elsewhere? Should I be more patient and wait for the website to update?

**Comment by arfon** [comment]
Ah, this isn't used after the initial import of this data @Kevin-Mattheus-Moerman - apologies for any confusion caused. I've made the updates you made in your change to this file.

**Comment by Kevin-Mattheus-Moerman** [comment]
Thanks. What is the process for altering editor list data in the future? Does one update the `seeds.rb` file and ping you?

**Comment by arfon** [comment]
Yes, that works.
