### ISSUE TITLE
Web view: show paper titles, instead of repo?

### ISSUE THREAD

**Issue by labarba** [openjournals/joss#482]
Might it be a better-looking and more friendly view to show paper titles on the main JOSS page, instead of repo names?

![screen shot 2019-01-09 at 9 20 12 am](https://user-images.githubusercontent.com/4800109/50899148-12343180-13f0-11e9-805e-0e3c15518309.png)

**Comment by jedbrown** [comment]
Titles are definitely better for administrators trying to decide whether JOSS is a "serious" journal and I don't think it hurts much (if any) for geeks who just want to see the code. I'm in favor of the change.

**Comment by arfon** [comment]
Fixed in the web UI updates.
