### ISSUE TITLE
possible to amend acknowledgements of published paper?

### ISSUE THREAD

**Issue by dbkeitel** [openjournals/joss#485]
Dear editors,

turns out I forgot a funding acknowledgment when we submitted [10.21105/joss.00707](https://doi.org/10.21105/joss.00707) and now the funder requests whether this can be still amended. I've already found #423 which says clearly that no major content changes are possible post-publication, but thought it can't hurt to ask if an update of acknowledgments might still be possible somehow?

Yours sincerely,
David Keitel

cc @kwwette as our corresponding author

**Comment by arfon** [comment]
Hi @dbkeitel - we can make this change. Please add the relevant section to your `paper.md` file and let me know when you've done this.

**Comment by dbkeitel** [comment]
Thanks @arfon for the super-quick reply! I'll check with @kwwette and get back to you with an updated file.

**Comment by kwwette** [comment]
@arfon Please update the OctApps paper using [this file](https://raw.githubusercontent.com/octapps/octapps/51a3ff06e8a5373fe1ec209c14876c0648c85dcb/paper/paper.md). This contains 2 minor updates from the accepted paper: 1) The funding acknowledgement for @dbkeitel has been added, 2) a defunct URL to the LALSuite software package has been replaced with a DOI. Please let me know if you have any questions.

**Comment by arfon** [comment]
OK that should be updated now.

**Comment by dbkeitel** [comment]
Looks like it is, thanks!
