### ISSUE TITLE
archiving reviews post-acceptance

### ISSUE THREAD

**Issue by danielskatz** [openjournals/joss#490]
It would be good to capture JOSS reviews post acceptance, and archive them.

One option would be to offer the authors to attach them to the paper as an appendix.
Or we could just save them somewhere, such as zenodo.

(This issue is partly based on discussion in the Jan 2019 editors call, thinking about what would happen if JOSS or GitHub went away, and how we plan for long-term archiving_  [clocks](https://clockss.org) is also part of this discussion)

**Comment by arfon** [comment]
This is now part of our Portico archives (implemented in #610 and https://github.com/openjournals/joss/blob/master/lib/tasks/portico.rake)
