### ISSUE TITLE
TRACKING: Archiving JOSS content

### ISSUE THREAD

**Issue by arfon** [openjournals/joss#495]
There are a couple of things we should probably be doing to archive JOSS content for the long-term:

**Archiving reviews**
 
As discussed in #269 & #490, this could be some kind of script that attempts to pull the comments for the review and deposit them as an archive in e.g. Zenodo. We would presumably then link to this review archive in the paper.

Alternatively we could use `archive.org` to create snapshots of the review page (e.g. https://web.archive.org/web/20190207112842/https://github.com/openjournals/joss-reviews/issues/1207) - it looks like this could be done programmatically https://archive.readme.io/docs/creating-a-snapshot . 

**Archiving papers**

We should probably use [CLOCKSS](https://clockss.org) to archive the papers from JOSS. This would require a fee of ~$250 per year and also for us to be [generating JATS XML](https://github.com/openjournals/joss/issues/153#issuecomment-414307930) (which we currently don't).

FWIW, it's also possible to archive the papers with `archive.org` but it's not clear to me if this is better or worse than CLOCKSS:  https://web.archive.org/web/20190207113237/http://joss.theoj.org/papers/10.21105/joss.01027 & https://web.archive.org/web/20190207113247/https://www.theoj.org/joss-papers/joss.01027/10.21105.joss.01027.pdf

**Comment by labarba** [comment]
CLOCKSS offers a full-featured service that includes public release under a Creative Commons license after a journal goes under, and it has the respect of librarians and publishers across the globe. I support joining CLOCKSS.

**Comment by labarba** [comment]
Ping @gforsyth 👋  — You wrote a script to download an issue thread into a markdown file, no? (to grab our review tracking for the inexact-gmres paper?) Do you have that script handy?

**Comment by arfon** [comment]
> CLOCKSS offers a full-featured service that includes public release under a Creative Commons license after a journal goes under, and it has the respect of librarians and publishers across the globe. I support joining CLOCKSS.

Me too. I wonder if CLOCKSS supports archiving reviews too? I'll get in touch with them and start exploring adding Open Journals to CLOCKSS.

**Comment by danielskatz** [comment]
It feels like the JATS part would also be good in general, though I'm not sure exactly why.

**Comment by arfon** [comment]
> It feels like the JATS part would also be good in general, though I'm not sure exactly why.

Yes, this would allow us to be indexed in PubMed.

**Comment by gforsyth** [comment]
> Do you have that script handy?

It might be somewhere on theo?  Probably simpler just to rewrite it.

**Comment by HaoZeke** [comment]
Wouldn't it be better to save the entire thread as is (eg. pdf) instead of parsing it (making it fragile to HTML changes)?

**Comment by arfon** [comment]
Just a quick update here. We ended up joining [Portico](https://www.portico.org/) for archiving of JOSS content.

We've yet to do the initial ingest but will do :soon:

**Comment by arfon** [comment]
As of https://github.com/openjournals/joss/pull/610 this is now done for both JOSS and JOSE.

Note, the Portico archives include a copy of the review issue too (in JSON format). Here's an example deposit:
[10.21105.joss.01700.zip](https://github.com/openjournals/joss/files/3665695/10.21105.joss.01700.zip)
