### ISSUE TITLE
Publication ethics and malpractice statement

### ISSUE THREAD

**Issue by arfon** [openjournals/joss#496]
For JOSS to be indexed in Scopus, we need to draft a publication ethics and malpractice statement and host it on the JOSS site.

Here's an example from an Elsevier journal: https://www.journals.elsevier.com/asia-pacific-journal-of-sports-medicine-arthroscopy-rehabilitation-and-technology/policies-and-guidelines/publication-ethics-and-publication-malpractice-statement and the guidelines from Scopus on what this document should contain: https://www.elsevier.com/__data/assets/word_doc/0018/116082/pems_june15.docx

**Comment by danielskatz** [comment]
The updated [COPE core practices](https://publicationethics.org/core-practices) are also probably important to consider.

**Comment by arfon** [comment]
@danielskatz - would you be willing to try and take a first pass at this?

**Comment by danielskatz** [comment]
yes

**Comment by danielskatz** [comment]
How should we define "research misconduct" for JOSS?

**Comment by arfon** [comment]
Two common cases I could imagine:
- Plagiarism (e.g. violation of another author's copyright) for both software and papers
- Incorrect author lists

Not sure what else we would want here. There are a [lot of possible scenarios](https://publicationethics.org/cases?f%5B0%5D=im_field_classifications%3A2771) and it doesn't seem realistic to try and cover them all...

**Comment by danielskatz** [comment]
Do we also want to talk about self-plagiarism?  An author has already published a software paper and then submits a JOSS paper as well about the same software/version?

Other possible misconduct - suggesting reviewers who are either fake people or have conflicts?  Reviewers who have conflicts but don't disclose them?  Editor misconduct due to conflicts?  Anything related to bribes for authors, reviewers, editors?

**Comment by labarba** [comment]
See for example
https://github.com/openjournals/joss-reviews/issues/714#issuecomment-462159552
_______________________________________
Lorena A. Barba
Associate Professor, Mechanical and Aerospace Engineering
The George Washington University
twitter.com/LorenaABarba <http://twitter.com/LorenaABarba>

**Comment by arfon** [comment]
I quite like what JORS has on this page https://openresearchsoftware.metajnl.com/about/research-integrity/

**Comment by danielskatz** [comment]
> I quite like what JORS has on this page https://openresearchsoftware.metajnl.com/about/research-integrity/

which part(s) specifically?

**Comment by arfon** [comment]
Sorry, I meant to say, I think they do a good job of just categorizing the ways in which they promote 'research integrity'.

**Comment by danielskatz** [comment]
while they call this research integrity, it looks more to me like a bunch of stuff about the journal, publisher, and policies, many of which have nothing to do with research integrity, such as licenses, indexing, archiving, and no lock-in.

**Comment by danielskatz** [comment]
As a status update, the AEiCs are working through a bunch of issues related to this in a different document; progress is being made.

**Comment by aloctavodia** [comment]
Any update about this?

**Comment by danielskatz** [comment]
👋 @arfon  - where are we on this?  I feel like my part (in this issue) is complete, but now I don't see the changes we made - did we lose this in moving to new site?  Or did we finish it but not post it to the JOSS site?

**Comment by arfon** [comment]
This got dropped in the changes with the new site. I've just added them back in https://github.com/openjournals/joss/commit/569ccb3d7b3fa99a8f6e604e9122566f5a0a05a4 which now show up here: http://joss.theoj.org/about#ethics.

I *think* this is now resolved?

**Comment by danielskatz** [comment]
well, not quite.  We have the following that we've prepared, which needs to be put on the website as the JOSS statement, but for the statement itself to be complete, the archiving item needs to be finished.  (see next comment for draft, almost complete statement)

**Comment by danielskatz** [comment]
JOSS Publication Ethics and Malpractice Statement

July 2019

1. Editorial Board 
The JOSS editorial board's members are recognized experts in the field. The full names and affiliations of the members are provided on the journal’s Web site.
(See http://joss.theoj.org/about#editorial_board. The individual editors' contact information are provided on that site, via their GitHub pages, and general contact information for the editorial office also on the journal’s Web site: http://joss.theoj.org/about#contact)


2. Authors and Authors responsibilities
- JOSS does not charge any fees for manuscript processing and/or publishing materials, as is stated on the journal's Web site (http://joss.theoj.org/about#costs)
- Authors are obliged to participate in peer review process, as described in submission guidelines (https://joss.readthedocs.io/en/latest/submitting.html#the-review-process)
- All authors have significantly contributed to the research. The submitting author is required to be a major contributor to the software they are submitting (https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements) and the review process includes a check that ‘the full list of paper authors seems appropriate and complete?’ (https://joss.readthedocs.io/en/latest/review_criteria.html#authorship)
- All authors are obliged to provide retractions or corrections of mistakes. (http://joss.theoj.org/about#ethics and https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain)
- JOSS papers are required to have a list of references (https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain), and financial support. (https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain)
- Forbidden to publish same research in more than one journal. (http://joss.theoj.org/about#ethics)

3. Peer-review process
- All of JOSS’s content is subjected to peer-review (http://joss.theoj.org/about and https://joss.readthedocs.io/en/latest/index.html) 
- JOSS Peer-review is defined as obtaining advice on individual manuscripts from reviewers expert in the field (https://joss.readthedocs.io/en/latest/editing.html#finding-reviewers).  This advice is public, and is given to both the editor(s) and the author(s), with the aim of pointing out issues the reviewers believe are insufficiently address for publication (https://joss.readthedocs.io/en/latest/reviewer_guidelines.html#guiding-principles).
- The JOSS review process is clearly described on the journal’s Web site (https://joss.readthedocs.io/en/latest/reviewer_guidelines.html).
- Judgments should be objective (https://joss.readthedocs.io/en/latest/reviewer_guidelines.html#guiding-principles).
- JOSS reviewers should ideally have no conflict of interest. In practice, this is not always possible. If a reviewer has a conflict of interest, it must be declared and recorded, and the editors may choose to waive it if this is in the best interest of the review process (https://joss.readthedocs.io/en/latest/reviewer_guidelines.html#joss-conflict-of-interest-policy).
- Reviewers should point out relevant published work which is not yet cited (https://joss.readthedocs.io/en/latest/review_criteria.html#an-important-note-about-novel-software-and-citations-of-relevant-work .
- JOSS reviews are public and non-anonymous while in progress and post-review, as they take place via GitHub issues in a public repository.

4. Publication ethics (all the subpoints below are addressed in http://joss.theoj.org/about#ethics)
- Publishers and editors shall take reasonable steps to identify and prevent the publication of papers where research misconduct has occurred. 
- In no case shall a journal or its editors encourage such misconduct, or knowingly allow such misconduct to take place. 
- In the event that a journal’s publisher or editors are made aware of any allegation of research misconduct the publisher or editor shall deal with allegations appropriately.
- The journal should have guidelines for retracting or correcting articles when needed.
- Publishers and editors should always be willing to publish corrections, clarifications, retractions and apologies when needed.

5. Copyright and Access 
- JOSS copyright and licensing information is clearly described on the journal’s Web site (http://joss.theoj.org/about#content_license).
- The journal and all individual articles are freely available to all readers.

6. Archiving
- A journal’s plan for electronic backup and preservation of access to the journal content in the event a journal is no longer published shall be clearly indicated.

7. Ownership and management
-  Information about the ownership and/or management of a journal shall be clearly indicated on the journal’s Web site. (http://www.theoj.org)
- JOSS and the Open Journals (http://www.theoj.org) do not use organizational names that would mislead potential authors and editors about the nature of the journal’s owner.

8. Web site
- A journal’s Web site, including the text that it contains, shall demonstrate that care has been taken to ensure high ethical and professional standards. (see http://joss.theoj.org and http://joss.theoj.org/about)

9. Publishing schedule
- JOSS is not a serial publication - it immediately publishes accepted articles.

10. Name of journal
- As far as we know, the Journal name (Journal of Open Source Software (JOSS)) is unique and not one that is easily confused with another journal or that might mislead potential authors and readers about the Journal’s origin or association with other journals

**Comment by arfon** [comment]
Ah yes, thanks @danielskatz. I'm about to sign the archiving agreement with Portico which should address #6.

**Comment by danielskatz** [comment]
So once you've done that, you will update 6 and add the updated statement to our website?

**Comment by arfon** [comment]
> So once you've done that, you will update 6 and add the updated statement to our website?

Yes.

**Comment by labarba** [comment]
Thinking about JOSE, and the fact that these ethics guidelines would apply just the same to JOSS and JOSE, I wonder: would it make sense to make these guidelines part of the joint documentation site for TheOJ?

**Comment by danielskatz** [comment]
I don't think they need to be - each journal could make slightly different choices. And if we do make this apply at the OJ level, we are then binding (at least by default) other OJ journals to the same choices.

I think it might be better for JOSE to copy these, if they like them, from JOSS, than to do this at the OJ level. (but this is just a slight preference)

**Comment by labarba** [comment]
I was just thinking that duplication of the content means maintaining it in two places. JOSE would adopt verbatim.

**Comment by arfon** [comment]
Note that we need to resubmit for Scopus indexing once we have the Portico archiving set up.
