### ISSUE TITLE
Docker Containers For Reviews

### ISSUE THREAD

**Issue by HaoZeke** [openjournals/joss#498]
I was wondering if JOSS reviewers should not create a docker image wherein the tests were carried out. To ensure that the software at the time of the review was working reproducibly.

**Comment by labarba** [comment]
I suppose you mean _authors_ should create a Docker image...

**Comment by HaoZeke** [comment]
Well that would certainly be helpful, but honestly I would just like a fully reproducible snapshot somewhere in the loop. 

If we ask the authors then we can't be sure the reviews included testing the installation. 


________________________________

**Comment by jedbrown** [comment]
Seems to me that continuous integration provides this. For CI systems that use user-provided container images, we could ask for the corresponding specification (i.e., Dockerfile).

**Comment by HaoZeke** [comment]
@jedbrown that is correct, however not all software submissions use CI systems.. I feel like it might not be a good idea to try to force containerization on the authors but instead to have a few common templates for the reviewers to customize and then link to.

Just as the current format links to the review, it would be nice to link to a Dockerfile with the exact functionality at the time of the review.

**Comment by jedbrown** [comment]
I think it's a nontrivial bar to require reviewers to do this work and that time would be better spent setting up CI.

**Comment by arfon** [comment]
> I was wondering if JOSS reviewers should not create a docker image wherein the tests were carried out. To ensure that the software at the time of the review was working reproducibly.

@labarba and I nearly had an exploratory conversation with some folks at Azure cloud a few months ago about potentially offering cloud-hosted VM environments for reviewers to get a 'clean' environment for testing software. Ultimately that conversation didn't actually go anywhere (it never happened).

I think all of these ideas are potentially interesting and someday we might consider some kind of 'reproducible track' for JOSS whereby authors would need to do something like this but ultimately, I agree with @jedbrown, this is a non-trivial amount of work for most authors.

**Comment by HaoZeke** [comment]
Yup I agree it is non-trivial for authors... I guess I am biased in the sense that I conduct most of my reviews in customized Ubuntu docker images anyway (mostly because my system has all sorts of broken packages). I guess this should be shelved for now.

I would be against segregation of articles on the basis of their installation ease (i.e a reproducible track would be sort of highlighted without a justifiable reason IMHO.)

**Comment by nuest** [comment]
Although this is closed, two comments:

- JOSS could recommend that the repository includes a Notebook for demonstration of the package and the repo is ready to be opened as a [Binder](https://mybinder.org/). Depending on the structure already implemented (e.g. Python or R package) that could be relatively easy for authors, even without container experience.
- A container for review should be there to document how to prepare the environment of a package, it should not be a backdoor to a complex installation. Users installing software outside of containers often exposes bugs worth fixing.
