### ISSUE TITLE
Call for Editors and Guidelines.

### ISSUE THREAD

**Issue by HaoZeke** [openjournals/joss#507]
I notice that there are instructions on how to volunteer as a reviewer but no details on the editorial board composition and policy....

**Comment by arfon** [comment]
Hi @HaoZeke - the editorial board is listed here: http://joss.theoj.org/about#editorial_board and we have governance docs for the Open Journals organization (the parent of JOSS): https://github.com/openjournals/governance .

Could you say a little more about what you're looking for?

**Comment by HaoZeke** [comment]
Specifically, the lack of any open calls for editors, or the guidelines for establishing or initiating the acceptance of new editors. I am rather concerned by the rapid growth of the editorial board. For reference, this is an [APS call for editors](https://careers.aps.org/jobs/11775282/assistant-editor-physical-review-a?utm_source=86197&utm_medium=featuredJobs&utm_campaign=mainLanding&utm_term=).

The [editorial policy and board composition](https://github.com/openjournals/governance/blob/master/governance.md#editorial-policies-and-processes) is very ambiguous in the Open Journals documentation.

**Comment by danielskatz** [comment]
I agree we could do a better job of describing roles in some regards, and we are always trying to improve our documentation.

On the other hand, the APS document you link to is a job advertisement for a full-time paid position.  JOSS editors are all volunteers - we don't have any full-time (or even part-time) paid editors.

**Comment by arfon** [comment]
> Specifically, the lack of any open calls for editors, or the guidelines for establishing or initiating the acceptance of new editors. I am rather concerned by the rapid growth of the editorial board. For reference, this is an [APS call for editors](https://careers.aps.org/jobs/11775282/assistant-editor-physical-review-a?utm_source=86197&utm_medium=featuredJobs&utm_campaign=mainLanding&utm_term=).

Got it. Thanks for clarifying. In addition to what @danielskatz we did actually issue a call for editors towards the end of last year - the new editors joining right now applied to this call: http://blog.joss.theoj.org/2018/12/call-for-editors

**Comment by HaoZeke** [comment]
@arfon thanks for linking to the blog and the call! Somehow I missed that...
