### ISSUE TITLE
How can I run this repo?

### ISSUE THREAD

**Issue by brayanrodpr** [openjournals/joss#509]
Hi. I want to start this respository project locally, could I?

**Comment by arfon** [comment]
Hi @brayanrodpr - yes, it's possible. 

You'll need to install Postgresql, a modern version of Ruby (>= ~2.4), and [bundler](https://bundler.io/).  Then, after cloning this repository you'll need to run `bundle install` to install the dependencies.

I'm not sure if you're familiar with [Ruby on Rails](https://rubyonrails.org/)? The JOSS application is built using this technology.
