### ISSUE TITLE
Whedon unassign editor when "paused"

### ISSUE THREAD

**Issue by labarba** [openjournals/joss#512]
I think we should unassign the editor when the submission is "paused" — this way, it doesn't count for the editor's current workload on the JOSS Statistics page (used as criterion when assigning new submissions to editors). 

Would it be possible for `whedon` to do it automatically upon adding the "paused" label?

If not, we can still do it by hand when adding the label.

The expectation is that the author will ping us when ready to re-engage with the submission. I have started to tell them to ping `@openjournals/joss-eics` when they are back.

**Comment by arfon** [comment]
Made substantial progress on this in https://github.com/openjournals/joss/commit/12e6f6e84f379d7c04e48c87b56a345a8012ccab

**Comment by danielskatz** [comment]
I don't think this is a good idea.  I think we want the editor to stay responsible for the paper, even while paused, so that they prod the author from time to time, and once the paper is ready to restart, the editor is already assigned.  I feel like this change is just to make stats more useful, and wonder if there's a better way we could do that, perhaps by how we generate the stats.

**Comment by arfon** [comment]
>  I feel like this change is just to make stats more useful, and wonder if there's a better way we could do that, perhaps by how we generate the stats.

What would you suggest? Isn't the problem simply that we want the AeICs to be able to understand the *actual* editorial load of an editor currently? If so, I think the change in 12e6f6e accomplishes this?

**Comment by danielskatz** [comment]
Yes, this change is fine - I was referring to the title of the issue overall

Specifically, I don't think we should
> unassign the editor when the submission is "paused"

**Comment by arfon** [comment]
Ok thanks for the clarification, I agree.

**Comment by labarba** [comment]
I am also of the opinion that we don't want to _unassign_ the editor when paused. If the review restarts,  we'd want the same editor to pick up where they left off—after all, they invited the reviewers, if assigned, or flagged the blocking issue that led to the pause.

On the email thread about this, I suggested we _close the issue_ when paused, and that `whedon` not count closed issues on the stats. Is this not a workable solution?

**Comment by labarba** [comment]
(I notice that I started this issue suggesting we unassigned. Bah. I guess I changed my mind!)

**Comment by danielskatz** [comment]
If the main goal is to fix the stats, let's just fix the stats.  Does the change in 12e6f6e do this sufficiently?

**Comment by labarba** [comment]
I also find myself wasting time clicking through paused papers over and over again when auditing stale threads on the dashboard:
http://joss.theoj.org/dashboard/in_progress

Would closing the issue for a paused review help here?

**Comment by arfon** [comment]
The `paused` label now shows up on the dashboard views. Hopefully this helps?

**Comment by danielskatz** [comment]
@labarba - do you think we can now close this issue?
