### ISSUE TITLE
Middle initial in doi.org

### ISSUE THREAD

**Issue by sjackman** [openjournals/joss#521]
The author of https://doi.org/10.21105/joss.00497 is recorded `L. Warren, René` when it should be `Warren, René L.`.

```console
$ curl -H "Accept: text/bibliography; style=bibtex" https://doi.org/10.21105/joss.00497
 @article{L_Warren_2018, title={Visualizing genome synteny with xmatchview}, volume={3}, ISSN={2475-9066}, url={http://dx.doi.org/10.21105/joss.00497}, DOI={10.21105/joss.00497}, number={21}, journal={The Journal of Open Source Software}, publisher={The Open Journal}, author={L. Warren, René}, year={2018}, month={Jan}, pages={497}}
```

cc @warrenlr @lcoombe

**Comment by arfon** [comment]
Fixed in https://github.com/openjournals/joss-papers/commit/7d25cf01834a0c541501a51161f82d38e4e4f5f1
```
curl -L -H "Accept: text/bibliography; style=bibtex" https://doi.org/10.21105/joss.00497
```

returns:

```
@article{Warren_2018, 
title={Visualizing genome synteny with xmatchview}, 
volume={3}, 
ISSN={2475-9066}, 
url={http://dx.doi.org/10.21105/joss.00497}, 
DOI={10.21105/joss.00497}, 
number={21}, 
journal={The Journal of Open Source Software}, 
publisher={The Open Journal}, 
author={Warren, René L.}, 
year={2018}, 
month={Jan}, 
pages={497}}

```

**Comment by sjackman** [comment]
Thanks for the quick response, Arfon!

**Comment by sjackman** [comment]
I've noticed that https://doi.org/10.21105/joss.00116 has the same metadata information problem.
```
author={L Warren, Rene}
```
should be
```
author={Warren, Rene L}
```
cc @warrenlr

**Comment by sjackman** [comment]
in fact it should be
```
author={Warren, René L.}
```
@warrenlr Do you prefer using the accented `é` in your name?

**Comment by warrenlr** [comment]
If it's ok (sometimes accent render poorly), then yes

**Comment by sjackman** [comment]
@arfon Is there anything that we can do on our end to avoid this issue in the future?

**Comment by arfon** [comment]
OK, fixed in https://github.com/openjournals/joss-papers/commit/df14e217c5d0146a4e520abafe2038d7057653c3 - this make take a few hours to resolve with Crossref properly.

> @arfon Is there anything that we can do on our end to avoid this issue with the middle initial in the future?

I think this was actually pretty much fixed in https://github.com/openjournals/whedon/commit/bb177132398f783012793cde624e751b656c42a5 for newer submissions but as these are issues with older metadata it's possible there are still some papers with metadata problems.

**Comment by sjackman** [comment]
Thanks again, Arfon!
