### ISSUE TITLE
Application should 404 for withdrawn or rejected papers

### ISSUE THREAD

**Issue by arfon** [openjournals/joss#522]
Sometimes papers don't make it through review. For non logged in users, if a paper has been withdrawn or rejected then we should return a `404`.

**Comment by labarba** [comment]
Return a `404` on the reserved DOI? Or on where?

**Comment by arfon** [comment]
The badges on GitHub link to URLs that look like this: http://joss.theoj.org/papers/0a9f9006cebb80198e0ad5448cc1fc10 - the reserved DOI (http://joss.theoj.org/papers/10.21105/joss.1049) for this paper won't ever resolve because the paper won't be accepted.

Basically I don't think it makes sense for there to be a public record on the JOSS site for papers that have been withdrawn or rejected, especially as we have a record of this on GitHub (e.g. https://github.com/openjournals/joss-reviews/issues/1049).

**Comment by labarba** [comment]
And have you found any software repos that keep a badge to a pre-review? I'm not sure I'm following: where do the links originate from? I agree with your second statement.

**Comment by arfon** [comment]
I have not. What I'm more worried about is Google keeping links to papers that we've rejected or were withdrawn. For example, the 4th link in this search: https://www.google.com/search?q=MTSS%3A+A+CUDA+software+for+the+analysis+of+Multivariate+Time+Series&rlz=1C5CHFA_enUS843&oq=MTSS%3A+A+CUDA+software+for+the+analysis+of+Multivariate+Time+Series&aqs=chrome..69i57j69i58j69i61j69i60.640j0j1&sourceid=chrome&ie=UTF-8

**Comment by Kevin-Mattheus-Moerman** [comment]
Returning a `404` sounds fine. Will this stop Google and others from presenting them in searches? To avoid this altogether is it possible to only reserve a DOI at the acceptance stage?

**Comment by arfon** [comment]
> Will this stop Google and others from presenting them in searches?

Yes, it should do.

> To avoid this altogether is it possible to only reserve a DOI at the acceptance stage?

We don't 'reserve' DOIs, we only create them when we accept a publication. What we do have are badges in the review issue e.g. this one:

[![status](http://joss.theoj.org/papers/8549074fbc29175a9823c1aca2f26d24/status.svg)](http://joss.theoj.org/papers/8549074fbc29175a9823c1aca2f26d24)

...which link to the paper at JOSS (this is how the badge automatically updates and turns green once a paper has been accepted.

We could remove this functionality but I have seen people use it and I think this is a good feature to keep.
