### ISSUE TITLE
Unicode in figure captions isn't rendered in the PDF

### ISSUE THREAD

**Issue by leouieda** [openjournals/joss#534]
The paper in openjournals/joss-reviews#1342 has some russian characters in the caption of a figure. For some reason, they are missing from the compiled PDF (see [this example](https://github.com/openjournals/joss-papers/blob/joss.01342/joss.01342/10.21105.joss.01342.pdf)). This is weird because there is usually no problem with unicode in other parts of the paper.

I have no idea where to start looking for a solution. Should I suggest the authors to just avoid using unicode in the caption?

**Comment by kgjerde** [comment]
Thanks for this. My theory is that the JOSS font does not support cyrillic characters and therefore leave blank spaces where the characters are supposed to be, but I am not a pandoc/latex expert!

**Comment by kgjerde** [comment]
Also, is it possible to force the figure with caption to be positioned not at the top of the page, but before the heading "Main dependencies"?

**Comment by arfon** [comment]
> Thanks for this. My theory is that the JOSS font does not support cyrillic characters and therefore leave blank spaces where the characters are supposed to be, but I am not a pandoc/latex expert!

I can investigate adding additional fonts to the Whedon compilation environment. 

> Also, is it possible to force the figure with caption to be positioned not at the top of the page, but before the heading "Main dependencies"?

Figure placement in Markdown -> LaTeX -> PDF (which is what we're doing here) is notoriously hard. I'll try debugging the figure placement locally to see if I can improve things.

**Comment by arfon** [comment]
I've tried debugging this for a few hours today and I've not made much progress sorry. There's _something_ about our [LaTeX template](https://github.com/openjournals/whedon/blob/master/resources/latex.template) causing this issue but for some reason I don't seem to be able to override the language being used by the template to enable support for cyrillic characters.

Would it be possible to remove the cyrillic characters from the caption or is this a blocking issue @kgjerde?

**Comment by kgjerde** [comment]
@arfon Thank you so much for digging into this! I think the best thing to do at this stage is to remove the culprit, which I now have done.

Regarding figure placement, I found that it is easy to do manually in the tex file (by appending "[!htb]" to "\begin{figure}" and add a "\bigskip" before that for some spacing, but I do not know how to do this in the markdown file.

**Comment by arfon** [comment]
> Regarding figure placement, I found that it is easy to do manually in the tex file (by appending `[!htb]` to `\begin{figure}` and add a `\bigskip` before that for some spacing), but I do not know how to do this in the markdown file, or if it is possible.

Some commands (such as `\newpage`) work in Markdown/LaTeX/Pandoc. Feel free to try out a few options and ask Whedon to recompile the paper with `@whedon generate pdf`

**Comment by kgjerde** [comment]
@arfon Figure placement problem solved by inserting the following directly into the .md file:

\bigskip
\begin{figure}[!tbh]
\centering
\includegraphics{man/figures/paper_illustration.png}
\caption{Illustration screenshots. To the left: part of interactive
corpus heat-map displaying occurences of Moses and Abraham in the
\emph{King James Bible}. In the middle: part of interactive corpus
calendar heat-map displaying occurences of `orthodox' in a collection of
transcripts from the Russian president's website. To the right: document
view with interactive document map and highlighted pattern matches.}
\end{figure}

Thanks for the close follow-up.

@leouieda I have updated the paper and whedon has generated a new pdf.
