### ISSUE TITLE
JOSS pre-submission enquiry: suite of modules for education and research applications

### ISSUE THREAD

**Issue by amoodie** [openjournals/joss#537]
## summary of software
[SedEdu](https://github.com/sededu/sededu) is a software package that provides a GUI framework for collating and distributing interactive modules for teaching and research within the geosciences. The SedEdu software is written with the Python Qt bindings (PyQt) and is the organizing software under which the modules are organized. The modules are written in Python (largely using the `matplotlib` library functionality) and usually include an interactive GUI and some worksheet activities to guide the use of the module.

So, the JOSS _software_ contribution is the framework for housing the modules, moreso than the education/research modules themselves.

## demo gif of software
![output](https://user-images.githubusercontent.com/8801322/58433213-53fa0780-8073-11e9-8eb7-1d33d6af38e2.gif)

## other important notes
 - Modules are developed independent of one another, and housed in their own git repositories, and then brought into SedEdu through `git submodule`. In this way, the entire suite is maintained as SedEdu, and distributed by pypi and Anaconda, but each module is maintained by it's own developers and can be distributed independently as well. There's a number of reasons for structuring SedEdu in this way, which I could discuss in the `paper.md` file.
- Because SedEdu provides a GUI rather than an API, the documentation of the project is more about how to develop and contribute to SedEdu, rather than how to interact with it. 
- SedEdu is often used for in the classroom, but modules have also been useful for rapid hypothesis testing and research applications.
- I would like to publish a paper about SedEdu to 1) raise awareness about contributing to SedEdu within my research community, and 2) to demonstrate to funding agencies the legitimacy of this tool in both research and teaching applications.
- Before submitting, I'd plan to implement some real tests with the `pytest-qt` plugin, and finish off and include a few more modules that are partially developed.

Some examples of the modules included in SedEdu are below:
- [rain_table](https://github.com/sededu/rain_table)
- [rivers2stratigraphy](https://github.com/sededu/rivers2stratigraphy)

## question
My question then is whether this software would be a good fit for JOSS? I know there is also JOSE, but this seems to be more of collections of notebooks, rather than a software package for managing those teaching a research tools.

I appreciate your review of the info and thoughts. Tagging two people I know have published with/are involved with JOSS from my community, to spark the discussion: @jedbrown @kbarnhart

**Comment by arfon** [comment]
Thanks for your inquiry @amoodie. I could imagine this fitting within JOSS or JOSE but I'd be interested to hear from @labarba on whether she thinks this is an especially good fit for JOSE.

**Comment by kyleniemeyer** [comment]
JOSE does publish software submissions that education as a primary goal (vs. research), in addition to courses/learning modules.

**Comment by amoodie** [comment]
Great, thanks for the responses. 

I see from the JOSE website that they seek "open-source software that serves as educational technology", which I think SedEdu definitely falls under. The JOSS guideline that "the software should have an obvious research application" and the API documentation requirements are also both satisfied by SedEdu, but a bit more weakly.

I'll wait and see if @labarba has any opinion before submitting anything to either, but I will start work on cleaning things up in the repo and preparing to write the paper. Thanks again.

**Comment by jedbrown** [comment]
I think this is a direct fit for JOSE.

**Comment by amoodie** [comment]
Thanks everyone, I've started working on a submission for JOSE. Will reconnect with (some of) you when I get that out the door.
