### ISSUE TITLE
Dead link in submitting.md on readthedocs site

### ISSUE THREAD

**Issue by MatthewFlamm** [openjournals/joss#543]
Link to https://raw.githubusercontent.com/adrn/gala/f6bb2532afeed3c0b0feea3037bf71a3f42b2a12/paper/paper.md
is converted to 
https://raw.githubusercontent.com/adrn/gala/f6bb2532afeed3c0b0feea3037bf71a3f42b2a12/paper/paper
on readthedocs.

The second link has 404 error.

**Comment by arfon** [comment]
Thanks for catching this @MatthewFlamm!
