### ISSUE TITLE
Published pdf different from 'test run' pdf?

### ISSUE THREAD

**Issue by kgjerde** [openjournals/joss#544]
@arfon @leouieda 

First of all, sorry for not noticing immediately when my paper was published two days ago (https://joss.theoj.org/papers/10.21105/joss.01342).

From the published paper:
>![image](https://user-images.githubusercontent.com/25481274/59550087-ebfa5b00-8f66-11e9-91f5-ff375dd07484.png)

From a whedon test run:
>![image](https://user-images.githubusercontent.com/25481274/59550081-da18b800-8f66-11e9-86f9-329b7a299225.png)

(Since that test run pdf was generated, I did a few minor formatting changes, but I was very sure I had checked that the pdf with those changes too.)

Compare also the first few lines of the published pdf:

>![image](https://user-images.githubusercontent.com/25481274/59550094-08969300-8f67-11e9-9d2d-a5eba9f5781c.png)

With the test run:

>![image](https://user-images.githubusercontent.com/25481274/59550097-16e4af00-8f67-11e9-869d-10f557431e12.png)

There seems to be a difference in font or something else, leading to lines ending in different places.

In my paper, then, this led to the not very pretty word division in the first image above. The reason is that I, probably unwisely, chose 'code formatting' for package names in the paper, and to fix one issue where latex divided 'corporaexplorer' into two lines with no hyphen, I manually added one, and made sure it came correctly out in the pdf.

In retrospect, this was obviously an unfortunate hack.

**Thus, my question is: Is it possibly to fix this by re-rendering the published pdf?** If so, the simplest thing would be to simply move the manual hyphen one place. (Or, I could change the formatting of package names, also no problem at all.)

Again thanks for all your help.

**Comment by arfon** [comment]
> Thus, my question is: Is it possibly to fix this by re-rendering the published pdf?

@kgjerde - yes, that's possible. Please make your changes to the `paper.md` file in your repository and let me know when you've done this.

**Comment by kgjerde** [comment]
@arfon Thank you so much. I have updated the paper in kgjerde/corporaexplorer@0a03f6d. 

I ran `@whedon generate pdf` in the [pre-review issue](https://github.com/openjournals/joss-reviews/issues/1329) (in order not to clutter the review thread), and the edit seems to work beautifully:

>![image](https://user-images.githubusercontent.com/25481274/59561915-00515d00-9026-11e9-986a-68b21cb81c1a.png)

So, the paper.md is ready to be re-rendered. Fingers crossed, and thanks again!

**Comment by arfon** [comment]
@kgjerde - can you check this one looks ok too? [10.21105.joss.01342.pdf](https://github.com/openjournals/joss/files/3294093/10.21105.joss.01342.pdf)

**Comment by kgjerde** [comment]
@arfon – Strange, but this seems to be a rendering of an earlier version of paper.md, before I made the changes we discussed in https://github.com/openjournals/joss/issues/534.

For example, the figure is now on the top of page 2, and the caption is the old, problematic one:

>![image](https://user-images.githubusercontent.com/25481274/59564212-40bfd380-9044-11e9-89f9-f5d5fc6cbf6f.png)

As opposed to the final one:

>![image](https://user-images.githubusercontent.com/25481274/59564222-5f25cf00-9044-11e9-8eea-bdb6bf16cc6f.png)

**Comment by arfon** [comment]
Sorry, not sure what happened there - I was compiling the paper locally. What about this: [10.21105.joss.01342.pdf](https://github.com/openjournals/joss/files/3294102/10.21105.joss.01342.pdf)

**Comment by kgjerde** [comment]
This one looks great. (Did you change the font size? The references now start at the bottom of page 2 and not at the top of page 3, but that does not make any difference.)

So, thumbs up from me! Thanks!

**Comment by arfon** [comment]
Yeah, the font is slightly different on my machine (where I have to generate these local version of the paper).

I've gone ahead and updated the live version but it may take a few hours to show up because of caching we do of the PDFs.
