### ISSUE TITLE
Broken link for a newly submitted paper

### ISSUE THREAD

**Issue by issamhammad** [openjournals/joss#551]
Hi,

I have submitted the following paper yesterday (issamhammad / RETS-Manager)

The link was working fine after submission. However, the link returns "page can't be displayed' now. The same issue occurs for another paper which was submitted after mine (cbeauc / phymcmc)

Below is the link for my submission:

http://joss.theoj.org/papers/d725365221cf7085476667484273933a

**Comment by arfon** [comment]
Can you try logging into the site and see if the link works? I can see the submission fine, we return `404` for papers that aren't published if someone other than the author or editor is trying to view.

**Comment by issamhammad** [comment]
Thanks. It works now after logging into the site. What was confusing is that I was able to view all the other submitted papers except the top 2 .. mine and the other most recent one. 

Thanks again.

**Comment by arfon** [comment]
Apologies for any confusion caused!
