### ISSUE TITLE
paper.md to pdf before submission

### ISSUE THREAD

**Issue by holgerteichgraeber** [openjournals/joss#553]
Is there a way to convert my paper.md to a pdf file before submission? 
I could not find anything in that regard in the documentation. 
I would like to give it to my co-authors in a format that they can see how the final version would look like. 
Thanks already in advance!

**Comment by jedbrown** [comment]
Unfortunately, installing [Whedon](https://github.com/openjournals/whedon) is not trivial. You can get much of the way (minus the template/page decoration) with pandoc and pandoc-citeproc (probably available in your package manager).

    pandoc --filter pandoc-citeproc --csl ~/src/whedon/resources/apa.csl --pdf-engine=xelatex paper.md -o paper.pdf

**Comment by arfon** [comment]
Also, this script should help you get you a pretty good preview too: https://gist.github.com/arfon/09a11047de1c972e37f77e95d2c10efa

**Comment by holgerteichgraeber** [comment]
Thank you @jedbrown  and @arfon , appreciated!

**Comment by letmaik** [comment]
@arfon This needs to be improved. Why not offer a Docker image which can generate the pdf?

**Comment by arfon** [comment]
> @arfon This needs to be improved. Why not offer a Docker image which can generate the pdf?

I love this idea. I'm just short on time and haven't been able to get to this yet unfortunately.

If anyone on this thread was motivated to work on this that would be ✨

**Comment by letmaik** [comment]
What about https://github.com/openbases/openbases-pdf? Is this dead? Working? Not supported by JOSS?
