### ISSUE TITLE
Paper should include software repo address and archive

### ISSUE THREAD

**Issue by arfon** [openjournals/joss#56]
Currently the compiled PDF doesn't include the software address or archive URL. This needs to be fixed!

/ cc @jakevdp

**Comment by cranmer** [comment]
Here's a simple tex example with a bibliography that shows DOI and arXiv preprint.
https://gist.github.com/cranmer/0deb0df720176d4389c099094343d292

**Comment by arfon** [comment]
@cranmer any chance you know how to do this in pandoc too? I'm struggling to get this working with `biblio-style: uphys`

**Comment by cranmer** [comment]
I was too, and then focused on the standalone tex hoping you would be more pandoc savvy.

**Comment by arfon** [comment]
> I was too, and then focused on the standalone tex hoping you would be more pandoc savvy.

Darn it 😸

**Comment by arfon** [comment]
OK this is fixed reasonably well now:

<img width="643" alt="screen shot 2016-05-10 at 7 03 24 am" src="https://cloud.githubusercontent.com/assets/4483/15147322/598d1baa-167d-11e6-8205-bec3447d2fb1.png">

**Comment by cranmer** [comment]
:+1:

**Comment by jakevdp** [comment]
Awesome – will the repository DOI appear among the references?

**Comment by arfon** [comment]
> Awesome – will the repository DOI appear among the references?

@jakevdp - I wasn't planning on including it. If an author cited it then it would show up. Do you think we should include it anyway?

**Comment by jakevdp** [comment]
Initially I was expecting that, but I suppose it's fine to leave that up to the submitter.

**Comment by arfon** [comment]
> Initially I was expecting that, but I suppose it's fine to leave that up to the submitter.

👍
