### ISSUE TITLE
Status of paper post submission

### ISSUE THREAD

**Issue by MatthewFlamm** [openjournals/joss#561]
I submitted a paper, but got no feedback from the system, nor do I see anything in the joss-reviews issues.  Afterwards, I realized I did not fill out the author information in the profile prior to submission.  The note about updating this information before submission only exists on the profile page as far as I can tell.  I'm not sure if this is required to submit and I did not do so, or what is going on now.  It could be that I'm simply impatient :smile:.

I suggest that this note about the profile also be added to [submission instructions](https://joss.readthedocs.io/en/latest/submitting.html#submitting-your-paper) as well as on the submission form page itself.

**Comment by arfon** [comment]
@MatthewFlamm - could you tell me what the title of your submission is?

**Comment by MatthewFlamm** [comment]
rtdpy: A python package for residence time distributions

**Comment by arfon** [comment]
I don't think it got properly submitted. Can you try again now that your profile information has been filled out?

**Comment by MatthewFlamm** [comment]
Thanks @arfon.  I resubmitted, and I immediately got a more information page.  If this was a one-off problem, I/you can close this issue.  If this is related to the lack of author profile setup, I think it should be left open due to the lack of instructions at the key locations.
