### ISSUE TITLE
Pre submission inquiry: Multiple Repositories -> 1 paper.md

### ISSUE THREAD

**Issue by faroit** [openjournals/joss#565]
We plan to submit our paper about a community baseline for music source separation. Because the machine learning community is currently divided into two big camps: tensorflow and pytorch, we decided to do implementations for multiple frameworks. 
Now, having all of them in a monolithic repo would confuse users, since many are only fluent in a single framework. 

Our plan is to create a github organization for the baseline and have several repositories for each framework such as

* `baseline-pytorch`
* `baseline-tensorflow`
* ...

Now, since JOSS requires to have (a single) `paper.md` embedded into the code repository, I would like to ask how to handle this case. This is probably related to #443 which is still open, so I don't know if any decisions were made on this.

**Comment by labarba** [comment]
Maybe you could create one repository for the over-arching project and include the two others as git sub-modules.

**Comment by faroit** [comment]
sure, I understand that sub-modules were also proposed in #443. This would mean that I would only create this for the purpose of the JOSS paper, hence I would name it `baseline-paper`. Would that be okay?

**Comment by faroit** [comment]
@labarba Can we proceed as proposed?

**Comment by labarba** [comment]
@arfon — what is your opinion?

**Comment by arfon** [comment]
> This would mean that I would only create this for the purpose of the JOSS paper, hence I would name it `baseline-paper`.

Yes, this is fine. Upon acceptance of the paper, we'd need you to archive both the `baseline-pytorch` and `baseline-tensorflow` codebases into a single archive (with Zenodo or figshare).

Assuming this sounds OK, I'm happy to proceed.

**Comment by faroit** [comment]
@arfon @labarba thanks for your input. We will proceed then with the paper and will soon submit it.
