### ISSUE TITLE
Design of "start meta review" interim page ugly

### ISSUE THREAD

**Issue by labarba** [openjournals/joss#568]
This is low priority, but after the website redesign, the "pre-Pre-Review" page where we do "start meta review" is kinda ugly

![Screen Shot 2019-07-29 at 7 53 45 PM](https://user-images.githubusercontent.com/4800109/62074615-0fd5df80-b23b-11e9-8be8-4e0a31dc0394.png)

**Comment by arfon** [comment]
Yeah, _very_ ugly. 

@AndyHulme - Do you think you could take a look at this? It's the screen you see when you submit a paper before the paper is accepted.
