### ISSUE TITLE
Question about submission of a position paper

### ISSUE THREAD

**Issue by SimonBiggs** [openjournals/joss#569]
I was hoping to take part in writing a position paper regarding the best practices of Open Source software development for Medical Physicists for our college, [ACPSEM](https://www.acpsem.org.au/).

This would not be a paper about Open Source software, but it would certainly benefit from reviewers who stand in the Scientific Open Source Software space.

I am just testing the water (information gathering) at this stage. Would this be something that would be considered okay to submit to JOSS?

I recognise that JOSS is for creating papers for Open Source software, not papers about Open Source software per se, so I would completely understand if this was not your preferred course of action.

**Comment by danielskatz** [comment]
This would be out of scope for JOSS - you might want to consider JORS (https://openresearchsoftware.metajnl.com)

**Comment by SimonBiggs** [comment]
> This would be out of scope for JOSS - you might want to consider JORS (https://openresearchsoftware.metajnl.com)

Thanks for that, completely understandable.

A follow up question, I would really like to be able to use `.md` and `.bib` files to build and format the paper. I realise this can be done with `pandoc` and was considering going down that route, but you have a great set of tooling here. 

Is there a JOSS CLI or something of that sort that I can play around with to learn how it works? Something of the like where I can write `joss input_dir output_filpath` and it will pick up the `.md` and `.bib` files and build a paper?

**Comment by kyleniemeyer** [comment]
@SimonBiggs you can try using this compilation script: https://gist.github.com/kyleniemeyer/f993a873e484e150131ef09f7ca3c277

(Thanks to @bjmorgan for creating or at least bringing this to my attention at https://github.com/connorourke/crystal_torture/blob/master/paper/compile; I copied into a Gist just so for ease of access and to ensure it doesn't go away.)

**Comment by SimonBiggs** [comment]
Brilliant, thank you for that.

The following also looks promising:

https://github.com/openjournals/whedon/blob/25f9a1307a83b6b89080d6d934a3621f6a244035/lib/whedon/processor.rb#L101-L122
