### ISSUE TITLE
Bug: dashboard/Papers with no editor includes items w/editor-assigned

### ISSUE THREAD

**Issue by labarba** [openjournals/joss#572]
On the "incoming" dashboard:
https://joss.theoj.org/dashboard/incoming

…two items appear listed under "papers with no editor" that do have an editor assigned:
https://github.com/openjournals/joss-reviews/issues/1580
https://github.com/openjournals/joss-reviews/issues/1618

**Comment by arfon** [comment]
Thanks for flagging this @labarba. Fixed in https://github.com/openjournals/whedon-api/commit/1d39cabbad902fa5ff6ebbb92f62ae5f6230fe96
