### ISSUE TITLE
PDF embed's height is tiny

### ISSUE THREAD

**Issue by remram44** [openjournals/joss#573]
Seems to not happen some of the time, and resizing the page fixes it, but paper pages usually load to this:

![Screenshot_2019-08-02 fmcmc A friendly MCMC framework](https://user-images.githubusercontent.com/426784/62391956-2c706100-b534-11e9-8ca5-8d0a485d0732.png)

As you can see the embedded PDF's height is wrong (141px).

Firefox desktop 68.0.1, Ubuntu 18.04.

**Comment by remram44** [comment]
Also when it does expand, it is too big, meaning I have to scroll on the page after scrolling in the embed to see the bottom of the document.

![Screenshot_20190802_145328](https://user-images.githubusercontent.com/426784/62392500-976e6780-b535-11e9-8d88-042f437d7784.png)

**Comment by arfon** [comment]
@remram44 @Kevin-Mattheus-Moerman - can you take a look again and see if this issue is now fixed?

**Comment by remram44** [comment]
No change for me, sorry

**Comment by Kevin-Mattheus-Moerman** [comment]
Yeah still tiny. It is fixed if I resize or refresh the page. 

![Peek 2019-08-08 16-03](https://user-images.githubusercontent.com/8392709/62714287-2f68c700-b9f6-11e9-9429-a1063326361f.gif)

**Comment by arfon** [comment]
@xuanxu - might changing https://github.com/openjournals/joss/blob/searchkick/app/assets/javascripts/papers.coffee#L27 to  `$(window.ready) ->` help here? I'm wondering if the function to resize the height is being called too soon.

**Comment by arfon** [comment]
@remram44 @Kevin-Mattheus-Moerman - could you take another quick look? I tried modifying the JavaScript on the page load.

Also, sorry I have to keep pinging you for feedback - I can't replicate this in Firefox locally :grin:

**Comment by xuanxu** [comment]
@arfon I’m not sure, `$()` is a shortcut for `$(document).ready()` so I’d expect no changes. Maybe we should wait not for the page but for the embed pdf reader to be loaded...

**Comment by arfon** [comment]
> Maybe we should wait not for the page but for the embed pdf reader to be loaded..

Right. I'm not sure if that's possible though for `<object>` embeds like we're doing. I might need to switch to using PDF JS to fix this...

**Comment by remram44** [comment]
The size is good now (but I changed location and this might be a timing issue, maybe faster internet plays a role?)

**Comment by xuanxu** [comment]
> I might need to switch to using PDF JS to fix this...

Naah, I'm sure we can fix it with the current object. Let me try a couple things.

**Comment by Kevin-Mattheus-Moerman** [comment]
@arfon it seems fixed for me now. The PDF views are immediately large enough.

**Comment by arfon** [comment]
@remram44 - @xuanxu made an even better fix in https://github.com/openjournals/joss/pull/577 - can you confirm this fixes things for you?

**Comment by remram44** [comment]
I can confirm I don't experience the problem anymore! Thank you everyone :smiley:

**Comment by arfon** [comment]
✨
