### ISSUE TITLE
Add ISSN to About page and/or footer

### ISSUE THREAD

**Issue by labarba** [openjournals/joss#579]
The journal ISSNs could be displayed on the paper-view page, perhaps also in the paper PDF (footer) and somewhere on the main web page. (Can be tiny font, but it should be there somewhere.)

I couldn't find the ISSN listed anywhere on the site, actually. It should probably be on the About page somewhere.

**Comment by arfon** [comment]
This is already on the about page in the first paragraph:

> The Journal of Open Source Software (JOSS) is an academic journal (ISSN 2475-9066) with a formal peer review process that is designed to improve the quality of the software submitted. Upon acceptance into JOSS, a Crossref DOI is minted and we list your paper on the JOSS website.

With https://github.com/openjournals/joss/commit/0363e569e7415620a2b2ac1070d3810d9fe805f7 it's also now on the footer throughout the site.
