### ISSUE TITLE
Link to pdf to open new tab

### ISSUE THREAD

**Issue by arokem** [openjournals/joss#593]
Small suggestion: could we make the link to the PDF that whedon posts into pre-/review issues open a new tab, rather than navigating away from the current tab?

**Comment by arfon** [comment]
Unfortunately GitHub won't allow this. See for example, a link that's crafted with the `target="_blank"` attribute:

<a href='https://github.com/openjournals/joss-papers/blob/joss.01662/joss.01662/10.21105.joss.01662.pdf' target='_blank'>:point_right: Check article proof :page_facing_up: :point_left: </a>

**Comment by arokem** [comment]
Hmm. That's too bad.

**Comment by arfon** [comment]
Yeah, I'm pretty sure this is a non-starter sorry.

**Comment by jedbrown** [comment]
We could link directly to the raw (depending on local PDF rendering) instead of GitHub's rendering (which doesn't support text search).

**Comment by leouieda** [comment]
@jedbrown that would trigger a download instead. I've had some luck with this by putting the PDF in a ``

**Comment by jedbrown** [comment]
@leouieda Yeah, GitHub works hard to distinguish their repositories from general-purpose static hosting. The fact remains that GitHub's PDF viewer is very bad (no search being the most acute problem) and the process is a bit cumbersome to follow links to get the PDF in a better viewer.
