### ISSUE TITLE
adjusting COI review criterion

### ISSUE THREAD

**Issue by danielskatz** [openjournals/joss#603]
We currently have as our first review criterion:

> As the reviewer I confirm that I have read the JOSS conflict of interest policy and that there are no conflicts of interest for me to review this work.

I suggest we change this to:

> As the reviewer I confirm that I have read the JOSS conflict of interest policy and that either there are no conflicts of interest for me to review this work, or that any conflicts have been identified and waived by JOSS for the purpose of this review.

Since we do sometimes have a reviewer with a conflict, they can't really check the first criterion as it is now worded - this fix would enable them to do so.

**Comment by arfon** [comment]
Shipped in #604
