### ISSUE TITLE
Login problem can JOSS be a standalone application

### ISSUE THREAD

**Issue by programmerommy** [openjournals/joss#608]
Hi
I have succeffuly forked the application in localhost but i fail to register its taking me
to https://orcid.org/signin?oauth&client_id= and its failing totally it can not load this Sign or Register page.Login and register page not loading.

**Comment by programmerommy** [comment]
I have successfully forked this application,forking this application in ubuntu you need to have ruby on rails installed you have to change the ruby gem file 2.5.1 and run bundle install and install any missing gems untill when you run bundle install is complete.You need to create a postgress username and password and update in database.yml. You also need to create postgress database before migrating the  database rake db:migrate also running bundle exec.

**Comment by arfon** [comment]
Hi @programmerommy - sorry the docs aren't great for setting up this application, that said, it's a fairly vanilla Ruby on Rails application so you should be able to make good progress getting up and running by reading Rails tutorials etc.

To your question about auth. The [omniauth gem](https://github.com/openjournals/joss/blob/master/Gemfile#L15) needs environment variables configured to load properly. You can read more about that here: https://github.com/datacite/omniauth-orcid

**Comment by programmerommy** [comment]
Thank you very much @arfon  i will look at it you saved my day.
