### ISSUE TITLE
I'd like to review for JOSS

### ISSUE THREAD

**Issue by ctb** [openjournals/joss#61]
Let's make academic software great again!

**Comment by arfon** [comment]
Hi @ctb. Many thanks for offering to review for [The Journal of Open Source Software](http://joss.theoj.org/).

There's a couple of things we'd like you to do at this point:

-  Accept the invite to join the 'joss-reviewers' [team](https://github.com/orgs/openjournals/teams/joss-reviewers) on GitHub that you should have received.
- Familiarize yourself with the JOSS [reviewer guidelines](http://joss.theoj.org/about#reviewer_guidelines)

**Volunteering for reviews**

When JOSS receives new submissions we will mention the joss-reviewers team (e.g. / cc @openjournals/joss-reviewers) in the review thread. You can see the submissions we've already received here: https://github.com/openjournals/joss-reviews/issues

Please keep an eye on your GitHub notifications for the https://github.com/openjournals/joss-reviews repository and if you think you would be able to review the submitted software please reply on the submission issue. 

Once again, thanks for volunteering to help out, we're delighted to have you on board!

If you have any questions, please don't hesitate to either reply on this thread or email directly on arfon.smith@gmail.com
