### ISSUE TITLE
Enzo paper has incorrect tags

### ISSUE THREAD

**Issue by bwoshea** [openjournals/joss#613]
The Enzo JOSS method paper (at https://joss.theoj.org/papers/10.21105/joss.01636) currently has three tags: Perl, IDL, and Prolog.  None of these are accurate - the appropriate tags should be C++, C, and Fortran.  Is it possible to update these?

**Comment by danielskatz** [comment]
I'm confident @arfon can fix this

**Comment by arfon** [comment]
Fixed!

**Comment by bwoshea** [comment]
Thank you, @danielskatz and @arfon !
