### ISSUE TITLE
Pre-submission enquiry: mummify

### ISSUE THREAD

**Issue by maxhumber** [openjournals/joss#615]
**Repo**: [mummify](https://github.com/maxhumber/mummify)

mummify is a research tool that helps accelerate the model prototyping process. The library takes care of git and logging management for research and machine learning projects so that the developer can focus on what's important.

**Fit**:

> JOSS publishes articles about research software. This definition includes software that: solves complex modeling problems in a scientific context (physics, mathematics, biology, medicine, social science, neuroscience, engineering); supports the functioning of research instruments or **the execution of research experiments**; extracts knowledge from large data sets; offers a mathematical library, or similar.

mummify likely fits into the **the execution of research experiments** category.

Looking forward to your feedback!

**Comment by arfon** [comment]
Hi @maxhumber - thanks for your enquiry. This looks like a useful piece of software but I think it would likely fall into our _minor utility_ category sorry (i.e. not in scope).
