### ISSUE TITLE
Pre-submission enquiry: gazpacho

### ISSUE THREAD

**Issue by maxhumber** [openjournals/joss#616]
**Repo**:  [gazpacho](https://github.com/maxhumber/gazpacho)

gazpacho is a web scraping library that enables rapid prototyping for extracting large amounts of data from any website. The library is small, simple, and consistent. And it outperforms popular alternatives on several speed tests while, at the same time, providing a more simple and unified interface to the researcher/developer.

**Fit**:

> JOSS publishes articles about research software. This definition includes software that: solves complex modeling problems in a scientific context (physics, mathematics, biology, medicine, social science, neuroscience, engineering); supports the functioning of research instruments or the **execution of research experiments**; **extracts knowledge from large data sets**; offers a mathematical library, or similar.

gazpacho likely fits into the **execution of research experiments** and **extracts knowledge from large data sets** categories.

Looking forward to your feedback!

**Comment by arfon** [comment]
Hi @maxhumber - thanks for your enquiry. This looks like a useful piece of software but I think it would likely fall into our _minor utility_ category sorry (i.e. not in scope).
