### ISSUE TITLE
Support for previewing a particular commit in a repository

### ISSUE THREAD

**Issue by DRMacIver** [openjournals/joss#617]
The new [preview page](http://whedon.theoj.org/) is very nice. However, it currently seems to assume that the paper is on the master branch. Would it be possible to have it preview a version at a particular commit? Or, if it is currently possible, could that be documented?

The context is that I'm currently putting together a submission for [hypothesis](https://github.com/HypothesisWorks/hypothesis/). We have a fairly strict pull request workflow, and it would be nice if we could preview the paper *before* it is merged to master as part of our review and/or CI workflow.

**Comment by arfon** [comment]
We currently have limited support for compiling at the HEAD of a different branch. Would that work here?

**Comment by DRMacIver** [comment]
> We currently have limited support for compiling at the HEAD of a different branch. Would that work here?

Yes, that would be fine, I mostly just want a way of previewing before we merge the branch so using the head of a particular pull request would work fine.

**Comment by arfon** [comment]
OK, I've added a field for specifying a custom branch. Can you try that our @DRMacIver? http://whedon.theoj.org

**Comment by DRMacIver** [comment]
> OK, I've added a field for specifying a custom branch. Can you try that out @DRMacIver? http://whedon.theoj.org

Works great, thanks! (Or rather it fails to compile, but I think that's correct behaviour in this context, which is exactly why I wanted to be able to preview!)

**Comment by arfon** [comment]
> Works great, thanks! (Or rather it fails to compile, but I think that's correct behaviour in this context, which is exactly why I wanted to be able to preview!)

Exactly! 😁
