### ISSUE TITLE
Add new author to existing article/software

### ISSUE THREAD

**Issue by chtheodoro** [openjournals/joss#620]
Hello,

is it possible to add new authors to existing article/software?

One of my colleagues will build a graphical user interface for my software published in JOSS
https://joss.theoj.org/papers/10.21105/joss.00082
and I would like to add him as an author...

Is this possible in JOSS?

**Comment by kyleniemeyer** [comment]
@chtheodoro if your colleague was not involved in the development of the software when it was published in JOSS, then it wouldn't be appropriate to add them at a later point—the publication recognizes the effort that has gone into the software up to that point.

However, if you add substantially different functionality (for example) and release a major update at a later point, then it would be appropriate to submit a follow on paper for that version, which would include authors that contributed to the new work.

**Comment by chtheodoro** [comment]
Thanks @kyleniemeyer ! Seems rational :)
