### ISSUE TITLE
JOSS website should have a clear "donate" button/link

### ISSUE THREAD

**Issue by danielskatz** [openjournals/joss#623]
I was thinking of tweeting that people should consider donating to JOSS, but our front page doesn't have button or line - we are good at putting "volunteer to review" buttons around, but not donate...

Also, the about page has a cost section that talks about donations, but no way to donate from there.

**Comment by danielskatz** [comment]
#627 was a partial solution, but as I wrote there, can we also add a more prominent "donate" link, perhaps in the right column index/toc on the about page?  (the small badge is very small and very hidden down at the bottom)

**Comment by arfon** [comment]
OK, I just tried to improve this in https://github.com/openjournals/joss/commit/e882afbb5c472d9ea9b931cc98d05d1e0f639679

<img width="1484" alt="Screen_Shot_2019-12-11_at_6_22_07_PM" src="https://user-images.githubusercontent.com/4483/70669044-4426c700-1c43-11ea-89a6-094fa94d789c.png">

**Comment by danielskatz** [comment]
thanks magic issue genie - this looks good!

I'm happy for that to be merged and this issue to be closed
