### ISSUE TITLE
Automate hunting for DOIs?

### ISSUE THREAD

**Issue by majensen** [openjournals/joss#629]
@briatte [suggested](https://github.com/cimentadaj/perccalc/issues/2#issuecomment-544239961) that whedon might do more to help find DOIs. That would be cool.

**Comment by arfon** [comment]
@majensen - more that Whedon can do already? (e.g. https://github.com/openjournals/joss-reviews/issues/1796#issuecomment-553592478)

**Comment by majensen** [comment]
Ooh maybe I and @briatte need a pro tip about that...?

**Comment by majensen** [comment]
I think we got it at https://github.com/openjournals/joss-reviews/issues/1796#issuecomment-553592249

**Comment by arfon** [comment]
So Whedon checks DOIs when editors prepare the final proof of a paper with `@whedon accept` but it might need to be better documented :-)

You can ask Whedon to check references at any time with `@whedon check references` ([docs](https://joss.readthedocs.io/en/latest/whedon.html)).

**Comment by danielskatz** [comment]
It's documented as an editor step after reviewers recommend acceptance - see https://joss.readthedocs.io/en/latest/editing.html#after-reviewers-recommend-acceptance

**Comment by danielskatz** [comment]
@majensen - Can we close this issue?

**Comment by briatte** [comment]
> It's documented as an editor step after reviewers recommend acceptance - see https://joss.readthedocs.io/en/latest/editing.html#after-reviewers-recommend-acceptance

It often is the case that reviewers will mention missing DOIs in their reviews. Perhaps a DOI check could be done to manuscripts before the reviewing starts?

**Comment by arfon** [comment]
> It often is the case that reviewers will mention missing DOIs in their reviews. Perhaps a DOI check could be done to manuscripts before the reviewing starts?

That's a good idea. We can do this at the start of the review process.

**Comment by arfon** [comment]
Added in https://github.com/openjournals/whedon-api/commit/fb4551927b1cc37f3c3791745049732f6d2933ac
