### ISSUE TITLE
Paper preview not downloading

### ISSUE THREAD

**Issue by khdusenbury** [openjournals/joss#633]
We recently submitted a paper to JOSS, but were not able to visualize our paper using the preview service. 

The preview service indicates that our paper successfully compiles, but when we click on the 'download preview' link, it takes us to http://whedon.theoj.org/%7B%7D, which shows a 'Not Found' error. 

Our paper and repo are [here](https://github.com/jbloomlab/alignparse/tree/master/paper) for reference, in case it's something with how we have it set up. Thanks for your help.

**Comment by arfon** [comment]
Looks like Whedon was falsely saying it could compile the paper when it actually couldn't - apologies for any confusion caused.

The fix for your paper is in https://github.com/jbloomlab/alignparse/pull/52

**Comment by artgoldberg** [comment]
Hello JOSS

I'm preparing a paper for JOSS and am also unable to visualize it with the preview service. As with the issue above, no preview is provided. Instead, when clicking on the preview link, I get "Not Found" at the link https://whedon.theoj.org/%7B%7D

I presume that my paper and/or bib file have formatting problems. but would like the problem(s) identified so that I can fix them.

Thanks
Arthur

PS. The paper and bib are in https://github.com/KarrLab/de_sim/tree/master/joss_paper

**Comment by arfon** [comment]
This seems to work fine for me @artgoldberg. Please make sure you're just putting the repository address in the field and not the full path to the folder with the paper (see the screenshot below for how I tested your paper):

<img width="1433" alt="Screen Shot 2020-06-17 at 5 17 00 PM" src="https://user-images.githubusercontent.com/4483/84951496-829fb180-b0be-11ea-9f92-f632272b7ac1.png">

**Comment by artgoldberg** [comment]
Thank you Afron. You identified my problem correctly. I interpreted the field heading on https://whedon.theoj.org/`Paper repository address` to mean "address (URL) of the paper in the repository".

**Comment by arfon** [comment]
> Thank you Afron. You identified my problem correctly. I interpreted the field heading on https://whedon.theoj.org/`Paper repository address` to mean "address (URL) of the paper in the repository".

Glad that fixed it. Yeah, I realize this is confusing. We plan in the future to try and have the UI check that the field is valid before attempting to compile the paper (and possibly failing silently).

**Comment by artgoldberg** [comment]
Thanks!
