### ISSUE TITLE
generated crossref XML missing linebreaks in citations

### ISSUE THREAD

**Issue by danielskatz** [openjournals/joss#634]
This makes it hard for an AEiC to check the xml file
For example, 
joss.01891/10.21105.joss.01891.crossref.xml
in
https://github.com/openjournals/joss-papers/pull/1118/files
has
```
        <citation_list> <citation key="ref1"> <doi>10.1145/351240.351266</doi> </citation> <citation key="ref2"> <doi>10.1145/1159789.1159792</doi> </citation> <citation key="ref3"> <unstructured_citation>In Praise of Property-Bsed Testing, ://increment.com/testing/in-praise-of-property-based-testing/, 2019, MacIver, David R.</unstructured_citation> </citation> <citation key="ref4"> <doi>10.1109/32.988498</doi> </citation> <citation key="ref5"> <doi>10.1145/2254064.2254104</doi> </citation> <citation key="ref6"> <doi>10.3847/1538-3881/aabc4f</doi> </citation> <citation key="ref7"> <doi>10.1109/MCSE.2011.37</doi> </citation> <citation key="ref8"> <doi>10.1145/3092703.3092711</doi> </citation> </citation_list>
```

**Comment by danielskatz** [comment]
I notice that the same problem occurs with authors - all authors are on one line of the XML file. This really makes it hard to review in the github interface, which by default does not wrap the long lines that are being generated, and also, this makes it hard to check tags

**Comment by arfon** [comment]
Yeah, this is a recent change which is the result of trying to fix a long-standing issue with the encoding of data passed into Pandoc. I realize this is sub-optimal and will investigate how to address this.

**Comment by arfon** [comment]
This should be fixed by https://github.com/openjournals/whedon/commit/cd7dadefdab33166c6b519828d85729004af656a

**Comment by danielskatz** [comment]
thanks!
