### ISSUE TITLE
Name incorrect in Welcome to the Tidyverse: https://doi.org/10.21105/joss.01686

### ISSUE THREAD

**Issue by LucyMcGowan** [openjournals/joss#635]
For some reason my name is not correct in the new Welcome to the Tidyverse paper (https://joss.theoj.org/papers/10.21105/joss.01686). I apologize if this is not the best place for me to bring this to your attention, I'm happy to redirect as needed! I think it was right yesterday, but somehow got wonky this morning. For what it's worth, my ORCID is correct. It is in as Lucy D'Agostino O'Leary in the pdf - my name is Lucy D'Agostino McGowan.

**Comment by arfon** [comment]
I'm so sorry about this @LucyMcGowan. I was trying to debug an issue with another author earlier today (on another paper) and it looks like I accidentally hard-coded their last name into the template.

This is now fixed but might take a few hours to show up as fixed as there is caching in place for the JOSS PDFs.

**Comment by LucyMcGowan** [comment]
haha no problem! ☘️
