### ISSUE TITLE
Suggestion for JOSS: metadata for Zotero

### ISSUE THREAD

**Issue by psmbln** [openjournals/joss#641]
Hi everyone,

I am using Zotero as a reference manager:
https://www.zotero.org/

Zotero tries to import embedded metadata from article landing pages, but this doesn't seem to work very well yet for JOSS articles. Please have a look into this; it would be great for a software journal to interact seamlessly with bibliographic tools.

Thanks and kind regards,
Paul Schultze-Motel

**Comment by psmbln** [comment]
more specifically:
- Item Type is recognised as "Web Page" (should be: "Journal Article") -> this leads to missing entries in fields 
  -"ISSN"
  - "Volume"
  - "Issue"
  - "Page"
  - DOI is mapped to "Extra" (instead of "DOI")
- URL is recognised incompletely

**Comment by arfon** [comment]
Thanks for reporting this @psmbln. Can you take a look again now that we've updated the Item Type in #642?

**Comment by psmbln** [comment]
Thanks - I have now tested the metadata import to Zotero with a recent JOSS article (cf. attached screenshot).

![driscoll2019_zotero](https://user-images.githubusercontent.com/29654660/70308771-47b5ea80-180c-11ea-8b78-29e7439abbba.png)

The issues above are now fixed, exept:
- URL is recognised incompletely

One more thing:
- the abstract is possibly not recognised correctly; in the "Abstract" field, there is instead a citation of the article

**Comment by arfon** [comment]
Thanks for helping us debug this @psmbln!

> URL is recognised incompletely

This should be fixed now. Do you think you could check again?

> the abstract is possibly not recognised correctly; in the "Abstract" field, there is instead a citation of the article

Right. This is going to be an issue as JOSS papers don't have abstracts. I'm not sure what we can do about this one...

**Comment by psmbln** [comment]
Great, thank you - the complete URL is now recognised by Zotero.

About the abstracts: if there is no abstract, would it be possible to leave the "Abstract" field empty?

**Comment by arfon** [comment]
> About the abstracts: if there is no abstract, would it be possible to leave the "Abstract" field empty?

I'm guessing it's picking up the `meta property="og:description"` field in the HTML and using that as the content for the abstract. 

```
<meta property="og:description" content="Driscoll, (2019). ComplexRegions.jl: A Julia package for regions in the complex plane. Journal of Open Source Software, 4(44), 1811, https://doi.org/10.21105/joss.01811" />
```

If there another tag for `abstract` that we can use (and leave empty) that Zotero would pick up that instead we could do that but I'd like to keep the `og:description` field as it is as these tags are used by platforms other than just Zotero (e.g. facebook).

**Comment by arfon** [comment]
I've been doing a little more digging and I don't think there's a _preferred_ tag we can use here for the actual `abstract` without replacing what we're currently doing with the `og:description`.

I'm therefore going to close this. Anyone should free to update this issue if they find possible solutions to this.
