### ISSUE TITLE
change template comments and documentation to avoid authors tagging potential reviewers

### ISSUE THREAD

**Issue by danielskatz** [openjournals/joss#643]
We should change our template comments that are created with a new pre-review issue, and also our documentation for authors and editors to strongly urge authors not to tag potential reviewers.  We should be clear that they should suggest reviewer1, not @reviewer1

**Comment by danielskatz** [comment]
In the first comment in a new prereview issue, we should replace
> if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, this list of people have already agreed to review for JOSS and may be suitable for this submission.

with
> if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, this list of people have already agreed to review for JOSS and may be suitable for this submission.

**Comment by danielskatz** [comment]
Also, in https://joss.readthedocs.io/en/latest/editing.html#overview-of-editorial-process in step 6, we should add
"If you ask the author to suggest reviewers, please be sure to tell the author not to @-tag their suggestions"

**Comment by danielskatz** [comment]
I've put the second in https://github.com/openjournals/joss/pull/644

**Comment by arfon** [comment]
The first is now in #644 too.

**Comment by arfon** [comment]
Thanks for this @danielskatz. This is now deployed.
