### ISSUE TITLE
Content tables included in paper.md

### ISSUE THREAD

**Issue by oschwengers** [openjournals/joss#652]
Hi,
I'm considering submitting a paper containing a table.

In this table I need to wrap rather long species names + identifier over at least 2 lines.

Example:
| Genome | Genome Size `<br>`  [kb] | Laptop `<br>` [m:s] | Server `<br>` [m:s] | # RG |
|--------|:-------------------:|:---------------:|:---------------:|-----:|
| *Escherichia coli* str. K-12 substr. MG1665 `<br>` (GCF_000005845.2) | 4,641 | 3:24 | 0:30 | 100* |

Does someone know, how to do this? a simple `<br>` was ignored by the PDF compiler.
Any hints are highly welcome.
Thanks a lot in advance and best regards!

**Comment by arfon** [comment]
I'm not sure sorry. I'm assuming you're testing out changes on the Whedon site here? http://whedon.theoj.org

I'd suggest digging around on e.g. Stackoverflow about pandoc and tables to seek solutions to this.

**Comment by oschwengers** [comment]
Thanks @arfon , I'll give it a try.

**Comment by oschwengers** [comment]
So far I couldn't find an acceptable solution. Does someone else have an idea?

@arfon Does JOSS use pandoc to compile the PDFs?

**Comment by arfon** [comment]
> @arfon Does JOSS use pandoc to compile the PDFs?

Yes. That's what we're using under the hood. I wonder if it's possible to fall back to a LaTeX table?

**Comment by oschwengers** [comment]
@arfon Ok, I finally found a proper way: https://pandoc.org/MANUAL.html#tables (Extension: multiline_tables)

Maybe I missed out something in first place. Thanks for the hints!
