### ISSUE TITLE
Paper about a software that is part of a larger package.

### ISSUE THREAD

**Issue by lindenb** [openjournals/joss#654]
Hi all, 

I'd like to write a paper about a software that is part of a package containing [many unrelated software](http://lindenb.github.io/jvarkit/). What would be the best place to put the `paper.md` ?

In a sub-directory like `papers/mytool/paper.md` ? then how should I tell the path to https://whedon.theoj.org/ ?

Or creating a very new project with a link to my main repo ? (sounds weird)

Thank you for your help,

Best regards,

P.

**Comment by arfon** [comment]
The `paper.md` file can be anywhere in the repository. Whedon [knows how to look for it](https://github.com/openjournals/whedon/blob/a7f2cab555ea56c26022f24b3bd5b28503fb24e5/lib/whedon/processor.rb#L57).

**Comment by lindenb** [comment]
Ah!  and it looks it will ask me which paper to compile ! https://github.com/openjournals/whedon/blob/01ece1d1d135eb8993fb6422ccaa96a056d4a7d5/bin/whedon#L60

very cool !

thanks

**Comment by arfon** [comment]
> Ah! and it looks it will ask me which paper to compile ! https://github.com/openjournals/whedon/blob/01ece1d1d135eb8993fb6422ccaa96a056d4a7d5/bin/whedon#L60

This is only exposed when using Whedon on the command line. Otherwise (as the Whedon bot), Whedon just picks the first paper. Let me know if you run into any issues.
