### ISSUE TITLE
Whedon does not provide meaningful error messages

### ISSUE THREAD

**Issue by arcuri82** [openjournals/joss#657]
Hi,
  I am working on a JOSS submission, but fail to compile the PDF preview in Whedon.
From [https://whedon.theoj.org/]() I m trying the following.

Paper repository address: `https://github.com/EMResearch/EvoMaster`
Custom branch (optional): `joss-paper`

And what I get is:

```
Your paper failed to compile with the following errors:

{}
```
  
Unfortunately, `{}` does not really provide me any hint on what is the problem with my paper files :(

**Comment by arfon** [comment]
Yep, sorry about this. This is a [known issue](https://github.com/openjournals/whedon-api/issues/73).

As for this paper, I think you need to remove completely the blank `orcid` lines e.g. ones that look like this:

```
orcid:
```

Also, the paper can be anywhere in the repository (it doesn't need to be in a folder named `paper`)

**Comment by arcuri82** [comment]
thanks for the quick reply! Removing the blank `orcid` fixed the problem
