### ISSUE TITLE
rejection workflow not clear to editors

### ISSUE THREAD

**Issue by danielskatz** [openjournals/joss#660]
When an editor rejects a submission by just rejecting it, it messes up the database. We need to define and document a workflow by which editors ask eics to do the actual rejection, and that the steps the eics should take include: 1. labeling the submission as rejected, 2. closing the pre-review or review issue, and 3. setting the database to indicate that the submission has been rejected, via the dashboard

**Comment by arfon** [comment]
Now addressed in https://joss.readthedocs.io/en/latest/editing.html#rejecting-a-paper
