### ISSUE TITLE
Encourage contributions to existing packages

### ISSUE THREAD

**Issue by danielskatz** [openjournals/joss#664]
To encourage contributions to be made to existing packages, rather than creating new standalone packages, we likely need changes in our docs to call for it, and maybe changes in whedon to support it

**Comment by arfon** [comment]
Just thinking this through a little, are we saying that this should be part of the scope assessment carried out by editors/reviewers etc? 

> The software should be a significant contribution to the available open source software that either enables some new research challenges to be addressed or makes addressing research challenges significantly better (e.g., faster, easier, simpler).

We could potentially highlight this in the statement above?

**Comment by danielskatz** [comment]
I think this is correct, but also seems a little disconnected from the overall point of the issue

**Comment by danielskatz** [comment]
maybe we put something in the submission docs or more general docs like:

While we are happy to review submissions in standalone repositories, we also review submissions that are significant contributions made to existing packages. It is often better to have an integrated library or package of methods than a large number of single-method packages.

**Comment by danielskatz** [comment]
We've never been able to define that in an absolute manner

**Comment by pdebuyl** [comment]
Fair enough.

**Comment by jedbrown** [comment]
We've refrained from a quantitative line of code standard or the like, but if it feels like a lot less than a journal publication, it probably is.

**Comment by kyleniemeyer** [comment]
I'll just add that generally we leave this decision up to the authors, but we can and should point out discrepancies in either direction if we see them.

**Comment by arfon** [comment]
OK, I've added some suggested language in #748.
