### ISSUE TITLE
Pre-submission enquiry

### ISSUE THREAD

**Issue by AndrewAnnex** [openjournals/joss#666]
https://github.com/AndrewAnnex/SpiceyPy

Hello, I am interested in submitting SpiceyPy to JOSS for review but had a few questions:

1. Given SpiceyPy is a wrapper for a library, is it in scope for JOSS?
2. I have a number of small contributors (1 commit) and I am unsure if they all should be included as co-authors. I'm all for being inclusive but I am wondering if there is a well understood threshold in JOSS. 
3. Should the paper.md, paper.bib, and codemeta.json be placed in the root directory or in a subdirectory?
4. How should works using SpiceyPy be cited/referenced in the JOSS submission? In the draft I sort of list generalities of things people are using SpiceyPy with and plan to cite those papers in the paragraph, but without an explicit enumeration of what specifically each paper did and how they used SpiceyPy and etc.

**Comment by kyleniemeyer** [comment]
Hi @AndrewAnnex, thanks for your interest. 

1. The two relevant requirements for submissions to JOSS to be within scope are:
- The software should be a significant contribution to the available open source software that either enables some new research challenges to be addressed or makes addressing research challenges significantly better (e.g., faster, easier, simpler).
- The software should be feature-complete (no half-baked solutions) and designed for maintainable extension (not one-off modifications). Minor ‘utility’ packages, including ‘thin’ API clients, are not acceptable.

I took a quick look, and also asked the JOSS editorial board for some feedback, and while your package is a wrapper, it is a substantial effort with a good test suite—so we would consider this in scope.

2. We let projects decide who to include as authors on the article. Some projects take a very inclusive approach to this and include anyone who has made any contribution, while others only include the major contributors/developers. In a case like this, it would be fine to not include folks who made very minor contributions as authors. 

3. These can be anywhere, whedon will find it. Frequently people include them in a `paper` directory, but this isn't required.

4. You don't need to go into a lot of detail, but certainly a few sentences with citations talking about works that use the package would be nice for context.

**Comment by AndrewAnnex** [comment]
thanks @kyleniemeyer, I'll think more about the co-author situation and will look into submitting within the next few days (I have the paper mostly written). feel free to close this issue, otherwise I'll close it when I submit
