### ISSUE TITLE
whedon preview, unclear error

### ISSUE THREAD

**Issue by nathanlyons** [openjournals/joss#668]
Along the lines of #657, I do know why my paper is failing to compile.

The repo is https://github.com/landlab/landlab

The branch is nathanlyons_species_evolver_joss_review

Suggestions on the cause of compilation errors?

**Comment by arfon** [comment]
@nathanlyons - can you change the URL of the figure to `https://raw.githubusercontent.com/landlab/landlab/nathanlyons_species_evolver_joss_review/joss/species_evolver/fig_zones.png`

**Comment by nathanlyons** [comment]
Changed the paper.md link in the figure to the url you provided. I still get

```
Your paper failed to compile with the following errors: 

Looks like we failed to compile the PDF.
```

**Comment by arfon** [comment]
This should fix it: https://github.com/landlab/landlab/pull/1114

**Comment by nathanlyons** [comment]
Many thanks @arfon, that did fix it.
