### ISSUE TITLE
Optioinal info is displayed too prominently on JOSS website

### ISSUE THREAD

**Issue by jakevdp** [openjournals/joss#67]
The optional info in the submission form has this description:

> Please add any notes here for the editor for example, where in your repository the paper.md file is. Please note that this contents will *not* be reviewed by the JOSS reviewers"

The text entered here is then posted prominently [on the JOSS landing page](http://joss.theoj.org/), which is probably not ideal.

**Comment by jakevdp** [comment]
Seems to have been changed now

**Comment by arfon** [comment]
Yep, I've removed it for now.
