### ISSUE TITLE
> formatted_doi in template

### ISSUE THREAD

**Issue by embruna** [openjournals/joss#672]
> That would be useful - either removal from the template OR a note that it should be deleted.

So this field _is_ included in a template somewhere? If so, could you please point me to it?

_Originally posted by @arfon in https://github.com/openjournals/joss-reviews/issues/2028#issuecomment-578242951_

@arfon @kyleniemeyer Sorry to make a new issue, but the previous thread (#2028) where a request to point to location of formatted_doi in template was closed. 
___
It took me a bit, but i figured it out why there was a blank `formatted_doi` in my YAML header.  Package `rticles` includes RMarkdown templates for various journals, including JOSS. The template isn't blank - it's the[ example provided on the JOSS page](https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography). However, the `rticles` template includes the formatted doi for the final version (see image below). To prep my submission I replaced the text in all fields of the template with my own except the doi, which I left blank because I assumed I would need to fill that in manually after acceptance.         

![image](https://user-images.githubusercontent.com/4655487/73282605-e254f900-41bf-11ea-98c5-0aae1c7b153f.png)

My guess is others generating the template via `rticles` might do the same, especially if (like me).  Maybe a pull request to `rticles` to make the template a generic one with instructions, rather than one from an accepted paper? Might be useful to have the same on the JOSS webpage.  

FWIW I really like the JOSS submission and review process.

**Comment by kyleniemeyer** [comment]
@embruna thanks for identifying where the issue came from—looks like the JOSS template on `rticles` needs to be corrected to remove that field.

**Comment by arfon** [comment]
> @embruna thanks for identifying where the issue came from—looks like the JOSS template on `rticles` needs to be corrected to remove that field.

Right. I'm happy to propose this change @embruna if you can point us to the template.

**Comment by embruna** [comment]
I think the best way to request a change in the template is via a pull request or issue on the [`rticles` package repo](https://github.com/rstudio/rticles)?

**Comment by arfon** [comment]
This is now fixed as of https://github.com/rstudio/rticles/pull/272
