### ISSUE TITLE
Recent ships

### ISSUE THREAD

**Issue by arfon** [openjournals/joss#674]
I thought it might be good for @openjournals/dev start documenting updates/improvements that have been made recently to JOSS/Whedon etc. in a semi-regular fashion so here's a summary of what's happened recently:

**Better support for BibTeX in JOSS & JOSE UI**: There's now a couple of links on the JOSS and JOSE paper view which allows for copying of the citation string (the thing shown in the UI) or a BibTeX entry.

<img width="560" alt="Screen_Shot_2020-02-07_at_10_24_30_AM" src="https://user-images.githubusercontent.com/4483/74042831-459c1380-4996-11ea-81bf-dc03168c36d7.png">

**Sortable table on editor dashboard**: It's now possible to sort the list of editors by the number of assignments they have on the dashboard.

<img width="1494" alt="Screen_Shot_2020-02-07_at_10_24_08_AM" src="https://user-images.githubusercontent.com/4483/74042918-6bc1b380-4996-11ea-805c-c83d20d656b6.png">

**EiC information now shown on pre-review issue**: The `pre-review` issue now shows which EiC opened up this issue on GitHub https://github.com/openjournals/joss/pull/669

**Whedon support for withdrawing and rejecting papers**: Papers can now be rejected and withdrawn by Whedon https://github.com/openjournals/joss/pull/662 https://github.com/openjournals/joss/pull/671 https://github.com/openjournals/whedon-api/pull/81 https://github.com/openjournals/whedon-api/pull/79

**Better errors in Whedon paper preview service**: Whedon now reports errors properly in the [preview service](http://whedon.theoj.org) https://github.com/openjournals/whedon-api/pull/80

**Email invites for authors**: It's now possible to invite editors to edit a paper, with an automated email sent to them https://github.com/openjournals/joss/pull/673 https://github.com/openjournals/whedon-api/pull/82

**Repository statistics now reported in pre-review issue**: In order to help editors make decisions about whether submissions are in scope, Whedon now reports some summary statistics in the `pre-review` thread about the repository https://github.com/openjournals/whedon-api/pull/77

/ cc @openjournals/jose-editors @openjournals/joss-editors

**Comment by labarba** [comment]
https://twitter.com/LorenaABarba/status/1225814899969941505?s=20

**Comment by danielskatz** [comment]
Re the first upgrade, which is great, a future next step would be to have a pulldown where the citation could be exported in a variety of formats - I think @mfenner knows how to do this...

**Comment by arfon** [comment]
> I think @mfenner knows how to do this...

Ooo yeah. That would be great. @mfenner any suggestions how to best accomplish this? The views are built with Ruby/Rails so some kind of gem would be great. Otherwise a JavaScript thing could work too.

**Comment by mfenner** [comment]
The easiest way to do this is to use DOI content negotiation to get back the formatted citation, works in any language :). What we have done in DataCite Search and Crossref Metadata Search (originally same source code at https://github.com/crosscite/doi-metadata-search) is hardwire some common styles in a Javascript popup window. You could of course do something similar in a Ruby view.

Crossref and DataCite currently run a separate backend service for citation formatting, but the DataCite service (source code at https://github.com/crosscite/content-negotiation) supports Crossref DOIs, and is arguably better maintained.

DataCite content negotiation supports providing the content type via header or via path:

```
curl -LH "Accept: "text/x-bibliography; style=ieee" https://data.crosscite.org/10.21105/joss.02004
```
or

https://data.crosscite.org/text/x-bibliography/10.21105/joss.02004?style=ieee

Our content negotiation of course also supports bibtex:

https://data.crosscite.org/application/x-bibtex/10.21105/joss.02004

**Comment by mfenner** [comment]
For a tighter integration you could also use the `bolognese` gem (which powers our content-negotiation and citation formatting), but that is probably overkill. https://github.com/datacite/bolognese

**Comment by labarba** [comment]
>  a future next step would be to... 

The next step is to write out a roadmap, and place feature ideas and requests in some form of priority list. Otherwise important dev work that is harder to complete gets eternally delayed, trumped by shiny nice-to-haves that are easy to do.

**Comment by arfon** [comment]
> The next step is to write out a roadmap, and place feature ideas and requests in some form of priority list. Otherwise important dev work that is harder to complete gets eternally delayed, trumped by shiny nice-to-haves that are easy to do.

@labarba: https://github.com/openjournals/joss/pull/684
