### ISSUE TITLE
Pre-submission enquiry bolognese

### ISSUE THREAD

**Issue by mfenner** [openjournals/joss#675]
Is https://github.com/datacite/bolognese within the scope of the journal? It is a utility library (command line or Ruby application) to convert scholarly metadata and thus very useful for bibliometrics research, but I am not sure it is a good fit for JOSS.

**Comment by danielskatz** [comment]
Could you describe cases where it has been used in research and perhaps would have been cited if there was a paper to cite, or where the github url was mentioned? If so, this would be part of the short paper you would need to write and I personally think this would be in scope.

**Comment by arfon** [comment]
I agree - I think this would be in scope.

**Comment by mfenner** [comment]
I think a good example is https://doi.org/10.1038/s41597-019-0031-8, and my work on using schema.org for exposing dataset metadata. The library is not referenced in the paper, but is heavily used at DataCite to convert DataCite XML to schema.org, and enable indexing from Google Dataset Search.

**Comment by danielskatz** [comment]
It's not clear that the latter part is research

**Comment by arfon** [comment]
Closing as stale.
