### ISSUE TITLE
bibtex link not working

### ISSUE THREAD

**Issue by pjotrp** [openjournals/joss#678]
The link to get a bibtex entry does not work for papers, e.g. try

https://joss.theoj.org/papers/10.21105/joss.00025

**Comment by arfon** [comment]
It should be copying the text to your clipboard. It worked for me on the paper you link to:

```
@article{Sloan2016,
  doi = {10.21105/joss.00025},
  url = {https://doi.org/10.21105/joss.00025},
  year = {2016},
  publisher = {The Open Journal},
  volume = {1},
  number = {2},
  pages = {25},
  author = {Zachary Sloan and Danny Arends and Karl Broman and Arthur Centeno and Nicholas Furlotte and Harm Nijveen and Lei Yan and Xiang Zhou and Robert Williams and Pjotr Prins},
  title = {GeneNetwork: framework for web-based genetics},
  journal = {Journal of Open Source Software}
}
```

**Comment by kyleniemeyer** [comment]
Yeah, it works for me too.

**Comment by pjotrp** [comment]
Not working in Firefox for Linux 68.3.0esr (64-bit)

**Comment by arfon** [comment]
Hrm, works on Firefox for Mac 72.0.2 (64-bit). Are there any errors in the console when you click the link Pj?

**Comment by arfon** [comment]
Closing as stale.
