### ISSUE TITLE
Pre-submission enquiry: hpiR

### ISSUE THREAD

**Issue by andykrause** [openjournals/joss#679]
Enquiring about submission of a package i've developed for easily/quickly creating house price indexes:  https://github.com/andykrause/hpiR

Easy creates indexes via standard methods plus new machine learning focused approach.  Offers clear evaluation framework, plotting, etc.  It is research-focused, currently hosted on CRAN.  Current citations are minimal (my own working papers) but has a few users in industry and government statistics.  

Thoughts?

**Comment by arfon** [comment]
I think this could be in scope, especially if it is being used to solve research problems. Are there published papers that you can link to that make use of this package?
