### ISSUE TITLE
Pre-submission enquiry

### ISSUE THREAD

**Issue by robqiao** [openjournals/joss#681]
openjournals/joss-reviews#2068 
This is a R package to wrap UCSC genomics data archive and a new pipeline to generate synteny conservation data then visualization via Bioconductor Gviz package 

I use this package gained a lot understanding about a gene cluster synteny I wasn't able to get otherwise, see we can get the review restarted. 

Plus, I would like to know what is the ballpark for a reasonably sized package. Do we have a whedon function to check the package size. Thx

**Comment by robqiao** [comment]
Thx @danielskatz for your info on openjournals/joss-reviews#2068

**Comment by robqiao** [comment]
@kthyng @danielskatz is this looking any better? I forgot to merge PR, my apology. 

      68 text files.
      62 unique files.
      31 files ignored.

```
github.com/AlDanial/cloc v 1.84  T=0.28 s (129.9 files/s, 4776.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               24             73            382            282
Markdown                         2             24              0            135
TeX                              1              6              0             83
Bourne Shell                     5             25             33             79
Rmd                              1             32            107             54
YAML                             2              2              2             35
HTML                             2              0              0              6
-------------------------------------------------------------------------------
SUM:                            37            162            524            674
-------------------------------------------------------------------------------
```

**Comment by kthyng** [comment]
@csoneson and @lpantano Could you take a look at this enquiry to help give advice? Thanks.

**Comment by lpantano** [comment]
Hi,

It is much better, at least I have an idea what is doing. However, I think I need to know a little bit more, like why the transcriptome data is used, actually I think this is the point that will make this tool a research software. As well, if it were an option to use the coordinates for one region in the genome of one species that can help to find the other region in the other species will be even more useful.

**Comment by csoneson** [comment]
I agree with Lorena that it's now much clearer what the package can do. I also agree that it would be much more convenient for users if they didn't have to look up the genomic coordinates in all species manually; if there is not a single corresponding region that is informative as well, and would be more easily detectable if it was done by the package. Without being an expert in synteny conservation analysis I think it would also be useful to have some quantitative measure of the conservation, rather than just leaving it to the user to visually inspect a collection of genomic region plots.

**Comment by robqiao** [comment]
Thx both @lpantano @csoneson of your time to take a look at this. 

@lpantano 
1. Transcriptomics data used here simply because this is the closest evidence to support the existence of the actual protein. Given the focus here is to infer the phenotypic significance derived from synteny conservation, protein level evidence is preferred. In addition, we would like to take a look at the significance of fold change at transcriptomics level across species in future. Surely, genomics data like UCSC genome browser data archive can also be used, this can be done in the next release.    
1. In term of automating searching for gene coordinates, it starts to get a bit fussier when the investigation goes out of mammals, the gene duplication events and less naming conventions start to get more difficult to derive consensus, hence gene coordinates search based on names I feel like is a bit less reliable. `Blast` is a potential option, but again, I am not sure with such big variations across species, what's a reliable cut-off score to minimise the mislocation. Do you @lpantano have any thoughts or suggestions on this? 

@csoneson 
1. Thanks for your thought on UX. Given less conserved naming conventions and diverse signatures across species, I am still lack of a reliable mechanism to pinpoint the gene. Do you @csoneson has any thoughts or you might know any packages solve this problem? 
1. The quantitative measure is a very nice thought, I am thinking to charter this feature in the next release, or you would like to have this asap?

**Comment by lpantano** [comment]
Thank you. I think you may be able to use a existent package to get the homologoes between species and then the genomic coordinates of those genes. At least for the main species should work, and it could be something to give the extra miles that this needs. For instance see: http://bioconductor.org/packages/release/data/annotation/html/hom.Hs.inp.db.html.

**Comment by csoneson** [comment]
Given that this is framed as an "analysis workflow", I would suggest including a quantitative measure already in this version, to help towards qualifying this as research software.

**Comment by kthyng** [comment]
Hi @robqiao — we at JOSS are generally less active now with the current virus-based circumstances. For example, we are not accepting new submissions for about 30 days at least. We should probably also table this discussion for now.

I noticed no one answered your question before. Less than 1000 lines of code raises flags for us about being a minor utility, but does not mean it isn't acceptable for JOSS. Still, your code base is much smaller than this guideline.

**Comment by robqiao** [comment]
@kthyng Thx for getting back on this. I will try to put up an update to address @csoneson and @lpantano suggestions. Take care, stay healthy at this difficult time.
