### ISSUE TITLE
Pre-submission enquiry - archivr

### ISSUE THREAD

**Issue by adam3smith** [openjournals/joss#686]
I'm considering submitting a paper about our R-package `archivr` https://github.com/QualitativeDataRepository/archivr to JOSS, and wanted to check if it'd meet the "no thin API clients" test. The package provides various ways to check and ensure that URLs used in papers, on websites/blogs, and in datasets are archived in the InternetArchive and/or perma.cc.
I'm fairly convinced that it'd be very useful to lots of researchers -- it fills a very real need -- which is why I'd love to get it into JOSS, but I'll freely admit that from a software engineering point of view it's pretty simple. 
I'd be very thankful if you could give me a quick preliminary assessment of fit.

**Comment by adam3smith** [comment]
As for usage in research: the package is pretty new, so no current citations, but it has been used to ensure URLs used in two high-profile books in political science have been archived and the output is used in the respective datasets:
https://doi.org/10.5064/F63776W4 and https://doi.org/10.5064/F6GYLSON

**Comment by danielskatz** [comment]
I'm unsure about the thin API part, but am more concerned that this doesn't sound like research software, any more than what word processing that was used to write the two books is.  This isn't to say that it doesn't fit a real need, much like word processing software does, just that it doesn't seem to fit the description of research software - software that is used as part of the research (not publishing) process.

**Comment by adam3smith** [comment]
Thanks Dan. The argument would be that it's essentially research reproducibility software. 
The same way containerizing/packaging tools such as [Reprozip](https://www.reprozip.org/) or [DataPackageR](https://docs.ropensci.org/DataPackageR/) help ensure that quantitative analysis remains reproducibility in the long-term, this tool helps ensure that qualitative analysis remains "reproducible," (where the exact meaning of this term may vary a bit) by ensuring continued availability of the sources used. 

If reproducible research tools are out of scope for JOSS (and this is an honest question -- I really don't know if they are), I'd definitely agree so is this one. If you'd consider such tools in scope, I'd want to make a case for archivr being in the same broad category.

**Comment by danielskatz** [comment]
Yes, this is a good question - I look forward to hearing from other JOSS editors on their thoughts

**Comment by arfon** [comment]
> If reproducible research tools are out of scope for JOSS (and this is an honest question -- I really don't know if they are), I'd definitely agree so is this one. If you'd consider such tools in scope, I'd want to make a case for archivr being in the same broad category.

I don't think we've ever really decided this so it's an excellent question to ask us. I'm inclined to say that they should allow some submissions in this space, but I'm not sure how to cleanly define allowable and not allowable (this is something we spend a lot of time on as an editorial team already).

Regarding this submission in particular, taking a quick look at the code, I suspect this would fall into our 'minor utility' category due to the relatively modest functionality.

**Comment by adam3smith** [comment]
> Regarding this submission in particular, taking a quick look at the code, I suspect this would fall into our 'minor utility' category

OK, I thought that might be the case, thanks for looking at the code. I'll not submit this then. 

I'll leave this issue open in case you want to continue the discussion on the repro tools question here (though I suspect it's better in a dedicated issue?). I'd be interested in that discussion if you could link it here in that case. 
Feel free to close this issue -- really appreciate the super-quick replies
