### ISSUE TITLE
Add missing acknowledgement to already published paper

### ISSUE THREAD

**Issue by magnusrahm** [openjournals/joss#687]
Dear editors,

I forgot an important acknowledgement in my recent contribution WulffPack (https://doi.org/10.21105/joss.01944). I have updated the paper.md file in the repository (https://gitlab.com/materials-modeling/wulffpack). Would it be possible make this kind of addition even though the paper is already published?

Sorry for the nuisance,
Magnus

**Comment by arfon** [comment]
Sure thing. This should be fixed in https://github.com/openjournals/joss-papers/commit/67ab7d9fa165a502563a0ec5650fb5bbf453ff29 .

Please note, the old PDF might show up on the JOSS site for a few hours as there's caching in place.

**Comment by magnusrahm** [comment]
Thanks a lot!
