### ISSUE TITLE
Pre-submission enquiry - HPC Reporting Tools

### ISSUE THREAD

**Issue by robqiao** [openjournals/joss#688]
Hi, Team, 

Just would like to ask if HPC reporting Tools will be in scope for JOSS. 

HPC reporting tools provide integrated information on HPC status and utility information. The reporting tool can be used not only by the HPC infrastructure research community to monitor system parameters and performance but also is beneficial for HPC system administrators. See what you think. Many Thanks

**Comment by arfon** [comment]
Thanks for the enquiry @robqiao. Has this software been used by the 'infrastructure research community' already in published work? I'm not really very well-versed in this topic area so would appreciate the thoughts/input of some of the other JOSS editors.

/ cc @gkthiruvathukal @labarba

**Comment by gkthiruvathukal** [comment]
@robqiao Is there a way to see a repo for your work? I'm also interested in your response to @arfon's question. It would be good if you can characterize who and how this work is used. Thanks!

**Comment by robqiao** [comment]
Thx @arfon This work is still at its $\alpha$ version and under active development in house atm. No known published material related. 

@gkthiruvathukal 
 In essence, it provides overall integration of HPC matrices for admins including but not limited to 
1. splunk, lmod, slurm
1. ansyst, wiki
1. git 

It also provides a machine learning module to analysing and predicting user behaviours for better HPC scheduling and research. 

We will try to put up a $\beta$ release and address user bases in the following post. 

Take care all during this difficult time.

**Comment by arfon** [comment]
Closing as stale.
