### ISSUE TITLE
I'd like to review for JOSS

### ISSUE THREAD

**Issue by Shuang-Plum** [openjournals/joss#689]
Hi, 

This is [Shuang Li](https://scholar.google.com/citations?user=HRc23MUAAAAJ&hl=en), currently a postdoc at Department of Pharmacology, University of North Carolina at Chapel Hill. I'm good with R, stats and Matlab. I got to know JOSS from our department posting and really likes the idea! I would like to volunteer for reviewing stuff. Usually, I would be able to get back within a week.

 Thanks for having such a cool idea and making it happen!!

Best,
Shuang Li

**Comment by arfon** [comment]
Great, thanks! Please fill in our form here: https://joss.theoj.org/reviewer-signup.html
