### ISSUE TITLE
Pre-submission enquiry -- the Basic Model Interface (BMI)

### ISSUE THREAD

**Issue by mdpiper** [openjournals/joss#690]
Hello editors,

I'm writing to ask whether a project I'm working on is appropriate for submission to JOSS.

The project is the Basic Model Interface (BMI): https://github.com/csdms/bmi. BMI supplies a standardized set of functions for querying, modifying, and running a numerical model. I've gone over the scope and submission requirements, and I believe I can be in compliance, yet I'm concerned that because it's an interface, it's not really software. (It's metasoftware!) The project has full [documentation](https://bmi.readthedocs.io). It also has software derived from it--specifications for four languages, plus sample implementations in these languages (please see the repo [README](https://github.com/csdms/bmi/blob/master/README.rst) for links)--but it's difficult to talk about these products without referring to the BMI from which they're derived.

Thank you for your time, and I look forward to hearing from you.

cc @mcflugen

**Comment by jedbrown** [comment]
Thanks for this interesting question. My opinion is that this could be reviewed in combination with clients (at least the various examples, which reside in different repositories; possibly a "real" client depending on opinions of other editors). I think the SIDL file and documentation on its own is too meta.

**Comment by mdpiper** [comment]
@jedbrown Thank you for your thoughtful comments. I agree with you--the SIDL file + docs are insufficient; the work should encompass the language specs + examples. (Note that the examples are intentionally scientifically uninteresting. They're designed to be simple, so the focus is on the BMI implementation.)

If it would help the editors in their decision, a **paper.md** file is available in the [mdpiper/paper](https://github.com/csdms/bmi/tree/mdpiper/paper) branch of the repository.

**Comment by arfon** [comment]
> My opinion is that this could be reviewed in combination with clients (at least the various examples, which reside in different repositories; possibly a "real" client depending on opinions of other editors). 

Yes, I think that would make most sense.

**Comment by mdpiper** [comment]
@arfon @jedbrown Sorry, it's been awhile. I'm prepared to submit, and from the discussion above, it seems that you're OK with this. But since it has been awhile, I'd just like to confirm with you. If so, I'll close this issue & submit. Thanks!

**Comment by arfon** [comment]
Yep, please go ahead and submit @mdpiper!

**Comment by mdpiper** [comment]
Awesome! Thanks!
