### ISSUE TITLE
Duplicate and follow-up submission checking

### ISSUE THREAD

**Issue by arfon** [openjournals/joss#698]
We need a better way to handle potential duplicate/follow-up submissions. This can happen in a number of situations (non-exhaustive list):

- When a submission is rejected and the author resubmits following feedback from JOSS editors.
- When a submission is rejected and the author resubmits without modifications.
- When a second paper is submitted to JOSS (e.g. a major new release of a package).

A few ways we could address this:

1. Offer authors an option to select the submission type on the submission form (e.g. novel submission, re-submission, new release/version of previously accepted submission).
2. Build support either into the editor dashboard here (https://github.com/openjournals/joss) or in Whedon (https://github.com/openjournals/whedon-api) to try and detect duplicate submissions.
3. Both of the above.

**Comment by danielskatz** [comment]
I think at least 1 would be good, but I think we also need a way that authors can provide some text about this as part of the submission, and have it be easily visible to AEiCs and editors from the dashboard

**Comment by kyleniemeyer** [comment]
I'm in favor of 1, with a dropdown menu for type of submission, perhaps with an associated text box for comments (e.g., linking to an old version or the issue for a rejected submission).
