### ISSUE TITLE
Pre-submission enquiry

### ISSUE THREAD

**Issue by TrashBirdEcology** [openjournals/joss#699]
Is JOSS open to submissions which are not strictly software or code-based? 

__If so, would the Journal be amenable to the following__?:

A piece addressing GUI usability in my field of study (ecology, conservation, natural resource sciences). The piece will review the usability of various GUIs (using high-level heuristics) and across multiple platforms in an attempt to identify _opportunities for developers to better design and/or document their GUIs_.

Thanks!

**Comment by danielskatz** [comment]
This would be out of scope for JOSS - JOSS is strictly for software. You might want to try another journal, for example, [JORS](https://openresearchsoftware.metajnl.com).

**Comment by TrashBirdEcology** [comment]
Thanks!
