### ISSUE TITLE
Need to draft guidelines for authorship

### ISSUE THREAD

**Issue by arfon** [openjournals/joss#7]
Things to discuss/support:
- Who should be listed as an author (do all committers to a repository count?)
- How to handle authorship between releases of a software package?
  - Suggest publish major versions only (point authors to [semantic versioning](http://semver.org/))
  - Suggest that authors between major versions should be only those authors that have contributed to to the delta
- What happens after acceptance?

**Comment by labarba** [comment]
RE. who should be listed as author ... I agree that this is a decision for the submitters. However, we may want to add guidelines on at least the requirement that any submission should be approved by all co-authors, and all contributors.

**Comment by jkahn** [comment]
Addressing the questions:
> authorship between multiple releases
and also
> what happens after acceptance

This raises the same questions I did [here](https://github.com/openjournals/joss-reviews/issues/27#issuecomment-226859556):

> Minting a new Zenodo snapshot & DOI before reviewing seems like wasted effort, since (I would hope) nearly all reviewers are going to request changes (even if minor) that will require a new Zenodo snapshot.
>
> Can reviewers bless a particular tag or revision in the target repo, and have authors or JOSS take the zenodo snapshot/doi after the review process is complete?

I get that this might not be convenient for non-github users, but it seems like the publication of a new release might warrant a version number upgrade as well, etc etc.

**Comment by arfon** [comment]
> Minting a new Zenodo snapshot & DOI before reviewing seems like wasted effort, since (I would hope) nearly all reviewers are going to request changes (even if minor) that will require a new Zenodo snapshot.

@jkahn - this is a good point. My original motivation for requesting the archive was that if the author has a very quick review (i.e. no modifications) then there's nothing left to do for the author post-review for the publication process to be completed.

That said, it does seem like a significant fraction of submitted software thus far has required a new DOI to be issued at the end.

I _thought_ that Zenodo supported the concept of linking to the 'latest' DOI for a particular archive but I don't seem to be able to craft a URL to return this for any of the stuff I have archived in Zenodo. @lnielsen is this possible? That or versioned DOIs 😉

**Comment by labarba** [comment]
I agree that minting the DOI before review is wasted effort — I was thinking the same thing, seeing the issue threads develop. 

And perhaps it's nice for the author to have an "accepted without changes, now go get your DOI, congrats" moment.

**Comment by jkahn** [comment]
@labarba -- that's about as close as any academic gets to a victory lap.

**Comment by cMadan** [comment]
I've been working on submitting a paper to JOSS and have also been thinking it makes more sense to get the DOI after the reviewers sign off (and as part of a 'all done, congrats!')

**Comment by arfon** [comment]
My only concern with getting authors to archive/issue an DOI after acceptance is that it makes some of the automated document preparation harder (Crossref metadata, compiling the PDF etc) but I can think of some work arounds for this.

**Comment by arfon** [comment]
This is WIP is #137
