### ISSUE TITLE
I'd like to review for JOSS

### ISSUE THREAD

**Issue by jkahn** [openjournals/joss#70]
Hi!

I'm a linguist, a data scientist (whatever that means), a PhD, and a software engineer, and I have strong interest in improving scientific tools and tooling. The JOSS sounds like a neat way to get involved.

I've worked in software industry and in academic and industry research groups, and I've played nearly every role in open software that there is to play (except "primary maintainer" of a large & well-established toolkit).  My pedigree may be found at http://trochee.net/about/work/.

I'm particularly interested in these areas (which may overlap):

- natural language processing (any)
- deep learning (especially for text or speech; image processing not so enthusastically.)
- statistical and machine learning tools
- Python
- toolkits for making non-software-expert domain expertise easier

**Comment by arfon** [comment]
Hi @jkahn. Many thanks for offering to review for [The Journal of Open Source Software](http://joss.theoj.org/).

There's a couple of things we'd like you to do at this point:

-  Accept the invite to join the 'joss-reviewers' [team](https://github.com/orgs/openjournals/teams/joss-reviewers) on GitHub that you should have received.
- Familiarize yourself with the JOSS [reviewer guidelines](http://joss.theoj.org/about#reviewer_guidelines)

**Volunteering for reviews**

When JOSS receives new submissions we will mention the joss-reviewers team (e.g. / cc @openjournals/joss-reviewers) in the review thread. You can see the submissions we've already received here: https://github.com/openjournals/joss-reviews/issues

Please keep an eye on your GitHub notifications for the https://github.com/openjournals/joss-reviews repository and if you think you would be able to review the submitted software please reply on the submission issue. 

Once again, thanks for volunteering to help out, we're delighted to have you on board!

If you have any questions, please don't hesitate to either reply on this thread or email directly on arfon.smith@gmail.com

**Comment by jkahn** [comment]
A UX quibble: until that invitation is accepted, that 'team' link draws a 404.  Happy to be part of this.

**Comment by arfon** [comment]
> A UX quibble: until that invitation is accepted, that 'team' link draws a 404. Happy to be part of this.

Yep, not much I can do about this though sorry :-\ it's a GitHub thing...
