### ISSUE TITLE
SAILS: software repo link broken

### ISSUE THREAD

**Issue by AJQuinn** [openjournals/joss#700]
Hello - hopefully this is the right place for this issue, apologies if not. We've recently had a paper accepted in JOSS: (https://joss.theoj.org/papers/10.21105/joss.01982#, doi: https://doi.org/10.21105/joss.01982) and the review issue is now closed. 

We've been using the site a bit since then and it looks like the link to the software repo is broken. It points to https://joss.theoj.org/papers/10.21105/vcs.ynic.york.ac.uk/analysis/sails rather than https://vcs.ynic.york.ac.uk/analysis/sails - not sure what might have gone wrong. Is there a way to update this?

Thanks for your help.
Andrew

**Comment by Kevin-Mattheus-Moerman** [comment]
I've re-opened that issue and pinged our support team there.

**Comment by arfon** [comment]
This is fixed now. Looks like the URL to the repository was entered at submission as `vcs.ynic.york.ac.uk/analysis/sails` which isn't a full URL which tripped up our processing.
