### ISSUE TITLE
Searching returns results in a seemingly random order

### ISSUE THREAD

**Issue by dpsanders** [openjournals/joss#701]
Searching e.g. for the "julia" tag produces results in a seemingly random order.

Maybe they could be ordered e.g. by most recent, or have different options available for how to order the search results.

**Comment by arfon** [comment]
If you search for 'Julia' you're going to get searches across tags, article titles etc. 

If you just want papers with software in the Julia programming language then you can use the per-language filters (e.g. https://joss.theoj.org/papers/in/Julia) which can be accessed by clicking the language tags in the UI.
