### ISSUE TITLE
More general approach 

### ISSUE THREAD

**Issue by Opussci** [openjournals/joss#717]
Hi,
I'm wondering is it possible to use Volumes and issues numbering when publishing?
This way many more publishers could adopt software for their own journals?
Thanks

**Comment by arfon** [comment]
Not sure I quite understand the question sorry. Are you asking if JOSS publications have issue and volume numbers?

**Comment by Opussci** [comment]
Sorry for not being precise.
No, my question is about your publishing platform. Does it allows to specify journal volume and issues?
I am editor in chief assistant of one academy-led journal and I see that you have made very good 👍publishing platform.
It could embraced in scientific publishing if that is the case. I would also appreciate if you could point me to same tutorial how to make local deployment.

**Comment by arfon** [comment]
Ahhh, OK, got it. Yes, we do actually have issue, volume, and page numbers. The JOSS convention (which could easily be changed) is:

- 1 issue per month e.g. March 2020 is [volume 47](https://joss.theoj.org/papers/issue/47)
- 1 volume per year e.g. 2020 is [volume 5](https://joss.theoj.org/papers/volume/4)
- The first 'page' number is the issue number on the `joss-reviews` repository. 

So for example, the [last paper we published](https://joss.theoj.org/papers/10.21105/joss.02042) has the following BibTeX string for the full citation:

```
@article{Bennett2020,
  doi = {10.21105/joss.02042},
  url = {https://doi.org/10.21105/joss.02042},
  year = {2020},
  publisher = {The Open Journal},
  volume = {5},
  number = {47},
  pages = {2042},
  author = {Andrew Bennett and Joseph Hamman and Bart Nijssen},
  title = {MetSim: A Python package for estimation and disaggregation of meteorological data},
  journal = {Journal of Open Source Software}
}
```

> It could be embraced in the scientific publishing if that is the case. I would also appreciate if you could point me to some tutorial how to make local deployment.

We don't have very good deployment docs sorry but I'd me more than happy to set up a call sometime to discuss our general technical approach and offer some advice on how to proceed.

Feel free to drop me a line on arfon.smith@gmail.com

**Comment by Opussci** [comment]
Is it possible to display volumes and issues on the website, in navbar maybe: current, archive?
Also in the article page, for example: 
`
MetSim: A Python package for estimation and disaggregation of meteorological data
Submitted 16 January 2020 • Published 27 March 2020
Volume xx, issue yy
`
And is it possible to customize citations with styles? APA, VANCOUVER
`
Bennett et al., (2020). MetSim: A Python package for estimation and disaggregation of meteorological data. Journal of Open Source Software, 5(47), 2042, https://doi.org/10.21105/joss.02042
`


I will contact you, thanks!

**Comment by arfon** [comment]
Yes, all of those changes would be possible!

**Comment by Opussci** [comment]
Excellent!
