### ISSUE TITLE
Jabberwocky: an ontology-aware toolkit for manipulating text Review questions

### ISSUE THREAD

**Issue by wdduncan** [openjournals/joss#718]
@majensen 
I finished the checklist for: https://github.com/openjournals/joss-reviews/issues/2168

However, what is the appropriate venue for reviewer comments?  
So, I will put my comments here:

1. I could not install the repo as per the instructions. When running the install script, I received error:
```
ERROR: TEST FAILED: /Users/wdduncan/.local/lib/python3.7/site-packages/ does NOT support .pth files 
error: bad install directory or PYTHONPATH
```
This could be b/c I am using OS X, or perhaps b/c I installed using venv. Should I report the issue on the repo? That might *unblind* my review.

2.. The examples reference a file named `/ontology/pocketmonsters.owl`. But this file is not in the repo.

3. The github documentation would benefit from having examples of expected output and descriptions of what the output means.

4. The paper refers to the jabberwocky-tests as a way to see the software at work. But that directory contains no instructions.

5. How long is the software supposed to be?

**Comment by arfon** [comment]
@wdduncan - thanks! Please leave your comments on the review issue for this paper: https://github.com/openjournals/joss-reviews/issues/2168
