### ISSUE TITLE
Compute JOSS' Impact Factor

### ISSUE THREAD

**Issue by DominiqueMakowski** [openjournals/joss#721]
Somewhat related to #153.

Despite its many flaws and all, journal impact factors are still used to get an idea of the impact of a journal. Although usually computed by official bodies (e.g. Clarivate Analytics), since the formula to compute IFs is so simple (*"In any given year, the impact factor of a journal is the number of citations, received in that year, of articles published in that journal during the two preceding years, divided by the total number of "citable items" published in that journal during the two preceding years"*, [wikipedia](https://en.wikipedia.org/wiki/Impact_factor)), I was wondering whether JOSS could compute its own IF?

This would be useful for instance for junior researchers to highlight their track record.

**Comment by arfon** [comment]
We could do this, in fact I think _anyone_ could do this right? Any suggestions where to get the citation information from? Citations through Crossref are incomplete, Google Scholar seems to have pretty good data but it can't be automated, Scopus and Web of Science don't index JOSS (yet). Thoughts?

**Comment by danielskatz** [comment]
I oppose us doing this.  In fact, I would like us to abide by https://sfdora.org (and maybe even sign it)

**Comment by arfon** [comment]
> I oppose us doing this. In fact, I would like us to abide by https://sfdora.org (and maybe even sign it)

Fair enough @danielskatz. I'm personally not particularly motivated to do this but was just thinking aloud how it could be done.

I don't think I'd read the declaration on https://sfdora.org before. It's definitely something we should discuss and consider as an editorial team but they make a pretty strong case for avoiding Impact Factors all together.

**Comment by DominiqueMakowski** [comment]
Thanks for mentioning this declaration @danielskatz, I wasn't aware of it! And I agree with it.

I was just curious to know the average citation number, because I have the feeling that it's *a lot* 😁 But indeed, maybe the data is too hard to get anyway (I though JOSS somehow tracked the number of citations for each paper through something similar to altmetrics but it seems like it's not that straightforward). 

Feel free to close this issue!
