### ISSUE TITLE
Pre-submission enquiry - tootsea

### ISSUE THREAD

**Issue by quai20** [openjournals/joss#726]
[https://github.com/quai20/TOOTSEA](https://github.com/quai20/TOOTSEA)

Hello, 
I'm interested in submitting our Tootsea tool to JOOS for review. This is a matlab tool we started couple years ago, to process oceanographic time series coming for various instruments that goes on mooring lines. The code is now on github, with some web documentation and a basic test suite. If I look at the JOOS scope, I think our tool is not too far (open source, obvious research application).    

But one question though, since the tool is UI based, some behaviors are difficult to implement in a test suite (ie, I didn't do it). Could this be a drawback to submitting ?

Thanks,

**Comment by arfon** [comment]
Hi @quai20, thanks for the enquiry. UI testing can be hard for many projects. Quoting from our [review criteria](https://joss.readthedocs.io/en/latest/review_criteria.html#tests):

Authors are strongly encouraged to include an automated test suite covering the core functionality of their software.

- **Good:** An automated test suite hooked up to an external service such as Travis-CI or similar
- **OK:** Documented manual steps that can be followed to objectively check the expected functionality of the software (e.g., a sample input file to assert behavior)
- **Bad (not acceptable):** No way for you the reviewer to objectively assess whether the software works

You can be in the 'OK' category provided  you can document some procedures for the reviewers to follow to verify the functionality manually. Might something like that be possible?

/ cc @Kevin-Mattheus-Moerman who is a Matlab expert on our team.

**Comment by quai20** [comment]
Thanks @arfon ! Yes I think a mix of "Good" (that I did for some parts of the code), and "OK" (I think some clear manual steps for the reviewer to follow are a good start, I'll do that)
