### ISSUE TITLE
Pre-submission enquiry - hepdata_lib

### ISSUE THREAD

**Issue by clelange** [openjournals/joss#727]
Dear JOSS team,

I would like to enquire whether [hepdata_lib](https://github.com/HEPData/hepdata_lib/) would qualify for publication in JOSS. hepdata_lib is a python (2.7+) library to help researchers get their publication results, i.e. plots and tables, into [HEPData](https://www.hepdata.net/), the "repository for publication-related High-Energy Physics data". hepdata_lib hereby provides an essential tool to convert several different formats such as a large number of [ROOT](https://root.cern.ch/) objects, but also simple text files, into the YAML format required by HEPData, creating an upload-ready archive. In addition, documentation including example notebooks are provided. The tool is under MIT license and actively being developed.

Thank you for your time and consideration!

**Comment by arfon** [comment]
Hi @clelange, many thanks for your enquiry. I think this is likely out of scope for a couple of reasons:

- Library size: While this looks to be useful, it looks to me like it would likely fall into our 'minor utility' category.
- Scope: Tools that help researchers publish their work are generally considered out of scope for us too.

Quoting from the [submission requirements/scope](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements) section of our docs:

> JOSS publishes articles about research software. This definition includes software that: solves complex modeling problems in a scientific context (physics, mathematics, biology, medicine, social science, neuroscience, engineering); supports the functioning of research instruments or the execution of research experiments; extracts knowledge from large data sets; offers a mathematical library, or similar.

**Comment by clelange** [comment]
Hi @arfon, thank your for taking the time to review my enquiry. I understand your reasoning and will try to find a different way of publishing this.
