### ISSUE TITLE
Pre-submission enquiry - Wiggum

### ISSUE THREAD

**Issue by brownsarahm** [openjournals/joss#728]
I'd like to consider the submission of [Wiggum](https://fairnessforensics.github.io/wiggum/) ([repo](https://github.com/fairnessforensics/wiggum)) to JOSS.  It meets (or will meet prior to submission) most of the criteria, including pending submitted research articles that use it.  However, I am concerned it may not meet the criterion of filling an "*obvious* research need".  Wiggum is a tool for investigating data and algorithms for bias.  Thus it's most obvious use may be for advocacy, but I do think that these tools support valuable increases in understanding of the behavior of algorithms and the biases in data and there are a growing number of tools in this class of research artifact.

**Comment by danielskatz** [comment]
I don't feel that there would be an issue with "a tool for investigating data and algorithms for bias" - this is clearly an area of research
