### ISSUE TITLE
Pre-submission enquiry - BigX

### ISSUE THREAD

**Issue by geekysquirrel** [openjournals/joss#730]
Hi everybody,
apart from my [work project](https://github.com/openjournals/joss/issues/729), I also have a "side" project, called "[BigX](https://gitlab.com/geekysquirrel/bigx)", a tool to help visualise geographical data without having to write code. It's been open-source ever since its conception and I'd written it out of personal interest but most recently I've been using it for work-related purposes such as to visualise movement of travellers in China during the COVID-19 outbreak and locations of prosthetic patients in Cambodia. I found that it helps with analysing data, particularly for people who normally work in excel and don't use standard data analysis tools such as R or python. As you can see, it's not a package either; it's a web application and although it doesn't tick all the boxes yet (I'm still working on the testing) I feel it does make addressing research challenges faster, easier and more comfortable and accessible.
Should I bother submitting it?

**Comment by arfon** [comment]
:wave: @geekysquirrel - this software definitely sounds interesting. It's not clear from your comment here whether this is already being actively used to support research projects already or whether you think it's of _potential_ value to researchers?

I ask as when deciding if software packages are in scope for JOSS, it's always easier to discuss this topic if there are existing academic users (and therefore potential work to cite).

**Comment by geekysquirrel** [comment]
Thanks for your comment.
At the time of writing, I had used it to map travellers in China, which was not for a research project but journalism. However, I'm now actively using it in my "day job" for mapping real-world data. As this work is new we haven't got any publications yet but I suspect we will have in the future.

**Comment by arfon** [comment]
Got it. Thanks. I think this is worth submitting. The handling editor and reviewers will have their inputs on scope too but it sounds like it very well could be in scope to me.
