### ISSUE TITLE
Submit a submodule (i.e., a scope-specific part of a bigger package)?

### ISSUE THREAD

**Issue by DominiqueMakowski** [openjournals/joss#732]
Hi! Sometimes packages are made of submodules, for instance in Python, which can be more-or-less specific and independent in their goal, implementation and nature.

In the case where a package has a mature and feature-complete submodule A, but is still considered as in-development for other submodules, and that this submodule A could almost be considered as a stand-alone software (in terms of scope), is it compatible with JOSS submissions?

**Comment by arfon** [comment]
If I'm understanding you correctly I *think so*. Would the intent in the long run to have multiple (JOSS) papers describing the package and the submodule? If so, this may raise concerns from the editorial team about duplicate publications/salami-slicing of the work.

It might be helpful to see the software and hear more about the package and the submodule.

**Comment by DominiqueMakowski** [comment]
> Would the intent in the long run to have multiple (JOSS) papers describing the package and the submodule? If so, this may raise concerns from the editorial team about duplicate publications/salami-slicing of the work.

Yes, that's definitely a valid concern! It's not related to a tangible project yet, but I was rather wondering if the idea of it was even acceptable (the idea that a package can have multiple independent scopes). I'll let you know if I have anything more precise, thanks again!
