### ISSUE TITLE
I'd like to review for JOSS

### ISSUE THREAD

**Issue by Spencerx** [openjournals/joss#74]
I'm online virtually hundred percent of the time when I'm on grid via Git, Repos, Jabber, Twitter and hangouts to name a few.
Anything else is on demand!

Cheers
Spencer

**Comment by arfon** [comment]
Hi @Spencerx. Many thanks for offering to review for [The Journal of Open Source Software](http://joss.theoj.org/).

There's a couple of things we'd like you to do at this point:

-  Accept the invite to join the 'joss-reviewers' [team](https://github.com/orgs/openjournals/teams/joss-reviewers) on GitHub that you should have received.
- Familiarize yourself with the JOSS [reviewer guidelines](http://joss.theoj.org/about#reviewer_guidelines)

**Volunteering for reviews**

When JOSS receives new submissions we will mention the joss-reviewers team (e.g. / cc @openjournals/joss-reviewers) in the review thread. You can see the submissions we've already received here: https://github.com/openjournals/joss-reviews/issues

Please keep an eye on your GitHub notifications for the https://github.com/openjournals/joss-reviews repository and if you think you would be able to review the submitted software please reply on the submission issue. 

Once again, thanks for volunteering to help out, we're delighted to have you on board!

If you have any questions, please don't hesitate to either reply on this thread or email directly on arfon.smith@gmail.com

**Comment by Spencerx** [comment]
Hi Arfon

Working on some drums and the only thing that'll get on the way is
timezones do I'm looking forward to getting practicing scientists or
research engineers.

On Saturday, 7 May 2016, Arfon Smith <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> Hi @Spencerx <https://github.com/Spencerx>. Many thanks for offering to
review for The Journal of Open Source Software <http://joss.theoj.org/>.
>
> There's a couple of things we'd like you to do at this point:
>
> Accept the invite to join the 'joss-reviewers' team
<https://github.com/orgs/openjournals/teams/joss-reviewers> on GitHub that
you should have received.
> Familiarize yourself with the JOSS reviewer guidelines
<http://joss.theoj.org/about#reviewer_guidelines>
>
> Volunteering for reviews
>
> When JOSS receives new submissions we will mention the joss-reviewers
team (e.g. / cc @openjournals/joss-reviewers
<https://github.com/orgs/openjournals/teams/joss-reviewers>) in the review
thread. You can see the submissions we've already received here:
https://github.com/openjournals/joss-reviews/issues
>
> Please keep an eye on your GitHub notifications for the
https://github.com/openjournals/joss-reviews repository and if you think
you would be able to review the submitted software please reply on the
submission issue.
>
> Once again, thanks for volunteering to help out, we're delighted to have
you on board!
>
> If you have any questions, please don't hesitate to either reply on this
thread or email directly on arfon.smith@gmail.com
<javascript:_e(%7B%7D,'cvml','arfon.smith@gmail.com');>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
<https://github.com/openjournals/joss/issues/74#issuecomment-217593760>


-- 
Regards
[image: Spencer online]


Spencer
coderbits.com/spencerc
  <http://coderbits.com/spencerc>

**Comment by Spencerx** [comment]
Hi Arfon

To accept joining joss-reviewers. Your team url is down
https://github.com/orgs/openjournals/teams/joss-reviewers
Got 404 does not exist error early today. Still down now?

Cheers
Spencer

**Comment by arfon** [comment]
Sorry Spencer. Looks like I didn't send the invite properly. Can you try again now?

**Comment by Spencerx** [comment]
Hi. It's not visible

**Comment by Spencerx** [comment]
Hi. The earlier link is not visible but this works https://github.com/orgs/openjournals/invitation?via_email=1

**Comment by arfon** [comment]
I think you can only see the team once you've accepted the invite (which it looks like you've done now).

Welcome aboard!

**Comment by Spencerx** [comment]
Thankfully Arfon that's the idea, as pointed out .

Cheers
