### ISSUE TITLE
Blog RSS feed is missing a title

### ISSUE THREAD

**Issue by logological** [openjournals/joss#741]
The [JOSS Blog](http://blog.joss.theoj.org/) features an [RSS feed of the blog entries](https://blog.joss.theoj.org/feed.xml), which is great.  But it's missing a feed title, as you can see from the `<title></title>` line in the excerpt of the raw feed XML below:

```
<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title></title>
    <description>Blog for the Journal of Open Source Software http://joss.theoj.org</description>
    <link>https://blog.joss.theoj.org/</link>
    <atom:link href="https://blog.joss.theoj.org/feed.xml" rel="self" type="application/rss+xml"/>
    <pubDate>Mon, 18 May 2020 11:25:03 +0000</pubDate>
    <lastBuildDate>Mon, 18 May 2020 11:25:03 +0000</lastBuildDate>
    <generator>Jekyll v3.8.5</generator>
```

Please add a succinct and accurate title, such as "Journal of Open Source Software Blog".  This way, when the feed is imported into a feed aggregator, it won't show up with a blank or placeholder title.

**Comment by arfon** [comment]
Thanks for spotting this @logological. I've just pushed a fixed for this (it's deploying now).

**Comment by arfon** [comment]
Yic

**Comment by arfon** [comment]
OK, blog title now fixed too. Thanks for spotting this @logological.
