### ISSUE TITLE
Can we submit the implementations of newly developed algorithms having a real life use case?

### ISSUE THREAD

**Issue by adeepak7** [openjournals/joss#743]
Respected Admin,

Can we submit the implementations of newly developed algorithms having a real life use case?

If not, are there any plans to initiate the Journal of Algorithms?

Thanks.

**Comment by arfon** [comment]
Hi @adeepak7. We would generally recommend submitting this to a different journal where the impact/value of such an algorithm can be more readily evaluated.

Here are some conferences that might be appropriate: https://en.wikipedia.org/wiki/List_of_computer_science_conferences#Algorithms_and_theory and here is a longer list of journals that might be appropriate: https://www.software.ac.uk/which-journals-should-i-publish-my-software

> If not, are there any plans to initiate the Journal of Algorithms?

Not currently no.
