### ISSUE TITLE
Typo on https://joss.theoj.org/papers/10.21105/joss.00267

### ISSUE THREAD

**Issue by dhermes** [openjournals/joss#746]
My name is listed as "Dany" (not "Danny"). Though I am a fan of Daenerys Targaryenn, that is not how I spell my name.

Comparing

- https://joss.theoj.org/papers/by/Danny%20Hermes
- https://joss.theoj.org/papers/by/Dany%20Hermes

it appears the typo is localized to just one field in the display for the paper.

----

Sorry if filing this issue isn't the right venue (I realize this isn't about the code that runs JOSS). I looked for a "report issue" button or related on the paper page but couldn't find one.

**Comment by arfon** [comment]
Sorry about that @dhermes. This was a regression introduced a couple of days ago. A fix is in the works in #747

**Comment by arfon** [comment]
<img width="1465" alt="Screen_Shot_2020-06-04_at_1_55_01_PM" src="https://user-images.githubusercontent.com/4483/83793999-51a99080-a66b-11ea-9322-4089cf0c06be.png">

**Comment by dhermes** [comment]
Thanks!
