### ISSUE TITLE
Peer review not started since a month

### ISSUE THREAD

**Issue by adeepak7** [openjournals/joss#755]
Respected Admin,

Our paper, "1build: Frictionless way of managing project-specific commands" was submitted before a month by the first author @gopinath-langote, but the review hasn't started yet.

This publication matters a lot to me to be done in time.

Therefore I request you to kindly look into this issue.

Thanks

**Comment by arfon** [comment]
Hi @adeepak7. I'm afraid we don't seem to have any record of this submission. Could you share with me the submission email confirmation you received so I can look into this?

**Comment by adeepak7** [comment]
Sir, we submitted it to JOSE

**Comment by adeepak7** [comment]
I understand that issue should have been opened in JOSE repository, the JOSE homepage redirected me to JOSS repository!

**Comment by arfon** [comment]
> I understand that issue should have been opened in JOSE repository, the JOSE homepage redirected me to JOSS repository!

Ah OK. Understood.

/ cc @openjournals/jose-eics

**Comment by danielskatz** [comment]
I'm going to close this, since it's not a JOSS issue
