### ISSUE TITLE
Pre-submission enquiry for ocean_data_tools

### ISSUE THREAD

**Issue by lnferris** [openjournals/joss#759]
Hello JOSS,

I’m writing to enquire about the suitability of my software package (https://github.com/lnferris/ocean_data_tools) for Journal of Open Source Software.  I think it would be a good fit because it simplifies the process of extracting, formatting, and visualizing bulk freely-available oceanographic data.

<img width="500" alt="model_domain_plot-hycom copy" src="https://user-images.githubusercontent.com/24570061/85363705-8e8cd880-b4ef-11ea-8fa7-1de11d6afade.png">

A wealth of oceanographic data (from research cruises, autonomous floats, and global ocean models, etc.) is available online. However, many oceanographers and environmental scientists (particularly those from subdisciplines not accustomed to working with large datasets) can be dissuaded from utilizing this data because of the overhead associated with determining out how to batch download data, format it into an easily-manipulable data structures, and make graphics. ocean_data_tools solves this problem by allowing the user to transform common oceanographic data sources into uniform structs (e.g. argo, cruise, hycom, mercator, woa, wod) and call generalized functions on these structs, or easily perform custom calculations. The package also includes instructions and shell scripts for downloading the data itself.

<img width="500" alt="transect_select" src="https://user-images.githubusercontent.com/24570061/85363815-d4e23780-b4ef-11ea-814e-198c5eb09cca.png">

Another neat feature is the ability to create virtual cruises from model data. The user can draw transects on a map to build stations out of the model data and make plots. I suspect this has value as a cruise-planning tool. Personally I use ocean_data_tools to gain contextual information from HYCOM model data for autonomous underwater glider surveys.

Thank you for taking the time to read my enquiry and I look forward to hearing from you.

Best regards,

Laur Ferris (lnferris@vims.edu)
PhD Candidate | Physical Oceanography
Department of Physical Sciences
Virginia Institute of Marine Science

**Comment by arfon** [comment]
:wave: @lnferris - this definitely looks like it could be in scope. My only potential concern with this software is the way it has been put together (i.e. structure of the package) and whether it meets our criteria of being [designed for maintainable extension](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements). On this question I defer to a MATLAB expert on this topic such as @Kevin-Mattheus-Moerman or @cMadan.

**Comment by kthyng** [comment]
Hi @lnferris! This looks awesome! I can personally attest to how much of a problem this is, even when you know how to deal with the data, even finding it can be a problem, and it would be great to not have everyone recreating solutions. 

It would be great to have it be well-packaged (as mentioned by @arfon), and if possible available also in Python (I see a folder listing there). I'd also hope to see that it is really easy to use for "not computer" people with as much automated as possible. This category of person often uses Matlab, and for Python I think Jupyter notebooks would be appropriate. And of course, the more datasets you can provide easy access to, the better! All of these items are just things that I am thinking about so I could use this or imagine people in my dept using this in the future, but not required necessarily.

**Comment by lnferris** [comment]
Hi @kthyng and @arfon , I appreciate your quick feedback! Here are some examples of how a person would use it (https://github.com/lnferris/ocean_data_tools/blob/master/demos/demos.m). I am interested in continuously adding support for more datasets (e.g. http://www.remss.com/ products, AVISO+, etc.) but have a question about this. 1. Would I be able to continue contributing to the package after hypothetically publishing it (e.g. assign a Zenodo "Cite all versions" doi), or does JOSS publish the release-specific doi? 2. The Python folder isn't part of the package per se, it's hanging out there for syntax examples if someone wanted to see how to do similar things in Python. You mean I should write a Python version of the package and also include in the repo, or remove the Python folder? 3. Could you please link me to a resource or example for what well-packaged means? I am motivated to improve my packaging as you have suggested but am unsure of what exactly to strive for. 4. One idea is to create Matlab functions that call the shell scripts (so a not-computer person could more easily use them. What do you think about this? Thank you!!

**Comment by kthyng** [comment]
Demos/examples can be used to demonstrate correct behavior for the code in addition to demonstration capabilities. For this, it's typical to include sample data with the package or somehow accessible long term (like through figshare) and then include the output, as numbers and/or what the resultant plot should look like. 

1. You can definitely continue to contribute to the package, though I think the Zenodo doi links to a specific release. Sometimes if a package has been substantially changed, people may even write another JOSS paper. However, I think more typical would be to make your changes and still cite the JOSS paper from the previous version, assuming they are similar enough. You could address this expectation in your paper potentially to suggest changes that may occur in the future.

1. You don't need to do anything with the Python folder necessarily, but I would personally appreciate a Python version of this code :)  

1. I will ping the Matlab people again about matlab packaging: @Kevin-Mattheus-Moerman or @cMadan. For Python packages this typically means making the package as easy to install as possible, having good documentation, good example, unit tests (or some way to demonstrate the code works for a user, like in the first item here). The basics are the same for any language, but the details are different.

1. Same for the last item.

**Comment by cMadan** [comment]
Regarding Matlab packaging, I think there aren't clear norms on how this is expected, but typically when a package involves more than a few Matlab files, I keep it together in a folder and then load it by using addpath in the project code or startup.m. Here my suggestion would be to move the main Matlab functions into a folder (e.g., this wouldn't contain the demos or non-Matlab code) so there's a ready folder of code for what the user would copy to their Documents/Matlab folder or project folder where they're using the code. This organisation would likely also make the project a bit more approachable as it's a bit unclear where to start (some additional documentation there would likely also be useful).

Presumably all of the Matlab functions in the main folder are those that you might expect a user to call directly? I noticed that there are more Matlab code files in the 'utilities' folder, so presumably none of these would be expected to be called directly by the user?

I think it would also be worth briefly explaining the what's in the Python code folder in the README.

**Comment by lnferris** [comment]
Thank you for the feedback! That is correct, the utilities are called by main functions. I moved the functions and will add some additional documentation.

**Comment by danielskatz** [comment]
I'm going to close this now - please free to reopen it or open another issue if needed
