### ISSUE TITLE
Thank you for JOSS

### ISSUE THREAD

**Issue by 1fmusic** [openjournals/joss#760]
I wanted to write a quick note to say thank you for creating this journal and making the process of submitting so painless. I recently submitted a package and even though it was not approved due to being a minor utility, the submission process really improved our documentation, code and accessibility. Submitting to JOSS ultimately made our code better. Thank you for your hard work. 

Regards,  
Summer

**Comment by arfon** [comment]
❤️ thanks @1fmusic! Glad this still had a positive effect for you even though it didn't work out this time.
