### ISSUE TITLE
blog TOC needed

### ISSUE THREAD

**Issue by danielskatz** [openjournals/joss#766]
Now that we a fair number of blog posts on our blog (https://blog.joss.theoj.org), the only way to find to find one is to scroll down.  It would be good to create a TOC on the page, since each one now is individually addressable

**Comment by arfon** [comment]
https://blog.joss.theoj.org/toc

**Comment by danielskatz** [comment]
I like this magic - find a problem, open an issue, wait a little bit, the solution appears :)
