### ISSUE TITLE
add

### ISSUE THREAD

**Issue by danielskatz** [openjournals/joss#775]
It appears we are Diamond/platinum OA 

"Journals which publish open access without charging authors article processing charges are sometimes referred to as diamond or platinum OA. Since they do not charge either readers or authors directly, such publishers often require funding from external sources such as academic institutions, learned societies, philanthropists or government grants."  -- https://en.wikipedia.org/wiki/Open_access#Diamond/platinum_OA

Maybe we should use this term in our docs.

**Comment by arfon** [comment]
💎 Yes! Does it make sense to state this in https://joss.theoj.org/about#costs ?

**Comment by danielskatz** [comment]
I was thinking https://joss.theoj.org/about#content_license - maybe elsewhere too?

**Comment by arfon** [comment]
:+1: that would work yes.
