### ISSUE TITLE
About Publishing new software release

### ISSUE THREAD

**Issue by iagolemos1** [openjournals/joss#776]
Hello, JOSS,
I already have a published paper in the journal called "thresholdmodeling: A Python package for modeling excesses over a threshold using the Peak-Over-Threshold Method and the Generalized Pareto Distribution". I am working in a new realease, which is almost done, remodeling completly the software, with new functionalities and algorithms.  Is it reasonable and allowed submiting another paper dealing with the new release? 
Thanks!

**Comment by kyleniemeyer** [comment]
Hi @iagolemos1, we will consider new versions of a software package that has been previously published, as long as the new version has substantial differences. For example, we would consider a major new version of the software that has substantially new or different functionality.

**Comment by iagolemos1** [comment]
Hi, @kyleniemeyer . Glad to hear. Thanks!
