### ISSUE TITLE
Pre-submission enquiry - BiPyMc

### ISSUE THREAD

**Issue by wgurecky** [openjournals/joss#786]
Hi JOSS,

I developed a package for model calibration called BiPyMc: https://github.com/wgurecky/bipymc.  BiPyMc (Bayesian Inference for Python using Markov Chain Monte Carlo) contains implementations of common Markov chain Monte Carlo routines, including Adaptive Metropolis, DREAM, and Delayed Rejection Adaptive Metropolis (DRAM) samplers. Additionally, this package contains a sub-module for Gaussian process regression and Bayesian optimization using parallel Thompson sampling.  I am wondering if this package is suitable for inclusion in JOSS.

The main differentiating factor of this package over other MCMC python packages is the inclusion of an MPI-parallelized version of Differential Evolution Adaptive Metropolis (DREAM) algorithm. For model calibration problems with a large number of unknowns, and a fairly high computation cost, it is beneficial to utilize 2 levels of parallelism: The first layer in the individual model simulations, and the second layer at the MCMC chain level. This package allows for such an approach.

This package has been exercised on a variety of calibration tasks and compared to a well-established sampler: Emcee.  Specifically, this package exhibited good performance when used to calibrate closure models in a thermal hydraulics package, and a PWR core simulator package.  The package includes a few generic example cases to show the relatively superior performance of DREAM in high dimension problems, and for multimodal problems.

Is this package in the scope of the journal?

**Comment by jedbrown** [comment]
Sounds in-scope and similar in some ways to hiPPYlib, which also supports model parallelism and has been [published](https://joss.theoj.org/papers/10.21105/joss.00940) in JOSS.
