### ISSUE TITLE
Pre-submission enquiry

### ISSUE THREAD

**Issue by milicag** [openjournals/joss#790]
@arfon I am impressed with your journal and would like to publish my code package on [Multiscale Solar Water Heating](https://github.com/LBNL-ETA/MSWH/) with you. I was reluctant to submit the paper directly as the code was already [published as DOE code](https://www.osti.gov/biblio/1515849-multiscale-solar-water-heating-mswh-v1), so I was not sure if it is still suitable for JOSS. Please let me know if you think the code is still a JOSS paper candidate and I am happy to submit the short paper with the code.

**Comment by danielskatz** [comment]
I think it depend on what your goals are.  I wouldn't call what happens with DOE code publishing, more depositing into a repository.  JOSS would also review your code and your paper, which the DOE code process does not.  And you certainly can do both.  In the JOSS process, you could use DOE code as the last step of depositing your code in an archival repository that gives a DOI, which is linked to the JOSS paper.
