### ISSUE TITLE
Pre-submission enquiry

### ISSUE THREAD

**Issue by VincentAlcazer** [openjournals/joss#792]
Dear Editorial team,

We are a french team working in the field of Immunology and bioinformatic in Lyon, France and we are currently developing a free software for every-day statistical analysis. As this software is more and more used by researchers and medical doctors in our institution (the Cancer Research Center of Lyon http://www.crcl.fr/209-Homepage.crcl.aspx?language=en-GB), we are thinking of publishing it as a both a website and a R package.

We would like to know if this work could be in the scope of your journal for our future submission.

The software is currently in beta-version and can be accessed online at: https://vincentalcazer.shinyapps.io/StatAid/

This software is developed with R and will include more and more features with coming updates. Current features are including:

    Exploratory data analysis: distribution, count, missing-values and outliers check
    Descriptive analysis, simple comparative analysis and publication ready 'table 1' output
    Univariate analysis and models for continuous and categorical outcome: Correlation, linear and logistic regression
    Univariate analysis and models for time-dependant outcome: Kaplan-Meier curves and cox regression
    Multivariate models for continuous and categorical outcome
    Multivariate models for time-dependant outcome (to be implemented...)
    Matched data support (case-control studies, repetead measures) 

A complete guide concerning data format and control will be concomitantly published and made available on the website. This guide will go through all the steps of "good practice" to gather data for data analysis, from data collection and encoding to data exploration and quality checking.

We believe this website/R package will be of great help and interest for researchers and medical doctors with no coding skills or no available statistical software for their study. The beta version has already helped multiple young medical student with their thesis, researchers for their PhD project and even confirmed principal investigators with a quick easy-to-use tool for every-day statistics.

Should you need further information please do not hesitate to contact me. Thank you by advance for your consideration.

Best regards,

Vincent Alcazer

**Comment by arfon** [comment]
Thanks for your enquiry @VincentAlcazer. I see you've gone ahead and submitted this 👍 so I suggest we discuss scope questions in the pre-review issue which will be opened shortly.
