### ISSUE TITLE
Pre-submission inquiry - genetic codes in yeasts

### ISSUE THREAD

**Issue by smuehlh** [openjournals/joss#793]
I'm working on genetic codes in yeasts and have identified unusual ones in the past using some custom Ruby scripts to create input for the proteomics software package [MaxQuant] (https://www.maxquant.org/) and to parse MaxQuant's output for codon translations. 

Original publications based on my scripts are: 
- https://doi.org/10.1016/j.cub.2018.04.085
- https://doi.org/10.1101/gr.200931.115 

Others have picked up the methodology we've described there and build upon it. 

To me, it is past time to finally publish my scripts. To this end, I am in the process of rewriting them into a concise library and completing it with tests. I am not yet finished and will keep the github repository private until then. 

Would this project be of interest for your journal, once the rewrite is complete and the repo is publicly available?

**Comment by arfon** [comment]
That sounds like it would be in scope. Please go ahead and submit when you are ready.
