### ISSUE TITLE
couldn't submit reviewer sign-up form

### ISSUE THREAD

**Issue by marwahaha** [openjournals/joss#795]
Sorry if this is the wrong place for a bug report.

I was trying to fill out the form to sign up as a volunteer reviewer. https://joss.theoj.org/reviewer-signup.html

I got through the form but it wouldn't submit. I noticed in the network tab this was happening:

![image](https://user-images.githubusercontent.com/2541209/91828358-df5a3500-ebf4-11ea-8251-d7e94c2302c3.png)

**Comment by arfon** [comment]
Thanks for spotting this @marwahaha. I just tried submitting too and it didn't seem to work.

@karthik - any ideas what might be going on here?

**Comment by karthik** [comment]
Looks like typeform was down earlier today: https://status.typeform.com/

I'll check shortly to make sure everything is back to normal

**Comment by karthik** [comment]
It works again

**Comment by arfon** [comment]
I agree the form is working but when I submit an entry, it no-longer seems to be being written to the spreadsheet (the last update was ~13 hours ago).

**Comment by karthik** [comment]
AH let me check Zapier.

**Comment by karthik** [comment]
I fixed the issue (sent you an email) and it works now. The copyright statement at the top will break the integration.  The Googlesheet should always only have column headers at the top.

**Comment by arfon** [comment]
Thanks for fixing this @karthik!
