### ISSUE TITLE
Adding link to pre-review issue

### ISSUE THREAD

**Issue by bsipocz** [openjournals/joss#797]
Unlike the review issue, the pre-review issue has software report summary, therefore I would find it useful if a quick link to the pre-review would exist in review post.

**Comment by danielskatz** [comment]
There is a link near the start of each review issue to the pre-review issue - just below the checklists.

Also, you can run ```@whedon check repository``` if needed

**Comment by bsipocz** [comment]
Ahh, ok, I indeed missed that cross reference, and was looking for an actual link. Also thanks for the whedon command.
