### ISSUE TITLE
Whedon doesn't provide error messages for broken bibliography

### ISSUE THREAD

**Issue by dstansby** [openjournals/joss#798]
I'm currently trying to compile the paper at https://github.com/dstansby/pfsspy/tree/joss-paper/joss-paper; whilst the paper compiles fine, none of the references are showing up properly (compiled paper [here](http://res.cloudinary.com/hju22ue2k/image/upload/v1599844407/ox1w5axgqcfyb1gmr6hl.pdf)). Whedon isn't showing any error messages to help me diagnose the problem, so I don't know what to do in this case, and more specifically it would be helpful if bibliography error messages were shown.

As an aside, is there any way to compile papers locally? I could only find information on using the Whedon website to do the compilation.

**Comment by emdupre** [comment]
> As an aside, is there any way to compile papers locally? I could only find information on using the Whedon website to do the compilation.

If you have a working Ruby environment, you should be able to [install the Whedon gem](https://github.com/openjournals/whedon#installation). Then you can run `whedon compile` locally !

**Comment by dstansby** [comment]
Ah fab, I'm not sure why I didn't find that before! Maybe it would be good to add a note/link to https://whedon.theoj.org/ saying that people can compile their papers locally?

**Comment by arfon** [comment]
We're actually in the process of developing a Docker image to for this kind of local debug. Not sure if this would help you @dstansby in this case? Intuitively I feel like a Docker image is more user-friendly than installing a Ruby environment.

**Comment by dstansby** [comment]
Yeah, probably easier, but takes up more space? (I'm still on a 128GB drive with my main laptop, so struggle with docker stuff, so having the ruby option is helpful for me). At least for this issue I should be able to diagnose locally now.

**Comment by arfon** [comment]
Just following up here, we now have the preview service (https://whedon.theoj.org), a GitHub Action, and a Docker option. They're all documented here: https://joss.readthedocs.io/en/latest/submitting.html#checking-that-your-paper-compiles
