### ISSUE TITLE
Pre-submission enquiry: cogli2

### ISSUE THREAD

**Issue by lorenzo-rovigatti** [openjournals/joss#799]
Hello. I am wondering whether the [cogli1/cogli2](https://sourceforge.net/projects/cogli1/) software, which is a tool that can generate publication-ready simulation snapshots and movies would be, in principle, publishable in JOSS.
The tool is mature and has been used for years to produce figures that have been published in several papers, although it has been directly referenced only a few times. 

Here are a few papers that explicitly mention cogli1:

* [The oxDNA coarse-grained model as a tool to simulate DNA origami](https://arxiv.org/abs/2004.05052)
* [Design and Synthesis of a Reconfigurable DNA Accordion Rack](https://www.jove.com/t/58364/design-and-synthesis-of-a-reconfigurable-dna-accordion-rack)
* [Computational Simulation of Adapter Length-Dependent LASSO Probe Capture Efficiency ](https://www.mdpi.com/2218-273X/9/5/199)

**Comment by arfon** [comment]
:wave: @lorenzo-rovigatti - thanks for your enquiry. Although we've treated submissions differently in the past, we generally consider submissions like this (i.e. ones that produce figures/tools related to publishing) out of scope for JOSS these days.
