### ISSUE TITLE
Question on new deployment

### ISSUE THREAD

**Issue by emdupre** [openjournals/joss#801]
Hi everyone,

Thanks so much for developing this great infrastructure !

I'm working on getting a deployment up and running on heroku, and I've successfully been able to work through most of the configuration. I have a record of everything that I've done so far, in case it's useful to add to the development docs later !

One question I can't figure out, though, is where to get the `WHEDON_SECRET` key. I notice that it's listed in this codebase and in the Whedon codebase, so I assume it's related to the Whedon-API application. Is it just the API key from the Heroku Platform API ?

Relatedly, I assume that the `JOSS_API_KEY` on Whedon-API is generated in the same way (but from a running instance of this application). But any insight here would be very much appreciated !

**Comment by emdupre** [comment]
OK, I think I've worked out that any key is fine, so long as `WHEDON_SECRET` and `JOSS_API_KEY` are the same !

I'm struggling to squash a few other bugs so I can really test that, so I'll leave this open for now :sparkles:

**Comment by arfon** [comment]
Ugh yes, sorry. `JOSS_API_KEY` on Whedon and `WHEDON_SECRET` on the JOSS application are the same secret. It's basic auth to make sure that Whedon can talk to the JOSS application.

As to how to make it. I'd recommend making a random SHA1 string or something like that.

**Comment by emdupre** [comment]
Great, thanks for confirming !

I'll close this and follow-up on more specific issues / PRs with info on working through the config :smile_cat:
