### ISSUE TITLE
Impact factor for this journal.

### ISSUE THREAD

**Issue by hongyi-zhao** [openjournals/joss#803]
Hi,

Does this journal also has an impact factor calculated by ISI/JCR?

Regards,
HY

**Comment by danielskatz** [comment]
FYI:
https://www.natureindex.com/news-blog/whats-wrong-with-the-jif-in-five-graphs
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6109637/
https://www.helsinki.fi/en/news/data-science-news/poor-correlation-of-journal-impact-factor-with-scientific-impact
https://sfdora.org/read/

**Comment by arfon** [comment]
Also related https://github.com/openjournals/joss/issues/721.

In short @hongyi-zhao - we don't have one and aren't very motivated to compute one.
