### ISSUE TITLE
Pre-submission inquiry: repro-catalogue

### ISSUE THREAD

**Issue by kevinxufs** [openjournals/joss#804]
The  [repro-catalogue](https://repro-catalogue.readthedocs.io/en/latest/) tool  is used to aid reproducibility of analysis.

>Research projects are frequently updated - new data are added, and the code undergoes regular changes. Under these circumstances, it’s easy to store results, yet lose track of the context in which they were produced. To ensure reproducibility of any scientific results we need to reliably record the input data, analysis code and analysis results.

> The catalogue tool aids reproducibility by saving hash values of the input data and the results, along with the git commit hash of the code used to generate those results. The catalogue command line interface then allows the user to easily compare the hash values from different occasions on which the analysis was run so that changes to the input data, code and results can be identified and the impact on reproducibility can be understood.

The _obvious research application_ is that it ensures analysis is reproducible as we can share our analysis process and/or share our inputs with others and ensure we get the same output. This can be crucial for collaborative research. Another application is to ensure any code refactoring maintains the same output data - this will be identified by having the same hash.

Would this tool be suitable for a JOSS submission?

([link to repo](https://github.com/alan-turing-institute/repro-catalogue))

Thank you

**Comment by arfon** [comment]
:wave: @kevinxufs - thanks for the enquiry. I would say this is likely *not* in scope for us as we generally do not publish software packages that enable research.

I'll leave this open for others to comment but I'm pretty sure this is out of scope for us.

**Comment by danielskatz** [comment]
> I would say this is likely not in scope for us as we generally do not publish software packages that enable research.

I agree

**Comment by edaub** [comment]
Thanks for the reply and for clarifying -- we appreciate your time and the hard work that goes into JOSS submissions!

**Comment by KirstieJane** [comment]
Hi @arfon & @danielskatz! I'm surprised by this decision (although @edaub assures me that it is consistent with previous decisions so I guess there's a logic that I'm just not getting).

What do you mean by "we do not publish software packages that enable research".... feels like an odd boundary to choose! Would `git` for example not be publishable by JOSS? (I'm not suggesting our little tool is the new git, just trying to understand the decision criteria!)

**Comment by danielskatz** [comment]
Yes, we would likely not publish a paper on git, in my opinion.  We publish software that directly supports research, software that researchers would choose to cite as contributing to their research.
