### ISSUE TITLE
check for valid repo before allowing submission to JOSS

### ISSUE THREAD

**Issue by danielskatz** [openjournals/joss#809]
We should check any incoming submissions to make sure the link provided by the submitter is to a repo (cloneable) and is not the full path to a paper (not cloneable).  It's clear we haven't succeeded in crafting instructions that submitters can always follow, so the next step should be to try to check this and not allow the submission until this is fixed.

**Comment by arfon** [comment]
I'd love to do this in JavaScript in the user interface, but haven't had a chance to figure out how yet...

**Comment by arfon** [comment]
Fixed in https://github.com/openjournals/joss/pull/812
