### ISSUE TITLE
Fit for JOSS?

### ISSUE THREAD

**Issue by darribas** [openjournals/joss#816]
Hello,

I'm opening this issue to enquire whether it'd be of interest to JOSS a paper describing the [`gds_env`](https://darribas.org/gds_env/). This is not exactly a _package_ in the traditional way, but instead is a project to develop standardised, up to date, containers with a broad suit of packages for geospatial. This is really an extension of the [Jupyter Stacks](https://github.com/jupyter/docker-stacks) to augment them with geospatial libraries (which are usually tricky to install natively). In that sense, I'd see a JOSS paper similar to the one for [Rocker](https://www.rocker-project.org/), published on the [R Journal](https://rjournal.github.io/archive/2017/RJ-2017-065/index.html) (but of course in a shorter format).

More generally, I think the paper would be a good venue to put forward more general ideas about the need to focus not only on individual packages but on the platforms that allow those packages to run, and the benefits of "standardising" these platforms in similar ways to how packages "standardise" bespoke code for scientific computing.

What do you think? I recognise this is probably slightly off the beaten path for JOSS so do feel free to be explicit if you don't think it's a good fit.

**Comment by arfon** [comment]
Thanks for the enquiry @darribas - this sounds like an interesting project. Unfortunately I think this is out of scope for us.

> More generally, I think the paper would be a good venue to put forward more general ideas about the need to focus not only on individual packages but on the platforms that allow those packages to run, and the benefits of "standardising" these platforms in similar ways to how packages "standardise" bespoke code for scientific computing.

☝️ this is really interesting and I think you should definitely find a place to publish about this. Perhaps something like PeerJ-CS?
