### ISSUE TITLE
Pre-submission enquiry

### ISSUE THREAD

**Issue by jaclark5** [openjournals/joss#817]
I'm looking for a journal to publish my python package in, and I believe JOSS would be a good fit. My package, "DESPASITO: Determining Equilibrium State and Parametrization: Application for SAFT, Intended for Thermodynamic Output" can be found here.
https://github.com/jaclark5/despasito

However, in your "JOSS submissions must:" list, I noticed a category under which my package could be placed. "Minor 'utility' packages, including 'thin' API clients, and single-function packages are not acceptable.

DESPASITO was initially a parametrization and validation application for a specific equation of state (EOS), but has been designed in a way that is easily extended. 
- Such areas of growth include, new EOSs (also supports Peng-Robinson) and additional thermodynamic property calculations
- Possible applications include,  (1) thermodynamic calculations of complex systems using EOS, (2) fitting parameters for MD simulations, and (3) undergraduate chemical engineering thermodynamics curriculum.

Alternative applications (gSAFT) are not as readily available commercial softwares.
https://doi.org/10.1016/B978-0-444-63965-3.50169-0

Would a publication on DESPASITO be a good fit for JOSS?

**Comment by arfon** [comment]
@kyleniemeyer - any thoughts on this submission?

**Comment by kyleniemeyer** [comment]
I think this would be in scope - it is not an API client and certainly offers more than a single function. 

(By "single function package", I think we mean something that, for example, offers a single Python function, rather than something that serves a single overall purpose, if that is the source of confusion.)

**Comment by jaclark5** [comment]
I'm glad to hear it! Thanks for clarifying. Are there limitations on publishing a package with a DOI from Zenodo? I haven't taken that step, but I've been advised to consider it.

**Comment by kyleniemeyer** [comment]
@jaclark5 no, in fact we require that as part of the JOSS publication process. After the reviews  and any changes/revisions to the package are complete, authors archive the newest version on Zenodo and the resulting DOI is published in the article. So, there's nothing at all incompatible about getting in the habit of archiving versions of your software!
