### ISSUE TITLE
reference formatting issue for @misc item with n.d.

### ISSUE THREAD

**Issue by danielskatz** [openjournals/joss#818]
In https://github.com/openjournals/joss-reviews/issues/2579, this bib entry

```
@misc{OpenSeadragon,
	title = {OpenSeadragon},
	publisher = {GitHub},
	journal = {GitHub repository},
	url = {https://github.com/openseadragon/openseadragon}
}
```

generates
> OpenSeadragon. (n.d.).GitHub repository. GitHub. Retrieved from https://github.com/ openseadragon/openseadragon

note that this should have a space after the date, and should be
> OpenSeadragon. (n.d.). GitHub repository. GitHub. Retrieved from https://github.com/ openseadragon/openseadragon

Is this something we can fix?  Or is a bug in something we don't control?  If so, can we report it?

**Comment by arfon** [comment]
I wonder if this is a fix that could be made in the CSL? I've look at the [JOSS CSL](https://github.com/openjournals/whedon/blob/master/resources/joss/apa.csl) but can't quite figure out where the fix might be...

@tarleb - any thoughts?

**Comment by tarleb** [comment]
I'll take a look later today.

**Comment by tarleb** [comment]
So far I couldn't figure out yet what's going on there. This is very strange.

Maybe the authors could use an alternative type to describe the resource? E.g.,

``` bibtex
@online{OpenSeadragon2,
  title = {OpenSeadragon},
  subtitle = {GitHub repository},
  url = {https://github.com/openseadragon/openseadragon},
  date = {2020},
  urldate = {2020-10-01}
}
```
renders as

> OpenSeadragon: GitHub repository. (2020). Retrieved October 1, 2020, from <https://github.com/openseadragon/openseadragon>

which is arguably nicer.

**Comment by danielskatz** [comment]
It's already published, and not worth changing at this point for the sake of a space.

This issue was more a general one, not for this specific paper.  This paper is just a demonstration of this problem.

**Comment by tarleb** [comment]
OK, found a fix; I'll prepare a PR.

I noticed that the `apa.csl` still contains the APA 6th edition, while there is also a 7th edition. The latest edition does not have the spacing problem. I'd need to re-apply the ISBN changes, but maybe this issue would be a good opportunity to switch to APA 7th edition?

**Comment by arfon** [comment]
:+1: sounds good to me @tarleb. Are you good to open a PR against https://github.com/openjournals/whedon ? 

Note the `apa.csl` exists in three places in the repo (https://github.com/openjournals/whedon/tree/master/resources) :-( . I should probably fix that too...

**Comment by tarleb** [comment]
Reminder to self: update in Docker image as well.
