### ISSUE TITLE
Ask authors about parallel/related submissions

### ISSUE THREAD

**Issue by arfon** [openjournals/joss#819]
When authors submit, we should ask them if any portion of the work is (or has been) being reviewed in another peer-reviewed publication venue.

Suggested language below:

> Has any portion of the submitted work (which includes code and documentation) been published or submitted, or is planned for submission, to another peer-reviewed publication venue?  If yes, please describe.

**Comment by danielskatz** [comment]
I think this is reasonable, but we have to then figure out what rules we use when they say yes, where those rules are consistent across both AAS and other publishers
