### ISSUE TITLE
Allow whedon commands to be issued in any empty line of the comment

### ISSUE THREAD

**Issue by sylvaticus** [openjournals/joss#820]
I have learn that whedon commands can be executed only when the whedon is "the only or first thing in a new comment".

Aside that this is not explained in the [documentation](https://joss.readthedocs.io/en/latest/whedon.html), isn't be too much restrictive? In most situations this means duplicate the posts of a thread, a single comment + command would result in a more compact thread, without duplicated notifications.

For example the [@JuliaRegistrator register](https://github.com/JuliaRegistries/Registrator.jl) bot allows the command to be issued on any empty lines in the comments.

**Comment by jni** [comment]
@sylvaticus Great minds think alike! https://github.com/openjournals/whedon/issues/81 :stuck_out_tongue_winking_eye:

**Comment by sylvaticus** [comment]
oh sorry.. I did look for similar issues before posting, but I didn't realised whedon is on a separate repository.. closing as duplicate.. cheers
