### ISSUE TITLE
Submitting a paper to JOSS requirements in terms of citations and page count

### ISSUE THREAD

**Issue by amirouche** [openjournals/joss#828]
There is no mention of number of citation and number of pages.

In particular the number of pages, most of the paper I skimmed over are two or three of pages? Is that the expected format?

ref: https://joss.readthedocs.io/en/latest/submitting.html

**Comment by danielskatz** [comment]
see https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain

**Comment by amirouche** [comment]
Thanks ^^'
