### ISSUE TITLE
PDF Generator - citation error

### ISSUE THREAD

**Issue by kadyb** [openjournals/joss#836]
I am trying to generate a PDF from Markdown using [Open Journals PDF Generator](https://github.com/marketplace/actions/open-journals-pdf-generator). But when using citation in Markdown from BibTeX, I get the following error:

> Error producing PDF.
> ! LaTeX Error: Environment CSLReferences undefined.

Here is an example repository: https://github.com/kadyb/test-gaia

**Comment by arfon** [comment]
Thanks for flagging this @kadyb.

@tarleb - I think this is related to the changes that were made for the latest Pandoc release (e.g. https://github.com/openjournals/whedon/commit/a852c1ce3cd09f64869f09106e6ee102cd65bb23), in which the LaTeX template needed modifications to the `CSLReferences` definition.

Any chance you could take a look here and see what's going on?

**Comment by tarleb** [comment]
:+1: I'll take a look later today.

**Comment by tarleb** [comment]
@arfon you were right, a simple rebuild of the Docker image solved this. I used the opportunity to also upgrade to pandoc 2.11.2.

@kadyb thanks for the report and sorry for the inconvenience. Everything should work now.

**Comment by kadyb** [comment]
I can confirm that it works for test repository now. Thanks for the help!
