### ISSUE TITLE
Pre-submission enquiry software write-up published elsewhere

### ISSUE THREAD

**Issue by McGregor14** [openjournals/joss#837]
Does JOSS accept submissions where a write-up of the software (i.e. a longer manuscript describing its uses and capabilities) is published/is intended to be published elsewhere?

I am thinking of a case where code review and a more extensive description of the software are both desired.

Thanks.

**Comment by arfon** [comment]
Hi @McGregor14 - this is a great question, and sometimes a difficult one to answer clearly without seeing the proposed submission. I'm assuming you've read the guidance we have drafted in the section of of submission guidelines on [_substantial scholarly effort_](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)?

Would it be possible for you to share a link to the repository/project you're planning on writing up?

**Comment by McGregor14** [comment]
Hello @arfon - thanks for the response. I can't share the repository at the moment, but I will try to answer the questions in the **_substantial scholarly effort_** section...

Background: we are developing software for delivering remote fear conditioning experiments.

_**Age of software (is this a well-established software project) / length of commit history.**_
We have been working on this software for approximately 4 years. We plan to make our 4th version (under development) open-source and accessible to other researchers. The first 3 versions were created with a different tech company and used by ourselves and a couple of collaborators.

_**Number of commits.**_
I am not sure of this and we have recently been re-platforming the software with a new company to allow for improvements.

_**Number of authors.**_
I imagine this would be around 10, though not confirmed.

**_Total lines of code (LOC). Submissions under 1000 LOC will usually be flagged, those under 300 LOC will be desk rejected._**
Should be well over this.

_**Whether the software has already been cited in academic papers.**_
We have validated a previous version of the software in a paper that can be found [here](https://www.sciencedirect.com/science/article/pii/S0005796719301615).

_**Whether the software is sufficiently useful that it is likely to be cited by your peer group.**_
We have a lot of interest in the software already and hope it will have a big impact in the field.

We really think the software would benefit from the code review your journal offers, but ideally we would also like to bring out a paper with an extensive description of the app where the write-up was also peer-reviewed.

**Comment by McGregor14** [comment]
Hi @arfon, 

Do you have any thoughts on this feedback, or is there anything else I can provide you with?

**Comment by McGregor14** [comment]
@arfon here is the link to the repository: https://github.com/flare-kcl

**Comment by arfon** [comment]
Sorry we never got back to you about this. Looks like it's under review here: https://github.com/openjournals/joss-reviews/issues/3270
