### ISSUE TITLE
Pre-submission enquiry about geneExpressionFromGEO package

### ISSUE THREAD

**Issue by davidechicco** [openjournals/joss#841]
Dear JOSS members,

I am opening this issue to submit a pre-submission enquiry regarding the possible submission of an article related to my software package `geneExpressionFromGEO` to JOSS. 
`geneExpressionFromGEO` is an R open source package based on some [Bioconductor](https://www.bioconductor.org/) packages that facilitates the read of gene expression datasets from [Gene Expression Omnibus (GEO)](https://www.ncbi.nlm.nih.gov/geo/) (one of the main public resources for gene expression data), that otherwise would be more complicated.

The main function of this package reads in only the GEO accession code of a databaset, retrieves the data from GEO, and returns a dataframe table with the genes on the rows and the samples on the columns. Additionally, this function can associate the gene symbols to the probesets, if the user requires so.
The main strength of `geneExpressionFromGEO` is its simplicity and easiness to use, that makes it quite useful for R users, especially for beginners.

`geneExpressionFromGEO` has been accepted on CRAN and is [currently available there](https://cran.r-project.org/web/packages/geneExpressionFromGEO/index.html).

I checked the [submission requirements of JOSS](https://joss.readthedocs.io/en/latest/submitting.html#what-we-mean-by-research-software), and I put **in bold** the ones that I believe my package satisfies:

> JOSS publishes articles about research software. This definition includes software that: solves complex modeling problems in a scientific context (physics, mathematics, biology, medicine, social science, neuroscience, engineering); **supports the functioning of research instruments or the execution of research experiments; extracts knowledge from large data sets;** offers a mathematical library, or similar.

> JOSS publishes articles about software that represent **substantial scholarly effort on the part of the authors**. Your software should be a significant contribution to the available open source software that either enables some new research challenges to be addressed or **makes addressing research challenges significantly better** (e.g., faster, **easier, simpler**).

[Here](https://github.com/davidechicco/geneExpressionFromGEO) you can find the GitHub repository of the package.

Please let me know if `geneExpressionFromGEO` could be considered in an article on JOSS.

Thank you

-- Davide Chicco

**Comment by danielskatz** [comment]
It seems that [this software](https://github.com/davidechicco/geneExpressionFromGEO) is a repository with about 100 lines of R, and 10 commits over 5 days.  If so, this does not meet the JOSS requirement for substantial scholarly effort.

I'm going to close this issue, but feel free to reopen it if I've missed something.

**Comment by davidechicco** [comment]
@danielskatz I see. Thanks for having considered my pre-submission enquiry
