### ISSUE TITLE
Pre-submission enquiry for follow-up papers, authorship limits

### ISSUE THREAD

**Issue by mkhorton** [openjournals/joss#842]
Hello,

I'm writing to enquire about JOSS' stance on software that fulfills all of the JOSS requirements but has been previously published in another journal, for example if a v1 was published many years ago, and a v2 with substantial new functionality is now available (that is, the new features and code in v2 would represent a "substantial scholarly effort" compared to the v1).

Secondly, does JOSS have any limits on the number of co-authors for a paper? Is there any ability to add authors after-the-fact if new authors later make substantial contributions to a software package already represented by a JOSS paper?

Thank you.

**Comment by danielskatz** [comment]
If there's been substantial new work in software published previously, whether in JOSS or elsewhere, JOSS is happy to consider the updated software.  The case you describe sounds reasonable for a JOSS submission.

JOSS does not have a limit on the number of co-authors. And the co-authors should be consistent with the work done on the software at the time of submission; we won't add new co-authors later based on work done after the submission/publication.

**Comment by danielskatz** [comment]
I'm going to close this issue, but feel free to reopen it if this hasn't answered your question.

**Comment by mkhorton** [comment]
Thanks Daniel, that answers my question.
