### ISSUE TITLE
info about pre-submission enquiry not in docs?

### ISSUE THREAD

**Issue by danielskatz** [openjournals/joss#843]
In https://joss.theoj.org/about#submitting, we say

> Authors wishing to make a pre-submission enquiry should [open an issue](https://github.com/openjournals/joss/issues/new?title=Pre-submission%20enquiry) on the JOSS repository.

But I can't find this in the docs.  It seems to me that we should also add this somewhere in https://joss.readthedocs.io/en/latest/submitting.html

**Comment by arfon** [comment]
:+1: agree. Would you mind opening a PR with this change?

**Comment by danielskatz** [comment]
ok - see https://github.com/openjournals/joss/pull/844

**Comment by danielskatz** [comment]
closed via #844
