### ISSUE TITLE
Pre-submission inquiry: Literature Mapper QGIS Plugin

### ISSUE THREAD

**Issue by MicheleTobias** [openjournals/joss#845]
**Request**
I would like to get feedback on whether Literature Mapper would be a good fit for JOSS.

**Software Summary**
[Literature Mapper](http://micheletobias.github.io/maps/LiteratureMapper.html) is a python plugin for QGIS that allows the user to georeference entries in a Zotero bibliography to facilitate mapping locations associated with publications.  It uses the QGIS graphical interface to provide visual tools for marking locations.  Under the hood, it uses the Zotero API to insert location information into an existing field in the Zotero data structure.

Code Repository: [GitHub Repo](https://github.com/MicheleTobias/LiteratureMapper)
Co-author: Alex Mandel

**Why**
I built this tool to help me understand the distribution of study sites in ecological research related to California's coastal sandy beach vegetation.  I was maintaining a paper map marked with citations, then build a shapefile that was always in danger of getting out of synch with my citation database.  I wanted a way to store the locations and citations together.  This tool has potential uses in any field - mapping study sites, author locations, cities mentioned in the text, etc.

**Other Information**

- [Example Web Map Project Built with Data Developed in Literature Mapper](http://micheletobias.github.io/maps/LiteratureMap.html)
- Work Citing this Project: Goldstein et al. (2018), Literature-based latitudinal distribution and possible range shifts of two US east coast dune grass species (Uniola paniculata and Ammophila breviligulata). PeerJ 6:e4932; DOI 10.7717/peerj.4932 https://peerj.com/articles/4932.pdf

**Comment by kthyng** [comment]
Hi @MicheleTobias! This tool looks really neat. My impression of it is that it might not be in scope for JOSS. It seems more like it would be like a meta-research tool (helps the process of organizing research) rather than in the research itself as much, though I do see a reference using it in your note. It's a fine line, so I may not be on the correct side of it. I'll ping a few editors who might be closer in expertise: @usethedata, @danielskatz @KristinaRiemer @karthik could one or two of you take a look and given an opinion?

**Comment by usethedata** [comment]
One person's metadata is another person's data.  From my perspective running a data center that supports field ecologists, this has research potential in a workflow, particularly when combined with other information such as land cover classification.  There may, however, be a scope question in the sense of meeting the [scholarly effort](https://joss.readthedocs.io/en/latest/review_criteria.html#substantial-scholarly-effort) criterion, based on my perusal of the github archive.  I can absolutely see the utility of what's been done, particularly given some of the present challenges of citing papers versus citing the data that the papers describe.  It is also hard, in any kind of an automated sense, to go from a paper to the data that the paper contains.  And the data is where the spatial coordinates are most likely to be found in the metadata.

This work would make a great <region of choice> Geophysical Union poster (Earth and Space Science Informatics section) for a future meeting (2020 AGU meeting is wrapping up Thursday this week).  It absolutely is something that's potentially useful to the field ecology research community.

**Comment by MicheleTobias** [comment]
The tool isn't automated.  It requires the user to make a conscious decision about what coordinates they want map.  At it's core, it facilitates data creation and storage for research purposes, which maybe isn't what this journal publishes.  The current release has been [installed 677 times](https://plugins.qgis.org/plugins/LiteratureMapper/) and a previous version 1600+ times if that helps to know.

**Comment by MicheleTobias** [comment]
This paper was published in Air, Soil, & Water Research so I'm going to close this ticket.
