### ISSUE TITLE
Pre-submission enquiry: TUM OpenInfraPlatform initiation

### ISSUE THREAD

**Issue by pjanck** [openjournals/joss#848]
I'd like to initiate the submission of [TUM OpenInfraPlatform](https://github.com/tumcms/Open-Infra-Platform) to your journal.

I'd like to get a feeling if we're approaching the submission correctly:

- we've opened a [new branch](https://github.com/tumcms/Open-Infra-Platform/tree/joss_submission)
- we've started with [initial commits](https://github.com/tumcms/Open-Infra-Platform/tree/joss_submission/Documentation/joss)
- we've collected our thoughts on the submission guidelines [here](https://github.com/tumcms/Open-Infra-Platform/blob/joss_submission/Documentation/joss/notes.md)
- we've listed possible reviewers [here](https://github.com/tumcms/Open-Infra-Platform/blob/joss_submission/Documentation/joss/notes.md#review)

I assume this submission will take some time on our side. We still need to make sure some things work correctly - observe the [project](https://github.com/tumcms/Open-Infra-Platform/projects/12) handle. Time plan is 2021. 

However, we'd like to initiate this in advance, in order to receive preliminary feedback and approach the submission correctly. I guess we'll use this issue tracker for further questions from our side.

**Comment by pjanck** [comment]
An update: we've now populated the paper with content and would be interested in your review - see https://github.com/tumcms/Open-Infra-Platform/pull/372 .

**Comment by pjanck** [comment]
Update: thank you for providing the github action. The resulting compile can be found at its usual place.

**Comment by arfon** [comment]
Hi @pjanck. Reviews are handled through submission to JOSS here: http://joss.theoj.org
