### ISSUE TITLE
change software_repository for joss.00622?

### ISSUE THREAD

**Issue by johrstrom** [openjournals/joss#851]
Hi I'm on the team who wrote `joss.00622` and we'd like to change the xml metdata for the `artifactinfo/software_repository` for that paper. Is this possible? We're in the process of copying the joss related metadata files over there now.

from 
```xml
 <software_repository>https://github.com/OSC/Open-OnDemand</software_repository>
```
to 
```xml
 <software_repository>https://github.com/OSC/ondemand</software_repository>
```

**Comment by arfon** [comment]
This should be fixed in https://github.com/openjournals/joss-papers/commit/2f72588fec890450f32eca4310ddad07d7c99fc4 (the paper and website are updated too with the new URL).
