### ISSUE TITLE
SAILS paper repo URL change

### ISSUE THREAD

**Issue by AJQuinn** [openjournals/joss#852]
Hello - I hope this is the correct place for this issue, apologies if not.

I submitted and published a paper in JOSS last year (#1982 [joss page](https://joss.theoj.org/papers/10.21105/joss.01982)). Due to a change in circumstances, we're now having to migrate this project from a [university hosted server](https://vcs.ynic.york.ac.uk/analysis/sails) to [gitlab.com.](https://gitlab.com/sails-dev/sails). It would be great to make sure the JOSS paper is pointing to the right place to avoid future confusion! The project is still supported and developement will continue as before.

Is it possible to change the project URL in an already published paper? If so, what would be the best way to go about it? I'm happy to provide any info or try to put together a pull-request if that would be useful.

Many thanks for your time & support

Andrew

**Comment by arfon** [comment]
Sure thing. This was updated in https://github.com/openjournals/joss-papers/commit/e5652fa9230e7924e9037f4efafefff0d5ce345d .
