### ISSUE TITLE
Pre-submission inquiry: Interactive Data Editor 

### ISSUE THREAD

**Issue by Koushikphy** [openjournals/joss#855]
I would like get feedback on whether my software [Interactive Data Editor ](https://github.com/Koushikphy/Interactive_Data_Editor) will be in the scope of publishing in JOSS.  
GitHub Repo: https://github.com/Koushikphy/Interactive_Data_Editor

### Software summary:
Interactive Data Editor is a software that lets the user refine/edit data using a easy-to-use easy-to-understand graphical user interface. Just open the data, identify the bad data or irregularities and apply one of the many ways available here to refine that data. All this happens in a GUI and no additional scripting is required from the user. Additionally it also includes some useful features that is often required when working with data. Apart from that this software can also be used as a simple plotting utility.

### Why:
Data refinement is a crucial step in any research area, specially in experimental and computational fields. It happens very frequently that the data we collect is not ideal and needs some refinement or filtering before using it for our research works. Sometimes we write script/program  to do those filtering if we already know the nature of those outliers, but an brute-force and WYSIWYG way may be the best and most efficient way in many cases. This software lets you do that exactly in a simple and convenient way.   
I believe this software can be a indispensable tool for those working with data in regular basis.

**Comment by arfon** [comment]
Hi @Koushikphy - this could be in scope for us. Without hearing more about its application to research problems it is a little challenging to answer. I would encourage you to submit to JOSS if you're still interested in pursuing a publication with us.
