### ISSUE TITLE
Pre-submission enquiry: oxDNA and oxpy

### ISSUE THREAD

**Issue by lorenzo-rovigatti** [openjournals/joss#856]
Hello,

I would like to ask whether [oxDNA](https://github.com/lorenzo-rovigatti/oxDNA) would be a good candidate for publication in JOSS. oxDNA is a simulation package aimed at performing simulations of coarse-grained systems in the physical-chemistry/biophysics field. I'm currently working on a new version of the code, ([repo here](https://github.com/lorenzo-rovigatti/oxDNA)), which will soon become the official repo of the software. I'm adding Python bindings, which is a feature that should make it more appealing to researchers who don't have a lot of experience on running simulations.

The code has the same name of a (well-known in the field) model for nucleic acids ([oxDNA/oxRNA](dna.physics.ox.ac.uk/)) which has been used in more than [one hundred](https://dna.physics.ox.ac.uk/index.php/Publications) publications.
It supports different simulation "backends" (molecular dynamics on CPU and on NVIDIA GPUs, Monte Carlo simulations) and it is especially tailored at studying DNA nanotechnology systems.
We have published a couple of papers where we directly reference the code ([here](http://dx.doi.org/10.1063/1.4754132) and [here](http://onlinelibrary.wiley.com/doi/10.1002/jcc.23763/abstract)), although we have never published the code itself. In the last few years more and more people have started conflating the code and the model and tend to reference the model's papers rather than the code's ones. Therefore, I (on behalf of all the code's authors) would like to have a single reference to point people to, which is why I'm writing this inquiry.

**Comment by arfon** [comment]
This sounds like it could be in scope, and I'd encourage you to submit.
