### ISSUE TITLE
Pre-submission enquiry: FreeCAD authors list?

### ISSUE THREAD

**Issue by kkremitzki** [openjournals/joss#865]
Hello, I'm interested in writing up a JOSS paper for FreeCAD so we have something citable, as we know there are people doing research with it. However, the [list of contributors](https://github.com/FreeCAD/FreeCAD/graphs/contributors) is rather long, and any reasonable list of authors would also be pretty long... the software is 18 years old, and I for example have only been around for a year short of half that.

**Comment by Kevin-Mattheus-Moerman** [comment]
@kkremitzki thanks for this query. We should be able to handle long author and contributor lists. We can decide on the most practical approach for the paper (e.g. if the list is formatted as usual or if it requires special treatment). 
You can distinguish between authors (people listed on paper as authors) and contributors. Have you decided, in your community, who the paper authors should be? 

@openjournals/dev @arfon any thoughts on this? Have we had this "issue" (very long author lists)  in the past?

**Comment by arfon** [comment]
Long author lists are OK - see the SunPy paper as an example: https://joss.theoj.org/papers/10.21105/joss.01832
