### ISSUE TITLE
Pre-submission enquiry

### ISSUE THREAD

**Issue by thewan05** [openjournals/joss#866]
Dear JOSS Editorial Board,

I am writing to know more about the content you are looking for.

My advisor and I have been working on a SAS Macro for Phase III clinical trials, and the macro executes a new method that was published in 2020. The macro is user-friendly with an accompanying ReadMe file, code comments, and error checks in place to validate user-defined input. The code is not available anywhere, and this would be an exclusive submission.

Please let us know your thoughts.

Thank you,

**Comment by arfon** [comment]
I'm not very familiar with SAS Macros but if it's anything like an Excel macro then this would not be considered research software by JOSS and therefore not publishable here sorry.
