### ISSUE TITLE
Pre-submission enquiry — uniparc_xml_parser

### ISSUE THREAD

**Issue by ostrokach** [openjournals/joss#870]
I would like to enquire whether [`uniparc_xml_parser`](https://gitlab.com/ostrokach/uniparc_xml_parser) is something that would ever be considered for JOSS?

The goal of `uniparc_xml_parser` is to transform the massive XML file (currently 173 GB gziped; see: <https://ftp.uniprot.org/pub/databases/uniprot/current_release/uniparc/>) that is used to distribute UniParc data into a set of relational tables that can be queried using SQL.

While the problem may appear trivial, we found that e.g. using Python to even just read the entire file becomes exceedingly slow. Furthermore, constructing a SQL schema that can be used to capture all the data stored in the XML file required some thought and familiarity with the UniParc XML schema.

Our solution to this problem is `uniparc_xml_parser`, a package written in Rust which leverages the excellent [`quick-xml`](https://crates.io/crates/quick-xml) pull-parser library to convert a stream of XML data into relations on the fly. Parsing the UniParc XML file into a set of CSV tabes is as simple as:

```bash
curl -sS ftp://ftp.uniprot.org/pub/databases/uniprot/current_release/uniparc/uniparc_all.xml.gz \
    | zcat \
    | uniparc_xml_parser
```

Reading the JOSS documentation, I think that `uniparc_xml_parser` does fit under the JOSS definition of [research software](https://joss.readthedocs.io/en/latest/submitting.html#what-we-mean-by-research-software) since it "extracts knowledge from a large dataset".

**Road-map:**

Recently, there was some activity on the issue tracker (see https://gitlab.com/ostrokach/uniparc_xml_parser/-/issues?scope=all&state=all), which suggests that the software may be useful to others. I can think of a number of improvements which would make `uniparc_xml_parser` even more widely applicable and useful.

- ✓ Simplify the table schema (merge `xref_property` and `property` tables).
- ✓ Make the generated tables publicly available so that users do not have to run `uniparc_xml_parser` themselves and can download only the tables of interest.
- ✓ Load the generated tables into Google BigQuery, so that users would be able to write SQL queries without downloading anything locally (BigQuery allows users to query up to 5 TB / month for free).
- ✓ Create a monthly cron job that keeps the downloadable assets and Google BigQuery tables up to date.
- ✓ Add a "Frequently Asked Queries" section that provides SQL queries that may be generally useful (finding domain definitions in a given protein, converting between Ensembl and UniProt identifiers, finding all sequences for a given gene name or PDB identifier, etc).
- Improve documentation.
- Add an option to output Parquet files instead of CSVs.

**Comment by arfon** [comment]
Hi @ostrokach – apologies for the very slow reply here. This submission is a little usual for us and so I think it probably makes sense to submit and for the standard editorial scope review process to run its course (when a number of editors can weigh in). Does that sound OK?

**Comment by ostrokach** [comment]
Sounds great!
