### ISSUE TITLE
Error when submitting paper

### ISSUE THREAD

**Issue by hknd23** [openjournals/joss#875]
Hello, 

I have been trying to submit my paper (https://github.com/hknd23/idcempy) to JOSS, but after filling all the required fields, I received the following error message: 

“We're sorry, but something went wrong.
If you are the application owner check the logs for more information.” 

My coauthor also received the same message when trying to submit the paper.

**Comment by arfon** [comment]
Apologies, this has been fixed in https://github.com/openjournals/joss/commit/5a6b865826187d50de19dbb9f1e56920f431433a
