### ISSUE TITLE
Some doubts about possible submissions

### ISSUE THREAD

**Issue by victormlb06** [openjournals/joss#878]
Good afternoon JOSS reviewers, I have two questions which are related to the submission of the article. 

- The first one is about the possibility of submitting more than one article by the same (software) which, however, would be on different versions in each one of the articles. In this sense, an article would be sent in the current version of the software and others a few weeks later after significant changes were made to the architecture and some functionalities of the software.  

- The second question would be if there is an average time estimate for the approval of the article.

Thank you for your attention. 
Best regards.

**Comment by arfon** [comment]
Hi @victormlb06 – two submissions in a short amount of time about the same software would likely not be allowed by us (it would be considered self-plagiarism).

Average review time at JOSS is about 3 months end-to-end but it can vary, depending upon the submission complexity.
