### ISSUE TITLE
Every mention of joss-reviewers team in an issue sends an e-mail to all the reviewers

### ISSUE THREAD

**Issue by ctb** [openjournals/joss#88]
I've gotten @arfon's responses to all of the requests to join the reviewer team. At the bottom of the e-mail it says "You are receiving this because you are on a team that was mentioned." Could this be fixed? I don't think those requests are something I need to see, and I'm not watching *this* repository either.

(I'm assuming this is unintentional behavior from mentioning the team URL. If it's intentional... uhh... why? ;)

**Comment by arfon** [comment]
Sorry about that @ctb. I'll stop mentioning the team when adding new reviewers

**Comment by arfon** [comment]
Hopefully you didn't just receive the last two since I closed this issue?

**Comment by ctb** [comment]
Nope!

--
Titus Brown, ctbrown@ucdavis.edu

**Comment by whedon** [comment]
:-)
