### ISSUE TITLE
Change of software's repository

### ISSUE THREAD

**Issue by kirui93** [openjournals/joss#880]
We want to transfer the maintenance of the software's repository to another person and we think it would be wise for the person to fork the main repository and maintain it from the forked repository. 

Is it therefore possible to change the repository of my software (as indicated on JOSS website) to another repository?

**Comment by arfon** [comment]
It is not possible to put a note on the repository that JOSS has a link to saying that the active fork is now somewhere else?

Ideally, we'd rather not update links in JOSS once a paper has been published.

**Comment by kirui93** [comment]
@arfon I think you have given me a good idea of putting a note on the repository.

Thanks. I will close this issue then.
