### ISSUE TITLE
License choice criteria in JOSS review

### ISSUE THREAD

**Issue by Jacob-Barhak** [openjournals/joss#889]
This issue was created after you asked me to review a paper here:
https://github.com/openjournals/joss-reviews/issues/3069#issuecomment-793927182

Your regulations on how to judge a submission according to a choice of license is incorrect since you sponsor OSI approved licenses. However OSI selection of licenses limits reproducibility, A few years OSI rejected a license that puts work in Public Domain. It is called Creative Commons Zero - [CC0](https://creativecommons.org/share-your-work/public-domain/cc0/). This kind of license removes barriers from reproduction and therefore superior to many copyright based licenses that OSI approves.

Today institutions like [BioModels](https://academic.oup.com/nar/article/48/D1/D407/5614569) adopted CC0 as a leading solution for disseminating information.

You will see a discussion on these topics here: 
Jacob. Barhak, Open Source and Sustainability, COMBINE 2020 October 5-9. [Video](https://drive.google.com/drive/folders/1actGnx6FwvoCcPrrF3qbnO0AmHt10WN6)  starting from minute 13:10.  [Presentation](https://jacob-barhak.github.io/COMBINE2020_OpenSource_upload_2020_10_04.odp)

OSI involvement in this journal should not dictate choice of license as part of acceptance criteria. In fact it limits this journal as a proper venue for reproducible scientific resources.

Hopefully the guidelines can be remedied to fix the situation.

**Comment by arfon** [comment]
If CC0 were OSI approved, we'd happily accept it. As an OSI affiliate, we are committed to supporting the OSI definition of _open source_ which, at this point in time, does not include CC0.
