### ISSUE TITLE
Pre-submission enquiry: Cellular Automata Library

### ISSUE THREAD

**Issue by lantunes** [openjournals/joss#890]
Hello, I've created a Python library that allows for the creation and study of various classes of Cellular Automata, called CellPyLib, located here:

https://github.com/lantunes/cellpylib

Is such a software project eligible for publication in the journal? The core library contains 819 LOC, just under the 1000 LOC criterion. I don't believe this detracts from the utility of the library, though, and is more a reflection of the conciseness of the programming language used, and the generality of the design. Also, the documentation is mostly in the form of examples.

If this project is suitable, I will be happy to prepare a submission to the journal.

Thank you.

**Comment by arfon** [comment]
Looks like this is [under review](https://github.com/openjournals/joss-reviews/issues/3608). Sorry we didn't respond to this.
