### ISSUE TITLE
Pre-submission enquiry

### ISSUE THREAD

**Issue by sandrinecharles** [openjournals/joss#896]
Dear JOSS editor,

I would like to use Overleaf to write a manuscript to submit to JOSS. Would you have a template that I could use?

Thank you in advance,
Sandrine

**Comment by danielskatz** [comment]
This will not work for JOSS, which requires the manuscript be in markdown.  Just write in markdown directly, following the [example](https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography), and you can use our service to [make sure that your paper compiles and preview it](https://joss.readthedocs.io/en/latest/submitting.html#checking-that-your-paper-compiles)

**Comment by danielskatz** [comment]
Also note that papers are expected to be [relatively short](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain)
