### ISSUE TITLE
Pre-submission inquiry: cerf

### ISSUE THREAD

**Issue by crvernon** [openjournals/joss#897]
Greetings,

I am close to finishing a major re-write of the Capacity Expansion Regional Feasibility (CERF) model (power plant siting under alternate futures) which was previously published in another software journal in 2018.  The original software was a Windows 7 only codebase and had a core C++ component lacking clarity that obfuscated the models decision structure. 

I re-wrote the software fully in Python, added a full test suite, and extended functionality to enable users to conduct multisectoral, multiscale research with CERF.  The modeling component of the software now performs ~1000 times faster than the original version which will set computational performance to permit global, variance based sensitivity analysis and the quantification of uncertainty.

Do you allow re-writes intended as a non-backwards compatible major version release to be published in JOSS?  If so, I will submit in the coming weeks.

Thanks so much for your time and have a great day,

Chris

**Comment by danielskatz** [comment]
Yes, this seems reasonable - our question will be if the advances from the previous publication are sufficiently large, and what you describe seems like we would say yes.

**Comment by crvernon** [comment]
Excellent.  Thank you so much!
