### ISSUE TITLE
Pre-submission enquiry: GemGIS

### ISSUE THREAD

**Issue by AlexanderJuestel** [openjournals/joss#898]
Hello, 

I would like to submit a pre-submission enquiry for our [GemGIS](https://github.com/cgre-aachen/gemgis) package. 

GemGIS wraps, combines and extends existing functions of Geopandas, rasterio, shapely, pygeos, and others to automate the workflow to process spatial data (vector data, raster data, XML-based data, data from web servers, etc....) for the purpose of structural geological modeling. GemGIS is a bridge between conventional GIS systems like QGIS and ArcGIS which geologists are usually familar with and geomodeling packages like [GemPy](https://github.com/cgre-aachen/gempy). As GemGIS does not reinvent the wheel but rather builds upon well-known data formats such as (Geo-)DataFrames or NumPy arrays, it is also easy for new users to make progress and build their first structural geological models. Another strength is the visualization of the processed data and the final structural model using the PyVista package. 

GemGIS features:

- A [documentation page](https://gemgis.readthedocs.io/en/latest/)
- [Many tutorials](https://gemgis.readthedocs.io/en/latest/getting_started/tutorial/index.html) also with sample data to explain single processing steps
- Many examples (currently in the making and to be finalized soon) to show the full workflow for processing spatial data
- A large and helpful community around it (Software Underground)
- The possibility to include more packages, to work with more data formats to create better models and to visualize input and output data.

During the [Transform 2021 Hackathon](https://github.com/softwareunderground/transform-2021-hackathon/discussions/4), many open issues will hopefully be solved.
This includes:

- creating a recipe for conda-forge releases
- fixing Github Actions to automatically perform tests, build the documentation and release to PyPi/conda-forge
- fixing the Binder integration for Notebooks 

Thanks and looking forward to your responses.
Alex

**Comment by AlexanderJuestel** [comment]
Pinging @danielskatz

**Comment by danielskatz** [comment]
I don't have a strong opinion here - perhaps another editor does.

**Comment by arfon** [comment]
This sounds like it is probably in scope, and I'd encourage you to submit.
