### ISSUE TITLE
Ensure articles are PDF/A

### ISSUE THREAD

**Issue by kyleniemeyer** [openjournals/joss#901]
We should probably make sure that our articles are PDF/A (archival PDF), both for longevity and also to help authors satisfy funder requirements (like NSF, which requires papers associated with grants to be deposited in its [Public Access Repository](https://par.nsf.gov) to be PDF/A).

I did find some instructions on what to add to a LaTeX document to do this here: https://www.mathstat.dal.ca/~selinger/pdfa/

I imagine the steps could be automated; mostly it involves adding `\usepackage[a-1b]{pdfx}` to the preamble, and including an additional file with PDF metadata.

cc @arfon @tarleb

**Comment by tarleb** [comment]
I played a little with the `pdfx` package, but so far I've been unable to make it work; both `xelatex` and `lualatex` produce errors when compiling with `pdfx`.

ConTeXt has been pitched to me as a great alternative to LaTeX, and apparently it is much better at supporting PDF/A. Since the layout isn't too demanding, we could give that a try.

**Comment by jedbrown** [comment]
The instructions [here](https://tex.stackexchange.com/a/535849) work for me with `lualatex` and `xelatex` as reported by `verapdf`:
```xml
<?xml version="1.0" encoding="utf-8"?>
<report>
  <buildInformation>
    <releaseDetails id="core" version="1.18.11" buildDate="2021-04-19T10:21:00-06:00"></releaseDetails>
    <releaseDetails id="validation-model" version="1.18.8" buildDate="2021-04-19T10:35:00-06:00"></releaseDetails>
    <releaseDetails id="gui" version="1.18.6" buildDate="2021-04-27T08:53:00-06:00"></releaseDetails>
  </buildInformation>
  <jobs>
    <job>
      <item size="31093">
        <name>/home/jed/lang/tex/pdfa.pdf</name>
      </item>
      <validationReport profileName="PDF/A-3B validation profile" statement="PDF file is compliant with Validation Profile requirements." isCompliant="true">
        <details passedRules="124" failedRules="0" passedChecks="1002" failedChecks="0"></details>
      </validationReport>
      <duration start="1641486930656" finish="1641486931365">00:00:00.709</duration>
    </job>
  </jobs>
  <batchSummary totalJobs="1" failedToParse="0" encrypted="0">
    <validationReports compliant="1" nonCompliant="0" failedJobs="0">1</validationReports>
    <featureReports failedJobs="0">0</featureReports>
    <repairReports failedJobs="0">0</repairReports>
    <duration start="1641486930539" finish="1641486931405">00:00:00.866</duration>
  </batchSummary>
</report>
```

So a few lines would need to be added to `latex.template`, but as I understand it, deployment of changes is blocked on buffy. If we're ready to accept a PR for this and nobody else wants to pick it up, let me know. (Cc: @arfon @xuanxu )

**Comment by jedbrown** [comment]
We merged support in Inari so JOSS will produce PDF/A when the transition to Buffy is complete. https://github.com/openjournals/buffy/issues/46

**Comment by jedbrown** [comment]
This migration is complete so new papers should be PDF/A-3b so long as the figures are compliant. If PDF/A support is important to you, you'll want to run a compliance-checker such as [verapdf](https://verapdf.org/home/) on a draft. We may be able to automate such checks in the future. The gotcha I wasn't able to automatically resolve is that using [librsvg](https://wiki.gnome.org/Projects/LibRsvg) (whether automatically in Pandoc or manually by the author) breaks PDF/A compliance.
