### ISSUE TITLE
slight change to paper publication message

### ISSUE THREAD

**Issue by danielskatz** [openjournals/joss#903]
In the message that is generated when a paper is accepted, one line is
>Wait a couple of minutes to verify that the paper DOI resolves {DOI}

It would be better if this was
>Wait a couple of minutes, then verify that the paper DOI resolves {DOI}

**Comment by arfon** [comment]
This should be fixed in https://github.com/openjournals/whedon-api/commit/d9dcc3e4074988cd19a96f7fb1f983ebe7be0e0a
