### ISSUE TITLE
Pre-submission enquiry - itermae, a barseq parser

### ISSUE THREAD

**Issue by darachm** [openjournals/joss#908]
I'd like to know if [itermae](https://gitlab.com/darachm/itermae/) would be a good fit for JOSS.

I have been writing and re-writing this tool since 2017, and now have a more novice-friendly interface. I am now activitely recruiting people to test it out, but I was here hoping to get a determination/opinion about the suitability for JOSS so I can best plan how to continue the work.

My main criteria of concern today:

1. Is the research application obvious?
2. Is the effort substantial and unique?

But any other commentary / feedback is very welcome.

# 1 - Research application

A common experimental design in biology is to measure the frequency of a DNA "barcode" sequence in a sample in order to estimate the abundance of different "barcoded" mutant cells within a pool. This requires parsing ~10^6 - ~10^9 DNA sequencing records (each of ~150 characters) to extract a particular pattern of sequence that represents each mutant (the "barcode"). Position-based extraction is simple but vulnerable to insertion/deletion mutations/errors and isn't compatible with the barcode length-variation that is unavoidable in large libraries. Plain regular-expressions are vulnerable to any mutation or error, technical or biological. Traditional alignment-based approaches are vulnerable to artifacts (ie the ymr258CKO barcode in yeast knockouts) and use software that is not designed with tunable parameters specific to for this particular application (such as handling kb-scale variable-length inserts in long-read data). Re-framing the problem into the end-to-end alignment-to-reference paradigm is not practical for architectures using multiple barcode combinations in the architecture. Fuzzy regular expressions to parse multiple variable locations into different capture groups handles the problem well, but while an expert user can write one-off scripts a more novice user may have difficulty writing and maintaining such a tool.

`itermae` is designed to be a barcode-sequencing command-line utility that extracts complex DNA barcode patterns from FASTQ/Z (or other format) inputs. The goal of `itermae` is to make fuzzy regular expression parsing of DNA barcode sequencing data accessible to a more general audience.

I was inspired to submit this to JOSS after seeing a paper describing a different approach to a similar application, [alignparse](https://joss.theoj.org/papers/10.21105/joss.01915). That tool uses a different core approach and interface and is focused more on long-read technologies, as opposed to the more traditional short-read Illumina data. I think presenting this tool in the same forum (JOSS) could help the inspire development of software around these applications.

# 2- Substantive effort

I began writing this software in 2017 to handle a particularly complex amplicon architecture for [this paper](https://doi.org/10.1371/journal.pgen.1007406). It was originally called  [SLAPCHOP](https://github.com/darachm/slapchop) and was based on pairwise alignments. It was mentioned in the methods of that paper, and explained in more detail in the second supplementary file along with benchmarking against the tool we previously used. The work up to this point (May 21 2018, release tag "as_published") was [tracked here](https://github.com/darachm/slapchop/).

Since then, I have fundamentally re-written the tool. It has the same application (barcode parsing), but uses a different core approach (fuzzy regular expressions), a different interface (regular expressions or YAML config), and interface philosophy (parallelization external to the program with STDIN/OUT focus). I have spent quite substantial amounts of time on this, especially because this is the barcode parser I use for my work.

As it stands, the actual code is ~1260 lines, not including documentation or tests. The work in question was tracked on [github](https://github.com/darachm/slapchop/) from May 2018 until moving to [gitlab](https://gitlab.com/darachm/slapchop) in April 2019, and [renamed to this repo](https://gitlab.com/darachm/itermae) in June 2020.

I plan to keep using/developing this tool for my own work and I would like to share it with others.

Thank y'all for your consideration and work in organizing this journal.

**Comment by arfon** [comment]
Hi @darachm – firstly, I'm very sorry for the slow reply here. 

To answer your question, I'm not sure. The tool looks like it's useful research software, but I have some concerns about how the package is put together, such as a [single Python file with the whole library ](https://gitlab.com/darachm/itermae/-/blob/main/itermae/__init__.py)(as far as I can tell).

I would encourage you to submit and the package will go through our normal scope review process with the wider editorial team.

**Comment by darachm** [comment]
Thanks for the message @arfon , I was about meaning to rewrite some parts anyways to better combine CLI/config-file control modes. Sounds like an opportunity to tidy it up.

Is the style concern (re monolithic __init__) covered in PEP8 or something similar that I can refer to?
