### ISSUE TITLE
Pre-submission enquiry

### ISSUE THREAD

**Issue by drcandacemakedamoore** [openjournals/joss#913]
I have been working on a code library for about a month (https://github.com/drcandacemakedamoore/cleanX). The library draws on a lot of earlier work done in Jupyter notebooks with my collaborators, so it is, in my eyes unfair to call its history a month long. Is it very important for the library to be three months old if we submit?

**Comment by jedbrown** [comment]
Hi, thanks for inquiring. It looks like a nice project and in-scope. What does the future look like for this package? The version 0.0.4 usually indicates that it's very immature and that fundamentals are likely to change. Is that true, or is it feature complete? What's between here and a future 1.0 release?

A couple notes from a glance at your repository:
1. If you rename `CODEOFCONDUCT.md` to `CODE_OF_CONDUCT.md`, then GitHub will recognize it.
2. This is inaccurate:

> The GLP [sic] license implies you should be open sourcing your entire code base, and sending me modifications.

GPLv3 says nothing about sending modifications upstream and one can make in-house modifications for which source is never made public, including when operated as part of a commercial product such as a service. This "loophole" is something the AGPL was written to address.
See also: https://www.gnu.org/licenses/gpl-faq.html#GPLCommercially

**Comment by drcandacemakedamoore** [comment]
Thank you so much! We are up to a 0.0.7 release. We added an anaconda version. I was afraid to call it 0.1.0 because I heard a rumor that if you change in a different order of magnitude it implies that what you did before is not supported. I changed my statement about the GPLv3, and renamed my code of conduct to upgrade as per your suggestions.
