### ISSUE TITLE
Pre-submission enquiry - License similar to but not BSD-3-Clause

### ISSUE THREAD

**Issue by stewartsl** [openjournals/joss#916]
Hello,

We have open sourced some software that we would like to submit for consideration to JOSS, but wanted to enquire about the OSI license requirement. 

Our repository is here: [Transformer eXplainability and eXploration](https://github.com/ORNL/tx2)
Our license file is here: [TX^2 License](https://github.com/ORNL/tx2/blob/master/LICENSE)

Our organization requires the use of this license for open source software, and it is motivated by the BSD-3-Clause (really it is quite similar to [Lawrence Berkeley National Labs BSD Variant License](https://opensource.org/BSD-3-Clause-LBNL) that is on OSI) but is worded slightly differently. Would JOSS be willing to consider our submission even though this license isn't OSI listed?

**Comment by jedbrown** [comment]
Hi, thanks for inquiring. We had a similar discussion in https://github.com/openjournals/joss-reviews/issues/1370#issuecomment-490606797 for software using the LBNL license and the author was able to change the license to a standard BSD wording. As you note, the LBNL variant has since been approved by OSI, though it doesn't alleviate concerns about license proliferation that are behind the xSDK recommendations.

There is lots of other software from ORNL that uses standard licenses. Could @usethedata weigh in on current ORNL policy?

**Comment by usethedata** [comment]
The license they have used is the one that ORNL's Technology Transfer generally directs people to use.  It is the one we've used for all of what my group has on GitHub.  There can be some routes to using a different license, and I will reach out to @stewartsl through ORNL-internal channels to discuss.  The Anti-Deficiency Act and the terms of the Prime Contract under which UT-Battelle operates ORNL for the Department of Energy create some interesting constraints.  LBNL would have similar issues, but a different prime contract.

**Comment by jedbrown** [comment]
DOE's xSDK policies include the following, which was was agreed to by a consortium that includes representatives from all labs:
> M7.The xSDK collaboration has a strong preference for packages to use an OSI-approved, permissive open-source license(e.g., MIT or BSD 3-Clause). All new packages will be required to use such a license. Current packages using other licenses are encouraged to relicense, where possible. Required dependencies must use an OSI-approved license that is considered compatible with the preferred permissive licenses for distribution purposes (see https://en.wikipedia.org/wiki/License_compatibility). Non-critical optional dependencies can use any OSI-approved license. 
https://figshare.com/articles/journal_contribution/xSDK_Community_Package_Policies/4495136 (https://xsdk.info/policies/)

When I was at Argonne (until 2015), ASCR gave us blanket authorization (and encouragement) to release under OSI-approved licenses. All the labs release lots of software under standard OSI-approved licenses. I'm confused as to why we seem to keep relitigating this.

**Comment by jedbrown** [comment]
DOE's xSDK policies include the following, which was was agreed to by a consortium that includes representatives from all labs:
> M7.The xSDK collaboration has a strong preference for packages to use an OSI-approved, permissive open-source license(e.g., MIT or BSD 3-Clause). All new packages will be required to use such a license. Current packages using other licenses are encouraged to relicense, where possible. Required dependencies must use an OSI-approved license that is considered compatible with the preferred permissive licenses for distribution purposes (see https://en.wikipedia.org/wiki/License_compatibility). Non-critical optional dependencies can use any OSI-approved license. 
https://figshare.com/articles/journal_contribution/xSDK_Community_Package_Policies/4495136 (https://xsdk.info/policies/)

When I was at Argonne (until 2015), ASCR gave us blanket authorization (and encouragement) to release under OSI-approved licenses. All the labs release lots of software under standard OSI-approved licenses. I'm confused as to why we seem to keep relitigating this.

**Comment by stewartsl** [comment]
Thanks for the conversation and input. Sounds like my path forward is following up on this internally with our tech transfer folks to see about using an OSI license.
