### ISSUE TITLE
Pre-submission enquiry for Micro-Manager Design overview manuscript

### ISSUE THREAD

**Issue by nicost** [openjournals/joss#921]
Very impressed with the goals and implementation of your Journal!  

We have been working on a manuscript describing the design, its advantages and shortcomings of Micro-Manager, which is open source software for microscope control in use in thousands of laboratories world-wide.   The manuscript serves as a starting point for discussions what to do to improve the impact of the software. 

The manuscript itself can be found here: [MMCoreDesign.pdf](https://github.com/micro-manager/futureMMCore/blob/main/MMCoreDesign.pdf), within the [futureMMCore repository ](https://github.com/micro-manager/futureMMCore) discussing the future direction of the project.

I am curious if you think this falls within the scope of the journal, and/or what modifications you feel we should make to improve its relevance.

**Comment by danielskatz** [comment]
While the software itself seems reasonable for JOSS, the manuscript and idea you describe (the future of the software and discussion about how to improve its impact) is not.

A JOSS manuscript should be a short description of the software itself, pointing to the documentation (see https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain), not a long discussion about the future of the software.  So while I think you could write a JOSS paper and submit it and the software, JOSS is not the right venue for the manuscript you currently have written.
