### ISSUE TITLE
Pre-submission enquiry: Bluetooth Low Energy

### ISSUE THREAD

**Issue by kevincar** [openjournals/joss#925]
I'm opening this enquiry to gauge whether [bless](https://github.com/kevincar/bless/tree/develop) is within the scope of JOSS and whether it meets the requirements for [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort). While a number of packages exist for deploying a bluetooth low energy (BLE) server on many linux distributions, the goal of this package is to provide an OS-independent implementation with the expectation that behavior is mirrored across all platforms. This package has helped us prototype and develop bluetooth low energy servers across devices with varying operating systems for our research projects.

Thank you

**Comment by arfon** [comment]
Sorry for the slow reply here. This sounds quite unusual for us, and somewhat outside of our normal definition of 'research software'. Without seeing a draft paper (that would articulate the research problems addressed with this software), it's hard for me to make a call here sorry. 

If you're still interested in pursuing a publication in JOSS, I'd encourage you to submit, and the normal scope review process would make a decision about this package.
