### ISSUE TITLE
Pre-submission enquiry: Plotly

### ISSUE THREAD

**Issue by nicolaskruchten** [openjournals/joss#928]
I'm looking to submit a paper for the Plotly Graphing Library, which is a bit of an ecosystem centered around Plotly.js, but mostly used via Plotly.py, Plotly.R or PlotlyJS.jl by folks who would be interested in citing a paper.

I can see two ways of submitting things:

1. one submission per repo: so one for Plotly.js and another for Plotly.py and another couple for PlotlyJS.jl and Plotly.R if those authors are interested
2. a single submission for "the whole ecosystem as it stands today", originating in the common-trunk repo Plotly.js, but discussing Plotly.py, Plotly.R, PlotlyJS.jl and listing the authors of those libraries (if they're interested)

Option 1 is clearly more "clean" from an authorship and repo perspective but would result in a bunch of different papers talking about Plotly and might cause confusion for folks who want to cite it. 

Option 2 is a bit messier but is easier to cite.

**Comment by arfon** [comment]
:wave: @nicolaskruchten. I'm delighted to hear you're planning on submitting a paper to JOSS about Plotly!

> Option 2 is a bit messier but is easier to cite.

I agree with your summary here. I'm not sure if this helps you make a decision but the Tidyverse folks basically did Option 2 here for their JOSS paper: https://joss.theoj.org/papers/10.21105/joss.01686

I think my preference is also for Option 2, even though it will likely make it harder for our reviewers (we might need to identify a larger number than usual to cover a review of all the different language-specific packages).

**Comment by nicolaskruchten** [comment]
Thanks @arfon!

Pinging @cpsievert and @sglyon ... would you be interested in being listed as co-authors on a unified "Plotly Graphing Library for Javascript, Python, R and Julia" JOSS paper, submitted from the Plotly.js repo, alongside all the Plotly.js and Plotly.py contributors of note? Anyone else we should loop in here?

**Comment by sglyon** [comment]
That sounds great to me! How exciting!

Let me know what support you need from the Julia side

**Comment by nicolaskruchten** [comment]
Awesome! So next step is I'll draft up something as a PR in the Plotly.js repo and I'll tag everyone. Since Carson and Spencer are on board, I'm thinking of a title like "Plotly: Interactive Data Visualization for Javascript, Python, R and Julia" or something like that :D

**Comment by nicolaskruchten** [comment]
Here's the stub PR to follow up: https://github.com/plotly/plotly.js/pull/5693
