### ISSUE TITLE
Whedon paper preview service not working

### ISSUE THREAD

**Issue by slwu89** [openjournals/joss#929]
Hello JOSS editors,

It seems the [paper preview service](https://whedon.theoj.org/) is down, I set up a minimal repo here (https://github.com/slwu89/test-joss) with the example paper and bibliography from the docs (https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography) and the paper compiling service simply returns the mysterious error:

```
Your paper failed to compile with the following errors:

{} 
```

**Comment by arfon** [comment]
Thanks folks. This is an issue with the service we use to upload the PDF previews too. I'm working on a fix here.

In the interim, please use this GitHub Action: https://github.com/openjournals/openjournals-draft-action

**Comment by arfon** [comment]
OK, this should now be fixed.

**Comment by slwu89** [comment]
Great! thanks.
