### ISSUE TITLE
Pre-submission enquiry: GeoHexViz - A geospatial hexagonal-binning visualization distribution

### ISSUE THREAD

**Issue by tony-zeidan** [openjournals/joss#931]
Hello,

The purpose of this enquiry is to gauge whether a geospatial visualization Python package that a colleague and I are developing 
would be suitable for publication in JOSS. The Python package, GeoHexViz, aims to simplify the generation of publication quality 
geospatial visualizations. It supports those researchers that do not have a significant background in geospatial visualizaiton
and yet need to produce high-quality visualizations as part of their research, or those who simply seek to reduce the time 
required to generate quality visualizations.

Our package focuses on visualizing geospatial data, including both quantitative and qualitative, through hexagonal binning. A user 
may construct a visualization in two ways. First, a script may be called on the command line that takes as input a set of parameters 
which describe the visualization, i.e., hexagon size, input data file, colour scale, etc., and generates a publication ready PDF. 
Second, a PlotBuilder class may be used within an exsiting Python script that provides a simple interface to generate such figures.

This package is built on top of several existing packages, including Plotly and H3. Thus, it integrates existing software to
produce visualizations, which can be time consuming to beautify, faster and easier.

Note: This work was inspired by visualizations developed by Hunter et al. (2021, pp. 25, 27, 28, 31) 
(see https://cradpdf.drdc-rddc.gc.ca/PDFS/unc356/p812844_A1b.pdf). In addition, this package has been developed by Defence
Research and Development Canada and if deemed acceptable to submission to JOSS, would be posted on DRDC's github site.

Thank you in advance for responding to this enquiry.

**Comment by jedbrown** [comment]
It sounds topically in-scope, but an editor would have to look at the repository to get a sense of the depth relative to the underlying libraries.
