### ISSUE TITLE
Possibility to use \nocite{*} to quote works in the bib file not cited in the md file?

### ISSUE THREAD

**Issue by Shyentist** [openjournals/joss#933]
Pardon me if this is already possible.

Having to cite in-text all the packages used to build a piece of software starts looking silly after a certain amount, especially in a short paper (250-1000 words). I have been looking for a way to use \nocite{*} to list all the entries in the bib file, even when not cited in-text, but I have failed thus far.

Would this feature be of any actual use or am I missing a key concept as to why it would not?

**Comment by arfon** [comment]
I think you can do this: https://pandoc.org/MANUAL.html#including-uncited-items-in-the-bibliography

But honestly, I prefer it when authors directly cite inline e.g.., [@citation1;@citation2;@citation3] because it offers more context for the reader _what_ is being cited and when.
