### ISSUE TITLE
Pre-submission enquiry

### ISSUE THREAD

**Issue by peach-lucien** [openjournals/joss#934]
Dear Editors,

We are interested in submitting a short paper on our software package [https://github.com/barahona-research-group/PyGenStability](https://github.com/barahona-research-group/PyGenStability) that implements the Markov Stability graph clustering algorithm (and its various variants). It uses a combinations of C++ and Python and is open source available. The package is regularly used by ourselves and our peers.

Would this fall under the scope of JOSS?

Best regards,
Robert

**Comment by arfon** [comment]
Hi @peach-lucien. This looks like it's pretty small, and given that it's wrapping another library, it may well be out of scope as a 'wrapper' package. If you'd like to submit, we would review the scope more formally at submission time.
