### ISSUE TITLE
Pre-submission enquiry

### ISSUE THREAD

**Issue by howardjp** [openjournals/joss#936]
Would a Docker/Singularity image for the Open Science Grid be suitable for submission?

**Comment by danielskatz** [comment]
JOSS reviews source code in source code repositories. There can be images built as delivery/packaging mechanisms, but the focus of JOSS is on the source code.

Additionally, JOSS focuses on research software - software that is intended for use in research, is used for research, and would be cited in a paper about the research.

**Comment by howardjp** [comment]
Well, certainly it is for research use (it basically does all the work for doing PyTorch on OSG, which is quite a pain).  When I saw we had thousands of downloads, I figured it might be worth documenting.  Cool, thanks! :)
