### ISSUE TITLE
Pre-submission enquiry: library of csv readers

### ISSUE THREAD

**Issue by nicholas512** [openjournals/joss#937]
I have some software I've been developing to support data handling in environmental sciences:

Dataloggers used in environmental sciences export textfile data with all kinds of different structures, date formats, separators etc. There is a great deal of heterogeneity between different datalogger manufacturers and even between different configurations of data from the same device.

This heterogeneity significantly reduces the interoperability of the data produced by different researchers, and means that its harder for researchers to share their data or develop common tools for data cleaning or processing; everyone comes up with their own scripts for handling their particular configuration.

Instead of trying to come up with a 'universal' reader like [cleverCSV](https://github.com/alan-turing-institute/CleverCSV) (in fact, many of the textfiles aren't "proper" csv files anyway and require some amount of preprocessing), this software is a library of readers for each device manufacturer that makes reading raw sensor data effortless for researchers.  Strong emphasis is put on tests, and including a 'zoo' of representative examples to facilitate that testing. There is a python and a R codebase to support different users / use-cases. 

This might be too much of a "Minor 'utility' package" though so I thought I'd check.

**Comment by arfon** [comment]
Hi @nicholas512 - without seeing the package, it's hard to say whether this would be in scope. I'd encourage you to submit and our standard scope review process would judge this at pre-review time.
