### ISSUE TITLE
Pre-submission enquiry

### ISSUE THREAD

**Issue by ghost** [openjournals/joss#940]
Hello, 

My co-authors and I would like to make a submission to JOSS, and were hoping to confirm that we are in scope of the journal. 

We have developed a tool that text mines exisiting scientific publications to assess the readability and neutrality of an authors' published work. We are hoping this tool will be useful to scientists, both to assess their own writing, but also to test hypotheses about complexity in science writing. 

Thanks, 
Bec

**Comment by danielskatz** [comment]
I think this is potential in scope in terms of topic, though there are also scope issues in terms of code size and effort.  In terms of topic, JOSS's interest is in research software, which the second use case clearly describes, but the first mostly does not, in my opinion.

**Comment by BecFeather** [comment]
Hi Daniel, 

Thank you - this is really helpful, and confirms our thinking. While there's a case to be made for it's use in assessing an individual's writing complexity, the strength of the tool is in it's ability to test hypotheses relating to readability and complexity in science writing. 

Kind regards,
Bec
