### ISSUE TITLE
Can we publish the code to the Zenodo first before submitting it to the JOSS for review?

### ISSUE THREAD

**Issue by philip928lin** [openjournals/joss#943]
Hi,
I wonder can we publish the code to the Zenodo first before submitting it to the JOSS for review?
Or, the code has to be reviewed first before generating any DOI?
Thank you very much.

**Comment by danielskatz** [comment]
You can, if you want, but if the review leads to changes in the code, you will then need to create a deposit of that updated code in zenodo (or similar) as part of the publication process, so if you don't mind multiple versions, go for it
