### ISSUE TITLE
Pre-submission enquiry: Viral Host Predictor Shiny App

### ISSUE THREAD

**Issue by wrightdw** [openjournals/joss#945]
I watched Arfon's talk at Coding in the Open webinar. I’m the guy that asked the question about PubMed.
 
I just wanted to ask about the criteria for inclusion in JOSS in relation to pre-trained machine learning models and whether my application is a good fit.
I have written a R/Shiny app for machine learning based predictions based on viral genome sequences.
https://bioinformatics.cvr.ac.uk/software/viral-host-predictor/
The source code is in a private GitHub repo at present but I would open source it for publication.
 
My app uses pre-trained machine learning models, and allows the user to upload their own viral sequences to run against them.
The machine learning model training process and prediction method was published in the journal Science previously.
https://science.sciencemag.org/content/362/6414/577.editor-summary
 
Following Arfon's talk, I am interested in publishing the work in JOSS.
I have read the criteria for publication at https://joss.readthedocs.io/en/latest/submitting.html and I note the part about pre-trained models not being part of the remit of JOSS.
As such, I’m not looking for the machine learning models themselves to form part of the publication – the model training process has already been published.
I’m looking to publish only my R/Shiny app code that runs predictions on the pre-trained models and visualises the results.
Would this fit the criteria for publication in JOSS?

**Comment by arfon** [comment]
Thanks for the question @wrightdw! 

> I’m looking to publish only my R/Shiny app code that runs predictions on the pre-trained models and visualises the results. Would this fit the criteria for publication in JOSS?

I think it probably depends (sorry!). Historically these kinds of submissions (especially Shiny apps) have fallen-foul of a couple of different JOSS scope areas:

- They're deemed too small/minimal.
- They're considered 'thin' clients for more substantial underlying capabilities (this may be the case here?)
 
There may also be others... Without seeing the software itself and engaging with the broader editorial team it's hard to say for sure sorry. Additionally, depending upon level of effort this might be deemed a duplicate publication of the same work (given https://science.sciencemag.org/content/362/6414/577.editor-summary exists).
