### ISSUE TITLE
Pre-submission enquiry: license criteria

### ISSUE THREAD

**Issue by eberharf** [openjournals/joss#946]
I am unclear about the license requirements for JOSS submissions: The wording on the website alters between "must" and "should" have an OSI approved license. Specifically, I was wondering whether a license that prohibits commercial use would be acceptable, since, as far as I understand, OSI opposes such restrictions for the licenses it approves.
Thank you! And my apologies if this has been addressed before.

**Comment by danielskatz** [comment]
Can you point out the "should" langauage - It should be "must" everywhere.

And on your question, a a license that prohibits commercial use would not be acceptable, unless there was a such a license that was (or became) OSI-approved

**Comment by eberharf** [comment]
Great, thanks for the quick response.

I found the "should" case here: https://joss.readthedocs.io/en/latest/submitting.html
where it says: "The software should be open source as per the OSI definition."

**Comment by danielskatz** [comment]
thanks - we'll fix that
