### ISSUE TITLE
Two related software packages, two papers?

### ISSUE THREAD

**Issue by grburgess** [openjournals/joss#948]
Hello, our software team is preparing a JOSS paper on our fitting software. However, our modeling software is a separate repo/package as it can be used beyond fitting. Should we write one paper covering both packages or do two separate papers? 

The issue with one paper is that it would be a large burden for the reviewers to cover both packages... but as they are related it is hard to consider just the fitting package without also having a look at the modeling package. 

Thanks!

**Comment by arfon** [comment]
Hi @grburgess - we often handle submissions where there are two pieces of software that need reviewing together, so this is probably OK. 

Please just be sure to flag this at submission time so the editors are aware.
