### ISSUE TITLE
Pre-submission enquiry: shutterplot (an R package)

### ISSUE THREAD

**Issue by siddhantaphuyal** [openjournals/joss#949]
Hello, 

We have developed an R package titled "shutterplot". The package has already been published in CRAN. It is based on the idea presented in the paper of title: "Shutter Plot: A Visual Display of Summary Statistics over a
Scatter Plot" written by Sarkar and Rashid. 

The initial paper does not contain any references to R codes. We have decided to publish an article that explains the procedures we have used in the shutterplot package. 

We want to know whether our package suffices the requirements of JOSS or not. 

Please go to the following link to access the package: 

https://github.com/siddhantaphuyal/shutterplot 

Thank You.

**Comment by arfon** [comment]
This is too small for JOSS sorry.
