### ISSUE TITLE
presubmission enquiry: a field experiment visualisation tool in R (R Packages)

### ISSUE THREAD

**Issue by jensharbers** [openjournals/joss#951]
Good morning everyone,

I am developing an R package with the working name agricolaeplotR.

The goal of the package is to visualize design exoeriments that are commonly used in agriculture, biology, forestry and ecology.
To my knowledge, there is no package  that plots experiments from agricolae and other packages as a field map using ggplot2.

You can find a few example plot below.
This is a latin square design:

![latin_square](https://user-images.githubusercontent.com/54183042/123604021-bbf31d00-d7fa-11eb-8af9-95e3b85bcf2b.jpeg)

This is a factorial ab design:
![factorial_ab_design](https://user-images.githubusercontent.com/54183042/123604024-bc8bb380-d7fa-11eb-852f-a801cda20a89.jpeg)

I have also some plot for split_plots (including mainplots and subplots) here:

![split_splot_main](https://user-images.githubusercontent.com/54183042/123605183-d8438980-d7fb-11eb-9b7f-ce3fa9b32f7e.jpeg)

![split_plots_subplots](https://user-images.githubusercontent.com/54183042/123605187-d8dc2000-d7fb-11eb-9850-f87e02bce6b7.jpeg)

my question is if these visualizations of experiment designs are in scope of this journal.
One can use those maps for orientation, finding missing values in a plot and also inspect the type of the experiment with the used statistics. In Agriculture we say: "Analyse as randomize".

The target groupos will be: researchers, field technicans, financial funding agencies and other stakeholder, involved in suchs experiments.

What do you think?

**Comment by arfon** [comment]
Hi @jensharbers – libraries that are primarily visualisation are generally out of scope for JOSS, unless there is a strong analysis component included in the tooling.
