### ISSUE TITLE
Pre-submission enquiry

### ISSUE THREAD

**Issue by pakjiddat** [openjournals/joss#952]
I have developed a package in R for working with n-gram language models. The package falls under the category of "Natural Language Processing". Here is a link to the project repository: https://github.com/pakjiddat/word-predictor. It has been published on CRAN. Does the project meet the submission requirements ?.

**Comment by arfon** [comment]
Hi @pakjiddat – this could be in scope, as long as there is a strong research application for this tool. Without seeing a draft of a paper, it's hard to say for sure but we'd welcome a submission to JOSS and the scope could be assessed at pre-review time.
