### ISSUE TITLE
Invalid Git repository address when submit paper 

### ISSUE THREAD

**Issue by ebocher** [openjournals/joss#953]
Dear JOSS community,

We try to submit a paper available here :  https://github.com/orbisgis/geoclimate/tree/master/docs/articles/joss

The compilation has been already tested using a Github action : https://github.com/orbisgis/geoclimate/suites/3132560351/artifacts/71862856

When we try to submit the paper, it returns the following message  "Invalid Git repository address. Check that the repository can be cloned using the value entered in the form, and that access doesn't require authentication.
"

Don't understand what's going wrong. 

Does the github repo meet the submission requirements ?

Thanks

**Comment by danielskatz** [comment]
In this case, the git repository is https://github.com/orbisgis/geoclimate/

It's what you would use in a git clone command...

**Comment by ebocher** [comment]
Thanks a lot. It rocks !
