### ISSUE TITLE
Pre-submission Enquiry

### ISSUE THREAD

**Issue by praneet1988** [openjournals/joss#954]
Dear Joss Team,
My colleague (Konrad Thorner) and I have developed a R package ELeFHAnt to address the two problems in the field of single cell RNA sequencing. Our package helps annotate cells in a query datasets using user defined reference dataset and it can harmonize cell-types across single cell datasets there by creating unified reference atlas.
We have the complete documentation about the package: https://github.com/praneet1988/ELeFHAnt

Can we submit to JOSS.

Looking forward to hearing from you.

Best,
Praneet

**Comment by arfon** [comment]
Hi @praneet1988 - while this submission looks like it has a research application, it looks like it's implemented in a [single R file here](https://github.com/praneet1988/ELeFHAnt/blob/main/R/ELeFHAnt_functions.R) which suggests to me that there might be substantial work required to improve the submission before we would send it out for review.

If you'd like the package to be considered, please submit and we'll assess the fit for the software at pre-review time.
