### ISSUE TITLE
Author name spelled wrong in #3290

### ISSUE THREAD

**Issue by joseph-palmer** [openjournals/joss#959]
It has just come to our attention that one of our athors last name is spelt incorrectly in a paper we recentrly published with JOSS: covidregionaldata: Subnational data for COVID-19 epidemiology. Nielson should be Nielsen. Sincere apologies for this oversight. We have amended this in the paper in the master branch of the package: https://github.com/epiforecasts/covidregionaldata.

Is there any way to update this in the official paper?

Apologies again!

**Comment by danielskatz** [comment]
Yes, @arfon will be able to help change this
