### ISSUE TITLE
Pre-submission enquiry: GitBuilding

### ISSUE THREAD

**Issue by julianstirling** [openjournals/joss#962]
Hi JOSS team,

We have poured many months person hours into [GitBuilding](https://gitbuilding.io) [[Gitlab repo](https://gitlab.com/gitbuilding/gitbuilding)], we are looking to write a paper to describe the software and the use case. We are unsure whether the project fits JOSS. We are a group in the University of Bath developing open source scientific instrumentation (mainly the [OpenFlexure Microscope](https://openflexure.org/)), but we needed a better way to track the documentation and have documentation for different variations of the microscope. This spawned GitBuilding. Scientific instrumentation is essential to good science, and documentation is essential to good reproducible instrumentation, however many would see this project as "too meta".

In case it helps here is my few sentence pitch. Something similar will be the abstract:
"Science is reaching a reproducibility crisis, with many scientists unable to reproduce the experiments of others or even their own work. Having the correct instrumentation and a deep understanding of how works is essential to reproducing and understanding experiment. However, instrumentation designed in academia is often only understood by a transient workforce of post-doctoral researchers and post-graduate students, as they leave this knowledge is often lost. There is a growing movement pushing for scientists to not only make their data and software openly available, but their hardware too. Open hardware must be documented well enough that it can be reliably reproduced and understood. GitBuilding is a tool that enable instrumentation to be written as hardware evolves. Procedures can be documented once with metadata about tool and part usage embedded directly into these instructions. These procedures can then be reused by multiple variations of a design as it evolves, complete navigable documentation can be compiled for each variation including complete, up-to-date bills of materials."

Would a paper on GitBuilding fit JOSS?

**Comment by arfon** [comment]
Thanks for the enquiry @julianstirling – this looks like an interesting tool, but I agree it's quite _meta_. Scope in JOSS is not a single-person decision (the whole editorial team can vote) and so while I think this _might_ be in scope for JOSS, I'm not sure. I would encourage you to submit and our normal scope review process can take its course.
