### ISSUE TITLE
Pre-submission enquiry

### ISSUE THREAD

**Issue by anaiy2004** [openjournals/joss#966]
My team at StartOnAI (AI-education nonprofit) have published an open-source Python package called "cerbo", which is essentially an educational package that wraps common AI/ML preprocessing / model libraries with the goal of making it easier for students to create machine learning models by doing automatic preprocessing and/or model creation and training. However, while it does seemingly have minimal research applications, our package has over 5000 downloads (https://pepy.tech/project/cerbo) and is used regularly. 
We were wondering whether such software would be in scope for the Journal of Open Source Software. (link: https://github.com/StartOnAI/Cerbo)

**Comment by danielskatz** [comment]
It seems like this would be a better fit for our sibling journal [JOSE](https://jose.theoj.org)
