### ISSUE TITLE
Pre-submission enquiry

### ISSUE THREAD

**Issue by wcj365** [openjournals/joss#967]
I developed the World Development Explorer (WDX), a web-based tool for global development researchers, analysts, and students:
http://www.worlddev.xyz
This tool is free for anyone to use. No user registration is required. So, I consider this an Free Open Source Software (FOSS).
However, I have not open sourced my code. The source code remains private to myself.
My question is: Does this meets your requirement of being "Open source"?
I would love to publish my software in the JOSS if it meets your requirements.
Thanks!

**Comment by danielskatz** [comment]
No, it does not.  "Open source" software means that the source code is open, and specifically, that it uses a license approved by the Open Source Initiative - see https://opensource.org/licenses

**Comment by wcj365** [comment]
Thanks for the quick response.
I may open source my code in the future. I will revisit when that happens.
