### ISSUE TITLE
Pre-submission enquiry

### ISSUE THREAD

**Issue by CodingLemon** [openjournals/joss#968]
Dear JOSS Editors,
I wanted to learn if our research could be published with JOSS. We have developed a specific algorithm/equation to assess protein topological features and while the work has already been published, we have a follow-up study focused specifically on the developed R package. That is, our new paper specifically focuses on the developed R package (simple use case), machine learning applications, and some new insights. The central theme is software applications for protein structural feature assessment. I was wondering if this would be of interest/relevant to JOSS?

Thank you for your time and I am looking forward to your comments.

Best wishes,

**Comment by danielskatz** [comment]
> The central theme is software applications for protein structural feature assessment.

This is a negative to me - JOSS is not about science results or fields, but specific software packages.

And not "a follow-up study" on the use of the package, but a short paper on the package itself.

So, we don't really publish papers that have "some new insights" - those would go in a science journal.

On the other hand, a paper about the software might be suitable, likely depending on what the original paper was about it.  If it was about the method and the software, it seems like a JOSS submission might then be viewed as not having enough new content.

**Comment by CodingLemon** [comment]
Thank you for your comments.
