### ISSUE TITLE
Pre-submission enquiry

### ISSUE THREAD

**Issue by elejeune11** [openjournals/joss#973]
Hello! Would it be appropriate to submit a straightforward but useful extension to FEniCS (https://fenicsproject.org/) to JOSS? For example, a solver that was not previously implemented following the format presented here https://fenicsproject.org/pub/tutorial/sphinx1/._ftut1006.html ?  If if would not be appropriate to submit this to JOSS, do you have any other suggestions for how to best share this type of work? Thank you!

**Comment by jedbrown** [comment]
The linked page, which is basically a walk-through of solving the Poisson equation, doesn't seem in-scope. It's an educational tool, and something a researcher might read before writing their own code, but not directly used for research. There are FEniCS apps that are directly used for research. It would help if you could refer to citations for research that uses the work, or (if no such papers/preprints exist) vignettes of what such research would look like. Please also keep this in mind:

> In addition, JOSS requires that software should be feature-complete (i.e. no half-baked solutions) and designed for maintainable extension (not one-off modifications of existing tools). https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort
