### ISSUE TITLE
Submission issue

### ISSUE THREAD

**Issue by AusteKan** [openjournals/joss#977]
Dear Community,

For some reason I cannot proceed with the submission as I keep getting "No paper preview found with that id. Please try compiling again. ". I am not sure what I am missing, as the repo contains: paper.md, paper.bib, figures, additional files, software tar.gz.

Maybe someone could let me know what to do? :smile:

Thank you in advance!

A

**Comment by AusteKan** [comment]
Just to add, the link for the repo: https://github.com/AusteKan/JOSS_Fiscore

**Comment by danielskatz** [comment]
This isn't exactly the problem, but what you are trying to do is the opposite of what we want.  We assume the software is housed (developed) in a git repository, and that the paper is added to this repository, and the submission is then made for this repository.  You seem to be creating a .tar.gz file of the software from somewhere, and putting it in a new repository created for the submission.  Where is the git repository in which the software was developed?  This repository should have a README that talks about the software, and how to contribute to it, for example.  You could look at previous JOSS publications to see some examples of the software repositories that have been submitted.

**Comment by AusteKan** [comment]
I see, thank you very much, Daniel, for taking the time to reply and explain. I will try to put everything together correctly. I will close this issue as soon as I get to sort out the submission. Apologies for newbie mistakes. JOSS is such a great initiative, it would be really grate to contribute and engage a broader bioinformatician/cheminformatician community. Thank you! 😄

**Comment by AusteKan** [comment]
Resolved! Thank you for your help, Daniel!
