### ISSUE TITLE
Wrong pdf compilation of unordered lists from paper.md

### ISSUE THREAD

**Issue by metelkin** [openjournals/joss#978]
Hi,
I generated pdf from my paper.md file but it seems something is wrong with my lists.
Below there are screenshot of the source code and the generated draft.
Did I do anything wrong?

The original paper is available here:
https://github.com/openjournals/joss-reviews/issues/3639

![2021-08-23_16-47-48](https://user-images.githubusercontent.com/23167846/130458560-d0924d87-429b-4a26-9762-9dfcc47857a5.png)

![2021-08-23_16-45-40](https://user-images.githubusercontent.com/23167846/130458172-031c3112-49e1-451d-890c-225746074827.png)

**Comment by fabian-s** [comment]
Try adding a blank line above "- Human-readable ..."  so markdown recognizes it as a bullet point list.

**Comment by metelkin** [comment]
Oh, that works! Thanks, @fabian-s
