### ISSUE TITLE
Presubmission enquiry: noisereduce

### ISSUE THREAD

**Issue by timsainb** [openjournals/joss#979]
I developed and maintain a small python package, noisereduce (https://github.com/timsainb/noisereduce) that performs spectral noise reduction on various time domain signals, making it useful in many scientific applications (in my case bioacoustics and neuroscience). At the same time, it is a "one function"  package: it does noise reduction on signals, that's it. Still, I'd like this to be citable beyond the zenodo distribution, so I'd like to enquire into whether this would be an appropriate submission to JOSS.

**Comment by arfon** [comment]
Hi @timsainb – this could well be in scope for us, but I'd want to ask the broader editorial team for their input to be sure. Please go ahead and submit and our standard scope review process will make a decision here.
