### ISSUE TITLE
Presubmission enquiry

### ISSUE THREAD

**Issue by jensharbers** [openjournals/joss#980]
I am developoping a shiny application to make Experimental Design easier for beginners. The User can choose between ten different Designs and can Type the needed Levels of the Factor(s), depending in the Design. The User is lead by the process of developing a proper Experimental Design. On the one Hand ,There is a possible problem as the application is written in R using Rshiny, a tool that is often claimed as a thin client.

On the other hand, some Papers using shiny are published on JOSS, See for example 

@article{Gopinath2021,
  doi = {10.21105/joss.03437},
  url = {https://doi.org/10.21105/joss.03437},
  year = {2021},
  publisher = {The Open Journal},
  volume = {6},
  number = {63},
  pages = {3437},
  author = {Pratheesh P. Gopinath and Rajender Parsad and Brigit Joseph and Adarsh V. S.},
  title = {grapesAgri1: Collection of Shiny Apps for Data Analysis in Agriculture},
  journal = {Journal of Open Source Software}
}
What do you think? Is it worth the efforts of writing a paper?

**Comment by arfon** [comment]
Without seeing the software it's hard to be sure. Also this sounds like it could be more of an educational tool, and more in scope for JOSE (https://jose.theoj.org).
