### ISSUE TITLE
Post-publication change request

### ISSUE THREAD

**Issue by ad48** [openjournals/joss#981]
Hello, we recently published a paper in JOSS. Thank you for a very helpful review process: https://joss.theoj.org/papers/10.21105/joss.03348

It has come to my attention that some of the author-lists in the references were incorrectly formatted. I have corrected the errors and updated the `paper.bib` file in the repo. https://github.com/sagepublishing/rejected_article_tracker_pkg 

Generating a preview at https://whedon.theoj.org/  shows the errors are corrected.

I'm sorry to be a nuisance, but is it possible to request a post-publication change to correct these errors in the version of record?

Specifically, the following author lists appear incorrectly:
`Fraser, L. A. D., Nicholas AND Brierley`
Should read:
`Fraser, N., Brierley, L., Dey, G., Polka, J. K., Pálfy, M., Nanni, F. & Coates, J. A.`

`Johnson, A. M., Rob; Watkinson`
Should read:
`Johnson, A., Watkinson, A. & Mabe, M.`

`Cabanac, T. B., Guillaume; Oikonomidi.`
Should read:
`Cabanac, G., Oikonomidi, T. & Boutron, I.`

**Comment by arfon** [comment]
This should be fixed now, but may take a few hours to show as updated on the JOSS site.

**Comment by ad48** [comment]
Thank you, @arfon . Greatly appreciated.
