### ISSUE TITLE
Pre-submission enquiry: Greek letters

### ISSUE THREAD

**Issue by maxkfranz** [openjournals/joss#982]
I'm in the process of preparing a submission, but I'm having trouble with the Greek letter 'α' as in 'TNF-α'.  The letter is removed from the test PDF.

You can reproduce the issue on the generator service: https://whedon.theoj.org

- Repo: `https://github.com/PathwayCommons/grounding-search`
- Branch: `joss`

Thanks

**Comment by arfon** [comment]
Hi @maxkfranz - please submit and we'll figure this out as we're in the process of publishing the paper.

**Comment by maxkfranz** [comment]
I had removed the problematic text from the paper before, so it shouldn’t be a problem now.  If you run into issues, just let me know
