### ISSUE TITLE
Pre-submission enquiry

### ISSUE THREAD

**Issue by KarstensLab** [openjournals/joss#983]
Dear Editors,

We are interested in submitting a short paper on our software package [microshades](https://github.com/KarstensLab/microshades/) that provides tools for visualization of complex data, including an extensive color vision deficiency friendly color palette and functions to help with organization. It is implemented in R and is open source. The package focuses on visualizations for microbiome sequencing data, but has several use cases and examples for the broader scientific community. 

Would this fall under the scope of JOSS?

Thanks,
Lisa Karstens

**Comment by arfon** [comment]
Hi @KarstensLab. Pure visualisation software is not in scope for JOSS, but I'm not sure if that's the sole purpose of this package. Also, this tool looks to be quite small, so may well be deemed out of scope as failing our 'substantial scholarly effort' criterion.
