### ISSUE TITLE
Pre-submission enquiry

### ISSUE THREAD

**Issue by johncwok** [openjournals/joss#985]
Dear JOSS team,

Over the last two years, I have been developing a toolbox containing standard methods of categorical time-series analysis. My main motivation was that these methods were either not implemented open-source or written in languages that I am unfamiliar with. 
The package is written in Julia and available here: [CategoricalTimeSeries.jl](https://github.com/johncwok/CategoricalTimeSeries.jl.git)
Do you think this is an appropriate submission for the Journal of Open Source Software?

Best regards,

Corentin Nelias

**Comment by arfon** [comment]
Hi @johncwok – this sounds like it could well be in scope, but I'm not an expert in these topics. Please go ahead and submit and the broader JOSS editorial team will have a chance to review the scope at submission time.
