### ISSUE TITLE
how to update author orcid of a published paper?

### ISSUE THREAD

**Issue by Saran-nns** [openjournals/joss#986]
I found the orcid id attached to one of my papers is wrong, is there any chance I could change the attached ORCID ID?

**Comment by arfon** [comment]
Sure thing. Which paper is it? Also, if you update the ORCID in your `paper.md` we should be able to reprocess the paper.

**Comment by Saran-nns** [comment]
Here are the links
Paper: paper https://joss.theoj.org/papers/10.21105/joss.03545 
I have updated the `paper.md` (metadata) which is at https://github.com/Saran-nns/sorn/blob/master/paper/paper.md

Thank you :)

**Comment by arfon** [comment]
This should be fixed now.
