### ISSUE TITLE
Unable to access dashboard

### ISSUE THREAD

**Issue by oyvinht** [openjournals/joss#987]
Dear JOSS,

I seem unable to access my dashboard at https://joss.theoj.org/dashboard/oyvinht when logged in using ORCID ID https://orcid.org/0000-0001-9884-548X

Error message: "You are not permitted to view that page"

**Comment by arfon** [comment]
Do you see a link to a dashboard? The dashboard should only be visible to JOSS editors.

**Comment by oyvinht** [comment]
Aha, OK, I was attempting to access the dashboard to review a paper I was assigned.
