### ISSUE TITLE
Split Whedon initial REVIEW comment to help reviewers find their own checklist

### ISSUE THREAD

**Issue by jarvist** [openjournals/joss#988]
One of my reviewers suggested (https://github.com/openjournals/joss-reviews/issues/3711#issuecomment-916389193) :
> Just a small meta-comment (is there an issue tracker for that?): For the review checklist, it would be convenient for the review lists of the different reviewers to be in a different comment. Last paper I reviewed, I accidentally checked off items for the other reviewer. If they're separate comments, I can bookmark a link to just my checklist.

I've also managed to do this when reviewing! Perhaps splitting the Whedon initial comments into Boilerplate, Reviewer # 1, Reviewer # 2 might make it easier to distinguish?

**Comment by arfon** [comment]
This is addressed with the changes to our review bot. Each reviewer now has their own checklist, and in fact, is unable to edit any other checklists. This functionality is enabled for reviews going forward...
