### ISSUE TITLE
Review of JOSS papers (diff sumbitted -> accepted) takes too long

### ISSUE THREAD

**Issue by sylvaticus** [openjournals/joss#989]
Just to share what I think is a problem of this git-based open review system: it's too slow.
My experience first as an author and then as a reviewer, and then by reading the other's paper review made me thought about this, and I think the main issue is that in this system there is no deadline. In typical journal review system you are asked to review within a certain deadline (3-4 weeks usually) and same, to respond to the reviewers, you have a deadline... here instead there is no deadline, and then often the conversation continue on minor topics for a while, not just the 2, very maximum 3 rounds of a typically journal.

What can be done to reduce the rewieving period of JOSS articles ? Could a deadline be envisaged and integrated in whedon ? Should a sort of tag attached to highlight in which "round" of revision we are ?

**Comment by jedbrown** [comment]
I understand this concern as an author, but quality reviewing takes time and many people are just maxed out. As an editor, what do you do if reviewers don't finish by the "deadline"? (You can find additional reviewers, but you'll likely get several declines before an accept, and they'll need time.)

Most journal deadlines are flexible -- editors will wait and send email reminders for as long as it takes, or decide they have enough to make a decision. The process emphasizes accept/reject decisions above constructive improvement; the opposite is true for JOSS. The required time is also very domain-dependent. For example, most journals in my field typically take 6-12 months from submission to acceptance when things go smoothly (sometimes plus nontrivial time to published issue), and it's exacerbated by the formality of "rounds" (the editor waits for the slowest reviewer, then curates before sending to authors). JOSS is much more casual in that one need not "finish" a review before providing feedback (sometimes leading to authors fixing dependent issues that the reviewer hasn't reached yet), and this drastically shortens the iteration time.

**Comment by arfon** [comment]
Thanks for opening this @sylvaticus. We do ask reviewers to complete their initial review in 4-6 weeks, and while I understand it can be frustrating that things can take longer than this, I think the iterative nature of JOSS reviews is generally a good experience for authors, reviewers, and editors so I'd rather keep away from the idea of 'rounds'.

BTW, we do generate metrics for JOSS, and you can see that our review time has been ~3 months on average for quite some time (http://www.theoj.org/joss-analytics/joss-submission-analytics.html#pre-reviewreview-time-over-time).
