### ISSUE TITLE
Pre-submission enquiry for rasusa

### ISSUE THREAD

**Issue by mbhall88** [openjournals/joss#991]
Hi,

I am enquiring about the suitability of submitting a bioinformatics tool I have developed - [rasusa](https://github.com/mbhall88/rasusa) - to JOSS.

Rasusa takes DNA sequencing read files and randomly subsamples them to a specified [coverage](https://en.wikipedia.org/wiki/Coverage_(genetics)). Solutions exist that do subsampling with limited capabilities, but nothing that does it to a specified [coverage](https://en.wikipedia.org/wiki/Coverage_(genetics)) - a very common requirement for genomics applications. A more extensive [motivation is detailed on the GitHub README](https://github.com/mbhall88/rasusa#motivation), which also outlines the limitations of existing solutions.

I am committed to maintaining this software program and have been doing so since I developed it two years ago.

**Comment by arfon** [comment]
Looks like you [submitted](https://github.com/openjournals/joss-reviews/issues/3831). Sorry we didn't respond here.
