### ISSUE TITLE
Handling time for JOSS articles

### ISSUE THREAD

**Issue by dmkaplan2000** [openjournals/joss#992]
Hi,

I am considering submitting an article to JOSS, but was wondering if you had an estimate of average handling times to a first decision? I currently have an article submitted to another journal that will remain nameless that has been under review for the better part of a year now and was thinking of pulling it and submitting it to JOSS, but don't want to end up back in the same situation at another journal.

Thanks,
David

**Comment by danielskatz** [comment]
See http://www.theoj.org/joss-analytics/joss-submission-analytics.html#pre-reviewreview-time-over-time for recent data.

**Comment by danielskatz** [comment]
Right
