### ISSUE TITLE
Pre-submission enquiry: does JOSS allow papers that describe an overarching framework for multiple software packages?

### ISSUE THREAD

**Issue by astronomyk** [openjournals/joss#995]
Hi JOSS,

as part of a large project, my team and I have developed 6 software packages (3 major, 3 minor) that all fit under the umbrella of a software environment. It would make sense to write one paper to summarise the environment and the need for the environment as a whole, and then to write individual papers for the 3 major packages. Without the summary paper, it would be tedious to explain the connection between the major packages in each of these 3 package papers.

I have two questions:
- will JOSS accept submissions that describe such software frameworks instead of describing a single piece of software?
- can multiple papers be submitted for individual packages under this framework? E.g: Paper I - Framework Overview, Paper II - Package 1, Paper III - Package 2, etc

For context our framework contains the following packages:
- A simulation engine
- An astronomical object description input generator
- A telescope optical system generator and database
- Several related minor stand-alone support packages

Each of the 3 major packages have stand-alone use cases, and the whole framework has another series of use cases. Each of the major packages represents at a minimum one person-year of work, with a total of around 6 person-years having gone into the framework in total.

Thanks in advance for your answer!

**Comment by arfon** [comment]
Hi @astronomyk – I think we'd be OK with multiple papers (as long as each package was within scope), but an 'overview' paper would not be permitted sorry.

**Comment by astronomyk** [comment]
@arfon thanks for getting back to this question! I'll do my best to explain the framework within the scope of each of the papers then 👍
