### ISSUE TITLE
Pre-submission enquiry: Veusz

### ISSUE THREAD

**Issue by jeremysanders** [openjournals/joss#997]
Dear Editors

I'm thinking of submitting an article on Veusz (https://github.com/veusz/veusz), which is a scientific plotting package I've been working on for many years (since 2003).

I'm wondering whether you have some guidelines on what is significant authorship? Would it be a significant number of lines of code, commits, ideas, or features? Most of the code in Veusz is my work, though a few people have contributed features or bug fixes. I'd probably say around 95%+ of the code lines are mine (excluding some copied from other non-scientific projects with a compatible licence). Of course the contributed features and bug fixes are very useful, so I don't want to neglect their contribution (but perhaps this is better in an acknowledgement?).

Thanks in advance for your answer!

Jeremy Sanders

**Comment by kthyng** [comment]
Hi @jeremysanders! We do have a section on authorship in our [docs](https://joss.readthedocs.io/en/latest/submitting.html#authorship) you can check out. We don't see it as our job to determine authorship. That said, I have seen packages invite everyone who has made a contribution (but some may choose not to be co-authors) and I have seen some that invite no one to be co-authors (in this case anyone who seems like they should be an author should probably be notified of this on github in some open way so they realize what is happening — always best to be open about everything!), and then most are probably somewhere in the middle.

**Comment by danielskatz** [comment]
I also want to mention that JOSS has sometimes found software that does plotting only (without analysis) to be out of scope. See https://joss.readthedocs.io/en/latest/submitting.html#what-we-mean-by-research-software and https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort

**Comment by arfon** [comment]
I think at this stage, it probably makes sense to submit and for our normal scope review process to take place. Please do highlight any significant analysis capabilities of the library here because as @danielskatz mentioned, pure plotting libraries are generally out of scope for us.
