### ISSUE TITLE
Question regarding Zenodo DOI requirements

### ISSUE THREAD

**Issue by aradhakrishnanGFDL** [openjournals/joss#998]
Few questions regarding the following part of the [documentation](https://joss.readthedocs.io/en/latest/submitting.html)-

"Upon successful completion of the review, authors will make a tagged release of the software, and deposit a copy of the repository with a data-archiving service such as Zenodo or figshare, get a DOI for the archive, and update the review issue thread with the version number and DOI."

Zenodo provides an option to provide a DOI that always resolves to the latest version (if one assigns a new version few months since the paper publication). Can the authors supply this DOI that possibly points to the latest version (tagged release) of the code at all times? Or is the DOI specific to a tagged release is the expected value to support the paper submission process and that it can't changed?

Apologies if I overlooked related documentation. Thanks for your support. 

Best,

**Comment by danielskatz** [comment]
We want the DOI that is tied to the version of the software that was reviewed in the paper.  JOSS does not review projects, it reviews software at a given point in time, and the archive should match that.

**Comment by aradhakrishnanGFDL** [comment]
Thanks @danielskatz. That makes sense to be able to trace things. Best,
