### ISSUE TITLE
Pre-submission enquiry

### ISSUE THREAD

**Issue by jlubbersgeo** [openjournals/joss#999]
Hi JOSS team,

I am wondering if some software I developed would be a good candidate for submitting to JOSS. I have created some Plotly Dash applications that take raw data from some an instrument in the lab I work in, take user decisions as input, and output useable geochemical data for further data analysis. I believe these tools are significant improvements to our field as they 1) are completely open source (which is not currently the case); 2) easy to use (although powerful); 3) more transparent about the underlying code and mathematics than anything else out there. The application can be run through Heroku or also downloaded and run locally via GitHub pending the user's preference or institution security concerns. All total the applications total about 1800 lines of code, but based am wondering if what is primarily published by JOSS is in the form of packages and not applications as I have created here. Thanks in advance for your help and clarification!

**Comment by arfon** [comment]
Web applications are generally out of scope for us (as you say, we more generally publish packages). That said, we have published some web-based tools. 

I would encourage you to submit and for our normal scope review process to run its course.
